### ISSUE TITLE
Round End Waiting times between Ikemen-go and Mugen characters.

### ISSUE THREAD

**Issue by doomjoshuaboy** [ikemen-engine/Ikemen-GO#1000]
### Describe the bug

Ikemen go has shorten the waiting time after each round ended  while Mugen has long waiting  times

### To Reproduce

1, Download  2 any POTS characters  1 mugen and 1 ikemen-go (https://network.mugenguild.com/pots/)
2. put the 2 character on select def and test it with ikemen go 
3. press f3 then f2 when you are on the fight area  and do a level 3 super  on  both and then wait for 10 sec and see if it fades quicker.

### Screenshots / Video

https://streamable.com/j5w64d
https://streamable.com/plgq01

### Engine Version (or source code date)

v0.98.2

### Operating system

Windows

**Comment by K4thos** [comment]
what do you mean by "Download 2 any POTS characters 1 mugen and 1 ikemen-go"? If you mean we should test ikemen-go versions on ikemen and mugen versions on mugen than this is not a proper test case. To get a reproducible test case between mugen and ikemen exactly the same character version should be used in both engines. And since mugen doesn't support ikemen go versions only testing mugen versions makes sense to highlight the differences.

**Comment by potsmugen** [comment]
I think you jumped the gun a little with this report.

But I did notice that Ikemen's waiting time works different from Mugen. It's part of the reason I made the Ikemen versions wait a shorter time before ending the round. Or more specifically, it's the AssertSpecial that's different.

In Ikemen GO, the RoundNotOver AssertSpecial freezes the lifebar's "over.time" period. In Mugen, it merely ignores it. What this difference means is that in Ikemen, if you set a RoundNotOver flag, when it ends you will still have to wait the entire "over.time" time, while in Mugen you only wait for what's left of it (usually 0).

If you put this in KFM's win pose:

```
[State 181, Wait]
type = assertspecial
trigger1 = time < 300
flag = roundnotover
```

You'll see that, in Mugen, the screen starts fading out when KFM's state time goes over 300. In Ikemen, the game keeps waiting a bit after those 300 ticks.

**Comment by lovelydumpling** [comment]
> In Ikemen GO, the RoundNotOver AssertSpecial freezes the lifebar's "over.time" period. In Mugen, it merely ignores it. What this difference means is that in Ikemen, if you set a RoundNotOver flag, when it ends you will still have to wait the entire "over.time" time, while in Mugen you only wait for what's left of it (usually 0).

Oh, this explains some things. I think I ran into this when I was dealing with the round end time being too long on my lifebars. If I lowered it too much, it'd cut during some characters' win-pose, but if I raised it too high, it took an eternity. It was tough finding a balance.
