### ISSUE TITLE
RemapPal doesn't support source = -1, 0 in helper, or omitted source; Tested on 0.98.2

### ISSUE THREAD

**Issue by beterhans** [ikemen-engine/Ikemen-GO#1001]
### Describe the bug

Original 1.1 document
If src_pal_grp is -1, all indexed-color sprites will be remapped to the dest palette. This only affects sprites of the same color depth as the dest palette. All other existing mappings will be removed.

If dst_pal_grp is -1, the mapping for the source is removed. Setting the dest pair to the same values as the source pair has the same effect.

### To Reproduce

type = RemapPal
triggerall = !IsHelper
triggerall = RoundState < 1 && RoundsExisted = 0
trigger1 = 1
source = -1, 0
dest = 1, 1

or 
type = RemapPal
triggerall = !IsHelper
triggerall = RoundState < 1 && RoundsExisted = 0
trigger1 = 1
dest = 1, 1

### Expected behavior

I'm expecting without knowing current sprite index, but able to remap to a new color palette.
in Mugen 1.1 is possible but in IKEMEN not possible. you need to state the correct source index, which is difficult to know sometime. for example a FX helper 

### Screenshots / Video
video explanation
https://www.youtube.com/watch?v=zc-QyfyGsH4

Character in the video
https://www.patreon.com/posts/saber-dec-2022-75311447

### Engine Version (or source code date)

v0.98.2

### Operating system

Windows 10

**Comment by K4thos** [comment]
I don't understand the documentation description. Please upload character that showcases the issue so that it can be tested.

**Comment by beterhans** [comment]
> I don't fully understand the documentation description. Please upload character that showcases the issue with the code already implemented.

HI @K4thos  
Added
### Screenshots / Video
video explanation
https://www.youtube.com/watch?v=zc-QyfyGsH4

Character in the video
https://www.patreon.com/posts/saber-dec-2022-75311447
