### ISSUE TITLE
Super throws deal dizzy damage by default

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1010]
### Describe the bug

Super throws are back to dealing dizzy damage by default. As such this affects every legacy character.

### To Reproduce

1. [Download Evil Ken by Reu](https://network.mugenguild.com/pots/)
2. Perform Shun Goku Satsu (X, X, F, A, Z)
3. The victim's dizzy points will go down substantially

### Expected behavior

This was fixed at some point between 0.98.2 and the current build, I think, so it's probably a regression.

### Engine Version (or source code date)

28/02/2023

### Operating system

Windows

**Comment by K4thos** [comment]
are you sure this ken is using HitDef with hyper attr set for this throw? Please post a code snipped that applies it, I can't find it.
