### ISSUE TITLE
Nightly build will not run on Linux Mint

### ISSUE THREAD

**Issue by RealFoobs** [ikemen-engine/Ikemen-GO#1018]
### Describe the bug

Discord user Shadic12#2837 tried to run the latest nightly on Linux Mint (ver. 20.3 "Una") and it would not work. Shadic can run 0.98.2 fine.

### To Reproduce

1. Download the current [nightly](https://github.com/ikemen-engine/Ikemen-GO/commit/c32c7c4f0f6a14661155cbd7f97d91b062f479c6).
2. Try to double click the program.
3. Ikemen will simply not open and won't even display an error message. No config.json file to be found in save/.

### Expected behavior

The nightly should work as it does for Windows, tested myself that such build does works just fine*.

### Engine Version (or source code date)

nightly

### Operating system

Linux

### Extra context or search terms

Shadic has more than the required specs to run any version Ikemen:

- 10th Generation Intel Core i9k.
- NIVIDIA GeForce RTX 2080 SUPER.
- 64 GB RAM.

*My best guess when trying to help him sort the issue was that the lack of the new [commonfx ](https://github.com/ikemen-engine/Ikemen_GO-Elecbyte-Screenpack/pull/9)files referenced in the nightly build could be the issue, but manually copying those did not work, and must be entirely unrelated. Even then it might be worth merging the pull request as the nightly currently has no fx during dizzy and guard crush states.

**Comment by K4thos** [comment]
try running it from terminal (not GUI) and post if there is any error printed there

**Comment by Shadic13** [comment]
Just posting the same images I posted on discord.
![Screenshot_from_2023-03-06_18-35-23](https://user-images.githubusercontent.com/84107935/223886090-5e1600a4-1016-4228-af17-4798ed278bf9.png)
![Screenshot_from_2023-03-06_17-22-32](https://user-images.githubusercontent.com/84107935/223886094-b71a9b18-5148-4d75-88c7-7f377c9621ae.png)

**Comment by K4thos** [comment]
please check if you still have this problem with this version: https://github.com/K4thos/test-cicd/releases/download/nightly/Ikemen_GO-dev-linux.zip
use the same commands if it won't run from gui

**Comment by Shadic13** [comment]
Thanks I will check it out once I am off work also are you going to do the same thing on the release candidate version as well since it shows the same problem as the nightly version?

**Comment by Shadic13** [comment]
Just tested it and it works.
