### ISSUE TITLE
Tagging after KO sinking bug with certain characters.

### ISSUE THREAD

**Issue by DolphinDan400** [ikemen-engine/Ikemen-GO#1019]
### Describe the bug

When playing on Tag mode with any of Gladiacloud & Solarflared Pokemon characters, if one of their teammates is KO'd and they jump into the stage, they will not play the landing animation and instead just slowly sink into the ground until you press a button or if they're hit, tested it on 0.99.0-rc.1, nightly and v0.98.2 and the behavior is the same.

### To Reproduce

1. Download the characters, included all 6 just in case: https://www.mediafire.com/file/ros7sazms4ta7vd/pokemonchars.rar/file
2. Choose any of them in Tag mode and get one character KO'd so they jump in.
3. The character fails to land and sinks into the ground until a button is pressed or they're hit.

### Expected behavior

Character should perform landing animation (action 47) once they hit the ground from their jump-forward animation (action 42)

### Screenshots / Video

https://user-images.githubusercontent.com/94821269/223048406-76b3ce57-131c-48f2-85fd-f7a35fd99834.mp4

### Engine Version (or source code date)

v0.99.0-rc.1, nightly and v0.98.2

### Operating system

Windows

### Extra context or search terms

Most likely a character specific bug, but haven't been able to find the cause.

**Comment by potsmugen** [comment]
This is caused by an incompatibility between the tag code and a safeguard in the characters. I submitted a fix for it.
