### ISSUE TITLE
Animated Images flicker Bug

### ISSUE THREAD

**Issue by OldGamers** [ikemen-engine/Ikemen-GO#1024]
### Describe the bug

animation that included has animation sprite transparent issue bug give a bad flicker dark black transparent

### To Reproduce

issue is the animation sprites

### Expected behavior

its ficker with dark transparent

### Screenshots / Video

https://user-images.githubusercontent.com/35203194/223685273-21657bc3-8f80-4e12-9bec-0df06b376c0d.mp4

![bad image](https://user-images.githubusercontent.com/35203194/223685315-df2868d3-1854-4e72-b244-caa0718042eb.png)

### Engine Version (or source code date)

0.99.0-rc.1

### Operating system

Windows

### Extra context or search terms

I dont know how to fix this issue

**Comment by K4thos** [comment]
not enough information - missing download link.

**Comment by OldGamers** [comment]
I posted a video and an image what else do you need >..>  Im new to github... I made it very clear what I found. Im not expert in sorta of things..  be more understanding when dealing with oldman just started making report of bug issue...for first time.. I drop the a image and video...

**Comment by K4thos** [comment]
you only gave visual proof, nothing else, hence the report as it is can't be easily reproduced (so don't count on it ever being fixed). If you can't share your screenpack than please prepare a test case using default ikemen screenpack.

**Comment by OldGamers** [comment]
> Your bug report only includes visual evidence and lacks additional information, making it difficult to replicate the issue. Without proper reproduction steps, the chances of the problem being addressed or even verified are significantly reduced. To ensure efficient resolution, it is recommended to provide clear and concise reproduction steps or, ideally, something that a developer can immediately use without having to spend time implementing themself or guessing the steps you took to trigger the issue. If you are unable to share your custom screenpack, please prepare a test case utilizing the default Ikemen screenpack.



> 
here the screen pack in the attackment its seem you dont want to give your discord contact so here the file. just let me know why the images animation is having bad bug flicker and please explain to me  in baby steps how to fix it. I dont do well in riddle of code speaking.  here the link https://drive.google.com/file/d/1SX3P0LCoM-8GhKFEgi2a59r9R5Sd98yE/view?usp=share_link

**Comment by Wftk** [comment]
is there a link to sp? cuz the one in the latest comment is down. I assume maybe issue already fixed but need to test just in case

**Comment by K4thos** [comment]
Half a year has passed without a reply, so I'm closing it for maintenance reasons. Feel free to request the reopening of the ticket if the issue persists in the latest nightly build (and if you're ready to provide the link to the screenpack)
