### ISSUE TITLE
Camera Problems

### ISSUE THREAD

**Issue by Ksylatarsh** [ikemen-engine/Ikemen-GO#1026]
### Describe the bug

In some random conditions (Can't tell exactly which are right now) the camera gets stuck when player is close to it and somehow it doesn't move. In another problem the camera struggles to follow Scorpion (In this example) when he does his teleport punch, there is no pausetime and nothing that could pause him, screenbound is movecamera =1,0.

### To Reproduce

Place P2 in a custom bouncing state and once it reaches the corner the camera will bug, not sure if the other player being mid-air has something to do with it.

### Expected behavior

Camera should move correctly.

### Screenshots / Video

The problem:
https://files.catbox.moe/oruokc.mp4

### Engine Version (or source code date)

0.99.rc1

### Operating system

None

**Comment by Ksylatarsh** [comment]
Work like it's intended to in 0.98

**Comment by K4thos** [comment]
not enough information. Missing stage and character for download. Missing inputs. Also please test how it behaves in mugen 1.1 and let us know since that engine is a point of reference if something works as intended.

**Comment by Ksylatarsh** [comment]
Works as intended in MUGEN 1.1

I can't really provide stage and character download in public but if anyone of the devs is willing to fix it; contact me on Discord.
Autismophrenia#8574

https://user-images.githubusercontent.com/126763763/224274988-dc096dc2-e3e0-4808-bf4a-dc3fa20355a6.mp4

**Comment by K4thos** [comment]
if you can't upload those resources here please prepare a simple test case with kfm and stage shipped with engine, please. Easy access to everything needed to reproduce problem locally is crucial part of bug report.

**Comment by Lazin3ss** [comment]
This problem happens if, while horizontally tracking P2, P1's negative velocity becomes greater than P2's positive velocity. Camera will then abruptly stop tracking in the direction it was originally moving to, and will go in P1's direction. In the video, since the characters are in the rightest side of the screen and camera started answering to left movement, it stops in its place until P1 touches the floor and loses its Vel X.

**Comment by Ksylatarsh** [comment]
Thanks to Lazin3ss this has been fixed :P
