### ISSUE TITLE
Seemingly tiny issue with IKEMENGO's POS trigger tracking compared to MUGEN

### ISSUE THREAD

**Issue by VinVulpis** [ikemen-engine/Ikemen-GO#1028]
### Describe the bug

So, in MUGEN, I made a helper that controls the camera in a slow, accelerating/decelerating method with some math. That eather keeps the cam smoothly focused on a single player (and slightly towards facing for minigames), or in a constant median between 2 players. In IkemenGo, it just flat out broke. I randomly decided to look at it again and I noticed what was breaking it.

So I have the helper cap it's y pos at -50, but I had to change my "pos y >=-50" to "pos y >=-51" and suddenly it works in IkemenGo. Seems like there's a sliiiight issue in difference with how the engine keeps track of POS compared to Mugen? I'm using 0.98.2, so donno if this was found and fixed, but figured I'd bring it up.

![image](https://user-images.githubusercontent.com/66293146/224213901-b9be0e14-f29d-4b79-b78d-349d81870feb.png)

This should be a lil snapshot of a part of the cod that was effected by this. the posset keeps the helper Y Pos at or "above" -50.
The trigger of pos y >=-50 SHOULD catch this, but it doesn't. Unless there's something I'm missing about the code that I did wrong, which is always possible knowing me, but I know it worked just fine in Mugen.

Seemingly super tiny is an issue, but I can see something like this confusing some folks if something seems off about behavior.

The version I'm reporting this about is 0.98.2, so there's a chance you folks caught this already, but guess it don't hurt to make sure.

I realize that I can just drop some of the y pos triggers as long as I'm keeping it capped, but still an interesting issue that might effect other stuff?

P.S.:
On that note, it'd bee pretty cool if something like this can just be worked right into IkemenGo itself, to make the camera keep a nice middle-ground focus between fighters, and very gently easy into it, rather than flat speed movements and zooms.

My helper uses it's width to zoom the camera in and out slowly based on how far the players are or how high one jumps to zoom out rather than scroll up. (The default behavior even in Mugen is too jarring and in this built seems completely broken in IKEMEN Go.

### To Reproduce

I'll go ahead and drop one of my WIPs with a stage designed to work nicely with the camera helper. Even though I patreon wall my WIPs, hahah
[Gejhi + BCtraining stage.zip](https://github.com/ikemen-engine/Ikemen-GO/files/10938163/Gejhi.%2B.BCtraining.stage.zip)
The helper variable is already turned on.

The camera helper's state is 55555 in Gejhi_AI.st If you change the >=-51s back to >=-50s for the triggers, the helper just gets stuck in place and locks up once it reaches -50. Then the camera freezes and wont let the camera scroll. Again, this doesn't happen in MUGEN.

### Screenshots / Video

https://user-images.githubusercontent.com/66293146/224213586-7f7d9253-fb12-4607-9840-4a3ca340e73b.mp4
 This is a video of the expected behavior, with some minor ikemengo differences for the camera handling in effect

### Engine Version (or source code date)

v0.98.2

### Operating system

Windows

**Comment by K4thos** [comment]
please test it on rc release

**Comment by VinVulpis** [comment]
It actually seems like this issue is fixed from what I can see here. The stage camera behavior seems pretty different now too. 

So , I guess you can disregard this post! Cool beans.

**Comment by VinVulpis** [comment]
CORRECTION. It still seems to very occasionally have the issue. Most of the time it's fine, but I noticed it gets snagged intermittently.
