### ISSUE TITLE
Picture display problem

### ISSUE THREAD

**Issue by MOGEN-ATON** [ikemen-engine/Ikemen-GO#1033]
### Describe the bug

[Statedef -2]

[State A]
type = Helper
trigger1 = time = 10
id = 33333
name = "g"
sprpriority = 1
pos = 0,0
postype = p1
stateno = 33333
helpertype = normal
pausemovetime = 999999
supermovetime = 999999
keyctrl = 0
ownpal = 1

https://user-images.githubusercontent.com/94386745/224466111-b7bc5b0d-9c32-423d-bf39-f0731f86866a.mp4

![%QN4ICYM8RWG~~6`0X{6 {K](https://user-images.githubusercontent.com/94386745/224466130-f4ac5e73-c468-42b5-b9c3-976afd4ead47.png)

![AQ034V2 CP@9 49D )2WBBH](https://user-images.githubusercontent.com/94386745/224466140-520ced73-fe0c-4cf7-bb35-3f0c9170a3a8.png)

### To Reproduce

Uploading 1678511213297.mp4…

### Engine Version (or source code date)

v0.99.0-rc.1

### Operating system

Windows

**Comment by K4thos** [comment]
please upload version o kfm that you've used to make those screenshots

**Comment by MOGEN-ATON** [comment]
> 

![20230316](https://user-images.githubusercontent.com/94386745/225525497-ca00cfd5-9b28-420e-9743-3ecdb5acd99d.jpg)

**Comment by K4thos** [comment]
those character don't contain graphic resources that you've showcased in screenshots

**Comment by MOGEN-ATON** [comment]
> those character don't contain graphic resources that you've showcased in screenshots

I put the picture in fightfx  


;============================

;;======================"级别P数"=======================
[Statedef 33333]
type = A
ctrl = 0
Anim = 99999
velset = 0,0
movetype = I
physics = N

;-----------------------PLAYER 1----------------------------------------------------
[State 1100, No.P]
type = Explod
trigger1 = palno = 1 && teamside = 1
persistent = 0
Anim = F331
postype = left
pos = 25,1
sprpriority = -999
ID = 333
bindtime = -1
ownpal = 0
[State 1100, No.P]
type = Explod
trigger1 = palno = 2 && teamside = 1
persistent = 0
Anim = F332
postype = left
pos = 25,1
sprpriority = -999
ID = 333
bindtime = -1
[State 1100, No.P]
type = Explod
trigger1 = palno = 3 && teamside = 1
persistent = 0
Anim = F333
postype = left
pos = 25,1
sprpriority = -999
ID = 333
bindtime = -1
[State 1100, No.P]
type = Explod
trigger1 = palno = 4 && teamside = 1
persistent = 0
Anim = F334
postype = left
pos = 25,1
sprpriority = -999
ID = 333
bindtime = -1
[State 1100, No.P]
type = Explod
trigger1 = palno = 5 && teamside = 1
persistent = 0
Anim = F335
postype = left
pos = 25,1
sprpriority = -999
ID = 333
bindtime = -1
[State 1100, No.P]
type = Explod
trigger1 = palno = 6 && teamside = 1
persistent = 0
Anim = F336
postype = left
pos = 25,1
sprpriority = -999
ID = 333
bindtime = -1


[Statedef -2]

[State A]
type = Helper
trigger1 = time = 10
id = 33333
name = "g"
sprpriority = 1
pos = 0,0
postype = p1
stateno = 33333
helpertype = normal
pausemovetime = 999999
supermovetime = 999999
keyctrl = 0
ownpal = 1

**Comment by Wftk** [comment]
i dont see any issue here, seems like helper which contains all this explods just spawn multiply each time = 10 so explods is not getting removed and just spawns ontop of each other.
