### ISSUE TITLE
GetHitVar(HitTime) behavior

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1034]
### Describe the bug

This GetHitVar is reset outside of Movetype = H in Ikemen, but in Mugen it keeps counting down normally.

Mikage's Touhou characters (wrongly) use Movetype = I for some guarding states, so this happens:
https://imgur.com/aeQ2FY4

Here's the same but against another character:
https://imgur.com/hmZctjl

### To Reproduce

1. Change one of the knocked back states in common1.cns.zss (151, 5001, etc) to MoveType = I
2. Have a character block or be hit into those states
3. They will exit the state immediately because of GetHitVar(HitTime) resetting

### Expected behavior

These Touhou chars worked normally in Mugen. Only when Mugenapple put them in Ikemen did he notice the difference.

I think this small difference is hiding more bugs in other characters that we just haven't found yet.

### Engine Version (or source code date)

0.99 RC1

### Operating system

Windows

**Comment by K4thos** [comment]
there seems to be a contradiction in docs:

> hittime: Returns time before player regains control and returns to an idle state after being hit. This counts down by 1 per game tick, as long as hitshaketime (see above) is greater than 0. It stops counting down when the value reaches -1. (int) "GetHitVar(hittime) < 0" is equivalent to the HitOver trigger.

but the HitOver trigger says:
> If the player is in a gethit state, returns 1 when the hittime has expired, and 0 otherwise. For an explanation of hittime, see the HitDef documentation.

so can GetHitVar(hittime) be >= 0 while HitOver = 0 in mugen or not? In other words should HitOver have additional gethit state check, since we're removing it from GetHitVar(hittime) timer.

**Comment by potsmugen** [comment]
I think that's a mistake in the documentation. Here I'm forcing KFM to have Movetype = I instead of H:

![Image1](https://user-images.githubusercontent.com/107247004/224504377-6c3988de-fe76-480d-b729-edb79ea49378.png)

(Mugen 1.1)

HitOver behaves the same as in MoveType = H. The "GetHitVar(hittime) < 0" seems about right. That's apparently all that HitOver is.

**Comment by potsmugen** [comment]
Figure I'll post it here instead of opening a new ticket, since it's related. The way hittime is counting down is slightly off. If you pull up the debug in Mugen 1.1, you'll see that at time = 0 of the sliding back state (5001 etc) it gets decreased by 1, but in Ikemen it doesn't. This means the hittimes will be off in every single character.

It works correctly in 0.98.2.
