### ISSUE TITLE
Character being thrown in the wrong height in 99 RC

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#1042]
### Describe the bug

In the 99 RC build if Vice do the 2 kicks grab the character gets thrown into the air when they're supposed to be thrown at the ground.

### To Reproduce

[Vice.zip](https://github.com/ikemen-engine/Ikemen-GO/files/10949477/Vice.zip)

Two kick while close to perform the grab.

### Screenshots / Video

![vice bug](https://user-images.githubusercontent.com/77592586/224511987-00aab6d6-55a5-45b5-8577-50cca8bc58e7.png)
98 - Correct behavior
![Ikemen_GO 2023-03-11 18-07-29](https://user-images.githubusercontent.com/77592586/224512003-1c781562-fa54-42a9-9e96-ac657ad88147.png)
99 RC1 - Bugged

### Engine Version (or source code date)

v0.99.0 rc1

### Operating system

Windows

**Comment by potsmugen** [comment]
Probably related to how position is updated while the character is bound. If you shift the PosSet one frame later the bug disappears.

**Comment by UrsoManso** [comment]
>If you shift the PosSet one frame later the bug disappears.

Thanks.

**Comment by potsmugen** [comment]
The Vice case reported is fixed, but I found another one:
[geese test.zip](https://github.com/ikemen-engine/Ikemen-GO/files/11011981/geese.test.zip)

Character will automatically do the affected move (but you have to hit him to trigger the counter). In Mugen and 0.98.2 the opponent will slide for a bit after thrown. In 0.99 he will stand still

**Comment by K4thos** [comment]
pots, does the new finding also happens in 0.98.2?

**Comment by potsmugen** [comment]
It doesn't.

**Comment by K4thos** [comment]
The problem with Geese is caused by #1056 @Lazin3ss, can you take a look?

**Comment by potsmugen** [comment]
The same throw doesn't have any issue if Geese activates it with Hitdef instead of Reversaldef.
