### ISSUE TITLE
RemapPal has no effect on helpers

### ISSUE THREAD

**Issue by slzero-X** [ikemen-engine/Ikemen-GO#1058]
### Describe the bug

I am developing a clone army type of character that has different types of clones to fight each with unique palettes, RemapPal on helpers works as expected in 1.0 and 1.1, however when applying it in Ikemen GO, it does not do anything, no warnings or errors are raised, nothing literally happens.

### To Reproduce

1. Have RemapPal on a helper be set to randomly shuffle the palette or apply it every frame I don't fucking know whathawosifzOIvhozxocgzxcvn Its inconsistent and UNEXPLAINABLE.

### Expected behavior

In 1.0 and 1.1, RemapPal works on helpers, in Ikemen GO's nightly build it does nothing to helpers.

### Engine Version (or source code date)

source, 3/15/2023, likely in 0.99-rc1 as well and prior versions

### Operating system

Windows

### Extra context or search terms

This might be due to changes from 0.98.2, but please test it on that build as well and see if it works at all, if it does, its likely a regression.

**Comment by K4thos** [comment]
can't reproduce

https://user-images.githubusercontent.com/8928195/225460300-5bc2c406-8a78-42ff-b4e5-51b608f0bd67.mp4

`[StateDef 123456]

[State 0, RemapPal]
type = RemapPal
trigger1 = root,command = "a"
source = 1,1
dest = 1,3
ignorehitpause = 1

[State 0, RemapPal]
type = RemapPal
trigger1 = root,command = "b"
source = 1,1
dest = 1,4
ignorehitpause = 1

[State 0, RemapPal]
type = RemapPal
trigger1 = root,command = "c"
source = 1,1
dest = 1,5
ignorehitpause = 1

[StateDef -1]

[State 0, Helper]
type = Helper
trigger1 = id = 56 && NumHelper(123456) = 0
helpertype = normal ;player
name = "Odb718's helper"
ID = 123456
stateno = 123456
pos = 0,0
postype = p1    ;p2,front,back,left,right
facing = 1
keyctrl = 0
ownpal = 1
supermovetime = 0
pausemovetime = 0`

**Comment by slzero-X** [comment]
How come it DOESN'T work for me yet it works for you? Impossible.

**Comment by slzero-X** [comment]
When its set to random, it doesn't do anything.

**Comment by slzero-X** [comment]
Its too inconsistent, you play around and see this absurd anomaly its really setting me off I can't understand why this is happening.

**Comment by slzero-X** [comment]
Its too inconsistent I can't explain, there is no explaining it its an anomaly, it is ENTIRELY dependent on HOW the code is formatted and what triggers are being executed/referenced.

**Comment by K4thos** [comment]
based on my tests there is indeed something wrong with roundstate = 0 and remapPal.

Test code:

```
[State 0, RemapPal]
type = RemapPal
trigger1 = 1
source = 1,1
dest = 1,1+random%6
ignorehitpause = 1

[StateDef -1]

[State 0, Helper]
type = Helper
trigger1 = id = 56 && NumHelper(123456) = 0
helpertype = normal
name = "Odb718's helper"
ID = 123456
stateno = 123456
pos = 100,0
postype = p1
facing = 1
keyctrl = 0
ownpal = 1
supermovetime = 0
pausemovetime = 0
```

Result:
1. If intro is interrupted than remapPal works
2. If intro is not interrupted remapPal is ignored
3. Adding roundstate = 2 to helper spawn trigger = remapPal works
