### ISSUE TITLE
gethitvar(animtype) will not return the correct value when set with other animtypes on a hitdef

### ISSUE THREAD

**Issue by AshtonTurner** [ikemen-engine/Ikemen-GO#1063]
### Describe the bug

Mugen currently assigns the value of the animtype of a hitdef based on when the attack hits:

animtype = when the opponent is not in the air
air.animtype = when the opponent is in the air and not in a hitfall state
fall.animtype = when the opponent is in a hitfall state

This is to establish that it will not set the animtype unless those conditions are met. 

In Ikemen Go however, it will overwrite the value if the opponent is set into any of the other conditions. For example

`animtype = Up
air.animtype = Back`

air.animtype will overwrite animtype if the y velocity of the attack is not 0.

### To Reproduce

using KfmZ or kfm:
1. add air.animtype to any hitdef and set it to any other value than the default animtype
2. set the y velocity of the attack to be <0
3.observe the gethitvar(animtype) of the target.

### Expected behavior

`animtype = Up
air.animtype = Back`

If the opponent was on the ground(statetype=S or statetype=C) when the attack hits, the first animtype (4) should show up as the gethitvar(animtype). If they were statetype=A, it should show 3.

### Screenshots / Video

using this displaytoclipboard:
[State 0, DisplayToClipboard];Attack 
type = DisplayToClipboard
trigger1 = 1
text = "animtype= %d"
params= enemynear,gethitvar(animtype)

Ikemen Go
![ikemen008](https://user-images.githubusercontent.com/85361890/225946830-97322f0c-0400-4e75-83b7-9cbb26cdb745.png)

Mugen
![aas](https://user-images.githubusercontent.com/85361890/225947454-c897e019-9a81-45a5-83a0-63ab060cd286.PNG)

### Engine Version (or source code date)

v0.99.0RC

### Operating system

Windows

### Extra context or search terms

gethitvar, animtype

**Comment by potsmugen** [comment]
It looks like the GetHitVar gets set correctly to 4, but when the character changes to statetype = A it updates to 3, as you said earlier. It keeps happening even after the target returns to the idle states.

While playing around with this I noticed that if you set the animtype to Up and don't make the opponent enter an air state (by not setting fall = 1 or not giving them Y velocity) they will try to use get hit animations that are not required and create debug messages. Looks like Mugen (and now Ikemen) forgot to account for that scenario in states 5001 and 5011.
