### ISSUE TITLE
Characters sink underground when hit off the ground

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1064]
### Describe the bug

When a character is hit out of the lying down state with some Y velocity, an offset of 15 pixels is applied and they will be drawn under the ground for one frame

### To Reproduce

1. Download any character with OTG combos, like OHMSBY's characters
2. Hit P2 when they're lying down
3. Check the frame where the attack connects

Or just pick KFM and sweep the opponent, then sweep them again while they are down.

### Expected behavior

In Mugen this just doesn't happen. It doesn't seem to be the case in 0.98.2 either. I think the offset is just applied too soon.

Incidentally while testing this I noticed that, while Elecbyte gave people a lot more control over how the characters hit the ground with the new "gethit" [Movement] constants, it looks like they just left this value of 15 pixels hardcoded.

### Screenshots / Video

Mugen 1.1:
![mugen](https://user-images.githubusercontent.com/107247004/225978145-e2642ecf-863b-4fe1-b254-168d750afb2e.png)

Ikemen 0.99 RC1
![ikemen027](https://user-images.githubusercontent.com/107247004/225978195-6bb98eb1-7af1-4c9b-85e3-7b8f11c1cb63.png)

### Engine Version (or source code date)

0.99 RC1

### Operating system

Windows

**Comment by K4thos** [comment]
from what I see the char.go code responsible for it has been reverted in one of the recent commits, so I've changed the label to reflect that it's a missing mugen feature, not a regression.

When this ticket was created following code existed (applied 1 frame too early)

```
		} else if c.ss.stateType == ST_L {
			if c.pos[1] == 0 {
				c.changeStateEx(5080, pn, -1, 0, "")
				if c.recoverTime > 0 {
					c.recoverTime--
				}
				if c.ghv.yvel != 0 {
					c.pos[1] += 15 / c.localscl
				}
			} else {
				c.changeStateEx(5020, pn, -1, 0, "")
			}
```
