### ISSUE TITLE
Problems with the input buffer.

### ISSUE THREAD

**Issue by Isakku** [ikemen-engine/Ikemen-GO#1087]
### Discussed in https://github.com/ikemen-engine/Ikemen-GO/discussions/862

> 
> <div type='discussions-op-text'>
> 
> <sup>Originally posted by **Windblade-GR01** May 23, 2021</sup>
> Currently the input buffer present some problems that make it harder to execute commands.
> This is show on these cases like #116.
> And any improvements like ones done by NeatUnsou break the functionality of current one.
> 
> So to solve problems and allow improvements in the future a full command buffer rewrite is needed.
> As compatibly with MUGEN is pority this new buffer would be fully backwards compatible with MUGEN chars.</div>
> 

I'm having this issue on Linux. It seems to have made a comeback in a weird way.

In some cases, some button combinations such as holding X and pressing forward or backwards, brings back the bug.
As I mentioned in that discussion, pressing directionals such as "forward" was giving the same result as double forward "FF"  
my char couldn't walk, it could only dash. Well, now it works well unless I'm holding down another button such as "X"

**Comment by K4thos** [comment]
there is already ticket for this: #365
