### ISSUE TITLE
BgPalFx Layer Issue

### ISSUE THREAD

**Issue by LeanneTM** [ikemen-engine/Ikemen-GO#1088]
### Describe the bug

So, when using BgPalFx, it works fine in most cases... until a stage's background element is on top of players and uses subtractive transparency.
For some reason, players also get affected by it when they shouldn't.

### To Reproduce

Download the file I provide, which includes a edited KFM stage with extra sub layer, and edited KFM's CNS file which adds BgPalFx whenever you perform a taunt.

[kfm_ikgobgpalfx.zip](https://github.com/ikemen-engine/Ikemen-GO/files/11044360/kfm_ikgobgpalfx.zip)

### Expected behavior

It shouldn't darken the players no matter if the stage BG uses layerno = 1 with any transparency, but rather the background alone, as in MUGEN 1.1.

### Screenshots / Video

(I'm using a private stage for this, but the thing works the same with test stage I sent)

MUGEN 1.1:
![mugen11](https://user-images.githubusercontent.com/83039977/227024469-8a72a678-8c24-4344-8062-e615a08515da.png)
IKEMEN GO 0.99 RC1 (got told same thing happens in 0.98.2):
![ikemengo099rc1](https://user-images.githubusercontent.com/83039977/227024619-cb7a7de5-e2b2-4d1e-9dc2-ffad9a8b9171.png)

### Engine Version (or source code date)

v0.99rc1

### Operating system

Windows

**Comment by potsmugen** [comment]
I'm not sure if this helps fixing this issue, but this almost looks like the sub transparency is applied before the PalFX, when it should be applied at the end.

**Comment by potsmugen** [comment]
This seems to be fixed in 0.99 RC4. At least in the stage you provided. Can you check with your stages?
