### ISSUE TITLE
The entire operation is paused.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#1094]
### Describe the bug

The entire operation of IKEMEN GO will temporarily stop.

### To Reproduce

1.Launch IKEMEN GO.
2.Select a character and stage at random and start the match.

### Expected behavior

The entire IKEMEN GO operation may temporarily stop.

### Engine Version (or source code date)

v0.99.0-rc.1

### Operating system

Windows

### Extra context or search terms

The operating system is Windows 11.

**Comment by K4thos** [comment]
report like this in unreproducible, not enough information

**Comment by Kuroteba** [comment]
Here are the specs of my computer.

Processor AMD Ryzen 7 5700U with Radeon Graphics 1.80 GHz
RAM 8.00 GB
System type 64-bit operating system, x64-based processor


Note that this bug did not occur in v0.98.2.

**Comment by lokpro** [comment]
Hi @Kuroteba,
Is the program completely freezed? Or some of the background animation still animating? background music still playing?
Is any key responsive ( Esc, F4, etc) ?

Did it happen every time you play a match? Can you narrow down to what stages or chars that will cause this erorr?

**Comment by Kuroteba** [comment]
During a match, during character selection, or in any other situation, the game will frequently stop for a brief moment and then immediately start moving. There is no error message and the Esc, F4, and other keys respond.
The background animation also stops for a split second.

This occurs in almost all situations, so the situation cannot be identified.

**Comment by lokpro** [comment]
Maybe this computer resource related?
Maybe try decrease the number of chars added to the game to see if any difference?
Maybe the Motif is too fancy ? such as this one The Best Ikemen GO 2021 - TBIG (Screenpack) - YouTube https://www.youtube.com/watch?v=zsGDfeK0tAU

**Comment by Kuroteba** [comment]
This bug occurs when the number of characters is less than 10 and at the default screen pack.

**Comment by lokpro** [comment]
I guess it might be the refactored graphic library does not play well with your hardware or driver. Maybe you try to update your driver first.
You can join Discord and search for "AMD" to see if anything you can try. Some users have reported performance issues with AMD GPUs.

If you can compile the program, try to narrow down if the problem begins around https://github.com/ikemen-engine/Ikemen-GO/commit/e7915ca9b6ba2b8370d751e9be0af682869cb10d

**Comment by K4thos** [comment]
AMD performance problem was fixed a year ago by AMD themselves
make sure your drivers are up to date
