### ISSUE TITLE
Issue with remapped palettes and explods created by helpers

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1104]
### Describe the bug

It looks like if a helper with ownpal = 1 creates explods with ownpal = 1, they may use the default palette instead of the helper's current palette. I don't think that's the whole story, but it's what I could find so far.

This bug is not present in 0.98.2.

### To Reproduce

[1. Download the Mugen version of my Nakoruru](https://www.mediafire.com/file/cvkp2dth5k8ukod/nakoruru_pots.zip/file)
2. Perform her fireball super (QCB, QCB, punch)
3. The effects will change color in Mugen according to the chosen palette, but not Ikemen GO

### Expected behavior

Same as Mugen.

### Screenshots / Video

Mugen 1.1:
![mugen023](https://user-images.githubusercontent.com/107247004/228494395-feeeec5d-6fc1-4413-820d-dcf93e988113.png)

Ikemen GO 0.98.2:
![ikemen006](https://user-images.githubusercontent.com/107247004/228494844-cb96a129-ccaf-4b40-8d6e-05c51f1e5e98.png)

Ikemen GO 28/03/2023:
![ikemen021](https://user-images.githubusercontent.com/107247004/228495023-5b9297c5-052b-4bc3-838e-9de3724a9342.png)

### Engine Version (or source code date)

28/03/2023

### Operating system

Windows

**Comment by potsmugen** [comment]
That helper's state is 10415. Further testing shows that removing the Explods only show up wrong while they're under the effect of ModiyExplod.

**Comment by K4thos** [comment]
caused by #1059. Please provide code snippets that showcase remappal values used for this move and information what type of helper this is and what ownpal value it uses.

**Comment by K4thos** [comment]
which ModifyExplod? I need exact position of the block that handles this explod to test if the changes are reliable.

**Comment by potsmugen** [comment]
State 10415 in the nakhelper.st file. Specifically the [State 10415, Scale] blocks.
