### ISSUE TITLE
Stage AutoTurn parameter not implemented

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1105]
### Describe the bug

The stage AutoTurn parameter is still not implemented. Setting it to 1 or 0 has the same effect.

### To Reproduce

1. Change autoturn to 0 in Mountainside Temple
2. Jump over the opponent
3. Characters will not autoturn in Mugen, but they will in Ikemen

### Expected behavior

Same as Mugen 1.1

### Screenshots / Video

Mugen 1.1
![mugen024](https://user-images.githubusercontent.com/107247004/228596368-9a2632d4-ab90-4bf5-93d1-20fae4066c2d.png)

Ikemen GO
![ikemen022](https://user-images.githubusercontent.com/107247004/228596567-daa6f488-8c9e-4531-bf1e-b0a22a23f2de.png)

### Engine Version (or source code date)

28/03/2023

### Operating system

Windows

**Comment by K4thos** [comment]
this one is already implemented in my z-axis fork, so will be available once it's merged
