### ISSUE TITLE
Ikemen limit of stages to display in the characterselect

### ISSUE THREAD

**Issue by ZyonZZ** [ikemen-engine/Ikemen-GO#1107]
### Describe the bug

ikemen only shows a limit of 98 stages during the select

### To Reproduce

Despite putting more than 120 stages, only 98-99 are shown. Is the limit linked to performance for some reason?

### Engine Version (or source code date)

.98 & v0.99.0-rc.1

### Operating system

Windows

**Comment by K4thos** [comment]
there is no such issue (tested) and there is no such limit
