### ISSUE TITLE
Screenpack localcoord seems to be broken.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#1140]
### Describe the bug

Changing motif1's localcoord to 640x480 enlarges everything.

### To Reproduce

Download the RC build and change the screenpack to motif1 with 640x480 localcoord.

### Expected behavior

Adjust the screenpack to 4:3 ratio.

### Screenshots / Video

![ikemen001 1](https://user-images.githubusercontent.com/77592586/229945866-306d1e5a-5516-4837-840f-af3adac32e39.png)

### Engine Version (or source code date)

v0.99.0 rc1

### Operating system

Windows

**Comment by K4thos** [comment]
same outcome in mugen:
![mugen001](https://user-images.githubusercontent.com/8928195/229982873-71d079c9-ba9c-490c-af8d-0957b65b5051.png)

if you mean auto screenpack scaling to fit lower resolution than it has nothing to do with changing screenpack localcoord and is not implemented (and likely won't be for foreseeable future)
