### ISSUE TITLE
Offset sctrl is inconsistent between 4:3 and 16:9 aspect ratios

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1174]
### Describe the bug

As title says. In widescreen, the offset sctrl applies a smaller offset than in 4:3.

This didn't happen in 0.98.2. I think it's related to the [RedirectID fix](https://github.com/ikemen-engine/Ikemen-GO/commit/6c88408c37125665296883233c789671faa6d459).

EDIT: Turns out it also works incorrectly with characters with localcoord different from 320x240 (try same steps with KFM 720).

### To Reproduce

1. Add this to KFM:
```
[State -2, Debug]
type = offset
trigger1 = 1
x = 10
y = 15
```
2. Configure video in a 4:3 aspect ratio
3. Put KFM in Stage 1 and check position. He will be on a different grid square compared to the usual (see screenshots)
4. Configure video in a 16:9 aspect ratio
5. Put KFM in Stage 1 and check position. He will no longer be lined up with the grid

### Expected behavior

The 4:3 one seems to be correct, so 16:9 should just do the same thing.

### Screenshots / Video

4:3 (apparently correct):
![ikemen037](https://user-images.githubusercontent.com/107247004/232831096-d28bb5ab-ef8c-4cc4-8d21-b7c8ea4b2f36.png)

16:9 (smaller offset than expected)
![ikemen038](https://user-images.githubusercontent.com/107247004/232831117-bdda981f-85d0-4414-b40f-6c88d4505214.png)

### Engine Version (or source code date)

18/04/2023

### Operating system

Windows

**Comment by K4thos** [comment]
reverted: https://github.com/ikemen-engine/Ikemen-GO/commit/0a745d326b5e11b81596532dd00897d3e08dfc0e
