### ISSUE TITLE
Unintended sound cancellation

### ISSUE THREAD

**Issue by zzzz0424** [ikemen-engine/Ikemen-GO#1190]
### Describe the bug

IKEMEN GO previously added a feature called priority to the state controller called PlaySnd.
However, this may have been a misdescription and is now reflected in the existing characters, causing some sounds to stop or only sound for a moment.

### To Reproduce

Download Krizalid99 here.
https://onedrive.live.com/?id=DD9E6829B1DE854C%21210&cid=DD9E6829B1DE854C
Compare the intro and special moves with the traditional IKEMEN version.

### Expected behavior

Limit reflection of priority in IkemenVersion or bug fix

### Screenshots / Video

https://user-images.githubusercontent.com/60909119/233901930-0f158de7-eaad-4d84-ba82-02a0fc7dd069.mp4

### Engine Version (or source code date)

0.99 RC1 and nightly build

### Operating system

Windows

**Comment by potsmugen** [comment]
I'm not sure the priority parameter is behind this. In theory it shouldn't and that char obviously isn't setting a priority for any sounds.
