### ISSUE TITLE
Deltarune Warriors: Spare Hyper Timing Bug

### ISSUE THREAD

**Issue by waspennator** [ikemen-engine/Ikemen-GO#1193]
### Describe the bug

Finally got this character in question to work on Ikemen GO and they seem to work alright, but i'm noticing a weird timing issue with their Spare Hyper. Moreso that the opponent seems to get KO'ed by it after they finish being dizzy, rather then when they start being dizzy.

### To Reproduce

[DeltaruneTrio.zip](https://github.com/ikemen-engine/Ikemen-GO/files/11315950/DeltaruneTrio.zip) (Modified to work on Ikemen GO)
1: Add character to roster and start match as Deltarune Warriors against KFM (Mostly suggest KFM cause it's easily noticeable on him)
2: Lower opponents health below 50% and then perform Spare Hyper (Down, Down, X+Z)
3: Watch for when the KO sign appears.

### Expected behavior

The opponent should be KO'ed around the start of their dizzy animation, not at the end of it.

### Screenshots / Video

Mugen 1.1b: (Appears right as the opponent gets dizzy)

https://user-images.githubusercontent.com/78768499/234161351-d83711f5-cc74-4b96-8861-afe7e1dc2c0e.mp4

Ikemen GO: (Appears after the opponent stops being dizzy)

https://user-images.githubusercontent.com/78768499/234161407-0d41c667-9244-4fb9-b7f0-97a032d29282.mp4

### Engine Version (or source code date)

Nightly Build 4/24/23

### Operating system

Windows

**Comment by potsmugen** [comment]
Looks like a difference in how long it takes for the "KO" text to appear. Not specifically tied to this character.

Another test case is KFM vs KFM and KO'ing the opponent with a light punch. In Mugen 1.1, the KO text appears just as the punch hitpause ends. In Ikemen it appears when P2 is already flying back.

That said it might be intentional.
