### ISSUE TITLE
Sound Spam during transition to Victory Screen

### ISSUE THREAD

**Issue by waspennator** [ikemen-engine/Ikemen-GO#1197]
### Describe the bug

Noticed this with a few characters on my end, but it seems like something regressed and now certain sounds seem to play into the victory screen testing with the latest nightly.

### To Reproduce

1: Download provided character 
[Khan.zip](https://github.com/ikemen-engine/Ikemen-GO/files/11330629/Khan.zip)
2: Start a match with Khan and win
3: Wait for win pose to finish and transition to win quote screen and notice sound issue.

### Expected behavior

Character sounds shouldn't be playing on the win quote screen.

### Screenshots / Video

Mugen and Ikemen GO 0.98.2

https://user-images.githubusercontent.com/78768499/234516513-4bbb2a02-3889-4055-90b1-fc2906d630d1.mp4

Ikemen GO 4/25/23 Nightly (Volume Warning)

https://user-images.githubusercontent.com/78768499/234516665-219fd251-0d6e-471e-bb40-6d643c069690.mp4

### Engine Version (or source code date)

Nightly Build 4/25/23

### Operating system

Windows

**Comment by potsmugen** [comment]
Also happens in version 0.99 RC1. Might be related to the sound update.
