### ISSUE TITLE
Add midi soundfont.

### ISSUE THREAD

**Issue by Windblade-GR01** [ikemen-engine/Ikemen-GO#12]
The ability to use soundfonts to load midi files.
We could use fluidsynth.

Requested by Mike77154
http://mugenguild.com/forum/profile/mike77154-31388

**Comment by Windblade-GR01** [comment]
Right now now Mike77154 mike is implementing fluidsynth.
Before implementing his changes I need a way to make the dependencies be downloaded by a bash/cmd script. (Docker compilation)

**Comment by Mike77154** [comment]
I'm having troubles With this

Using fluidsynth and Tinysoundfont both

And how about adding the ym2610, ym2151 and ym2612
