### ISSUE TITLE
Characters Audio Bug Victory Screen, Music Continue Loop Screen Exiting menu and Select Screen?(Some Other Characters Maybe?)

### ISSUE THREAD

**Issue by ReonaAshio** [ikemen-engine/Ikemen-GO#1211]
### Describe the bug

Just Reporting a bug.
(Is Hard to remember in English)

### To Reproduce

GM's Chars, Peppino Character, etc. (Continue Screen)
Some Other Characters Audio start playing Victory Screen

### Engine Version (or source code date)

nightly-build

### Operating system

Windows

**Comment by K4thos** [comment]
reasoning for the closure - not enough information. Please put a bit more work when creating a bug report. If you're not feeling confident writing in English you can write detailed report in your own language and use google translate. Here are general guidelines for bug reporting: https://github.com/ikemen-engine/Ikemen-GO/blob/master/CONTRIBUTING.md#submit
