### ISSUE TITLE
MacOS Shader Issue

### ISSUE THREAD

**Issue by jmagee22** [ikemen-engine/Ikemen-GO#1215]
### Describe the bug

I upgraded to  IKEMEN v0.99.0-rc.1 and I've received this message multiple times after I attempted to run the command. 

I'm aware this issue has been brought up multiple times but no resolution has been found.

Any help would be greatly appreciated!!

"Last login: Fri May  5 15:32:32 on ttys000
/Users/jonathan/Downloads/Ikemen_GO/Ikemen_GO.command ; exit;
jonathan@Jonathans-MBP ~ % /Users/jonathan/Downloads/Ikemen_GO/Ikemen_GO.command ; exit;
2023/05/05 15:41:05 Using OpenGL 2.1 Metal - 83.1 (Apple M1)
panic: Shader compile error: ERROR: 0:1: '' :  version '400' is not supported
ERROR: 0:2: 'precision' : syntax error: syntax error

goroutine 1 [running, locked to thread]:
main.compileShader(0x23d4c8?, {0x100528c55, 0xe4})
	/Users/runner/work/Ikemen-GO/Ikemen-GO/src/render_gl.go:86 +0x14c
main.newShaderProgram({0x100528c55?, 0xc000000001?}, {0x100529480, 0x54e}, {0xc0000061a0?, 0xc00023d578?})
	/Users/runner/work/Ikemen-GO/Ikemen-GO/src/render_gl.go:51 +0x3d
main.(*Renderer).Init(0x10083e700)
	/Users/runner/work/Ikemen-GO/Ikemen-GO/src/render_gl.go:201 +0x30f
main.(*System).init(0x10082cae0, 0x18?, 0x0?)
	/Users/runner/work/Ikemen-GO/Ikemen-GO/src/system.go:417 +0x505
main.main()
	/Users/runner/work/Ikemen-GO/Ikemen-GO/src/main.go:86 +0x187

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]"

### To Reproduce

Honestly not sure

### Screenshots / Video

<img width="952" alt="Screenshot 2023-05-05 at 3 41 36 PM" src="https://user-images.githubusercontent.com/116285295/236555123-d23cc506-3506-43fb-8249-ecc162914f47.png">
<img width="278" alt="Screenshot 2023-05-05 at 3 45 07 PM" src="https://user-images.githubusercontent.com/116285295/236555126-13cb5795-28bd-4ef8-ab68-21346aecca81.png">

### Engine Version (or source code date)

v0.99.0-rc.1

### Operating system

macOS

**Comment by NativeFunction** [comment]
This looks like it is in relation to https://github.com/ikemen-engine/Ikemen-GO/blob/master/src/system_glfw.go#L40 
The shader is requesting version 400 aka opengl 4.0 but the opengl version in code is set to 2.1

**Comment by K4thos** [comment]
it's a known regression, reported twice already, so I'm clisong this one.
https://github.com/ikemen-engine/Ikemen-GO/issues/1062
https://github.com/ikemen-engine/Ikemen-GO/issues/728
@samhocevar is working on a solution. If someone is able to build the engine for mac that solve the issue than please post a solution in one of the above tickets. The intended opengl version required by the engine is 2.1 (if it only works on 4.0 than that's a regression too).

**Comment by Lazin3ss** [comment]
Try modifying the shader version. Go into `src\shaders` and change the versions on all shaders to the next: `#version 130`. After that, build the engine and share results here.
