### ISSUE TITLE
Same math produces two different results in Mugen 1.1b and IKEMEN GO.

### ISSUE THREAD

**Issue by SaltAddict** [ikemen-engine/Ikemen-GO#1218]
### Describe the bug

The math my character uses to create his projectile effect seems to have two different results in MUGEN 1.1 and IKEMEN GO. The projectile is made up of a series of overlapping explods whose position is calculated based on the helper's speed. You can see that the effect displays as one continuous trail in MUGEN but IKEMEN seems to have some slight difference which causes the green balls to be displayed further ahead than where they should be.

[State x speed]
type = Varset
triggerall = ishelper(1005)
trigger1 = time = 0
var(0) = 12

[State y speed]
type = Varset
triggerall = ishelper(1005)
trigger1 = time = 0
var(1) = -6

[State y accel]
type = Varset
triggerall = ishelper(1005)
trigger1 = time = 0
fvar(0) = 0.375 

[State set velocity]
type = VelSet
trigger1 = time = 0
x = var(0)
y = var(1)

[State add gravity]
type = Veladd
trigger1 = time > 0
y = fvar(0)

[State fireball head]
type = explod
trigger1 = time = 0
anim = 1002
id = 1004
velocity = var(0),var(1)+fvar(0)*2
accel = 0,fvar(0)
pos = var(0),var(1) 
postype = p1
removetime = -1
bindtime = 0
sprpriority = 4

[State trail effect 1]
type = explod
trigger1 = time = 0
anim = 1004
id = 1004
velocity = var(0),var(1)+fvar(0)
accel = 0,fvar(0)
pos = -var(0),-var(1)
postype = p1
removetime = -1
bindtime = 1
sprpriority = 3

[State trail effect 2]
type = explod
trigger1 = time = 1
anim = 1005
id = 1004
velocity = var(0),var(1)+fvar(0)
accel = 0,fvar(0)
pos = -var(0)*2,-var(1)*2
postype = p1
removetime = -1
bindtime = 1
sprpriority = 2

[State trail effect 3]
type = explod
trigger1 = time = 2
anim = 1006
id = 1004
velocity = var(0),var(1)+fvar(0)
accel = 0,fvar(0)
pos = -var(0)*3,-var(1)*3
postype = p1
removetime = -1
bindtime = 1
sprpriority = 1

[State trail effect 4]
type = explod
trigger1 = time = 3
anim = 1007
id = 1004
velocity = var(0),var(1)+fvar(0)*0.90
accel = 0,fvar(0)
pos = -var(0)*4,-var(1)*4
postype = p1
removetime = -1
bindtime = 1
sprpriority = 0

[State trail effect 5]
type = explod
trigger1 = time = 4
anim = 1008
id = 1004
velocity = var(0),var(1)+fvar(0)*0.75
accel = 0,fvar(0)
pos = -var(0)*5,-var(1)*5
postype = p1
removetime = -1
bindtime = 1
sprpriority = -1

[State trail effect 6]
type = explod
trigger1 = time = 5
anim = 1009
id = 1004
velocity = var(0),var(1)+fvar(0)*0.5
accel = 0,fvar(0)
pos = -var(0)*6,-var(1)*6
postype = p1
removetime = -1
bindtime = 1
sprpriority = -2

![mugen001](https://user-images.githubusercontent.com/62810901/236649532-1e872cb2-2c77-484f-98f9-652baa341804.png)
![ikemen001](https://user-images.githubusercontent.com/62810901/236649535-846d0d37-2c1b-405f-81a9-1a8428386cb9.png)
![mugen002](https://user-images.githubusercontent.com/62810901/236649668-baffdbbc-3da2-4333-b223-803031996cd2.png)
![ikemen002](https://user-images.githubusercontent.com/62810901/236649674-f0c0f037-a368-4c00-81a8-9083d5543012.png)

### To Reproduce

1, Download from: https://mugenguild.com/forum/topics/cage-mk2-beta-release-1-197739.0.html
2. Start a match with him
3. Launch projectile (command is B, D, F, a)

### Engine Version (or source code date)

v0.99

### Operating system

Windows

**Comment by potsmugen** [comment]
It's probably not the math but something about the bindtimes. Disabling them in Mugen makes the fireball look the same as in Ikemen. As does increasing all of them by 1F. Maybe it's the difference between bindtime = 1 and bindtime = 0.
