### ISSUE TITLE
Alter Amiba: Amiba Liddel 34 hyper practice mode issue

### ISSUE THREAD

**Issue by waspennator** [ikemen-engine/Ikemen-GO#1221]
### Describe the bug

Dunno if this is an Ikemen GO thing or not, so i'm just gonna report it just to be safe. Alter Amiba seems to have an issue where if you perform his "Amiba Liddel 34" hyper in practice mode, instead of playing the special animation for doing it in practice mode, it plays the special animation if you tried to KO an opponent that somehow managed to survive the hyper finish. I was able to get it working by spamming space to keep both characters at full health and meter till it happens and i'm guessing it might be because of this code in the CNS.

[State 0, Training mode?]
type = VarSet
triggerall = var(5) = 50
trigger1 = power >= powermax
trigger1 = (enemynear,power) >= (enemynear,powermax)
var(3) = 1

(Also there's a jumpscare warning towards the end of the animation, you don't need to watch through it fully, you should be able to tell at the start which animation it is.)

### To Reproduce

1: Download Alter Amiba here (http://www.melv.thedailypos.org/mainsite/mugencharacters/alteramiba.html)
2: Start a match in practice mode, use shift+f2 to lower p2 hp down to 1 and perform "Amiba Liddel 34" (level 3, < 50% of opponent's health) - d, f, d, f, z)
3: Watch as the animation for the hyper failing to KO an opponent in a regular match plays.

### Expected behavior

Performing the hyper in practice mode should play the animation for doing it in practice mode.

### Screenshots / Video

[Amiba Liddel Ikemen GO.zip](https://github.com/ikemen-engine/Ikemen-GO/files/11414177/Amiba.Liddel.Ikemen.GO.zip)

How it is in Mugen

https://user-images.githubusercontent.com/78768499/236663754-11a5edd0-17b6-4ae9-9fb2-23158c471675.mp4

### Engine Version (or source code date)

Nightly Build 5/6/23

### Operating system

Windows

**Comment by potsmugen** [comment]
This is probably because Mugen's training refills power constantly while Ikemen only refills it when characters are idle (better IMO). A non-issue I think.

**Comment by K4thos** [comment]
it works as intended
