### ISSUE TITLE
Music Looping Glitch possibly?

### ISSUE THREAD

**Issue by Artemethis** [ikemen-engine/Ikemen-GO#123]
So in my previous mugen, before moving to the latest ikemen, all my music looped absolutely perfect, no seams whatsoever(Believe me i try to hard in loop perfection lol), so i ported my music to ikemen. I used same stages, same song files(just drug them from the mugen folder to the ikemen folder) and same exact loop points. 
          
   However i noticed the songs didnt loop correctly. The values despite being correct in audacity and mugen, don't loop exactly like they did before. in ikemen, the music looping feels, idk....Inconsistent.  I listened hard and noticed that the looping point was fluctuating within a small part around where the loop points are. Sometimes its right the first loop, then the second loop its like slightly after the beginning of the loop point, keeping it from looping seamlessly.  THEN sometime it loops a tad bit prematurely.  changed song frequency from 48000(what it was originally) to 32000 and adjusted loop points accordingly, didnt work. changed formats from mp3(Which crashed my game randomly btw) to ogg, and bore no fruit. Im not sure if its me or a glitch. But i thought id mention it(the mp3 crashing thing too). The songs i used were 48000hz, and 44100hz, all in ogg since mp3 crashes randomly midmatch after some time. no error message either. Just a crash.

**Comment by K4thos** [comment]
if you're still around, please upload music and stages for testing

**Comment by Artemethis** [comment]
Ill see if i still have da build and i can throw the exact files i used yer way^^

**Comment by K4thos** [comment]
Thanks. I can't hear a problem with looping on upload stage, so I assume it's already fixed. Please reopen the ticket if you think it's still valid.

**Comment by Artemethis** [comment]
> Thanks. I can't hear a problem with looping on upload stage, so I assume it's already fixed. Please reopen the ticket if you think it's still valid.

Okiee glad to hear! If i run into a problem for sure i shall inform ya

**Comment by K4thos** [comment]
apparently the problem was still there, fixed by #677

**Comment by Artemethis** [comment]
Ahhh okie tyty, is there anyway to try the newer build with this fix? or has it not been implemented? i havent updated mine a good year ish? and im not sure where everything is anymore. can test an also confirm further?
