### ISSUE TITLE
Issues with explod scaling/positioning

### ISSUE THREAD

**Issue by RealFoobs** [ikemen-engine/Ikemen-GO#1236]
### Describe the bug

Some explods are not being displayed properly on current build.

### To Reproduce

1. Download [Jmorphman's Kyo](https://network.mugenguild.com/jmorphman/characters/kyo-kusanagi/) (most "Pots Tile" characters would work):
3. Use his lv3 super (hcb,hcb+2p)
4. The super portrait he'd normally display is terribly misaligned.

https://github.com/ikemen-engine/Ikemen-GO/assets/115939744/27761893-1de9-4f02-af68-d87fdd12762a

### Expected behavior

This is how the animation should look like in mugen 1.0/previous ikemen versions.

https://github.com/ikemen-engine/Ikemen-GO/assets/115939744/8d6e105d-cc9e-4869-9af7-ce26af231e80

This video was recorded on 0.99 RC1, so the issue must have been introduced recently.

### Engine Version (or source code date)

Current Build

### Operating system

Windows

### Extra context or search terms

StateDef 8520 on helpers.st controls the explods displayed above.

**Comment by Lazin3ss** [comment]
Regression introduced in a72026133ec0883ae071839a95f68c4c7086fe16

**Comment by potsmugen** [comment]
Fixed. Now both this and the previous Johnny Cage cases are working properly, but I can't help but feel that the Explod code needs to be refactored or something. It has too many workarounds.
