### ISSUE TITLE
Smaller Resolutions cut off character dialogue portraits

### ISSUE THREAD

**Issue by BackslashBKS** [ikemen-engine/Ikemen-GO#1240]
### Describe the bug

Dialogue Portraits seem to get cut the smaller resolution you set. In the 1st image (the one with the window name) the resolution is set to 854x480 and the character dialogue portraits get cut off significantly. Meanwhile in the other screenshot, the resolution is set to 1280x720 and the character dialogue portraits don't get cut off as much but still do. In lowest possible resolutions, the portraits aren't even slightly visible anymore. The character dialogue portraits are 200x210 in size. Player 2 portrait always gets cut off more regardless of character.

### To Reproduce

1. Set resolution to 854x480 or lower
2. Have a top/bottom layout of dialogue boxes
3. Initiate dialogue between characters in any way

### Screenshots / Video

![image](https://github.com/ikemen-engine/Ikemen-GO/assets/134202604/f7ea6962-96e3-49c5-a463-abf5d481a8ab)
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/134202604/f95af5eb-ff95-490a-bb08-2359c3ada17d)

### Engine Version (or source code date)

v0.98

### Operating system

None

**Comment by potsmugen** [comment]
You should also test in the Nightly build release, just in case.

**Comment by K4thos** [comment]
can't reproduce, not detailed enough repro steps. Please provide all the files that can be used to test it.
