### ISSUE TITLE
Dialogue Text Limit?

### ISSUE THREAD

**Issue by JTDaddy17** [ikemen-engine/Ikemen-GO#1241]
### Describe the bug

Apparently there's a limit in the dialogue feature, and if you surpass it, you get an error and the game crashes. This was not an issue in older versions of Ikemen Go but now it's a thing. Please revert this limit, it's very unnecessary. Here's the log:
[Ikemen.log](https://github.com/ikemen-engine/Ikemen-GO/files/11525706/Ikemen.log)

### To Reproduce

I wish I could, but the files are "too big" to upload 4 characters...

### Expected behavior

It's supposed to play the cutscene just fine, but halfway through it, it crashes and shows an error. The cutscene I have is 31 lines of dialogue.

### Engine Version (or source code date)

v0.99

### Operating system

Windows

**Comment by K4thos** [comment]
you can make a showcase with a kfm by simply pasting the code to it

**Comment by JTDaddy17** [comment]
> you can make a showcase with a kfm by simply pasting the code to it

Can I just give you the Dialogue code itself? Will that work too?

**Comment by JTDaddy17** [comment]
Can I just give you the Dialogue code itself?
