### ISSUE TITLE
Intro storyboards not having any audio

### ISSUE THREAD

**Issue by DaInferno** [ikemen-engine/Ikemen-GO#1246]
### Describe the bug

Not sure if this is already known and is being patched or if there's a work around for this, but I thought I'd mention it anyways.

### To Reproduce

Happens on its own.

### Expected behavior

Assigned audio should play.

### Engine Version (or source code date)

v0.99.0-rc.1

### Operating system

Windows

**Comment by K4thos** [comment]
can't reproduce

https://github.com/ikemen-engine/Ikemen-GO/assets/8928195/6ff6358f-1889-4463-b043-03e7bbd8a5b7
