### ISSUE TITLE
DBK: image not flipped on P2

### ISSUE THREAD

**Issue by GreatFunk** [ikemen-engine/Ikemen-GO#1252]
### Describe the bug

for some reason, the deebeekaw on P2 doesn't see on his right, i wonder why?

### To Reproduce

1. Download DBK from Logical Bends: [https://www.justnopoint.com/lbends/index.php?location=chars&page=2](url)
2. Start a match with 1v1 DBK
3. dbk is not flipped on the right.

### Expected behavior

that i want it to be close to the mugen.

### Screenshots / Video

![ikemen000](https://github.com/ikemen-engine/Ikemen-GO/assets/98719115/83a8d374-8b8c-4361-8f75-d9e57bcc04af)
look on the right char.

### Engine Version (or source code date)

Nightly Build 5/26/23

### Operating system

Windows

**Comment by potsmugen** [comment]
This is caused by an undocumented feature of ModifyExplod where updating poistype also updates facing. Not sure this is desirable behavior for the feature so in the meantime I'll lock it to ikemenversion=0 characters.
