### ISSUE TITLE
Ground/air.type = None does not set GetHitVar "ChainID"

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1268]
### Describe the bug

Hitting the opponent with a type = None attack does not assign them a GetHitVar ChainID. It used to work in 0.98.2.

### To Reproduce

1. In KFM's light punch Hitdef, replace "ground.type = High" with "ground.type = None" and give it an ID
2. Hit the opponent and display their gethitvars to the clipboard
```
[State -2, Debug]
type = displaytoclipboard
trigger1 = 1
text = "%d"
params = gethitvar(chainID)
ignorehitpause = 1
```

Or
1. [Download Yuyutista](https://onedrive.live.com/?authkey=%21AKhHlTEgha4b0Kg&id=E7B291CB4009EF92%21193&cid=E7B291CB4009EF92)
2. Hold X for a couple seconds, then release X to create a "Gem"
3. Press Y to do an attack that in Mugen detonates that Gem. The Y attack hits the Gem with a type None attack. The Gem uses gethitvars to detect the hit)

### Expected behavior

Hitdef with ground/air.type = None should assign an ID to the target

### Screenshots / Video

Mugen 1.1:
![mugen063](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/55170ee3-2627-4e7f-8f8f-ab030dcd1213)

Ikemen GO (nightly):
![ikemen030](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/6555ce8e-e677-44b9-8b0a-71bdcea7c69c)

Ikemen 0.98.2:
![ikemen010](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/6690d8dc-c9ce-4c7e-8d36-ffc88391db1c)

### Engine Version (or source code date)

06/06/2023

### Operating system

None

**Comment by Eiton** [comment]
Maybe we can move this line to somewhere else?
```t.ghv.hitid = -1```

**Comment by potsmugen** [comment]
I added an exception so that ID is kept if the hit type was None. I get the feeling that line could be removed but for now this should work.
