### ISSUE TITLE
Wrong window size from startup running

### ISSUE THREAD

**Issue by LasombraDemon** [ikemen-engine/Ikemen-GO#1293]
### Describe the bug

Config is a Laptop with Dual Monitors running both on a 1920x1080 resolution on a 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz with a NVIDIA GeForce RTX 3050.

Tested in 0.98.2 all the way to current Nightly.

Possibly related to:
https://github.com/ikemen-engine/Ikemen-GO/issues/399
https://github.com/ikemen-engine/Ikemen-GO/issues/512
https://github.com/ikemen-engine/Ikemen-GO/issues/649

### To Reproduce

Just starting up the engine gives this error. Hitting Alt+Enter twice will fix it... 

### Expected behavior

But it should be fine from the getgo.

### Screenshots / Video

![imagen](https://github.com/ikemen-engine/Ikemen-GO/assets/74574875/d064c553-888b-4f68-9a62-635129df2c02)

![imagen](https://github.com/ikemen-engine/Ikemen-GO/assets/74574875/dde28d5a-c553-4bc1-ab5e-7cb4cc1c3085)

### Engine Version (or source code date)

v0.98.2 and Nightly

### Operating system

Windows

### Extra context or search terms

Windows 11

**Comment by K4thos** [comment]
Closing as a duplicate for maintenance.
