### ISSUE TITLE
Runtime Error when opening character

### ISSUE THREAD

**Issue by anomaletix** [ikemen-engine/Ikemen-GO#1310]
### Describe the bug

When trying to play as the character in the fullgame (Maple Battle Royale: The Game), it gives me a runtime error.
[Ikemen(1).log](https://github.com/ikemen-engine/Ikemen-GO/files/11928539/Ikemen.1.log)

### To Reproduce

(This assumes you are using the Maple Battle Royale: The Game files to run the character, mostly because I think it has shit that is needed to make the character actually work. I think it works with just the straight MUGEN though? I don't know.)

1. Download full character from here: https://drive.google.com/drive/folders/1AOXYi1iCsGewNPbvnePg76v4Unn36M0H?usp=sharing

2. Put character folder in the chars folder and edit the select.def accordingly to have them appear on the character select screen.

3. Open the game and head to either Local Battle, or Training Mode. (I mainly use Training Mode, probably works the best.)

4. Select both characters, at least ONE of them being the modded character (Taylor).

5. You SHOULD get the runtime error and the game crashes.

### Expected behavior

The game opens and lets both players move as usual. 

### Screenshots / Video

This video shows the game crash happening. The error log appearing is the same as the one I put in the "Describe the bug" section.
https://github.com/ikemen-engine/Ikemen-GO/assets/88979751/3b5080b2-5460-4f37-b6ac-14d60b885051

### Engine Version (or source code date)

v0.98.1

### Operating system

Windows

### Extra context or search terms

-This character is actually using one of the roster (Noob specifically) as a base for making the character, mainly because he has all the files. Strangely, when I had first made this character just from a from-scratch .def, the game opened fine.

-Most of the move code is still intact from Noob, not sure if that would be a factor in the game buggin out like this as when it DID work from the new .def I didn't have any of Noob's move code in there.

-It ONLY happens with this character. I can play the game just fine, it's just trying to use this specific character that bugs it out.

**Comment by Lazin3ss** [comment]
Try using 0.99-RC1 or Nightly release, 0.98.1 is too outdated.
