### ISSUE TITLE
If playing on widescreen, the camera "skips" when the characters jump. yDelta is also different.

### ISSUE THREAD

**Issue by Hexioum** [ikemen-engine/Ikemen-GO#1319]
### Describe the bug

All my stages seem to have this problem where the delta movement is wrong (Probably because IKEMEN now reads a parameter that was being ignored)
But the main issue is the camera movement when characters lift off the ground or are about to land.

This problem does not happen with the stages bundled with the program.

### To Reproduce

1) Set the screen to 1280x720
2) Load any of these 2 stages [2stages.zip](https://github.com/ikemen-engine/Ikemen-GO/files/12023341/2stages.zip)
3) Jump

### Expected behavior

A smooth camera movement, which does work on the stages bundled with the program.

### Screenshots / Video

IKEMEN v0.99:
https://github.com/ikemen-engine/Ikemen-GO/assets/36753605/f3035761-94a7-4906-99fb-b03b71ccc8b9
https://streamable.com/zsnqmp
MUGEN 1.1:
https://github.com/ikemen-engine/Ikemen-GO/assets/36753605/356519ef-9ea9-463f-9c27-83ba059512cd
https://streamable.com/4hkxtx

*Edit: Added a streamable link in case the video upload didn't work.

### Engine Version (or source code date)

v0.99.0-rc.1 and nightly from Mar 9

### Operating system

Windows

### Extra context or search terms

Vertical movement, ydelta. Camera behaviour.

**Comment by Lazin3ss** [comment]
Campera skipping is related to mishandling of drawOffsetY field from `StageCamera` struct in camera.go. Delta issue... I'm not sure, I would need further understanding of background drawing to find a solution.

**Comment by NeatUnsou** [comment]
The issue with ydelta seems to be related to hires=1
currently, ydelta is broken for all stages that are using hires
