### ISSUE TITLE
Stunbar is displayed correctly in player p1 & p2.. but in p4 and p3 it is not displayed

### ISSUE THREAD

**Issue by ZyonZZ** [ikemen-engine/Ikemen-GO#1324]
### Describe the bug

the Stunbar is displayed correctly in player p2.. but in p4 and p3 it is not displayed.... despite being configured correctly..

I did not configure the Guardbar but I suppose it will be the same since perhaps the 2vs2 was not thought of and for that reason it was not given a configuration to be displayed in the p3 and p4 chars

As an addition I would like some option in config.json that could manage the hits needed to enter Stun.
just like the hits needed to lower the guardbar

### To Reproduce

the stunbar is not shown in "p3 and p4" in 2vs2 combat despite being configured..
the stun effect on the players does work... only the progress is not shown..
the same for the guardbar.

### Screenshots / Video

![Ikemen_GO 2023-07-17 20-19-27](https://github.com/ikemen-engine/Ikemen-GO/assets/129194444/53fa0d4b-dbfb-4ed6-9736-820f8d4fc00c)

![Ikemen_GO 2023-07-17 20-33-42](https://github.com/ikemen-engine/Ikemen-GO/assets/129194444/64c123bd-656d-4258-9c46-5656ec5789c7)
GreenCircle:: the stunbar in leona if it goes up ..
but in the character p4 it does not do it..

;Ikemen feature
[Stunbar]   ;;
p1.pos =0,200             ;;in p1  0,200
p1.front.spr = 14,20    ;;in p1  14,20          		;redstun bar
p1.range.x = 0,140         ;;in p1  0,140                   
p1.front.layerno = 2 

p2.pos = 1280,200
p2.front.spr = 14,20		;redstun bar
p2.range.x =  0,-140                 ;;
p2.front.layerno = 2
p2.front.facing = -1

;;stunbar Bug p3 and p4
p3.pos =0,205                       ;;0,400
p3.front.spr = 14,20                ;14,20          		;redstun bar
p3.range.x = 0,140                   ;;0,140                  
p3.front.layerno = 2 

p4.pos = 1280,205
p4.front.spr = 14,20		;redstun bar
p4.range.x = 0,-140         ;;0,-140                    
p4.front.layerno = 2
p4.front.facing = -1

### Engine Version (or source code date)

v0.99.0-rc.1

### Operating system

Windows

**Comment by K4thos** [comment]
i assume you have shared powerbars selected in options

**Comment by ZyonZZ** [comment]
> i assume you have shared powerbars selected in options

the problem persists... with "Team power share":: NO

**Comment by rakieldev** [comment]
I’m not sure I’d classify this as a bug. According to the documentation and the source, the engine specifically expects the `_3p` sections for a 2v1 fight and `_4p` for 2v2. Without those tags, sections without them don't take more than P1 and P2 into account. This is pretty clearly separated. Maybe we could rework it at some point, but for now, that's just how the engine works. Each section is necessary.
