### ISSUE TITLE
Stages with the RGB image splitting method show bugged behavior

### ISSUE THREAD

**Issue by Amidweiz** [ikemen-engine/Ikemen-GO#1326]
### Describe the bug

This is a historical bug that has existed within mugen that involves [Cyblasters automatic stage tool](http://network.mugenguild.com/cybaster/other/stage_tool.rar) specifically involving one of the methods you could use to split an image for optimization purposes. Historically discovered with [Warusaki3's CvS2 characters](https://mugedoso.web.fc2.com/warusaki3/index.html) where their super would cause the background to go completely white. Which Ikemen GO also displays this behavior however upon recent discovery, mugen 1.1b1 displays the correct behavior upon how the super effects should operate. I have also linked the 
[stage](https://github.com/ikemen-engine/Ikemen-GO/files/12088024/test.zip) I generated for this.

### To Reproduce

1. Download and install any one of [Warusaki3's CvS2 characters](https://mugedoso.web.fc2.com/warusaki3/index.html) and said [stage](https://github.com/ikemen-engine/Ikemen-GO/files/12088024/test.zip)
   -Optionally you can [use said tool to generate your own the RGB method](http://network.mugenguild.com/cybaster/other/stage_tool.rar)
2. Go into VS/Training/etc and perform a super with the CvS2 character on the stage.

### Expected behavior

Like mugen 1.1b1 the background should not turn white but rather just inversed. 

### Screenshots / Video

Ikemen GO:
https://github.com/ikemen-engine/Ikemen-GO/assets/55671166/ca7cf592-ff91-4fc5-9bf9-241172df6bb2
Mugen 1.0:
https://github.com/ikemen-engine/Ikemen-GO/assets/55671166/02cefb62-61f2-4ee4-b739-5a147c54dd60
Mugen 1.1b1:
https://github.com/ikemen-engine/Ikemen-GO/assets/55671166/2d9ce0ba-5c98-4d96-865c-5a9d7e795f1d

### Engine Version (or source code date)

v0.99rc1

### Operating system

Windows

### Extra context or search terms

For historical context people used this method before mugen 1.1 or SFFV2.1 came into existence with it's 32 bit sprites.

**Comment by Wftk** [comment]
I guess it got "fixed" by mugen 1.1 buggy behaivior because any palfx sctrl there inverts alpha as well, so "add" becomes "sub" and sub becomes add.

**Comment by potsmugen** [comment]
Might be the same phenomenon as #1088.

**Comment by K4thos** [comment]
and probably this one, if what Wftk mentioned is related #288
