### ISSUE TITLE
Zoom camera borders inconsistency

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1334]
### Describe the bug

I have a stage that worked fine in Mugen 1.1 and in the builds from a couple weeks ago, that suddenly started zooming to parts of the floor that should not be visible.

### To Reproduce

1. Try this stage:
[WaterfallDojo.zip](https://github.com/ikemen-engine/Ikemen-GO/files/12136663/WaterfallDojo.zip)

### Expected behavior

Same as Mugen 1.1.

### Screenshots / Video

Mugen 1.1:
![mugen007](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/7275625f-f0b2-4e2b-bca4-e48dff28b586)

Nightly:
![ikemen008](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/860f031b-99a3-4acb-a9b4-1cfe71715b2b)

### Engine Version (or source code date)

22/07/2023 (worked in 07/07/2023 build)

### Operating system

Windows

### Extra context or search terms

This might be an issue for another time, but while posting this I noticed that the camera zooms out further in Mugen than it does in Ikemen.

**Comment by Lazin3ss** [comment]
To fix this bug, a separation between zoom scaling and other bg positioning variables (delta, start, etc) should be made. Right now they're too entangled and modifying one will alter the other. For example, setting Delta Y to 0 on floor BG will "fix" the positioning when zooming out, but modifying Delta Y on MUGEN 1.1 has no effect on Y-axis positioning of BG elements after zooming out in a stage.

**Comment by K4thos** [comment]
From what I understand it has been fixed by #1346
