### ISSUE TITLE
Zoom factor inconsistency

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1335]
### Describe the bug

It looks like the camera zooms out further in Mugen than it does in Ikemen GO.

### To Reproduce

1. Add zoom to Mountainside Temple:
```
startzoom = 1
zoomout = 0.5
zoomin = 1
```
2. Compare screenshots

### Expected behavior

Same as Mugen 1.1

### Screenshots / Video

Here's a gif:
![Animation1](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/d67336bf-f586-45c6-b047-5e28eafe3d71)

The Mugen screenshot has the lifebars.

### Engine Version (or source code date)

22/07/2023

### Operating system

Windows

**Comment by Eiton** [comment]
This should be fixed in nightly.

**Comment by potsmugen** [comment]
Indeed.
