### ISSUE TITLE
Single character selection

### ISSUE THREAD

**Issue by 1240005127** [ikemen-engine/Ikemen-GO#1352]
It is very weird to select same character for each player. We need the function to select only one character in one gorup in game. And I hope there is the function to let both player only can do select single character. For example, like Metal Slug. If player1 select first character, the player2 can not select that character anymore.

**Comment by 1240005127** [comment]
We need that function can do this modify for game creator.

**Comment by lokpro** [comment]
"team duplicate" in settings can fulfil your first request.

**Comment by 1240005127** [comment]
> 

OMG, my bad. I found it! Thank you. Now I gonna try this function. Thanks for sharing your information! I try to make professional game.   Here is my video. https://www.youtube.com/watch?v=CG2VcTd0BZw
