### ISSUE TITLE
Big Motif empty Option menu

### ISSUE THREAD

**Issue by beterhans** [ikemen-engine/Ikemen-GO#1357]
### Describe the bug

Big Motif no Option menu empty

![Image](https://i.imgur.com/XnZvF7e.png)

### To Reproduce

download 0.99 RC 2
load /data/big/system.def

feels like font handling issue.

### Expected behavior

options displayed correctly

### Engine Version (or source code date)

v0.99 rc2

### Operating system

macOS

**Comment by SuperFromND** [comment]
This is likely because of the `Open_Sans.def` file being missing from the `font` folder.
[Open_Sans.zip](https://github.com/ikemen-engine/Ikemen-GO/files/12268128/Open_Sans.zip)

I believe this has already been fixed since this issue was filed, but perhaps just not applied to the macOS release of rc2. Sorry about that!

**Comment by K4thos** [comment]
it's already fixed, redownload the release

**Comment by beterhans** [comment]
> it's already fixed, redownload the release

I redownloaded RC2
it not been fixed.

the file still shows 3 days before
when I found the issue is 2 days before

the Open_Sans.def is in the font folder
just the IKEMEN macos can't handle ttf fonts. 

I tried other ttf fonts also can't be displayed

**Comment by K4thos** [comment]
what about RC1 and 0.98.2?

**Comment by beterhans** [comment]
> what about 0.98.2?

> what about 0.98.2?
just tested 0.98.2 have the same issue.  (but during the 0.982 time, I don't know how to change motif)

currently I modified save/config.json to change motif (is this the correct way?)
like
 "Motif": "data/big/system.def",
  "MSAA": false,
  "NumSimul"

0.99 rc1
the macOS binary can't run at all as far as i can remember

**Comment by K4thos** [comment]
same issue as #599, so I'm closing this one
