### ISSUE TITLE
Super not fully connecting

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#1362]
### Describe the bug

The flame pillar completely whiffs on Ikemen.

### To Reproduce

Download character: [Syo.zip](https://github.com/ikemen-engine/Ikemen-GO/files/12321087/Syo.zip)
Perform the super: 2x qcf + 2p

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/77592586/66fc393a-d66e-4077-a646-237d8de2fb33

MUGEN 1.1 - Correct behavior

https://github.com/ikemen-engine/Ikemen-GO/assets/77592586/25949033-fb6b-4a5c-bb13-52a32afa9b04

Ikemen GO v0.99.0 rc2 - Bugged

### Engine Version (or source code date)

v0.99.0 rc2

### Operating system

Windows

**Comment by potsmugen** [comment]
This is a difference in projectile behavior between Mugen and Ikemen. I'll upload a fix.
