### ISSUE TITLE
Modify IKEMEN_GO controls and I can't execute my custom configuration.

### ISSUE THREAD

**Issue by TheFighterSFMK2022** [ikemen-engine/Ikemen-GO#1363]
I'm facing an issue while trying to modify the controls in IKEMEN_GO. I have tried to modify the controls as shown below:

I would like to modify my IKEMEN_GO, I tried to modify this.
keymenu.itemname.up = "Up" ;Ikemen feature
keymenu.itemname.down = "Down" ;Ikemen feature
keymenu.itemname.left = "Left" ;Ikemen feature
keymenu.itemname.right = "Right" ;Ikemen feature
(like play station)
keymenu.itemname.up2 = "D-Pad Up" ;Ikemen feature
keymenu.itemname.down2 = "D-Pad Down" ;Ikemen feature
keymenu.itemname.left2 = "D-Pad Left" ;Ikemen feature
keymenu.itemname.right2 = "D-Pad Right" ;Ikemen feature
keymenu.itemname.a = "KickL" ;Ikemen feature
keymenu.itemname.b = "KickM" ;Ikemen feature
keymenu.itemname.c = "KickH" ;Ikemen feature
keymenu.itemname.x = "PunchL" ;Ikemen feature
keymenu.itemname.y = "PunchM" ;Ikemen feature
keymenu.itemname.z = "PunchH" ;Ikemen feature
keymenu.itemname.start = "Start" ;Ikemen feature
keymenu.itemname.d = "KickLMH" ;Ikemen feature
keymenu.itemname.w = "PunchLMH" ;Ikemen feature
keymenu.itemname.m = "Block" ;Ikemen feature
keymenu.itemname.menu = "Menu" ;Ikemen feature
keymenu.itemname.back = "Back" ;Ikemen feature
keymenu.itemname.page = "Page" ;Ikemen feature.
![Captura de pantalla 2023-07-14 075003](https://github.com/ikemen-engine/Ikemen-GO/assets/115765959/ab3af834-37d6-44be-9e34-f34b4d801044)
how to see the image, it does not appear
keymenu.itemname.up2 = "D-Pad Up" ;Ikemen feature.
keymenu.itemname.down2 = "D-Pad Down" ;Ikemen feature.
keymenu.itemname.left2 = "D-Pad Left" ;Ikemen feature.
keymenu.itemname.right2 = "D-Pad Right" ;Ikemen feature.
keymenu.itemname.m = "Block". ;Ikemen feature.

However, I'm encountering difficulties in getting my modified configuration to work. I followed the advice of someone who suggested downloading the IKEMEN_GO repository and attempting to modify it there. Unfortunately, my attempts have not been successful.

Solution I'm Seeking:
At this point, I'm feeling stuck and unable to proceed. If anyone in the community has experience with modifying controls in the 'ikemen_go' repository, I would greatly appreciate your assistance. It would be incredibly helpful if someone could create a video tutorial demonstrating the process and explaining how to make the modifications work. This would not only show me that it's possible but also guide me through the steps, given that I'm facing difficulties doing it on my own.

Thank you for your help."

**Comment by K4thos** [comment]
there is no such parameters like "keymenu.itemname.up2". Issues section is for reporting bugs, not giving advice how to implement features that don't exist.

**Comment by TheFighterSFMK2022** [comment]
> there is no such parameters like "keymenu.itemname.up2". Issues section is for reporting bugs, not giving advice how to implement features that don't exist.

I see that the English translation of my post does not match my problem, I have asked my friend to translate in English and I see that it was wrong, now I had to translate it very detailed into English in google translate, Sorry, I have to modify this post.
