### ISSUE TITLE
PotS styled characters with projectiles that do multiple hits adding to the visible hitcount if they clash.

### ISSUE THREAD

**Issue by RagingRowen** [ikemen-engine/Ikemen-GO#1371]
### Describe the bug

When you fire a multi-hit projectile and the other character does the same, when they collide they add to the combo popup when they shouldn't. 

This was pointed out by Json.

### To Reproduce

1. Download a PotS '08 styled character that uses multi-hit projectiles. (Iori by KarmaCharmeleon used as a recent example)
2. Have two multi-hit projectiles (as helpers) clash with each other.

### Expected behavior

No additions to the hitcount.

### Screenshots / Video

https://streamable.com/xxfk91

### Engine Version (or source code date)

v0.99 RC2

### Operating system

Windows

**Comment by potsmugen** [comment]
This one's also fixed by #1515.
