### ISSUE TITLE
Black Border at Bottom of Stage

### ISSUE THREAD

**Issue by Flowrif** [ikemen-engine/Ikemen-GO#1376]
### Describe the bug

When I start a match , the stage shows a black , semi transparent border at the bottom. Some Stages actually cut the players legs off. 

### To Reproduce

1. Downloaded latest Ikemen GO release
2. Added stages and characters. I did not add screenpack for testing purposes.
3. Start match in any mode

### Expected behavior

The stage is suppose to show proplerly 
![Screenshot (289)](https://github.com/ikemen-engine/Ikemen-GO/assets/100743148/28b15b61-37b2-4f0d-b103-2b3e4a36abbc)

### Screenshots / Video

![Screenshot (287)](https://github.com/ikemen-engine/Ikemen-GO/assets/100743148/db8aff37-1431-4806-a342-31151a90ba4e)

### Engine Version (or source code date)

v0.99.0-rc.2

### Operating system

Windows

**Comment by Flowrif** [comment]
Issue Still persists in 0.99 Latest Release

**Comment by K4thos** [comment]
This report is unproducible as it stands. Please upload the stage here so that it can be tested locally, otherwise the ticket will be closed.

**Comment by Flowrif** [comment]
What format should I upload the stage in? The system only allows documents
