### ISSUE TITLE
Zoom interfering with stage corner behavior

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1380]
### Describe the bug

It looks like some combinations of stage camera and character constants can allow characters to jump over the enemy in the corner of a stage.

This doesn't seem to happen in 0.98.2

EDIT: Actually it does happen in 0.98.2 as well. It was just less likely to happen because tensionhigh and tensionlow were not working properly.

### To Reproduce

1. [Download this char](https://www.mediafire.com/file/lpz0s809wrr82df/geese_pots.zip/file)
2. [And this stage](https://www.mediafire.com/file/mijswtzwvcdaq7t/GoukenTempleAlt.zip/file)
3. Try to jump over KFM in the corner of the stage
4. Disable the stage's zoom or change boundleft and boundright
5. Try to jump over KFM again

UPDATE:
Actually there's an easier way to reproduce it: double jump with KFM over P2.

### Expected behavior

P1 should not be allowed to jump over P2 in the corner of a stage. This normally happens already, but it seems there's something about zooming that can break it.

### Screenshots / Video

![ikemen008](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/f242a251-b3df-4ea8-a878-1205487fd220)

https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/964f2bb0-1a71-4f9c-8614-0cf9d85b384e

### Engine Version (or source code date)

25/08/2023

### Operating system

Windows 7

**Comment by potsmugen** [comment]
Update: This happens at least all the way back to 0.99 RC1.

**Comment by K4thos** [comment]
I can't reproduce it on nightly anymore, so I assume it's fixed. Please let me know if the ticket should stay open.

**Comment by potsmugen** [comment]
Sadly it's still there.

**Comment by K4thos** [comment]
some better test case may be needed, I can't replicate it

**Comment by potsmugen** [comment]
I thought that was odd so I checked in different game resolutions and for this stage it only happens in 4:3. Which only makes it weirder since 4:3 is the base resolution.

I've seen people post a similar issue on Discord in a different stage in 16:9, however.

It takes a particular interaction of zoom and character velocities/positions for it to happen, so it won't be the same in every stage with every character. In the uploaded stage in 4:3 resolution, Kung Fu Man can trigger it with double jumps.
