### ISSUE TITLE
Palettes apply to this character in MUGEN1.1 but not IKEMEN Go 0.99 RC2

### ISSUE THREAD

**Issue by lovelydumpling** [ikemen-engine/Ikemen-GO#1382]
### Describe the bug

The character is Izayoi by Deoxgigas. For some reason, palettes do not apply to the character correctly, she will always have her default palette. Notably however, the shield in her intro does change palette.

The palettes work correctly in MUGEN 1.1, so it seems to be an issue with IKEMEN.

### To Reproduce

[Download Izayoi from here.](https://onedrive.live.com/?authkey=%21AP3dhJMk2Rc%5FOdo&id=CA799DA891DFB124%21304&cid=CA799DA891DFB124)

Try out her various palettes. She will look the same across them all, although the shield that forms her armor will be of a different palette in her intro. 

### Expected behavior

The palettes should apply correctly and she should look differently based on what button was pressed to choose her, like it does in MUGEN.

### Screenshots / Video

MUGEN 1.1:
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/30986053/82d204be-4ddd-444b-824b-b04e45adf5d0)

IKEMEN GO 0.99 RC2
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/30986053/ff242664-ae2a-491b-8439-db9ad8a0fe97)
![ikemen015](https://github.com/ikemen-engine/Ikemen-GO/assets/30986053/c6ce248e-2e4b-4a9d-aa27-f5c5a7784d57)

### Engine Version (or source code date)

0.99 RC2

### Operating system

Windows

### Extra context or search terms

palettes, pal, remappal

**Comment by potsmugen** [comment]
Just to add that this did not happen in 0.98.2 or 0.99 RC1. Though I did have one instance where loading 2 of this char in 0.98.2 made the screen go black.

**Comment by SuperFromND** [comment]
I just went ahead and looked through commits between 0.99rc1 and 0.99rc2, and after building to confirm, I can definitely say this regression started at the commit 105cf553d3f609896f9eeb739791c83822a73da5. 

![image](https://github.com/ikemen-engine/Ikemen-GO/assets/22881403/ab92664f-f174-4143-98ce-b8a34e76d43d)
