### ISSUE TITLE
Shadows not matching scaled or rotated sprites.

### ISSUE THREAD

**Issue by smackyjackson** [ikemen-engine/Ikemen-GO#1406]
### Describe the bug

When using Xshear on a stage, the shadows will malfunction if the character is scaled down, or rotated. It will instead display the normal shadow with no distortion, except moved to the X position of the shear. 
If a sprite is 1:1 scale and has not interpolation or rotation, the shadows will display properly. They also display properly in mugen 1.1.
Her is a picture showing the issue. Character on the left is scaled down 50%, character on the right is rotated. The shadows do not match.
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/127048865/055f6d5f-f21d-4250-85d3-7601c2116c3e)

Here is an image from the same map used in mugen 1.1 with a scaled down fighter. The shadow is properly aligned.
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/127048865/0348ed24-59a6-4d38-b127-3ba3206ed899)

### To Reproduce

1. Use any character.
2. scale them down using any method. Either scaling in the anim, or constants. Alternatively rotate the sprites in the anim, as that affects them as well.
3. go to any stage with shadows turned on.
4. Increase the Xshear by a noticeable value. 0.4 is what i used. 
5. Shadow should be displaced from character, and or not match the animation.

### Expected behavior

Shadows should match sprite no matter what, like 1.1.

### Screenshots / Video

![image](https://github.com/ikemen-engine/Ikemen-GO/assets/127048865/055f6d5f-f21d-4250-85d3-7601c2116c3e)

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

### Extra context or search terms

Shadows
Xshear
Scale

**Comment by Lazin3ss** [comment]
I didn't take into account scaling and rotation when implementing xshear, gonna fix this after 0.99

**Comment by potsmugen** [comment]
Even with unmodified sprites they seem to be misbehaving in different localcoords. Here's a 640x480 stage:
![ikemen000](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/837f413c-af8a-4875-8f8b-3b76dfdc963c)

**Comment by softmgr** [comment]
I also encountered this bug.

**Comment by K4thos** [comment]
already fixed
