### ISSUE TITLE
Effects And explosions have a transparent background bugged

### ISSUE THREAD

**Issue by MisukiKTH** [ikemen-engine/Ikemen-GO#1411]
### Describe the bug

It's a bug where some effects have a black background around them, this happens with the sub effect

### To Reproduce

So i discovered the source of the bug, it's in palFx, with the add, the add makes the black background appear:
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/145942077/deedc6d0-4b74-4555-82d9-9dcfb89c4091)
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/145942077/70da2d21-cafe-4f8f-9213-9a89d8800f47)
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/145942077/53bacb5e-7105-4bdf-a3fe-fa7b88536540)
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/145942077/3760e9a1-f8f6-483a-8113-8b4648c97066)
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/145942077/cb1671ef-ff30-475c-97e2-a55a694020bf)

the bug is in the palfx code, and this is an ikemen bug because I tested it in the original mugen and it worked, both with the character in 1.1 and 1.0, and in other versions of ikemen it doesn't happen like InSeph.
https://www.youtube.com/watch?v=YfXvAuWFc18

### Engine Version (or source code date)

v0.99.0-rc.3

### Operating system

Windows

**Comment by Wftk** [comment]
Did some tests, its related to palfx "add" param value inverse if blend = sub, it also related to this issue #989. Because after fixing add param inverse it solved problem there too.
