### ISSUE TITLE
How Z axis function work?

### ISSUE THREAD

**Issue by 1240005127** [ikemen-engine/Ikemen-GO#1412]
I try to make Capcom's cadillacs and dinosaurs. But after check IKEMENGO's Wiki, there is no information about the Z axis. We need Z axis to make Z axis game.

**Comment by K4thos** [comment]
issues section is not a place for asking questions

**Comment by 1240005127** [comment]
Thank you, my bad. I will go to discussions area to ask question. Sorry to make mistake.
