### ISSUE TITLE
Boss: David Bell doesn't get more damage in specific chars

### ISSUE THREAD

**Issue by FrankSP7ps** [ikemen-engine/Ikemen-GO#1413]
### Describe the bug

Apparently the boss, David Bell by The_None and Balthazar, has a bug about not getting more damage, right when he has little remaining of health.

Characters that no matter the attacks, special, supers, the damage that he recieves, he doesn't get more damage, when he only has a little remaining of health.

-Those characters that suffer in not give the K.O on him in this engine are:
Blossomko
Kinyo 
Dink (2017)
Beavis
Butthead
Blizzard.
All of them made by the same autor, T_N.

But surprisely not only some chars of that autor.
Raiya Mikazuchi by  エス  
MC-Hisui by Maitake 

Suffer of this problem too.
And so that means that some other character there can suffer of this too.

Meanwhile in Mugen 1.0 or 1.1 beta, Any of these characters can give K.O to him without problems.

I doubting if it is a engine problem or just a autor code that doesn't react propely in Ikemen GO.

### To Reproduce

David bell can be downloaded on T_N, Aokmaniac13 page, Logical Bends.
https://www.justnopoint.com/lbends/index.php?location=chars&page=1

Same goes for Blossomko, Dink, Kinyo, Blizzard, etc. 

Raiya Mikazuchi by  エス can be downloaded here:  https://www.mediafire.com/download/e060bfzfu4ybo47/Raiya+Mikazuchi%28%C6%92G%C6%92X%29.rar

MC-Hisui by Maitake can be downloaded here: 
https://web.archive.org/web/20180212025505/http://www.geocities.jp/aozora302/chars/MC_Hisui.zip

1: Play or put David bell as the opponent.

2: Play any of the characters that I mentionded.

3: Attack him until you see he has little health remaining.

4: If in that point the boss should not suffer more damage by these chars.
Unless if some chars that is not mentioned like KFM and Mech Hisui 404 by Sennou Room for example, then It would get damage propely.

### Expected behavior

David Bel should no get more damage If:

-He has a little remaining of health
-The opponent is one of the characters that I mentioned
-If the opponent is not one of the characters that I mentioned or suffer of this problem, the opponent should logically give damage to him and give K.O

### Screenshots / Video

Tested in Ikemen go, playing as Blossomko and Kinyo, trying to give K.O to him. David Bell seems not to give any reaction to damage on last remaning of health on these chars.
https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/a277063d-66d6-4096-a773-306978ba0878

Still in Ikemen go. Controlling Mech Hisui 404 for this one. This time David Bell gives the proper reaction, get a K.O
https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/603a4f20-486d-4c5e-9ee2-d2cc9d0ad455

Tested in Mugen 1.1, playing again as Blossomko and Kinyo. David Bell gives propely the K.O as it should be.
https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/70075f41-810a-4a3b-9ead-a4a10a0a0c89

### Engine Version (or source code date)

v.0.98.2

### Operating system

Windows

**Comment by potsmugen** [comment]
Looks like this happens because in Mugen helpers can receive more damage than the life they have left.

I found the solution but it made me wonder if that behavior couldn't also extend to players as well.
