### ISSUE TITLE
AssertSpecial NoMakeDust doesn't work in KFM backwards dash

### ISSUE THREAD

**Issue by LasombraDemon** [ikemen-engine/Ikemen-GO#1415]
### Describe the bug

The assertspecial doesn't hide KFM's backwards dash little cloud of dust with KFM when he touches the ground. :(

Works in other instances.

### To Reproduce

Backdash with KFM while asserting the SCTRL. Other dust instances are hidden, this one isn't.

### Expected behavior

https://github.com/ikemen-engine/Ikemen-GO/wiki/State-controllers#nomakedust

NoMakeDust

While asserted, player is not generating hardcoded dust

### Screenshots / Video

![ikemen000](https://github.com/ikemen-engine/Ikemen-GO/assets/74574875/3fe9cf15-1b48-449a-8644-45d94b8f0d17)

### Engine Version (or source code date)

v0.99 RC3

### Operating system

Windows

**Comment by Lazin3ss** [comment]
I have the impression NoMakeDust should also disable dusts made with MakeDust SCTRL too 🤔
