### ISSUE TITLE
Unemulated behavior when hitdefattr does not contain =

### ISSUE THREAD

**Issue by jenngra505** [ikemen-engine/Ikemen-GO#1418]
### Describe the bug

When using the code line trigger1 = hitdefattr in Mugen 1.0 or 1.1, the engine does not crash but instead responds as if it were valid code, if you try to do this in IKEMEN the engine will crash.

### To Reproduce

1. Download Spooky from http://www.mediafire.com/file/fp1kqu8hkahub2i/Spooky.zip/file
2. Try to run character
3.

### Expected behavior

The character will run but a debug error will pop up when the state is entered.

### Screenshots / Video

![image](https://github.com/ikemen-engine/Ikemen-GO/assets/18198665/d07bfe90-3f7f-4744-9911-840b155bc9ce)

### Engine Version (or source code date)

v0.99 RC3

### Operating system

Windows

**Comment by potsmugen** [comment]
This is already reported in #1102 and #1004.

For what it's worth, that code does nothing in Mugen either. It just doesn't crash.
