### ISSUE TITLE
some chars have a broken shadow

### ISSUE THREAD

**Issue by notkidgamer23** [ikemen-engine/Ikemen-GO#142]
I noticed quite a few chars have a shadow that's just a box, no detail or shape just one big box as their shadow. It happens with several chars, but it's fairly easy to replicate with Om Hy's Sasuke. When running forward the shadow is fine but running backward causes it to turn into a large square. Here's a link to the Sasuke https://youtu.be/eq1q6n1ISHA (direct download https://drive.google.com/file/d/1e5ft8qQVzqyTdArTbYDTPCKiFAS2ik62/view )

**Comment by K4thos** [comment]
fixed
