### ISSUE TITLE
Looped sound doesn't stop

### ISSUE THREAD

**Issue by jankespro12** [ikemen-engine/Ikemen-GO#1422]
### Describe the bug

When i was using Ikemen Go 0.99.0-rc3, when i did the Hiden Houoh Kyaku with Soy_Sauce's Kim, looped sound should stop instead of keep playing the sound. Can you fix this plz?

### To Reproduce

Character: Kim Kaphwan by Soy_Sauce
Move: Hiden Houoh Kyaku
Error: Sound Doesn't Stop

### Expected behavior

Looped sounds should stop

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/63473068/eb162f19-4452-4e68-b27e-548dd5db1c8c

### Engine Version (or source code date)

v0.99.0-rc3

### Operating system

Windows

**Comment by Eiton** [comment]
https://github.com/ikemen-engine/Ikemen-GO/releases/tag/nightly
Did you try the nightly build?

**Comment by jankespro12** [comment]
I did not, but i will try

**Comment by jankespro12** [comment]
I tried the nightly build, and then, used the Kim's Hiden Houoh Kyaku super, and the looped sound stopped here!

**Comment by Eiton** [comment]
That means this issue is fixed in the latest build and can be closed.
