### ISSUE TITLE
A specific sound on Franko (WSMIP) and Missigno still plays if you pause on the right moment, even outside of the match.

### ISSUE THREAD

**Issue by FrankSP7ps** [ikemen-engine/Ikemen-GO#1425]
### Describe the bug

Not sure if someone did already report this with other that may share this problem, but oh well.

The deal here is that Franko (WSMIP Budokai version) and MNO made by the same autor, The_None have a little problem about how a specific sound plays. If you pause the game being menu or the pause/break putton of your keyboard right when the sound plays, it will be still playing, besides that it desafinate the tone somehow if you do other moves.

### To Reproduce
**Be careful doing as the sounds here obviously hurts for you ears, I suggest to down your volume when you try this.**

Franko you can get from WSMIP Budokai:
https://www.justnopoint.com/lbends/wsmip/
It should work fine outside with some little deal that just included the common1.cns in his folder.
Be aware that he is only 1.1 only, but it should work fine in Ikemen GO.

(The one of the video is a edited one by me, it is standlone, with no requiring of the common1.cns, besides that I included fightsparks sprites and stuff in his .sff and .snd)

Missigno on same page:
https://www.justnopoint.com/lbends/index.php?location=chars&page=1

Go do a match or training.

Franko: Do the fart loading bar super by pressing Y+Z and let the opponent touch the bar so then get lagged.

Missigno by doing any of his supers, that screen always appears.

### Expected behavior

It should play sound there normally.
If you pause right when the sound plays, that's where the bug happends.
I repeat, reccomend have the volume down tho, kinda hurts hearing it.

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/981cd263-fd6b-4d17-aa6c-6aa8da0f2c6c

### Engine Version (or source code date)

0.99.0-rc.3

### Operating system

Windows

**Comment by potsmugen** [comment]
Please try it on [the nightly build](https://github.com/ikemen-engine/Ikemen-GO/releases/tag/nightly) since it sounds like an issue that was recently fixed.

**Comment by FrankSP7ps** [comment]
Test it and well yeah it did gets fixed most of the part.
Only 1 little detail.
When the sound is like the one last bit for that super, it happens again but it gets quick solved by using the super again and hopefully the opponent gets lagged again so it stops.

Alternaly by just quitting the match, the sound is stopped.

For Missigno I must imagine it must be the same but with his super background.

Here a video example of what im reffering of "When the sound is like the one last bit for that super, it happens again but it gets quick solved by using the super again and hopefully the opponent gets lagged again so it stops."

https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/c753f406-fefb-49a9-8325-4410d0117be0
