### ISSUE TITLE
victory bgm plays contionusly

### ISSUE THREAD

**Issue by iamno1one** [ikemen-engine/Ikemen-GO#1431]
### Describe the bug

victory screen bgm carries on playing indefinatly

### To Reproduce

start a team versus
tag 
defeat opponent 
victory screen needs to have a looped bgm 

once you press a button victory screen bgm carries on playing indefinatly

### Expected behavior

victory bgm to stop upon button press or when the screen reverts to char select screen

### Screenshots / Video

victory.bgm = sound/Winning.mp3

needs to be defined in screenpack 

system.def

### Engine Version (or source code date)

v99rc3

### Operating system

Windows

**Comment by potsmugen** [comment]
Does it play over the other screenpack BGM's? It should probably be set up in a way that only one BGM can play at a time.

**Comment by iamno1one** [comment]
it keeps repeating does not stop at all

**Comment by Lazin3ss** [comment]
Doesn't happen to me in RC5

**Comment by Ganbare-Lucifer** [comment]
It also happens to me.

Is it fixed on the stable release?

**Comment by K4thos** [comment]
Please upload a build based on a stable release so that we can test it. Otherwise I'm going to lock this ticket.
