### ISSUE TITLE
Projectile inconsistency between 1.0 and Ikemen GO

### ISSUE THREAD

**Issue by SynErrorD11** [ikemen-engine/Ikemen-GO#1445]
### Describe the bug

Just found an inconsistency between Mugen 1.0 and Ikemen GO regarding the way projectiles work. This breaks states that use projectiles as regular effects, or in any other manner, even thought they have movetype = i, other players can get stuck into guard states.

### To Reproduce

Just add any regular projectile into negative states, doesnt matter if the animation has collision boxes or not. Other players as soon as they get close to it, they'll tend to enter guard states whenever you press back.

### Expected behavior

On 1.0, this behavior is different by just changing the color of the hitbox from blue to purple. If its purple and the char just received a hit, instead of hurt states, its gonna be redirected into guardstates.

### Screenshots / Video

1.0 behavior: 
https://github.com/ikemen-engine/Ikemen-GO/assets/148153298/6499aa3c-58ba-4d97-8c9a-77566f5b6e5f

Ikemen GO:
https://github.com/ikemen-engine/Ikemen-GO/assets/148153298/0bc558e9-deae-4b20-9362-587121a5fb4f

Tested on all 0.99 RCs from 1 to 4, and all display the same behavior.

### Engine Version (or source code date)

.99

### Operating system

None

**Comment by potsmugen** [comment]
Interesting. You can see that in Mugen they can trigger the blocking flag (hurtboxes become purple) but not proximity guard.

**Comment by potsmugen** [comment]
Do you mind sharing the projectile code you used? I thought the thing here would be with projectiles lacking Clsn1, but it looks like Mugen makes the char guard those as well.

**Comment by potsmugen** [comment]
This bug also happens in a mirror match with this char:
https://drive.google.com/file/d/1A-PCbrk4nqeEWHtgOZNVm0THzSxQHSG8/view

When you walk past the knife on the floor, a blank projectile will make the enemy guard.

It looks like Mugen only lets you guard projectiles when they have an actual attack attribute.
