### ISSUE TITLE
Shadows are just squares

### ISSUE THREAD

**Issue by DakBulletStorm** [ikemen-engine/Ikemen-GO#1449]
### Describe the bug

Hey I found that the shadows with one of my char's does not render properly.Here are some screenshots
**Mugen 1.1**
![mugen000](https://github.com/ikemen-engine/Ikemen-GO/assets/90212312/1db7706d-9efd-481e-92dc-d7e1187f27d9)
![mugen001](https://github.com/ikemen-engine/Ikemen-GO/assets/90212312/bf0c1980-3fd9-4dfe-8380-d2ec3a97994f)
![mugen002](https://github.com/ikemen-engine/Ikemen-GO/assets/90212312/1fddc12f-317c-4e5b-85ec-469ea5f3505a)
![mugen003](https://github.com/ikemen-engine/Ikemen-GO/assets/90212312/0dfe7bb5-ed2a-4473-9253-0acc8cda7f0d)

**Ikemen Go, v0.98.2**
![ikemen002](https://github.com/ikemen-engine/Ikemen-GO/assets/90212312/dadacbae-b8b4-4dfb-8be2-d91c80f65caf)
![ikemen003](https://github.com/ikemen-engine/Ikemen-GO/assets/90212312/42f015e1-f015-4021-90fe-8af9b781a479)

**Note the inconsistency with the two attack states, where in state 3000, the shadow is broke, while in state 200, the shadow isn't**

![ikemen006](https://github.com/ikemen-engine/Ikemen-GO/assets/90212312/c20b9e32-8fe7-4e0e-b076-52f0901f9846)
![ikemen007](https://github.com/ikemen-engine/Ikemen-GO/assets/90212312/5452d6c8-d5d9-478e-9302-a0e95360d756)

### To Reproduce

This can be replicated with Om Hy's Itachi. Specifically in the standing, jumping, crouching, running, and some other assorted states, Itachi's shadow is just a rectangle. However, (some of) his attack states seem fine. [This is the link to the video, the download link is in the description. ](https://www.youtube.com/watch?v=V-a9ajNdk1E&t=99s&ab_channel=omHy)

### Engine Version (or source code date)

v0.98.2

### Operating system

Windows

### Extra context or search terms

This is because of the transparent part of the sprites being rendered with the shadow, but even that isn't consistent (shown with anim 200). If this could fixed, that would be great. Thanks

Note: this still is an issue in the latest release.

**Comment by Wftk** [comment]
It's happens because char palettes done in weird way,and seems like shadows still consider first color in palette slot as transparent one this is why in combo moves it show correct behavior because pallete there been done right and color in first slot is the bg one. But its bug indeed.

**Comment by K4thos** [comment]
does it happen in rc4?

**Comment by DakBulletStorm** [comment]
yeah it happens in rc4, downloaded it fresh and put in the char just to make sure. [Here's the video](https://youtu.be/DDzYHAKPnTw)

Is there at least a way I can work around it?
