### ISSUE TITLE
Setting hit priority based on a variable produces different results in IKEMEN GO and MUGEN 1.1

### ISSUE THREAD

**Issue by SaltAddict** [ikemen-engine/Ikemen-GO#1450]
### Describe the bug

I don't quite understand whats going wrong here so I'll do my best to explain.

`priority = cond(var(58) = 1, cond(var(19) = 1, 7, 1), 4), hit`

I'm using that line above on all my hitdefs to change the priority of the hit based on the value of var(19). If var(19) is 1, the hitdef will have priority = 7 and if var(19) is -1, then the hitdef will have priority = 1. At the beginning of the round, p1's var(19) is set randomly to either 1 or -1, and p2's var(19) is then set to the opposite of p1's. This way, one player is randomly chosen to "win" all hit trades for that round, which is how it works in the original Mortal Kombat games. Basically, both players should not be able to hit each other at the same time.

Var(58) is there so that the system can be turned on and off through a config file. 

Now, in MUGEN 1.1, this works exactly how you would expect, but in IKEMEN GO, if p1's var(19) is set to -1, the hits will still trade, even though debug mode shows all the values are being set up correctly. You can see this in the images I posted below, 1st one is MUGEN 1.1, the other two on the hell stage are on the latest version of IKEMEN GO, showing that both p1 and p2 are using the correct values but are still able to hit each other at the same time. This does not seem to happen if p1's var(19) is set to 1. These were tested using the same attack activated on the exact same frame.

### To Reproduce

1. Get character from https://mugenguild.com/forum/topics/cage-mk2-beta-release-1-197739.0.html

2. Use the same attack at the same time on both p1 and p2 sides.

3. The hits will "trade" and both players will hit each other.

### Expected behavior

Both players should not be able to hit each other at the same time.

### Screenshots / Video

![screen](https://github.com/ikemen-engine/Ikemen-GO/assets/62810901/535285c7-d84d-4617-beca-0bd7cb161827)
![ikemen001](https://github.com/ikemen-engine/Ikemen-GO/assets/62810901/a2c1c03f-49b4-4cf9-9ce6-ee4fc26e6a0a)
![ikemen002](https://github.com/ikemen-engine/Ikemen-GO/assets/62810901/ff8651ea-2e6c-4698-9e93-aa7c1d2e036a)

### Engine Version (or source code date)

v0.99rc4

### Operating system

Windows

**Comment by potsmugen** [comment]
Can't reproduce it in current build. Every time I Shift F4 the winner for that round is correctly randomized.

Are you sure you tested in RC4? It sounds a lot like issue #1410, which was recently fixed.

**Comment by SaltAddict** [comment]
Oops, my bad, it was RC3. Sorry about that. Glad to hear it's already been fixed.
