### ISSUE TITLE
Continue screen doesn't display helpers.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#1451]
### Describe the bug

If a character's win pose has a helper it won't be displayed on continue screen.

### To Reproduce

Download sakura
[Sakura.zip](https://github.com/ikemen-engine/Ikemen-GO/files/13081157/Sakura.zip)

Let her win the match(not by perfect) on arcade mode and hold start to trigger the win pose with her friend.

### Expected behavior

The helper to be displayed on continue screen.

### Screenshots / Video

![ikemen000](https://github.com/ikemen-engine/Ikemen-GO/assets/77592586/9ffc13c6-6965-4715-9d3d-52718b874488)
![ikemen001](https://github.com/ikemen-engine/Ikemen-GO/assets/77592586/c95cb9fa-0977-4479-b0f9-2af58a6ab7d4)

### Engine Version (or source code date)

Nightly

### Operating system

Windows

**Comment by potsmugen** [comment]
Perhaps this was done intentionally so that custom victory screens don't linger in the continue screen.

**Comment by K4thos** [comment]
intentional, iirc
