### ISSUE TITLE
Stage Zoom doesn't work

### ISSUE THREAD

**Issue by MisukiKTH** [ikemen-engine/Ikemen-GO#1456]
### Describe the bug

So, I was wanting to port my game to the rc4 version of ikemen, but a bug in the scenarios is bothering me. In version 98.2, the scene zoom works fine and the camera is centered too, but I don't know why in current versions, the scenes don't have functional zoom.
 
image references:
rc4: 
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/145942077/25504e18-6292-40dd-b280-e51db32e8955)

98.2:
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/145942077/2817db3c-a24a-4275-bcbb-b107662f6012)

in both versions the localcoord has the same value
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/145942077/72ec3db4-ce72-45bf-83a5-d4cc5aaf6bbf)

but when I tried to change the value, this happened...
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/145942077/7dc495f1-1029-468e-ba76-a66d050efd7f)
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/145942077/543bc5d6-e377-4ca1-bf6b-b5a0e861f688)

If you could support me and resolve this bug, that would be amazing, have a great day!

### To Reproduce

So, I was wanting to port my game to the rc4 version of ikemen, but a bug in the scenarios is bothering me. In version 98.2, the scene zoom works fine and the camera is centered too, but I don't know why in current versions, the scenes don't have functional zoom.

### Engine Version (or source code date)

v0.99.0-rc.4

### Operating system

Windows

**Comment by TitanUranus83** [comment]
Try adding
[Camera]
zoomanchor = bottom

**Comment by MisukiKTH** [comment]
> Try adding [Camera] zoomanchor = bottom

nothing happened, I'm going to delete this bug, and I'm going to redo the scenarios from scratch again. But I'll report another one I found, which is quite... boring.

**Comment by ZyonZZ** [comment]
> > Try adding [Camera] zoomanchor = bottom
> 
> nothing happened, I'm going to delete this bug, and I'm going to redo the scenarios from scratch again. But I'll report another one I found, which is quite... boring.

so that in the next version they play the stages again and they are deconfigured again... I gave up, I stayed on the Nighty... and until a super-fixed version comes out with some improvement that I like, I'll change... because rc1 rc2 rc3 have scenario changes and I'm already bored of fixing them xD, I advise you the same... stay on a previous version. xDDD

**Comment by Lazin3ss** [comment]
please let us know if the stage works the same in MUGEN as in RC4+. If it's like that, please close the issue, otherwise upload the stage so we can take a look
