### ISSUE TITLE
X/Y offsets defined in animations are incorrectly scaled when placed in a custom state

### ISSUE THREAD

**Issue by Jmorphman** [ikemen-engine/Ikemen-GO#1459]
### Describe the bug

If a character (let's call them P1) is placed in a custom state by an opponent (P2) with a different localCoord than P1's own, and if that custom state makes P1 play one of their own animations (ie, ChangeAnim, not ChangeAnim2), and if that animation has any elems that use an x or y offset, those offsets will be scaled according to P2's localCoord, not P1's.

As an example: assume P1 has a localCoord of 1280x720, and has an animation with index 100, consisting of a single AnimElem with x and y offsets both set to 80. Let's also assume that the game's localCoord is 320x240, and P2 has also has the localCoord of 320x240. If P1 were to play their animation 100 normally, outside of any custom states, those offsets would be reduced to 20, as a result of proper localCoord calculations, and the animation would be displayed as intended. If however P2 were to put P1 into a custom state, and had P1 execute a ChangeAnim sctrl that made them play P1's animation 100, those offsets would not be reduced to the correct amount; they will instead both be left unscaled (as 80), since P2 and the game have the same localCoord.

### To Reproduce

1. [My own Kyo](https://network.mugenguild.com/jmorphman/wp-content/uploads/characters/Kyo.7z) whose punch throw (B/F + any 2 punches) does exactly what is described above: it makes the opponent play their animation 5160, which is frequently one that uses a y offset.
2. kfm720 is a very convenient testing dummy for this because he not only uses a different localCoord than Kyo, but he also has a 5160 anim with a sizeable y-offset.
3. Have Kyo use his punch throw on kfm720.

### Expected behavior

In MUGEN, this error is not at all present; a character will always have their animation offsets scaled to the correct amount, even in a custom state.

### Screenshots / Video

First, this is how bog standard KFM looks when being thrown:
![localcoord offset scaling (KFM)](https://github.com/ikemen-engine/Ikemen-GO/assets/22782271/eb6c7acc-6703-46b6-ab21-7acfd4832d14)

Here is kfm720 using the unscaled y offset amount, causing him to be drawn below the floor:
![localcoord offset scaling (KFM720)](https://github.com/ikemen-engine/Ikemen-GO/assets/22782271/0547a7ae-a4d0-44a5-b77a-35e384f5d2a4)

Adjusting Kyo's own localCoord to 1280x720 produces the expected behavior in kfm720:
![localcoord offset scaling (720p kyo vs KFM720)](https://github.com/ikemen-engine/Ikemen-GO/assets/22782271/97b97519-3f51-4e18-a8ae-35645809f4e9)

### Engine Version (or source code date)

v0.99RC4 (also true of v0.98.2)

### Operating system

Windows

### Extra context or search terms

Issue #459 appears to be the same underlying bug: there, a 480p character places a 240p character in a custom state so that the 240p character can play a non-standard hit animation (one of the community's optional animation standards): a vertical spinning standard that has two separate animations, one with the character's body facing upright, and the other facing downwards.

In the 240p character, both of these animations cycle between AnimElems that use fairly dramatic y offsets (-92) and AnimElems which have y offsets of 0. It is very likely that the "judder" described in this issue is the result of the localCoord scaling bug described above, as the character cycles between the 0 offset AnimElems being displayed normally, and the -92 offset AnimElems that are being wrongly scaled.

**Comment by potsmugen** [comment]
Looks like this happens when the state owner localcoord is different from the animation owner localcoord.

240p KFM works correctly in another 240p char's custom state:

![ikemen003](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/b7813358-ca74-4c49-906c-6976cd89c626)

KFM720 does not:

![ikemen002](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/e3bfd6df-a7e7-469a-8214-ddd9f640d164)
