### ISSUE TITLE
Characters like Ragna the Bloodedge regain more health than intended.

### ISSUE THREAD

**Issue by Mushypepito123** [ikemen-engine/Ikemen-GO#1463]
### Describe the bug

I'm not sure whether it is a bug. But characters like Ragna the Bloodedge regain more health in his soul eater than was intended. Btw, I used my character Josuke to demonstrate how he can regain his health.

Are you sure that this is a bug? If yes, then can you at least fix it? If not, I would like to know how to reduce this.

### To Reproduce

1. Download the original Ragna or Josuke in these links: https://drive.google.com/file/d/1I_wSNkzz29Ug3FyaE2JfBwVaGPOSyJnY/view

https://drive.google.com/file/d/1jULycxlJ10VT8_E6hGtPuH2-BIQz4HlR/view

2. Start the match and only do normal combos on either Josuke or Ragna.

3. And see the error.

### Screenshots / Video

Here's his Soul Eater drive as it functions normally in older versions of IKEMEN GO.
https://streamable.com/ymz3tq

Then here's his Soul Eater drive as it functions in the current version of IKEMEN GO.
https://streamable.com/u1ah9c

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

**Comment by potsmugen** [comment]
You should compare it to Mugen 1.1 rather than previous Ikemen versions. Maybe it's only working correctly now.

**Comment by Mushypepito123** [comment]
> You should compare it to Mugen 1.1 rather than previous Ikemen versions. Maybe it's only working correctly now.

Tested it on MUGEN 1.1 and it still has the same function as the previous IKEMEN versions like 0.98.2, as shown in the video above.

**Comment by potsmugen** [comment]
Thanks. This has to do with differences in projectile behavior. I'll upload the fix soon.
