### ISSUE TITLE
Explod Bad Position with Zoom Stages

### ISSUE THREAD

**Issue by IkuTronHD** [ikemen-engine/Ikemen-GO#1467]
### Describe the bug

Basically the Explod is positioned poorly and does not fit with the previous version of Ikemen.

### To Reproduce

1. Start the Match
2. Go to the edge of the stage with zoom.
3. And make it show an explod.

### Screenshots / Video

0.98.2
https://i.imgur.com/gtGF95S.png
0.99.0
https://i.imgur.com/XzRvWYV.png

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

**Comment by RealFoobs** [comment]
Might want to mark this one as solved given the explods are behaving consistently with mugen 1.1

**Comment by IkuTronHD** [comment]
You can now close this, since we saw it the same day as this publication, and it was the same with 1.1.
