### ISSUE TITLE
Corner pushback not working correctly.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#1477]
### Describe the bug

Some moves will not pushback while the opponent is guarding on the corner.

### To Reproduce

Download Kyo [Kyo.zip](https://github.com/ikemen-engine/Ikemen-GO/files/13257528/Kyo.zip)

Press heavy punch against a guarding dummy in the corner.

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/77592586/002ddbae-9ac7-461f-9cf6-996f5c3a4fa5

MUGEN 1.1

https://github.com/ikemen-engine/Ikemen-GO/assets/77592586/8cbccc52-ebec-435c-9b09-95302a9a6bd3

Ikemen GO v0.99.0

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

**Comment by potsmugen** [comment]
Can't reproduce. Have you tried on a clean install? Also can you upload the stage?

**Comment by UrsoManso** [comment]
Nvm. I found out that the issue for some reason was being caused by the frame data display file I'm using.
