### ISSUE TITLE
Gametime not triggering

### ISSUE THREAD

**Issue by SynErrorD11** [ikemen-engine/Ikemen-GO#1478]
### Describe the bug

Experimenting with gametime I've found that it doesnt trigger when its supposed to, if compared to Mugen 1.0/1.1b. !gametime or gametime = 0 will always trigger.

The inconsistency lies when its gonna first trigger. For example, whenever i try it, its gonna trigger on tick 3 onwards, a friend of mine has tried it as well and in his case its only gonna trigger if gametime is >= 10.

### To Reproduce

In a negative state just put any regular sctrl and try to trigger it at !gametime. 
try to narrow down where gametime starts to trigger, as i said, its inconsistent.

I tested it using BGPalFx so its easy to see,

### Expected behavior

On Mugen 1,1b and 1.0 gametime will trigger anything as soon as the fight starts

### Screenshots / Video

Mugen 1.0/1.1b behavior:

https://github.com/ikemen-engine/Ikemen-GO/assets/148153298/d6aa2835-393a-49a0-bfbe-6088c250e065

Ikemen 0.99:

https://github.com/ikemen-engine/Ikemen-GO/assets/148153298/6590ad21-60b0-4f67-a3fe-79a13f1ad805

### Engine Version (or source code date)

v0.99

### Operating system

Windows

### Extra context or search terms

gametime

**Comment by potsmugen** [comment]
Gametime starts counting from the moment you open Mugen/Ikemen, so starting a match at gametime = 0 should be impossible unless you're using command line or something. For that reason I think this is inconsequential.

**Comment by beterhans** [comment]
gametime in ikemen starts from 16x
