### ISSUE TITLE
Pink color on envshake effect

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#1481]
### Describe the bug

I'm pretty sure I'm not reporting this correctly, but on some stages the envshake effect displays a pink effect different from MUGEN 1.1(and Ikemen 98.2) where it's black.

### To Reproduce

Download files: [files.zip](https://github.com/ikemen-engine/Ikemen-GO/files/13261182/files.zip)
Knockdown Kyo on the stage provided.

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/77592586/8c39b045-52b7-42e9-bb92-f5692e3434f0

MUGEN 1.1

https://github.com/ikemen-engine/Ikemen-GO/assets/77592586/d21537a0-f84a-48c6-89ca-0ad300be58cf

Ikemen GO v0.99.0

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

**Comment by potsmugen** [comment]
This sounds like the same issue as #1300. The pink is because the author forgot to disable the stage's debugging mode.

**Comment by UrsoManso** [comment]
Ok but why it doesn't happens on MUGEN as well?

**Comment by potsmugen** [comment]
Oh, it _is_ a bug. I just meant it was already reported.

**Comment by UrsoManso** [comment]
I see, my bad.
