### ISSUE TITLE
Pyron attacks! (Actual one) stage by MasterYoda, seems to have some sprites not working propely on the engine.

### ISSUE THREAD

**Issue by FrankSP7ps** [ikemen-engine/Ikemen-GO#1501]
### Describe the bug

The "Pyron Attacks! (actual version) by Master Yoda seems to have a little problem that some sprites doesn't work propely on this engine.
Gives the same issue in the Nighty build.

### To Reproduce

1: Chose the actual version or Nighty build
2: Download the stage
https://sites.google.com/view/senseiyoda/sensei-yodas-mugen/stages-lr
3: Test the stage, with any char (as they are not obviously the reason)
4:Let the stage progress and you will see the little bugs.

### Screenshots / Video

![ikemen182](https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/54a8fc36-c8d3-43bb-a767-cc795231c9b8)
![ikemen183](https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/391f8b24-9511-4e6d-9b77-3833ea95e7cd)
This two on 0.99.0

This one on Nighty build 
![ikemen000](https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/48880e43-fac0-41d0-a342-0abbc5a95c1b)

### Engine Version (or source code date)

 v0.99.0 then I checked on the Nighty build

### Operating system

None

**Comment by Wftk** [comment]
This bugged parts doesnt drawn at all in mugen 1.1 but in 1.0 it do. On bugged parts theres two commas after Horizontally flip in anim code(**23, 2,0,0,4, H,, AS224D256**) which cause the bug(correct one should be like that **23, 2,0,0,4, H, AS224D256**) .

**Comment by K4thos** [comment]
@Wftk, so there is nothing to fix on our side?

**Comment by Wftk** [comment]
@K4thos yeah.

**Comment by FrankSP7ps** [comment]
> This bugged parts doesnt drawn at all in mugen 1.1 but in 1.0 it do. On bugged parts theres two commas after Horizontally flip in anim code(**23, 2,0,0,4, H,, AS224D256**) which cause the bug(correct one should be like that **23, 2,0,0,4, H, AS224D256**) .

Did the change and yep that fix it.

![ikemen001](https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/8faa04c9-ee95-41a9-abc1-f291bb432d66)
![ikemen002](https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/8d8ed0a6-9096-4eed-b38e-143b26ef446f)


I did sorta knew that do some change on the .def should have do the trick, BUT.
I wouldn't didnt think that just deleting two comas on the "H (Horizontal) left arm and flame eye of big Pyro eye anim code would be the solution. :P

Thanks for the explanation!

**Comment by potsmugen** [comment]
Yeah I don't think making air files be read differently according to Mugenversion is worth it. Especially if the stage also has issues in 1.1.

**Comment by Wftk** [comment]
> Yeah I don't think making air files be read differently according to Mugenversion is worth it. Especially if the stage also has issues in 1.1.

This stage broken parts are just invalid syntax, I think it works in 1.0 only because transparency values ​​are the last parameters in the queue for parsing. While in 1.1 and ikemen there are new parameters such as scale,angle,offset which comes after the transparency parameters.
