### ISSUE TITLE
crazy camera, when the fight starts

### ISSUE THREAD

**Issue by ZyonZZ** [ikemen-engine/Ikemen-GO#1502]
### Describe the bug

crazy camera, when the fight starts

There are quite a few scenarios that do this...

You adjust it and center it, but when the combat starts... the camera goes up, and many times to the point of not seeing well... or in the middle of the characters...
In this scenario it is a little noticeable... but there are other extremes where it rises quite crazy

Why does the camera do this?

in previous versions it did not occur (98.2)

### To Reproduce

"when the fight starts"

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/129194444/715692b4-6349-45da-b173-9eb3809aac02

### Engine Version (or source code date)

0.99.0 last

### Operating system

Windows

**Comment by potsmugen** [comment]
Please upload or link the stage.
But I have a feeling it's because of an external module. Smooth camera maybe? Either way the question is if that setup does the same thing in Mugen 1.1 or not.

**Comment by ZyonZZ** [comment]
> Please upload or link the stage. But I have a feeling it's because of an external module. Smooth camera maybe? Either way the question is if that setup does the same thing in Mugen 1.1 or not.

based on your comment... I said why couldn't it be something external??...
so I downloaded a clean ikemen 99 again... and put the scenario there... it seemed surprising to me because this error does not occur in 98.2... the only thing I did was update... go from 98.2 to 99...

Surprisingly, in the clean ikemen99 I didn't fail...

then I went to the custom modules that I have... removing them... the custom tag... etc... and the error continued...
In the end I discovered that it was the addition of the Common of add004... there is something wrong that does this...
I'll investigate that common... calmly..
but you were actually right... it was something external that caused the camera to go up...
 if an admin sees it, close it
And thank you, your advice helped me find the cause :D
