### ISSUE TITLE
Death by O Ilusionista doesn't get K.O'd 

### ISSUE THREAD

**Issue by FrankSP7ps** [ikemen-engine/Ikemen-GO#1507]
### Describe the bug

So...
In one point I did wanted to play and fight again this fella after a long time.
I download him, included on my roster, all fresh.

But in the fight if you give all to the zero health.

He...Doesn't get ko'd?

The why is MAAAYBEEE because of the health regenartion that Ilusionista made for him. That may can be the reason?
But the rare thing is, is that in Mugen 1.0 or 1.1 beta he gets ko'd even with his health regeneration included.

So I find it weird that that this happend on Ikemen go, but oh well a different engine can bring different results uh?

### To Reproduce

Download Death, from Demon Hunter Legend 2. by O ilusionista from his well know Brazil mugen team page
https://brazilmugenteam.com/download/death/

Put him in the your ikemen go.

Fight him, until you get his health, zero.
I'll suggest low his health for the sake of see the bug in action and of course do it in versus mode.
Don't try fight him in quick match, the ai + he floats + some of his attacks and supers gives *(insert flex tape damage quote here)*

### Expected behavior

When he health gets to zero, he is not gonna react go get Ko'd.
He would still active as nothing happend
Look his health.

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/f577c7c1-d64f-4eb2-bab2-6a4597c76ad1

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

**Comment by potsmugen** [comment]
So it turns out that, in Mugen, if a character has a HitOverride active they can receive more damage than the life they have left. This was also the true reason behind David Bell not working.
I'll upload a fix later.

**Comment by FrankSP7ps** [comment]
Oooooh.
Welp, makes a lotta sense now (even more with David Bell).
Guess with the fix, that should make more bosses compatible with this engine.
