### ISSUE TITLE
Little to no Damage bug

### ISSUE THREAD

**Issue by thoj900** [ikemen-engine/Ikemen-GO#152]
edit:
Download my updated test files here: https://drive.google.com/file/d/1OOof9eoABS0j60KxPy2gNlT0loj0bp_m/view?usp=sharing

I made the button combinations a bit easier (instructions with how to do it with video link below).

First I saw your video, but it looks like you are doing an assist, the bug happens only if you hyper cancel out. So I created an in depth video to show you what I mean, with the steps to reproduce the bug, and the button combinations, I hope it helps: https://streamable.com/izapzn

So also I found out, if you change Super.TargetDefenceMul to 1 instead of 1.5, the bug no longer happens but then the hypers do too much damage and messes up other modes that might need that 1.5. So it appears, maybe supertargetdefencemul is being bugged out by something in HELPER STATE 1251101 that is making supertargetdefencemul go up by a huge amount instead of 1.5. I hope this makes sense, and hopefully the video explains everything well.

Happens with the execution of hyper cancel using this Helper code in example files, its [Statedef 1251101] and the inclusion of this code that appears in statedef 1251131: 

**[State 1251131, X]
type = Helper
trigger1 = sysvar(4) != 2
trigger1 = Time = 1
Helpertype = Normal
ID = ifelse((NumPartner && Partner,StateNo=1251125),1251102,1251101)
StateNo = 1251101
name = "X"
ownpal = 0
supermoveTime = ifelse((NumPartner && Partner,StateNo=1251125),1,9999)
pausemoveTime = ifelse((NumPartner && Partner,StateNo=1251125),1,9999)**

If you delete the above code from state1251131, it will delete the partner entering animation and helper, but damage will be fixed and normal. Looks like something isnt parsing right in ikemen.

**Comment by K4thos** [comment]
video is no longer working, so it's impossible to test if it's still a problem. In future please upload video by drag and dropping it directly to github video.

**Comment by thoj900** [comment]
Fixed on October 29 2020 by gacel
