### ISSUE TITLE
Default.IgnoreDefeatedEnemies is not working.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#1527]
### Describe the bug

Changing Default.IgnoreDefeatedEnemies works the same as before the change.

### To Reproduce

1.Open data/common.const and set the value of Default.IgnoreDefeatedEnemies from 1 to 0.
2.Performs the 22y command of fu-lin's SPY-DAMA (filename is [dama]) to make the enemy turn around.
3.When the helper disappears, the other party will remain turned around.
  (The same thing happens without changing Default.IgnoreDefeatedEnemies from 1.)

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

**Comment by NeatUnsou** [comment]
It is not related to DefeatedEnemies because it is the Playertype Helper.

**Comment by Kuroteba** [comment]
IKENEN GO continues to face the Playertype Helper even after the Playertype Helper disappears.
In MUGEN, when the Playertype Helper disappears, it turns back toward the enemy.
