### ISSUE TITLE
Stage camera StartY not implemented

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1538]
### Describe the bug

So in the source code there's this comment about that parameter:
`//sec[0].ReadI32("starty", &s.stageCamera.starty) //does nothing in mugen`

However if you set up some test cases you can see that it does work in Mugen.

### To Reproduce

1. Open Mountainside Temple and set starty to -100 for instance
2. Add this code to KFM:
```
[State -2, Test]
type = screenbound
trigger1 = !(stateno = 200 && time = 1)
movecamera = 0, 0
```
3. Select KFM vs KFM in Mountainside Temple

In Ikemen you won't see any difference in the camera, but in Mugen the camera will start high above and come down a bit every time you use a standing light punch.

### Expected behavior

Same as Mugen 1.1

### Engine Version (or source code date)

v0.99

### Operating system

Windows

**Comment by K4thos** [comment]
implemented in #1703
