### ISSUE TITLE
IsAsserted is broken

### ISSUE THREAD

**Issue by RealFoobs** [ikemen-engine/Ikemen-GO#1539]
### Describe the bug

IsAsserted is returning 0 on every check regardless of accuracy. 

### To Reproduce

1. Add this to KFMZ's statedef 20:
```assertspecial{flag:noshadow}```
and on statedef -2:
```
if playerno = 1 {
	if isasserted(noshadow) {text{removetime:1; layerno:1; pos:100,100; text:"NO SHADOW";}}
	else {text{removetime:1; layerno:1; pos:100,100; text:"SHADOW";}}
	}
```
2. Walk.
3. Stop.

### Expected behavior

The text should change from "SHADOW" to "NO SHADOW" as KFM moves and stops.

### Screenshots / Video

![ikemen002](https://github.com/ikemen-engine/Ikemen-GO/assets/115939744/7478761e-385b-47f8-9fc7-c7521bdc1ef8)
![ikemen003](https://github.com/ikemen-engine/Ikemen-GO/assets/115939744/e3bff3c9-2a45-442e-867e-bfc40c28c04c)

### Engine Version (or source code date)

Nightly

### Operating system

Windows

**Comment by RealFoobs** [comment]
Addendum: the issue is not order processing, putting the text code in statedef +1 instead of a negative state yields the same result.

**Comment by potsmugen** [comment]
My bad. I'll PR a fix later after I playtest some other changes some more.
