### ISSUE TITLE
CTD durning special character load

### ISSUE THREAD

**Issue by Kiwi1444** [ikemen-engine/Ikemen-GO#1552]
### Describe the bug

CTD durning loading of character [TienUB22](https://mugenarchive.com/forums/downloads.php?do=file&id=101579-tienub22-gohanssm2-colosse)

### To Reproduce

1. Download and install TienUB22 character 
2. Try to start the match with this character

### Expected behavior

As in Mugen 1.1 (no CTD)

### Engine Version (or source code date)

v0.99

### Operating system

Windows

### Extra context or search terms

[Ikemen.log](https://github.com/ikemen-engine/Ikemen-GO/files/13626107/Ikemen.log)

**Comment by Finally1994** [comment]
Projectile of state 1200, "=" is missing in the offset description
If you add this, it will start normally.
In cases like this, it would be better to have strict error detection rather than having a description error overlooked.

**Comment by K4thos** [comment]
#1583
