### ISSUE TITLE
Super finish not triggering on cheap KO

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#1553]
### Describe the bug

The tatsu super won't trigger the super finish ko background on cheap kills, only after the hit lands.

### To Reproduce

Download character - [Ryu.zip](https://github.com/ikemen-engine/Ikemen-GO/files/13626745/Ryu.zip)
Cheap kill the opponent with his tatsu super(2x qcb+kick).

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/77592586/7f7c47fd-15b3-4900-8274-a73b6d34328a

Ikemen GO v0.99.0

https://github.com/ikemen-engine/Ikemen-GO/assets/77592586/e63b2507-3392-43b3-b4a5-1f93eab80eae

MUGEN 1.1

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

**Comment by potsmugen** [comment]
This is because Ikemen considers the last hit to have been guarded, while Mugen and the commercial games I just checked consider it a clean hit. I'll push a fix later.

**Comment by UrsoManso** [comment]
Thing is, every other super triggers the finish effect on cheap kill, only the tatsu has this issue.
