### ISSUE TITLE
Win.snd also rings when double KO's are made.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#1569]
### Describe the bug

It also plays when the life bar win.snd is double KO.

### To Reproduce

1.Select the appropriate character in VS mode.
2.KO each other's characters at the same time.

### Expected behavior

When the roundstate reaches 4, win.snd is played.

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

**Comment by potsmugen** [comment]
Duplicate with #762.

I recently ran into this as well.
