### ISSUE TITLE
fight.def %p percent feature doesn't calculate correctly.

### ISSUE THREAD

**Issue by crowspaceboy** [ikemen-engine/Ikemen-GO#1575]
### Describe the bug

So. I have a crouching LP that's chainable into itself, and each hit does 1% damage, resulting in 3 hits and a 3% damage combo on the combo counter. If I chain it quickly, the %p feature works as intended and displays 3 hits and 3% damage. However, if I delay the last hit, the combo counter reads the whole combo as 3 hits 1% damage. The actual damage dealt is correct, it's just the %p feature in fight.def calculating the total percent incorrectly. 

### To Reproduce

Here's the code for my c.LP. It's not terribly different from KFM.

[Statedef 400]
type    = C
movetype= A
physics = C
juggle  = 0
ctrl = 0
anim = 400
sprpriority = 2

[State 400, 1]
type = PlaySnd
trigger1 = Time = 1
value = 0, 0

[State 400, 2]
type = HitDef
trigger1 = Time = 0
attr = C, NA
damage    = 11
priority  = 3, Miss
animtype  = Light
hitflag = MA
guardflag = M
pausetime = 6,8
sparkno = s10009
guard.sparkno = s10000
sparkxy = -40,-168
hitsound   = 5,0
guardsound = 6,0
ground.type = Low
ground.slidetime = 6
ground.hittime  = 11
ground.velocity = -16
air.velocity = -5,-19
air.hittime = 3  
forcenofall = 1
getpower = 5
givepower = 10
GuardPoints = 0

[State 0, CounterHit Prevention] ; This is so counterhits are correctly assigned
type = StateTypeSet
trigger1 = AnimElem = 4
statetype = C       ;S,A,C,L
movetype = I        ;I,A,H
physics = C         ;A,C,S,N
;ignorehitpause = 
;persistent = 

[State 400, 4]
type = ChangeState
trigger1 = AnimTime = 0
value = 11
ctrl =1

And here's the code that makes the c.LP chainable into itself.

;---------------------------------------------------------------------------
;Crouching Light Punch
[State -1, Crouching Light Punch]
type = ChangeState
value = 400
triggerall = command = "x"
triggerall = command = "holddown"
triggerall = (statetype = S) || (statetype = C)
trigger1 = ctrl
trigger2 = (stateno = 400) && (movecontact)
trigger2 = time > 5

I genuinely don't think this issue is related to c.LP as I've seen %p report combo percent wrong in other situations, but this is the easiest to reproduce and by far the most consistent. I can make it trigger incorrect data 100% of the time at normal speed. The fact I have trouble doing it in debug in slowed down speed really makes me think it's some sort of issue with the timing of which %p reports the combo percent damage.

### Expected behavior

The combo should report the same % of damage regardless of how quickly or slowly it's input. It's almost as if %p is reporting combo percent damage before hitstun has ended.

### Screenshots / Video

![screenshot](https://github.com/ikemen-engine/Ikemen-GO/assets/98061969/9908486c-1762-418e-b0bd-a895c19b2ece)

### Engine Version (or source code date)

0.98.2

### Operating system

Windows

**Comment by potsmugen** [comment]
Try it in the nightly build. There were several fixes done to delayed combos.

**Comment by K4thos** [comment]
Can't reproduce, so I assume it's fixed already. Please let us know if the ticket should be reopend.
