### ISSUE TITLE
HELP, IKEMEN GO AND PLUS ULTRA NO RUN WINDOWS 7 32BITS

### ISSUE THREAD

**Issue by PintaX724** [ikemen-engine/Ikemen-GO#1576]
### Describe the bug

IKEMEN does not run. My PC is W10 Pro 64 bits 16RAM, it plays for me in perfect condition.

What is the problem?

My friend has a laptop and also a desktop PC and both do not run IKEMEN Go, nor do they even run Plus Ultra. When you open the .Exe, the process closes itself without issuing errors in less than 5 seconds.

If I examine carefully from the Windows task manager, the process appears but disappears on its own, your PCs are formatted and you do not have an antivirus or anything that blocks opening a project like Ikemen.

Any game works for him and so does M.U.G.E.N but not IKEMEN

AID!

I think your problem is that it is 32-bit and I have a suspicion that Ikemen was created only for 64-bit.

Tell me which path to choose.

It would be good if IKEMEN was universal for all Windows and/or operating systems.

Thanks for reading, I hope you can answer me.

### To Reproduce

I think your problem is that it is 32-bit and I have a suspicion that Ikemen was created only for 64-bit.

### Engine Version (or source code date)

Cualquier version de Ikemen no le corre

### Operating system

Windows

### Extra context or search terms

Please!

**Comment by K4thos** [comment]
#1086
