### ISSUE TITLE
arcade team mode still uses same arcade.maxmatches path instead of team.maxmatches

### ISSUE THREAD

**Issue by doomjoshuaboy** [ikemen-engine/Ikemen-GO#1580]
### Describe the bug

in arcade singles mode it uses arcade.maxmatches path, but when using team arcade mode. it still uses the same arcade,maxmarches path were it supposed to use team.maxmatches.

### To Reproduce

1. Download a few characters from: https://network.mugenguild.com/pots/
2. add character with order=2, single=1, in select.def
3. Replace Arcade and Team Max matches with these paths:
arcade.maxmatches = 4,1,4,1,1,0,0,0,0,0
team.maxmatches = 2,1,2,1,1,0,0,0,0,0
4.run it go arcade -> Team.
5. select simul, tag or turns  and character then select team mode for cpu side then start play them till you reach 2 or 4.

### Expected behavior

it should have  for other arcade team modes.

### Engine Version (or source code date)

Nightly (22/12/2023) 

### Operating system

Windows

**Comment by K4thos** [comment]
Can't reproduce it. If you mean that if you select team arcade but choose team mode = single for the enemy than arcade.maxmatches being used is intentional. What controls it is the team mode selected for the enemy team, not the game mode.
