### ISSUE TITLE
Priority of a state sometimes crashes the game

### ISSUE THREAD

**Issue by BgueC6595** [ikemen-engine/Ikemen-GO#1584]
### Describe the bug

For some states, if a move has an additional `Hit` argument in its `priority` value, the game will crash. 

### To Reproduce

1. Download Chris Redfield from [Flavio Camarao's website](https://flyper1989.weebly.com/chars.html)
2. Start the game, have either party select him.
3. The game will crash on round start.

Relevant log:
```
.\external\script\start.lua:1403: chars\Chris Redfield/Chris_Super.st:6506:
3, Hit
priority: Invalid data: ,
stack traceback:
	[G]: in function 'game'
	.\external\script\start.lua:1403: in function 'f_game'
	.\external\script\start.lua:1839: in function 'launchFight'
	external/script/default.lua:2: in function <external/script/default.lua:0>
	.\external\script\start.lua:1457: in function 'f'
	external/script/main.lua:3069: in function 'loop'
	external/script/main.lua:3189: in function 'loop'
	external/script/main.lua:4156: in main chunk
	[G]: ?
```

If the `, Hit` parts of line 6491 and 6605 are removed, the game runs fine.  
I don't make characters so I'm not sure what went wrong here, but I imagine it's because these states' types are set twice (first as `PlaySnd` and then as `HitDef`), and maybe `PlaySnd` can't have the `Hit` argument on `priority`?

### Expected behavior

The game runs (tested on MUGEN 1.1 beta)

### Engine Version (or source code date)

nightly build 62db3c0

### Operating system

Windows

**Comment by potsmugen** [comment]
>I don't make characters so I'm not sure what went wrong here, but I imagine it's because these states' types are set twice (first as PlaySnd and then as HitDef), and maybe PlaySnd can't have the Hit argument on priority?

That's exactly right. It works in Mugen because that whole large Hitdef block is just interpreted as a PlaySnd. It doesn't work in Ikemen because PlaySnd now also happens to have a priority parameter which works different from Hitdef's.

However I personally don't agree with changing the engine to make bad code not crash.

**Comment by NeosNight** [comment]
Thank you it's working.

**Comment by K4thos** [comment]
#1583
