### ISSUE TITLE
Specific character not working on IKEMEN, but works on MUGEN

### ISSUE THREAD

**Issue by AsuToki360** [ikemen-engine/Ikemen-GO#1585]
### Describe the bug

I've downloaded a Kurumi Tokisaki character, and I added it to Ikemen, but for some reason the character doesn't want to work at all with Ikemen.
On MUGEN 1.1 works fine, so it's kinda weird how the character doesn't want to work on Ikemen... any fix?

The error log shows this:
.\external\script\start.lua:1403: chars\tokisaki_kurumi/kurumiH.cns:2930:
999981
name: Not enclosed in "
stack traceback:
	[G]: in function 'game'
	.\external\script\start.lua:1403: in function 'f_game'
	.\external\script\start.lua:1839: in function 'launchFight'
	external/script/default.lua:2: in function <external/script/default.lua:0>
	.\external\script\start.lua:1457: in function 'f'
	external/script/main.lua:3105: in function 'loop'
	external/script/main.lua:3189: in function 'loop'
	external/script/main.lua:4156: in main chunk
	[G]: ?

### To Reproduce

1. Download char from _"https://www.andersonkenya1.net/files/file/3651-kurumi-tokisaki"_
2. Add it in IKEMEN
3. Select the character in game.

### Expected behavior

I've expected it to work, cause I have another char made by the same person and it works, but this one it doesn't.

### Screenshots / Video

![image](https://github.com/ikemen-engine/Ikemen-GO/assets/40326499/dbf36d78-1f0b-45dc-a529-144a8d490c11)

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

**Comment by Finally1994** [comment]
Helper name 999981 is not enclosed in ""
There was another place
If you fix these two places it will work
I think it would be kinder to detect errors in cases like this.

**Comment by AsuToki360** [comment]
I understand

Strange, cause in the code 2930 there's nothing
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/40326499/ea487786-f20b-4dfe-8187-97e567360116)

**Comment by Finally1994** [comment]
Error lines may be displayed slightly off-center.
I don't know why.

**Comment by Daru00** [comment]
well is an issue with ikemen not implementing or having those features broken.
there is no fix to date and i assume won't be in the near future (lot of 1.1 exclusive chars have issues with ikemen go)

**Comment by K4thos** [comment]
#1583
