### ISSUE TITLE
Properties in the "Options Screen" are not working

### ISSUE THREAD

**Issue by rjadrodrigues** [ikemen-engine/Ikemen-GO#1587]
### Describe the bug

When changing the properties:
menu.item.selected.active.offset
menu.item.value.conflict.offset
menu.item.info.scale
menu.item.info.active.offset
menu.item.info.active.scale

Doesn't seem to affect the menu items as configured.
Not a big issue but a nice to have.
Any way thank you for the great work.

### To Reproduce

Make a configuration change in either of these options and validate the menu again

### Expected behavior

menu.item.selected.active.offset - Should change the position of the p.ex: screen resolution, when selecting the active choice
menu.item.value.conflict.offset - Should change the position of the Conflicted key when choosing a key already used by another player
menu.item.info.offset - Should change the position of the Auxiliar key info for instance "(F1)" for Player 1
menu.item.info.scale - Should change the font size of the Auxiliar key info for instance "(F1)" for Player 1
menu.item.info.active.offset - Should change the position of the Auxiliar key info for instance "(F1)" for Player 1 when active
menu.item.info.active.scale - Should change the font size of the Auxiliar key info for instance "(F1)" for Player 1 when active

### Engine Version (or source code date)

v0.99

### Operating system

Windows

**Comment by TitanUranus83** [comment]
Are those not handled by keymenu?

**Comment by K4thos** [comment]
these are leftover params, use the keymenu prefixed equivalents
menu.item.value.conflict.offset
menu.item.info.scale
menu.item.info.active.offset
menu.item.info.active.scale

this one was indeed missing:
menu.item.selected.active.offset

**Comment by rjadrodrigues** [comment]
Thank you very much for the help
