### ISSUE TITLE
Some stage elements not being displayed

### ISSUE THREAD

**Issue by updeshxp** [ikemen-engine/Ikemen-GO#1589]
### Describe the bug

Some sprites/elements are not visible in IKEMEN Go 0.99 and nightly but visible in Mugen 1.1b

### To Reproduce

1. Download attached stage and run it in Ikemen Go
[elenastage.zip](https://github.com/ikemen-engine/Ikemen-GO/files/13864789/elenastage.zip)

### Expected behavior

Elephant sprites in the back should be visible

### Screenshots / Video

MUGEN 1.1B
![m1 1](https://github.com/ikemen-engine/Ikemen-GO/assets/17386732/0088497a-5a95-429a-8ae6-5d552b9f7119)

IKEMEN GO 0.99 and Nightly
![ik99](https://github.com/ikemen-engine/Ikemen-GO/assets/17386732/6dd03d7e-6e62-48a0-98e3-c3320d6bd6cb)

### Engine Version (or source code date)

0.99

### Operating system

Windows

**Comment by Finally1994** [comment]
When I check it in FF3, it is displayed, but the pic of 3,0 is the same as the pic of 2,0.
In the other production tool I use (SAEditor), all the elephant pictures (2,0 to 2,3 and 3,0 to 3,3) are simply blank pictures.

**Comment by Finally1994** [comment]
When you look at it in FF3, it looks fine, but when you check the pics with other production tools, the elephant pics (2,0 to 2,3 and 3,0 to 3,3) are shown as blank pictures.
After importing the pic that was once exported in FF3 to SFF again, it is now displayed correctly in IkemenGo.
This is the first time I've seen such symptoms.

**Comment by updeshxp** [comment]
Indeed, works after exporting and re-importing the sprites in FF3. This can be closed.
Thanks!
