### ISSUE TITLE
Targets get dropped from roundstate 3 to 4 in a specific situation.

### ISSUE THREAD

**Issue by Mogotke** [ikemen-engine/Ikemen-GO#1592]
### Describe the bug

In IKEMEN, if P1 KOs P2 and puts them in a P1 custom state, upon roundstate 4, P1 will lose P2 as their target, P2 should still remain in said state.
In MUGEN, P1 still retains P2 as a target.

### To Reproduce

Made a small edit to KFM as an example.
1. https://mega.nz/file/v88SRAID#AARJN1c7bSukiXt61fywzyOPv17afhQG7EHePVAGLIg
2. Have one KO the other.
3. Wait (Speed it up with debug mode) for the transition from roundstate 3 to 4.

### Expected behavior

Expected P1 to keep their target.

### Screenshots / Video

![imagem](https://github.com/ikemen-engine/Ikemen-GO/assets/84547679/32130381-652a-450a-a11e-a42f97be42f9)

![imagem](https://github.com/ikemen-engine/Ikemen-GO/assets/84547679/78fd4a30-c319-424a-9e94-8a07dcd01957)

### Engine Version (or source code date)

Nightly build - 62db3c0

### Operating system

Windows

**Comment by potsmugen** [comment]
It looks like that in Mugen 1.1 the char stops being a target when it's in state 5150 specifically, whereas in Ikemen they do it in Roundstate 4 regardless of state.
