### ISSUE TITLE
Key input identification problem

### ISSUE THREAD

**Issue by weiwangko** [ikemen-engine/Ikemen-GO#1596]
The latest 0.99 version often fails to recognize two buttons at the same time, such as ex ability (x➕y) can not be released, requires a pre-attack action to recognize, this situation often occurs, but sometimes restart ikemen is normal again, can be triggered. What's going on here? bug?

**Comment by potsmugen** [comment]
By latest do you mean 0.99 stable or the Nightly build? Simultaneous button inputs have been notoriously difficult for most of Ikemen's life, but the Nightly build has an option to make them easier (on by default).

**Comment by weiwangko** [comment]
> By latest do you mean 0.99 stable or the Nightly build? Simultaneous button inputs have been notoriously difficult for most of Ikemen's life, but the Nightly build has an option to make them easier (on by default).

Nightly build Solved the problem
