### ISSUE TITLE
Problem with zoomed out stage

### ISSUE THREAD

**Issue by Rurouni-X** [ikemen-engine/Ikemen-GO#160]
The axis of the stage elements are not drawn in the correct position, including the zofsset.

In MUGEN 
https://i.imgur.com/trF2kcd.png

In IKEMEN
https://i.imgur.com/DY7y9Np.png

Download:
https://mega.nz/folder/309ySC5L#r7eVXVIK7KanbVw5DQnYYw/folder/vxNAHagI
Stage by Exshadow

**Comment by Orochikyocr** [comment]
Issues with stages should be re-tested as Gacel has made huge improvements on zoom and delta parameters since then.

**Comment by waspennator** [comment]
> Issues with stages should be re-tested as Gacel has made huge improvements on zoom and delta parameters since then.
> 
> This should be marked as close since issues like this were not reported anymore.

I retested this with the latest version and can confirm the issue still persists though.

**Comment by lokpro** [comment]
in case not know yet, the same issue is updated here: https://github.com/Windblade-GR01/Ikemen-GO/issues/172

**Comment by K4thos** [comment]
fixed by #605
