### ISSUE TITLE
Multiplayer configuration in stage file doesn't work

### ISSUE THREAD

**Issue by shadowpage** [ikemen-engine/Ikemen-GO#1600]
### Describe the bug

Player 3 and Player 4 configuration in stage file doesn't work.

### To Reproduce

1. edit stages\kfm.def , in [PlayerInfo] section, change Player 1 configuration:
p1startx = 0

   then add Player 4 configuration:
p4startx = -70
p4starty = 0
p4facing = 1

2. select VS Mode -> Team Versus -> P1 select Single, P2 select Simul -> Select Stage 2: Mountainside Temple

### Expected behavior

Player 4 should stand behind Player 1, not with Player 2.

### Screenshots / Video

![ikemen000](https://github.com/ikemen-engine/Ikemen-GO/assets/6863595/a3e66b9b-e976-4fdc-b932-20da9271c0d2)

### Engine Version (or source code date)

v0.99.0

### Operating system

None

**Comment by potsmugen** [comment]
This was probably missed in the first place because it's an undocumented feature. Should be added and expanded up to player 8 I think.

**Comment by K4thos** [comment]
already implented
