### ISSUE TITLE
WIP - Working in WebAssembly

### ISSUE THREAD

**Issue by formula1** [ikemen-engine/Ikemen-GO#1606]
So I'm trying to get Ikemen Go to work in the browser.
The general Plan is
- FileSystem
  - Change the filesystem to load from a zip and save as memory or localstorage
  - I'm thinking LocalStorage for things like Controller Config
- Controller
  - Controllers will be handled in the browser
    - This includes maping GamePad's to compatible Ikemen Go Controllers
  - Every Frame, Ikemen will run a "getControllerInputs" function which will provide all the controllers current Buttons
- Audio
  - Hopefully I can just use beep or another go library
  - Try to use WebAudio
- Draw
  - Whatever's closest to current (Webgl, Canvas, etc)

FileSystem and Controllers are likely the easiest but I need some help

So I'm having some issues with Go Generics FileSystem
- It seems you're using only a [small subset](https://github.com/formula1/ikemen-go-js-bindings/blob/master/go/src/file_abstract.go) of what `os` has to offer
- It's relatively easy to create [bindings to native](https://github.com/formula1/ikemen-go-js-bindings/blob/master/native/file_native.go)
- But I'm having issues with handling the Generics
  - Generic callbacks https://github.com/formula1/ikemen-go-js-bindings/blob/master/native/file_native.go#L35
  - The Whole Mess that is New Types https://github.com/formula1/ikemen-go-js-bindings/blob/master/go/src/file_wasm.go

This is my first time getting deep into go so any guidence would be appreciated

**Comment by potsmugen** [comment]
You should probably post this in Discussions with the engine dev tag.

**Comment by formula1** [comment]
Closing in favor of https://github.com/ikemen-engine/Ikemen-GO/discussions/879
