### ISSUE TITLE
Stage intro bugs

### ISSUE THREAD

**Issue by Kamuidelosvientos** [ikemen-engine/Ikemen-GO#1613]
### Describe the bug

There are chars (especially if they are mirror matches) that Intro Stages does not work.

### To Reproduce

https://github.com/ikemen-engine/Ikemen-GO/assets/158575147/69ba3611-056d-4d73-aac7-d6d35a97f7b1

### Expected behavior

I was trying the stage introduction attachedchar, and it works, but when other characters (especially if it's a Mirror Match) this happens, it doesn't reproduce the character well.

### Engine Version (or source code date)

nighty

### Operating system

Windows

**Comment by potsmugen** [comment]
Looks like an oversight in the module rather than a bug in the engine itself.
