### ISSUE TITLE
Nightly Release (Windows/Wine): Issue with stage that works fine in stable

### ISSUE THREAD

**Issue by rawardy** [ikemen-engine/Ikemen-GO#1617]
### Describe the bug

Sagat Sunset stage by ExShadow - True widescreen (TWS) Patch by Beterhans

Stage renders part way up the screen (screenshots) in some odd aspect while running at 1920x1080 resolution on Nightly. When tested on stable Windows/Wine and also Linux ver it runs correctly. Haven't tested on nightly linux ver as it has issues with my inputs.

### To Reproduce

1. Download stage from two links on https://www.patreon.com/posts/sagat-sunset-by-77365522 (Not Paywalled)
3. Make sure you grab the original sff from the first link. Then run with XX'SUNSET'XX_TWS.def from the second.
4. I had stage set to Sagat char rather than extra stages in select.def. No additional options. Has non standard file path "stages/Streetfighter/Sagat/Stage-1/XX'SUNSET'XX_TWS.def" Not sure if that matters.

### Expected behavior

Stage renders at 16:9 aspect ratio.

### Screenshots / Video

Nightly
![ikemen000](https://github.com/ikemen-engine/Ikemen-GO/assets/20464881/8b24ffb4-5b2c-46c4-9cf4-0651345c55c7)
Stable
![ikemen000](https://github.com/ikemen-engine/Ikemen-GO/assets/20464881/cfefbc5d-b95d-49b8-b6ca-350ff51ccb6d)

### Engine Version (or source code date)

62db3c0

### Operating system

Linux

### Extra context or search terms

Stages, Nightly

**Comment by potsmugen** [comment]
> Haven't tested on nightly linux ver as it has issues with my inputs.

Please report that issue as well when you get the chance.

**Comment by K4thos** [comment]
this is a regression introduced by #1475
@NeatUnsou
@Eiton (Tagging you in case you have insights on what might be wrong here, given your extensive research on how Mugen stages function recently)
