### ISSUE TITLE
Weird Auto-Guard Behaviour for Explodsive Buffering

### ISSUE THREAD

**Issue by RagingRowen** [ikemen-engine/Ikemen-GO#1626]
### Describe the bug

Characters with this system don't seem to guard despite changing the Guard Mode.
Notably, it only guards while going/holding forward.

### To Reproduce

1. Download and add character using Explodsive Buffering (for example, recent characters by Jmorphman, Chun-Li shown)
2. Start Training Mode and turn Guard Mode to All
3. Try hitting character.

### Expected behavior

Character would guard like most normal chars.

### Screenshots / Video

https://streamable.com/7pm5jb

I know Streamable's not the best choice but the vid's too big for here

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

### Extra context or search terms

Seems that older Explodsive chars are affected by this.

**Comment by potsmugen** [comment]
Custom buffers that read helper inputs instead of player inputs used to have that limitation. But it was fixed a few weeks ago. Try in the nightly.

**Comment by K4thos** [comment]
Half a year has passed without a reply, so I'm closing it for maintenance reasons. Feel free to request the reopening of the ticket if the issue persists in the latest nightly build.
