### ISSUE TITLE
[BUG] AffectTeam/Teamside does not affect Projectiles properly

### ISSUE THREAD

**Issue by thoj900** [ikemen-engine/Ikemen-GO#164]
An issue in team modes only. If you launch a projectile with affectteam = b or new teamside parameter, the effects wont affect your team members projectiles depending on order of character selection. They won't hit. This works fine in Mugen 1.1, but seems to be a bug and work incorrectly in current Ikemen GO. 

It's quite extensive so please download these test files for yourself and watch the included demonstration video that goes IN DEPTH on what happens, how, and ways to re-produce the bug. You will notice in regular MUGEN everything works fine.

Video: https://streamable.com/dt1ogl

Test Files: https://drive.google.com/file/d/14XaoK9Mu0wtpP7VnKIayldoT4ASFudan/view?usp=sharing

**Comment by K4thos** [comment]
no idea what is causing it but at least can confirm that the same problem always existed in ikemen go (tested on builds with only Suehiro's code) so it's unrelated to changes introduced by commit that added TeamSide parameter to hitdef.

**Comment by thoj900** [comment]
ok revisiting this actually I understand more whats happening with the bug, its only looking for partners that are after you. So if youre on a team with 3 members, then if you are partner 1, partner 2 and 3 on your team will affect your projectile.

if your the 2nd character on your team, the partner after you (partner 3) will only affect your projectile but not partner 1. It doesn't search before you. If you are partner 3, then partner 1 or 2 wont affect your projectile. Basically its not affecting for any partners that come before you. Still don't know the solution but thought I'd just add that.

**Comment by thoj900** [comment]
So I solved the problem for my specific case but NOT the actual problem with the affect team paremeter (could help with others doing a similar type move). I got rid of using affect team completely and used teamside value of -1 to act like an attachedchar side, anyway this ended up working, because the only thing that needs to be affected is the idle helper state when hit with projectile from both sides which sets off a change state. there is no affect team when it is ignited, and only hurts the enemy side.

Anyway, it is a workaround and my problem with this move has been solved, but again doesn't solve the actual affectteam paremeter. I'll still leave this as opened

**Comment by K4thos** [comment]
reuploaded video: 

https://user-images.githubusercontent.com/8928195/130037790-6165c468-61fd-4f88-85c7-148f04deb68a.mp4

[Test Files BUG_AFFECTTEAM_TEAMSIDE.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7012905/Test.Files.BUG_AFFECTTEAM_TEAMSIDE.zip)

https://discord.com/channels/233345562261323776/233363722934943744/877738319532937286

**Comment by Orochikyocr** [comment]
I can confirm this. affectteam = F or affectteam =  B, both wont work. 
https://streamable.com/1a1sn1
