### ISSUE TITLE
Can't remove team configurations

### ISSUE THREAD

**Issue by ca3gamedev** [ikemen-engine/Ikemen-GO#1641]
### Describe the bug

I want to default to a single team configuration on the fight, but I am unable to remove the multiple team configurations.

### To Reproduce

Open ikemen, can't remove the multiple team and tag and simult configurations.

### Expected behavior

I want to have a single 3 character tag team default battle.

### Engine Version (or source code date)

0.98.2

### Operating system

Linux

**Comment by K4thos** [comment]
this is not a bug report. Also 0.98 is no longer supported.

**Comment by lokpro** [comment]
hi @ca3gamedev , you may want to check 

	; These parameters allows renaming or disabling team modes from selection
	; (via blank assignment) in all modes that supports them.
	teammenu.itemname.single = "Single"
	teammenu.itemname.simul = "Simul"
	teammenu.itemname.turns = "Turns"
	teammenu.itemname.tag = "" ; Tag
	teammenu.itemname.ratio = "" ; Ratio

in system.base.def

and try to set Tag's Max/Min char to 3?

**Comment by ca3gamedev** [comment]
> hi @ca3gamedev , you may want to check
>

Thanks.
