### ISSUE TITLE
serious 2 Bug find. 

### ISSUE THREAD

**Issue by TasogareForever** [ikemen-engine/Ikemen-GO#1648]
### Describe the bug

at video.
https://youtu.be/_G7KJ7LUNWQ?si=AJTtMKkd5Yr7DnfF

1. More high gravity then mugen 1.1
2. Unabel special system at turn match

use Character
DABA's Shiori
Frule Neyuki
Shikyoku Raoh

### To Reproduce

at video.
https://youtu.be/_G7KJ7LUNWQ?si=AJTtMKkd5Yr7DnfF

1. More high gravity then mugen 1.1
2. Unabel special system at turn match

use Character
DABA's Shiori
Frule Neyuki
Shikyoku Raoh

### Engine Version (or source code date)

v0.99

### Operating system

Windows

**Comment by K4thos** [comment]
can't reproduce on latest nightly, so I assume it's fixed already

vs kfm (240p localcoord)

https://github.com/ikemen-engine/Ikemen-GO/assets/8928195/359cbadd-5748-4df4-aaab-053d7bf4b0ec

vs kfm720 (720p localcoord)

[Ikemen GO 2024-04-11 18-55-09.zip](https://github.com/ikemen-engine/Ikemen-GO/files/14949276/Ikemen.GO.2024-04-11.18-55-09.zip)

gauge is not reset

https://github.com/ikemen-engine/Ikemen-GO/assets/8928195/5b5bf9b4-c289-404d-b193-156ecf40a02e

Raoh - I have no idea how to fill such gauge, when reporting bugs please always provide commands to do the moves. But it did not reset when I was fighting CPU in turns mode and the opponent won the round.
