### ISSUE TITLE
Verticalfollow more jerky / faster in Ikemen than in Mugen 1.1

### ISSUE THREAD

**Issue by Kasasagi77** [ikemen-engine/Ikemen-GO#1652]
### Describe the bug

The scrolling when jumping is visibly more jerky, and almost assuredly faster than in Mugen 1.1, for the same value of `verticalfollow`. The difference is easily visible.

Tested on newest `develop` as of making this issue (1518892e).

### To Reproduce

You can use my previously uploaded stage for testing:  [graveyrd.zip](https://github.com/ikemen-engine/Ikemen-GO/files/14324642/graveyrd.zip). This `zip` contain a zooming stage with different/separate `.def` variants, use the Mugen 1.1 variant (`*-mugen.def`).

Jump in Mugen 1.1, jump in current Ikemen, observe the difference.

The stage uses zoom, however it is not clear to me of this issue is zoom-dependent - is seems faster in this stage regardless of the current zoom value, however the stage has zoom range fully in the zoom-out area (zoom < 1.0), so the behavior may yet be different for zoom >= 1.0.

### Expected behavior

The overall speed and the speed curve of vertical scrolling should be the same in Ikemen Go and in Mugen 1.1.

### Engine Version (or source code date)

2024-02-23

### Operating system

Linux

**Comment by potsmugen** [comment]
Yeah. I don't think it's that noticeable, but if you output Camerapos Y to the clipboard you can see that Ikemen is slightly off compared to Mugen. The difference is under 1 pixel though.

It also looks like Mugen has a camera lag while Ikemen does not. You can see it in this stage if you jump with KFM and frame step. When KFM lands, the camera is back in its original position in Ikemen, but in Mugen it takes a few frames to get to that position. This lag is probably why it feels smoother in Mugen. Maybe it's a feature we should port?

Another test case is adding this to KFM's light punch:
```
[State 200, Test]
type = posset
trigger1 = time = 5
y = -50
```
In Ikemen, at time = 5 the camera will teleport to the new position. In Mugen, it takes about 12 frames to get there.

**Comment by Kasasagi77** [comment]
~It may be that it is actually the lag that is causing what I am seeing as "jerky" camera movement?~

To me, the perceptual difference is stark in the fluidity / speed of scrolling (when I made my stage edits I often had to set a different `verticalfollow` value to achieve a perceptually similar behavior in Ikemen and Mugen). Especially when the camera reaches the upper bound it is like hitting a brick wall in Ikemen, in stark (for me) contrast with Mugen 1.1.

Anoter idea - is the camera scrolling speed in both in Ikemen and Mugen constant, without any acceleration? Because I wonder if the "smoothness" is see in Mugen, as opposed to Ikemen, can be related to some kind of acceletration/deceleration in the camera movement?

**Comment by potsmugen** [comment]
You should try this one again in the new nightly.

**Comment by Kasasagi77** [comment]
**New info below.**

---

Tested on latest develop [0cc38532].

A new test stage with camera position meters, for easy testing: [camera-test-075.zip](https://github.com/ikemen-engine/Ikemen-GO/files/15099645/camera-test-075.zip).

The test characters (but the issue is probably **not** character-dependent): [test-chars.7z](https://drive.proton.me/urls/6PZ744N3C8#dKkekGQqo2kW).

---

**Current conclusions**

It turns out, that most probably the target camera height (or y position) is the problem and differs largely in relation to Mugen 1.1, at least for zoom `0.75`.

![camera-follow](https://github.com/ikemen-engine/Ikemen-GO/assets/142987375/5df9d034-66b2-43c0-b44d-1a7b0673915d)

I do not know if it is a coincidence, but scaling the Ikemen curve exacly by `0.75`, which is coincidentaly the _zoom_ value seems to result in a curve similar to Mugen 1.1. The curves are a little wonky, because I just eyeballed the values on the scale and entered them manually into a spreadsheet.

Spreadsheet: [camera-follow.ods](https://github.com/ikemen-engine/Ikemen-GO/files/15111677/camera-follow.ods).

Raw frame screenshots: [camera-follow-frames.zip](https://github.com/ikemen-engine/Ikemen-GO/files/15111678/camera-follow-frames.zip).

---

@K4thos - could you please reopen this issue?

**Comment by Kasasagi77** [comment]
I just tested it additionally on different characters and the problem still persists, so it is **most probably not character-dependent**.

**Comment by Kasasagi77** [comment]
Added spreadsheet with tested camera height/y depending on different `verticalfollow` and `zoom` values: 
[y-follow-zoom.ods](https://github.com/ikemen-engine/Ikemen-GO/files/15123562/y-follow-zoom.ods).
