### ISSUE TITLE
Camera jerks horizontally (left-right) when jumping straight up, but moves purely vertically in Mugen 1.1

### ISSUE THREAD

**Issue by Kasasagi77** [ikemen-engine/Ikemen-GO#1653]
### Describe the bug

When jumping **straight up**, with `verticallfollow`, the camera in Ikemen does not only scroll purely in the vertical axis (up and down), but sometimes, just slightly but rapidly, jerks in the horizontal axis (left and right). This is not game-breaking, but distracting.

It does not happen in Mugen 1.1, where the camera moves **purely** in the vertical axis (up-down), with **no movement in the horizontal axis** whatsoever.

### To Reproduce

⚠️ **This is character-specific**, use the following test characters: [test-chars.7z](https://drive.proton.me/urls/6PZ744N3C8#dKkekGQqo2kW).

I upload a test stage: [camera-test-a.zip](https://github.com/ikemen-engine/Ikemen-GO/files/15185703/camera-test-a.zip) with camera position meters, for easy testing. However this is **not specific to this particular stage**, I can provide other stages with `verticallfollow`, where the backgrounds shake left-right when jumping straight up.

---

<ins>**The easiest scenario to reproduce this issue.**</ins>

1. Use the attached stage and ⚠️ **characters**.

2. Jump **straight up** with one or both characters (just press _UP_, do **not** jump sideways).

3. Watch the camera jerk exacly **half of a local pixel** horizontally.<br/>
    a. Please note that it is not a screen resolution pixel, but a large lowres pixel / `localcoord` pixel - this jerk is very clearly visible for backgrounds with horizontal delta >=1.0, especially on large screens.<br/>
    b. This is very clearly visible on the horizonal axis of the special camera position meter in the test stage, but it can also be observed on the main backgrounds.

4. If you load the same stage in Mugen 1.1, there is no jerk - the pointer on the horizonal axis of the camera position meter is always perfectly still when a character jumps straight up (there is no camera movement in the horizontal axis whatsoever, the camera movement is purely vertical).

---

<ins>**A more generic scenario (for other stages).**</ins>

1. ⚠️ **Use the attached characters**.

2. Move the left character to left edge of the screen or the right character to the right edge of the screen.

    a. Both characters should ideally be at the outer limit of their position, with maximum allowed horizontal distance between them.

3. Jump **straight up** with one or both characters (just press _UP_, do **not** jump sideways).

4. Watch the backgrounds with high delta (>=1.0) jerk/shake left-right in Ikemen (in addition to moving vertically up-down), but move **purely** vertically (up-down) in Mugen 1.1 (with **no movement in the horizontal axis** whatsoever).<br/><br/>

### Expected behavior

Matching Mugen 1.1 behavior, with pure vertical (up-down) movement.

### Screenshots / Video

Also an animated GIF showing the problem in Ikemen: [horiz-jerk.gif](https://github.com/ikemen-engine/Ikemen-GO/assets/142987375/da72c587-7d46-4565-85d5-1fde3e33ce5e).

Watch the lower horizonal axis of the camera meter.

### Engine Version (or source code date)

Tested on newest `develop` [15e29188], as well as older develop e.g. [0cc38532], [1518892e].

### Operating system

Linux

**Comment by potsmugen** [comment]
This could use reproduction steps that are a bit more specific I think. Or a video.

**Comment by Kasasagi77** [comment]
I have fixed an expanded the description and reproduction steps to be more detailed and clearer. Please tell me if something in particular is still not clear in the description.

**Comment by K4thos** [comment]
please provide a movie showcasing the problem in mugen 1.1 and ikemen.

**Comment by Kasasagi77** [comment]
I have made a new test stage, with **camera position meters**, that work in Ikemen and Mugen and allow for a detailed comparison of camera movent: [camera-test-075.zip](https://github.com/ikemen-engine/Ikemen-GO/files/15099645/camera-test-075.zip).

The new test stage shows the problem in much more detail:

1. The jumping character has to be near the edge of the screen.
2. If the character is near the left edge, the camera jerks left, if it is near the right edge, it jerks right.
3. The camera jerk is exacly **half of a local pixel** - please note that it is not a screen resolution pixel, but a large lowres pixel / `localcoord` pixel - this jerk is very clearly visible for backgrounds with horizontal delta of 1.0, especially on large screens.
4. If you load the same stage in Mugen 1.1, there is no jerk - the pointer on the horizonal axis of the camera position meter is always perfectly still when a character jumps straight up.

Also an animated GIF showing the problem in Ikemen: [horiz-jerk.gif](https://github.com/ikemen-engine/Ikemen-GO/assets/142987375/da72c587-7d46-4565-85d5-1fde3e33ce5e). Watch the lower horizonal axis of the camera meter.

**Comment by potsmugen** [comment]
That's a great test case you made. Have you tried the current build though? I can't reproduce it there.

**Comment by Kasasagi77** [comment]
Tested on latest develop [0cc38532] - I can reproduce it without a problem.

**Hovever** - I additionally tested this with totally different characters - and it turns out I do not reproduce the problem for different characters. I have uploaded my test characters: [test-chars.7z](https://drive.proton.me/urls/6PZ744N3C8#dKkekGQqo2kW) (this is the same file that I previously included in the first post).

Maybe the problem is something related to how the character position is calculated in relation to the camera?

It seems that the scope of this issue is narrower than I originally thought.

**Comment by potsmugen** [comment]
Yeah to be fair I only tried with KFM and one other char.

**Comment by Kasasagi77** [comment]
Still present on current develop [15e29188].

Also - I upload an even better stage to test this: [camera-test-a.zip](https://github.com/ikemen-engine/Ikemen-GO/files/15185703/camera-test-a.zip).

This stage has higher zoom-in and in consequence does not require the repositioning of characters. The shaking of normal backgrounds is also more visible.

**Comment by Kasasagi77** [comment]
Updated the main / top description with all of the latest information and an even better test stage.
