### ISSUE TITLE
Zoom twitches when frame stepping

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1658]
### Describe the bug

A minor issue but it might be a side effect of a bigger issue. If you frame step while the camera is in the middle of zooming in/out, you can noticeably tell the zoom twitches a bit.

### To Reproduce

1. Select a stage with zoom. Preferably with super jump capability. [Many here for instance](https://network.mugenguild.com/pots/)
2. Double jump with KFM
3. Pause and frame step (scroll lock) while paying attention to the zoom

### Expected behavior

Smooth camera zoom.

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/43e2056b-ee34-4a42-a452-c521b288e68a

A bit hard to see since it happens fast, but should be noticeable here.

### Engine Version (or source code date)

23/02/2024 but also as far back as 0.98.2

### Operating system

Windows

**Comment by Eiton** [comment]
I think this is fixed in nightly.

**Comment by potsmugen** [comment]
Looks like it. Nice job.
