### ISSUE TITLE
Repeated final round calls

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#1659]
### Describe the bug

The "final round" behavior should only trigger when a draw would end the match. Currently it triggers if both players are one round away from winning. This is not only inaccurate to some fighting games, but results in multiple "final rounds" being possible.

### To Reproduce

1. With default settings, select Versus
2. Win one round with each player
3. The conditions for "final round" will be met

### Expected behavior

Usually "final round" means the current round is _really_ final, meaning a draw results in a mutual loss.

### Screenshots / Video

An example from SFA3:

https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/af884a2f-4591-44e8-9b9d-e0aa2690001f

### Engine Version (or source code date)

23/02/2024

### Operating system

Windows

**Comment by potsmugen** [comment]
It looks like "final round" is also immediately announced when you're playing a match with only one round.

**Comment by K4thos** [comment]
The behavior is intentional. We can consider changing how it works, but there are commercial games that function similarly (Tekken comes to mind).

**Comment by potsmugen** [comment]
I think the issue is that it says final round _before_ you have reached "max draw games". We could make it act like either Tekken or SFA3 if it did that (for Tekken you'd set max draws to 0).

We also had a chat on Discord about this and came up with the idea that when a match has a single round, it should use the generic round call ("Ready? Fight!" for example) instead of saying the round number or final round (unless you then have a draw game).

**Comment by K4thos** [comment]
I was the one who added this feature, but feel free to make any changes to make it work as you see fit. It's coded in lifebar.go LifeBarRound section iirc: I think we should also consider changing this trigger behavior if that lifebar change is made: https://github.com/ikemen-engine/Ikemen-GO/wiki/Triggers-(new)#roundtype

**Comment by potsmugen** [comment]
I think for the purpose of char code that trigger already works how you'd want it to. For instance to perform a Fatality you don't need to care about number of draw games. It's mostly a lifebar thing.
