### ISSUE TITLE
An error occurred in Input Settings

### ISSUE THREAD

**Issue by softmgr** [ikemen-engine/Ikemen-GO#1663]
### Describe the bug

Ikemen_GO (dev-windows 2024-02-23)
Options -- Input Settings -- Key Config --> Show error window.

The contents of the Ikemen.log file are as follows:

.\external\script\options.lua:2045: attempt to index a non-table object(nil) with key '1'
stack traceback:
	.\external\script\options.lua:2045: in function 'f_keyCfg'
	.\external\script\options.lua:994: in function <.\external\script\options.lua:989>
	.\external\script\options.lua:1244: in function 'loop'
	.\external\script\options.lua:1251: in function 'f'
	external/script/main.lua:3106: in function 'loop'
	external/script/main.lua:4157: in main chunk
	[G]: ?

### To Reproduce

Download the latest development version Ikemen_GO-dev-windows.zip, unzip it and run it.

### Engine Version (or source code date)

2024-02-23

### Operating system

Windows

**Comment by potsmugen** [comment]
Seems like commit #1645
