### ISSUE TITLE
Issues with y coordinates in some stages

### ISSUE THREAD

**Issue by softmgr** [ikemen-engine/Ikemen-GO#1664]
### Describe the bug

In v0.99.0 and the latest development version, the y coordinate position of the ground is different. 
For example: 
[FFSP_Mai_Stage_Wide.zip](https://github.com/ikemen-engine/Ikemen-GO/files/14396025/FFSP_Mai_Stage_Wide.zip)

### To Reproduce

Please set the resolution to: 1280x720

Screenshots:
![screenshot3](https://github.com/ikemen-engine/Ikemen-GO/assets/8928195/882efe48-9bc4-4188-b112-857bec8cf699)

### Engine Version (or source code date)

2024-02-23

### Operating system

Windows

**Comment by potsmugen** [comment]
The reference here should be Mugen 1.1 rather than previous Ikemen builds. Is it different from it?

**Comment by softmgr** [comment]
> The reference here should be Mugen 1.1 rather than previous Ikemen builds. Is it different from it?

Thanks for the reply. After testing, I found that the problem occurred after adding support for "cuthigh, cutlow".
After this, the ground plane of many stages was lowered by about 10 pixels.
I tested based on the resolution 1280x720.

**Comment by Kasasagi77** [comment]
@softmgr - from what I understand this is an intentional breaking of compatibility with 0.99.

See #1642.

**Comment by K4thos** [comment]
I assume there is no difference between current nightly and ikemen 1.1 than? In this case we can close this ticket, thanks for the update.
