### ISSUE TITLE
In the character selection interface, some animations cannot be displayed.

### ISSUE THREAD

**Issue by softmgr** [ikemen-engine/Ikemen-GO#1667]
### Describe the bug

In the animation of the character selection interface, when the sprite is "shared", the interface cannot be displayed. Can only be displayed if the sprite is "unique". (Animation number 0 and 181)

### To Reproduce

I tested: If the sprite in the *.sff file is changed from "shared" to "unique", it can be displayed.

### Engine Version (or source code date)

2024-02-23

### Operating system

Windows

**Comment by K4thos** [comment]
known, not really a bug, the functionality may be expanded in future
