### ISSUE TITLE
Error with some characters on the recent nightly build

### ISSUE THREAD

**Issue by sonic30655** [ikemen-engine/Ikemen-GO#1683]
### Describe the bug

runtime error: index out of range [-1]
goroutine 1 [running, locked to thread]:
github.com/yuin/gopher-lua.(*LState).PCall.func1()
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua1988 +0x212
panic({0x7ff612989600, 0xc012826390})
   C:/hostedtoolcache/windows/go/1.20.14/x64/src/runtime/panic.go:884 +0x213
main.(*Char).actionPrepare(0xc0054ae000)
   D:/a/Ikemen-GO/Ikemen-GO/src/char.go:6079 +0xa85
main.(*CharList).action(0x7ff6128ff300, 0x202a2030?, 0x203d3a2029343328?, 0x730a0d2931303038?, 0x3d2059586b726170?, 0x30202b2030312d20?, 0x2872617628202a20?, 0x35203d3a20293533?)
   D:/a/Ikemen-GO/Ikemen-GO/src/char.go:6837 +0x7a
main.(*System).action(0x7ff6128fe4a0)
   D:/a/Ikemen-GO/Ikemen-GO/src/system.go:1336 +0x479
main.(*System).fight(0x7ff6128fe4a0)
   D:/a/Ikemen-GO/Ikemen-GO/src/system.go:2081 +0x158a
main.systemScriptInit.func57.2()
   D:/a/Ikemen-GO/Ikemen-GO/src/script.go:998 +0x579
main.systemScriptInit.func57(0xc0001389a0)
   D:/a/Ikemen-GO/Ikemen-GO/src/script.go:1046 +0x3d3
github.com/yuin/gopher-lua.callGFunction(0xc0001389a0, 0x0)
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua202 +0x37
github.com/yuin/gopher-lua.init.3.func26(0xc0001389a0, 0xc0c0001?, 0xc00021f000?)
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua821 +0x379
github.com/yuin/gopher-lua.mainLoop(0xc0001389a0, 0xc000760a80?)
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua31 +0xfa
github.com/yuin/gopher-lua.(*LState).callR(0xc0001389a0, 0x0, 0xffffffffffffffff, 0xc00000a7e0?)
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua1211 +0x1b4
github.com/yuin/gopher-lua.(*LState).Call(...)
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua1967
github.com/yuin/gopher-lua.(*LState).PCall(0xc0001389a0, 0x0, 0xc000760a80?, 0x0)
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua2030 +0x145
github.com/yuin/gopher-lua.(*LState).DoFile(0xc0001389a0, {0xc000024978?, 0x0?})
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua396 +0x6b
main.main()
   D:/a/Ikemen-GO/Ikemen-GO/src/main.go:89 +0x218

stack traceback:
   [G]: in function 'game'
   .\external\script\start.lua:1403: in function 'f_game'
   .\external\script\start.lua:1840: in function 'launchFight'
   external/script/default.lua:20: in function <external/script/default.lua:0>
   .\external\script\start.lua:1457: in function 'f'
   external/script/main.lua:3106: in function 'loop'
   external/script/main.lua:3190: in function 'loop'
   external/script/main.lua:4157: in main chunk
   [G]: ?

I get this error whenever I use Sagat by M206 more than one match
 https://mugenguild.com/forum/topics/sfv-supreme-sagat-5-3-191236.0.html

### To Reproduce

1. Get the sagat from here https://mugenguild.com/forum/topics/sfv-supreme-sagat-5-3-191236.0.html
2. select Sagat in a match (can be arcade, or watch, etc...)
3. play another match or go to the next stage.
4. get the error.

### Engine Version (or source code date)

2024-03-05

### Operating system

Windows

**Comment by SuperFromND** [comment]
I can reproduce this! How strange. I tried changing the character's folder and DEF names thinking maybe the spaces/underscores were screwing with it but, nope, same crash. Happens on latest nightly.

It seems like the cause of this has something to do with resetting CLSN scales, the char.go line mentioned in the resulting crash log points to here:
```go
		c.clsnScale = [...]float32{sys.chars[c.animPN][0].size.xscale, sys.chars[c.animPN][0].size.yscale}
```

Which is in turn called from this bit of code, ran at the start of `action()`:
```go
	// Prepare characters before performing their actions
	for i := 0; i < len(cl.runOrder); i++ {
		cl.runOrder[i].actionPrepare()
	}
```

This seems to happen any time this character is loaded into a match and then "reset", such as when advancing in Arcade Mode or if he happens to win a fight in Random Test and advance to the next one. It does NOT, however, happen if you load the character and then go back to character select and load somebody else before finishing the fight, and it doesn't happen by pressing F4 or Shift+F4.

**Comment by SuperFromND** [comment]
Quick update: after looking into the character a bit, it seems like there might be some kind of garbage data in their .AIR file or elsewhere that Ikemen is parsing, realizing it's garbage data when resetting, and then flipping out at. Mugen's parser is _much_ looser than ours *and* said .air file is over ten thoussand lines long, which probably explains why the character's author didn't catch it.

Oddly, removing these comment blocks *didn't* fix the problem, but it is still notable: for whatever reason this character has around a dozen comment blocks formatted incorrectly (note the lack of a ; before the S5Z4 string):
```
S5Z4;***************************************************************************;
;******************* Created in Fighter Factory Ultimate *******************;
;*******************      http://www.virtualltek.com     *******************;
;***************************************************************************;
```

**Comment by Jesuszilla** [comment]
We found and fixed the issue in Discord. Character is missing an anim 0 which MUGEN defaults to the first anim in the .AIR if it doesn't exist. Gonna submit a PR to match behavior in a few.

**Comment by emilio1981-tech** [comment]
I tried the character in question but I was unable to get the error,I have a lot of characters who have the error in question, how do you know which character is it?

**Comment by emilio1981-tech** [comment]
How do I identify the character?

runtime error: index out of range [223] with length 223
goroutine 1 [running, locked to thread]:
github.com/yuin/gopher-lua.(*LState).PCall.func1()
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua1988 +0x212
panic({0x7ff68e958e00, 0xc0293f09d8})
   C:/hostedtoolcache/windows/go/1.20.14/x64/src/runtime/panic.go:884 +0x213
main.BytecodeExp.run_ex({0xc020b3b720?, 0x1d, 0x7ff68e68046f?}, 0xc04c3c0000, 0xc04fb67008, 0xc04c3c0000)
   D:/a/Ikemen-GO/Ikemen-GO/src/bytecode.go:2947 +0xc456
main.BytecodeExp.run({0xc020b3b720?, 0x1d, 0x20}, 0xc04c3c0000)
   D:/a/Ikemen-GO/Ikemen-GO/src/bytecode.go:1886 +0x7e09
main.BytecodeExp.evalB({0xc020b3b720?, 0xfffffffe?, 0x0?}, 0x0?)
   D:/a/Ikemen-GO/Ikemen-GO/src/bytecode.go:3643 +0x1e
main.StateBlock.Run({0x1, 0xffffffff, 0xfffffffe, 0x0, {0xc020b3b720, 0x1d, 0x20}, 0x0, {0xc03bc9ca40, 0x3, ...}, ...}, ...)
   D:/a/Ikemen-GO/Ikemen-GO/src/bytecode.go:3841 +0x37a
main.StateBlock.Run({0x1, 0xffffffff, 0xfffffffe, 0x0, {0x0, 0x0, 0x0}, 0x0, {0xc0aa2bdc00, 0x1f, ...}, ...}, ...)
   D:/a/Ikemen-GO/Ikemen-GO/src/bytecode.go:3855 +0x4c6
main.(*StateBytecode).run(0xc04c3c0158, 0xc02c77c6c0?)
   D:/a/Ikemen-GO/Ikemen-GO/src/bytecode.go:12367 +0x225
main.(*Char).actionRun(0xc04c3c0000)
   D:/a/Ikemen-GO/Ikemen-GO/src/char.go:7831 +0x6ff
main.(*CharList).action(0x7ff68e8c48e8)
   D:/a/Ikemen-GO/Ikemen-GO/src/char.go:8966 +0x99
main.(*System).action(0x7ff68e8c3720)
   D:/a/Ikemen-GO/Ikemen-GO/src/system.go:1599 +0x54a
main.(*System).fight(0x7ff68e8c3720)
   D:/a/Ikemen-GO/Ikemen-GO/src/system.go:2394 +0x18e6
main.systemScriptInit.func54.2()
   D:/a/Ikemen-GO/Ikemen-GO/src/script.go:1272 +0x52a
main.systemScriptInit.func54(0xc0000ba000)
   D:/a/Ikemen-GO/Ikemen-GO/src/script.go:1320 +0x3d3
github.com/yuin/gopher-lua.callGFunction(0xc0000ba000, 0x0)
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua202 +0x37
github.com/yuin/gopher-lua.init.3.func26(0xc0000ba000, 0xc0c0001?, 0xc0000bc000?)
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua821 +0x379
github.com/yuin/gopher-lua.mainLoop(0xc0000ba000, 0xc000a33840?)
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua31 +0xfa
github.com/yuin/gopher-lua.(*LState).callR(0xc0000ba000, 0x0, 0xffffffffffffffff, 0xc000600138?)
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua1211 +0x1b4
github.com/yuin/gopher-lua.(*LState).Call(...)
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua1967
github.com/yuin/gopher-lua.(*LState).PCall(0xc0000ba000, 0x0, 0xc000a33840?, 0x0)
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua2030 +0x145
github.com/yuin/gopher-lua.(*LState).DoFile(0xc0000ba000, {0xc00024e321?, 0x0?})
   C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua396 +0x6b
main.main()
   D:/a/Ikemen-GO/Ikemen-GO/src/main.go:113 +0x2f2

stack traceback:
   [G]: in function 'game'
   .\external\script\start.lua:1441: in function 'f_game'
   .\external\script\start.lua:1887: in function 'launchFight'
   external/script/default.lua:20: in function <external/script/default.lua:0>
   .\external\script\start.lua:1504: in function 'f'
   external/script/main.lua:3181: in function 'loop'
   external/script/main.lua:3266: in function 'loop'
   external/script/main.lua:4227: in main chunk
   [G]: ?
