### ISSUE TITLE
fonts for characters not working

### ISSUE THREAD

**Issue by Seb471** [ikemen-engine/Ikemen-GO#1684]
### Describe the bug

After looking on the fact that it's possible to add fonts to characters in Ikemen GO, I tried adding some to use for the Text controller and they didn't work.

First I looked at how to create a font in elecbyte's tutorial for fonts which don't end in .fnt by creating a def file, and then added this font to the character.
After adding the font to the def file of the character and changing the font parameter of the text controller to match the font in question, it instead put the font of debug.
After that, I tried with a .fnt of a screenpack that I've seen it used. It didn't work either.

How do I make it work ?

### To Reproduce

1. Download a font from internet or take it from a screen pack
    1.1. If it's a ttf/otf file, make a def file out of it
    1.2. If it's an fnt, no need to change it
2. Add the font to the def file of the character in the [Files] section using the pattern fontX = _the font_.def/fnt
3. Add a text controller for the character (in my case I added it to the state -2 to happen under certain conditions) and then put the X in the font parameter

### Expected behavior

It should use the fonts that are defined in the def file, instead they use the debug's font.

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/16428353/4efc99c7-bbae-4bd5-826e-6a5b31e868f0

### Engine Version (or source code date)

v0.98.2 and above

### Operating system

Windows

**Comment by potsmugen** [comment]
They seem to be working in a test I ran:

![ikemen000](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/6e8cbf51-171f-47db-9f37-69bf9bde0dd3)

```
[Files]
cmd     = kfm.cmd           ;Command set
cns     = kfm.cns           ;Constants
st      = kfm.cns           ;States
stcommon = common1.cns      ;Common states (from data/ or motif)
sprite  = kfm.sff           ;Sprite
anim    = kfm.air           ;Animation
sound   = kfm.snd           ;Sound
ai      = kfm.ai            ;AI hints data (not used)
movelist = movelist.dat     ;Ikemen feature: Movelist

font0 = arcade.def
```

```
[State -2, Test]
type = text
trigger1 = teamside = 1
removetime = 1
layerno = 2
text = "Test"
align = 0
pos = 160, 80
localcoord = 320, 240
font = 0
scale = 1, 1
```

Try playing with the position and localcoord. Maybe you're creating it just outside the screen or something.

**Comment by Seb471** [comment]
could you show me your arcade.def ?
because the problem isn't that it isn't showing, it's that it's not applying the font...

**Comment by potsmugen** [comment]
It's the same arcade.def that comes with a clean install.

**Comment by Seb471** [comment]
gotcha, also what does the tag unverified mean ?

**Comment by potsmugen** [comment]
That devs/mods were unable to reproduce the issue.

**Comment by Seb471** [comment]
even using the files I put in the ikemen-help channel ?

**Comment by potsmugen** [comment]
You should probably also put them here. But I'll try those.

**Comment by Seb471** [comment]
I tried putting them here, but the formats aren't supported for some reason

**Comment by potsmugen** [comment]
Try zipping them. I tried them and they worked:

![ikemen020](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/9fd44c41-f937-488a-bdbc-25411ba94c17)

![ikemen021](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/fbea3543-5097-438b-b429-2123394cbc91)

![ikemen022](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/a8076867-7add-419b-9653-417b2342d8a5)

```
[Files]
cmd     = kfm.cmd           ;Command set
cns     = kfm.cns           ;Constants
st      = kfm.cns           ;States
stcommon = common1.cns      ;Common states (from data/ or motif)
sprite  = kfm.sff           ;Sprite
anim    = kfm.air           ;Animation
sound   = kfm.snd           ;Sound
ai      = kfm.ai            ;AI hints data (not used)
movelist = movelist.dat     ;Ikemen feature: Movelist

font0 = font/Yeongest.def
font1 = font/msgothic-tt20.def
font2 = font/EVE_KOF.fnt
```

```
[State -2, Test]
type = text
trigger1 = teamside = 1
removetime = 1
layerno = 2
text = "Test"
align = 0
pos = 160, 80
localcoord = 320, 240
font = 1
scale = 1, 1
```

I noticed pressing Shift F4 won't reload fonts and that I had to restart Ikemen when changing them. So maybe it's an issue caused by using Fighter Factory to run Ikemen like you're doing.

**Comment by Seb471** [comment]
also this worked on 0.98.2 ?

**Comment by potsmugen** [comment]
I only tested the latest build, which I think is the only one that has active support here.

**Comment by Seb471** [comment]
ok so I've learned multiple things :
- local coord doesn't seem to work in 0.98.2
- you are correct, the font works only if you launch ikemen and not from ff3... (which sucks in the long run)
