### ISSUE TITLE
We need custom work done to Ikemen GO.

### ISSUE THREAD

**Issue by ivands** [ikemen-engine/Ikemen-GO#1685]
We need some custom features added to Ikemen GO and will compensate for the work.
If any top contributors are interested, please let me know.

**Comment by ivands** [comment]
It wouldn't be much work btw.
@K4thos

**Comment by formula1** [comment]
@ivands

I'm not proficient in golang but there are places you can hire programmers such as https://www.codementor.io

**Comment by ivands** [comment]
@formula1 

Thanks, but we already hired some to help us. Sadly he's stuck and needs a little help by a dev more familiar with the codebase.

**Comment by formula1** [comment]
Are these features that you'd like to share or private?
