### ISSUE TITLE
Wrongly Looped Music not matching up with bgmloopstart/end

### ISSUE THREAD

**Issue by RagingRowen** [ikemen-engine/Ikemen-GO#1701]
### Describe the bug

bgmloopstart = 1088688
bgmloopend = 3983472

Instead of looping at these points, it loops a few seconds behind and comes with a pretty nasty click alongside it.

### To Reproduce

1. https://drive.google.com/file/d/1W-DpTn6tj1MUlTiMsxOuEDTAeQpGNDkk/view?usp=sharing download the music used from this link.
2. Add it to a stage with these the bgmloopstart/end in "Describe the bug"
3. Open the stage in IKEMEN and listen.

### Expected behavior

The music will loop properly according to the assigned samples.

### Screenshots / Video

https://streamable.com/lngpjv Loop happens at 0:20

### Engine Version (or source code date)

Nightly (as of 21/03/24)

### Operating system

None

**Comment by Eiton** [comment]
Pretty sure it is the problem of mp3 decode library used by Beep. It loops properly when it is converted to wav.

**Comment by K4thos** [comment]
already reported here #1547

**Comment by K4thos** [comment]
Closing as a duplicate for maintenance.
