### ISSUE TITLE
Latest nightly build messes up stages

### ISSUE THREAD

**Issue by Shadic13** [ikemen-engine/Ikemen-GO#1710]
### Describe the bug

So I decided to download the latest version of the nightly build and most of my stages or either too zoomed in or out for me to even play. Is there a way to fix this issue?
![ikemen002](https://github.com/ikemen-engine/Ikemen-GO/assets/84107935/4ef01df6-59a0-47f2-b566-ed540263600f)
![ikemen000](https://github.com/ikemen-engine/Ikemen-GO/assets/84107935/04bdf3ba-22e4-4946-8512-d445251d90ba)

### To Reproduce

Stage name is silver seafloor by POTS and here is the link. https://www.mediafire.com/file/hpjvx9kmb5wueaz/SilverSeafloor.zip/file
The other stage is Blazblue Kagutsuchi PM 1.1 by Derek edited by Imperius but don't have the link for it at the moment. Once I get home I will upload it from my computer to medafire. They work fine in Mugen 1.1 though.

### Engine Version (or source code date)

Nightly Build

### Operating system

Linux

**Comment by potsmugen** [comment]
Have you tried in a clean install?

Here's what Silver Seafloor looks like for me:
![ikemen044](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/30faf10e-6667-4aaf-a166-a1c5cec00083)

**Comment by Shadic13** [comment]
Gotcha I will re download the stages when I get off work. I was also messing with certain values of all my stages such as tension high and bound high along with zoom in and out every time I downloaded them to make them support really high jumps for OHMSBY styled characters so that could  have factored in the problem.

**Comment by Shadic13** [comment]
I found the issue it was the values I changed with bound high and tensionhigh by returning them to their original value the stages function correctly.
