### ISSUE TITLE
Sparkangle not working

### ISSUE THREAD

**Issue by leandrooffline** [ikemen-engine/Ikemen-GO#1717]
### Describe the bug

I tested the last build 2024-04-01.
hitdef, parameter sparkangle = 120
and not working

### To Reproduce

![Captura de tela 2024-04-01 120905](https://github.com/ikemen-engine/Ikemen-GO/assets/4389151/3397e939-cfa3-43bf-bb80-79d14fa099b4)

Change sparkno = 0 to 60 for test
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/4389151/3e63d795-43d2-44c1-a802-cc418108a517)

### Expected behavior

Angle spark change for 90º

### Engine Version (or source code date)

last build 2024-04-01

### Operating system

Windows

**Comment by potsmugen** [comment]
It might have been left out during other Explod code updates. I'm uploading a fix.

**Comment by leandrooffline** [comment]
Not Working to me
![image](https://github.com/ikemen-engine/Ikemen-GO/assets/4389151/c2cf8891-b75f-43c1-8686-31fa6f271e1c)

char test its kfm720

Build test:
[Ikemen test.zip](https://github.com/ikemen-engine/Ikemen-GO/files/14826649/Ikemen.test.zip)
