### ISSUE TITLE
bgmusic.life not working when running from command line

### ISSUE THREAD

**Issue by DataFragment** [ikemen-engine/Ikemen-GO#1722]
### Describe the bug

I'm trying to use a stage with bgmusic.life but it only plays the default bgmusic, it never changes to the low life theme.
This only happens when I run the engine from the command line, if I normally run the .exe and manually select the stage from inside the game, the change of music works perfectly.

### To Reproduce

Run a fight from the command line
```.\Ikemen_GO.exe char1 char2 -s stageWithLowLifeMusic```

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

**Comment by K4thos** [comment]
not a bug, some music parameters controlled by lua are not supported when running from command line.
