### ISSUE TITLE
Initial camera zoom out of [zoomout, zoomin] bounds

### ISSUE THREAD

**Issue by Kasasagi77** [ikemen-engine/Ikemen-GO#1735]
### Describe the bug

When `startzoom` is **not** set in the stage `def` and the `[zoomout, zoomin]` range is wholly below `1.0` then the initial camera zoom is still `1.0`. Mugen 1.1 does not behave this way. This is a recent bug and it worked the same as in Mugen 1.1 before the latest camera rework (@Eiton).

### To Reproduce

1. Set for a stage: `zoomin = 0.75`, `zoomout = 0.75` in the stage `def`.
2. Do **not** set `startzoom`.
3. Start the stage normally (with characters present).
4. Observe the stage camera zoom starting at `1.0` instead of `0.75` (it starts at `0.75` zoom in Mugen 1.1).

### Expected behavior

The initial camera zoom should be `0.75` in the above case, like in  Mugen 1.1

In fact, in Mugen 1.1, if you set `zoomin = 0.75`, `zoomout = 0.75`, the stage will **always** start with the zoom at `0.75` regardless if `startzoom` is set to any other value or unset.

### Engine Version (or source code date)

2024-04-12

### Operating system

Linux

### Extra context or search terms

Adding a simple min/max bounding for `zoomout`/`zoomin` [here](https://github.com/ikemen-engine/Ikemen-GO/blob/d292aec7b8753b6fff07d4c8f73e17fe217ea409/src/camera.go#L326) fixes the issue.

I can make a simple PR adding this, however I do not know if this is the best fix for this issue or if it suggests that a different bugfix is needed somwhere above. @Eiton - should I make such a one-line PR myself?

**Comment by potsmugen** [comment]
It's probably better to let Eiton see this since he's been in the middle of reworking the camera and making changes there could throw him off.

**Comment by Eiton** [comment]
I am not going to change the camera code in foreseeable future (unless when there are new bugs). You are welcome to make the PR if the problem is easy to fix.

**Comment by WouMugen** [comment]
Is it serious that the solution to the problem for you was to remove startzoom?
