### ISSUE TITLE
Big falls starts to lag, when the opponent touch the ground in that fall

### ISSUE THREAD

**Issue by FrankSP7ps** [ikemen-engine/Ikemen-GO#1742]
### Describe the bug

Not sure if point out this (besides of have a feeling that maybe someone already reported despite of be in a different situation probaly?)

Apparently the big falls starts to lag a little, which that doesn't happend on MUGEN or some past Ikemen Go builds (that includes past Nightly ones).

Did discover it while I was testing the lifebar and screenpack with random chars.

I wonder if these build got some change in render or something.

### To Reproduce

Any char that can just simply launch the opponent on high, like T_N Butthead.

Do that on the nightly build.

### Expected behavior

When the opponent touch the ground in that hard fall, the game starts to lag a little til the opponent have his second small fall.

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/9d216bf0-c906-4cee-81dd-9e688a37b974

### Engine Version (or source code date)

Nightly build (especifically the one around 4/04/24)

### Operating system

Windows

**Comment by potsmugen** [comment]
Does it happen with any fightfx or specifically that one?

**Comment by FrankSP7ps** [comment]
Nope, seems to happen to any fightfx, including the default one.
So it doesn't matter which fightfx is that I use.


https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/e3696485-0c15-4aaf-b203-94f9e287d4d8

**Comment by potsmugen** [comment]
This is weird. Does it happen with any char? As in it's not something coded in Butt-Head? Also check the FPS in the latest nightly debug mode.

**Comment by FrankSP7ps** [comment]
Yep, any char for what it seems.

Did happend with Magic Geese, Mech Hisui 404. So most likely with any.

https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/29eb8b93-d6a8-4805-9a00-a54834449a8c

https://github.com/ikemen-engine/Ikemen-GO/assets/108790388/8430794d-e1db-4dc8-8f7f-ccc8dc5cd588

**Comment by FrankSP7ps** [comment]
Ok this is kinda weird.

There a two points that I'll most likely need to check out for myself.

1: For some reason the Butthead of the build that im using shoes those "invalidad action" which apparently that doesnt show in a clean build.

2: As I kinda expected on a clean build, seems the large fall works fine without some lagging.

Again this is most likely something that I need to see myself slowly to point out what is.

Oh boy, I hate when this type of stuff happends...

**Comment by potsmugen** [comment]
In theory it's not because of 1. Calling an invalid action just makes the explod not come out at all.

**Comment by K4thos** [comment]
please provide proper way to reproduce it - upload characters and provide commands that should be done.

**Comment by FrankSP7ps** [comment]
Ok I found the issue.
The screenpack that im using on the engine, seems to come with a **common1.cns** which is **pretty unusual** to see on screenpacks. That was responsible for this "big slow falls".

Most likely was included just because of the fightfx that "kinda fits" on that slow fall.

Here the screenpack if you want to check it, be aware that is gotta look like a little disaster as mugen 1.1 beta seems did take different some stuff.

https://www.andersonkenya1.net/files/file/33091-mugen-kof98um-remake-beta-11/

**Comment by potsmugen** [comment]
Just for some closure, that common1.cns file specifically has a slow motion code in that scenario.
