### ISSUE TITLE
I.K.E.M.E.N GO is somewhat laggy.

### ISSUE THREAD

**Issue by Plu1223** [ikemen-engine/Ikemen-GO#1743]
It could just be because my computer is doodoo fart, but my computer seems to have trouble running the game. This lag didn't happen when I used M.U.G.E.N 1.1 or WinMUGEN.

**Comment by potsmugen** [comment]
Try this build:
https://github.com/ikemen-engine/Ikemen-GO/discussions/952

**Comment by Plu1223** [comment]
Thanks, I've tried

**Comment by Plu1223** [comment]
(I accidently clicked completed, oops.)

Thanks, I tried that out but I don't really see too much of a difference.

**Comment by K4thos** [comment]
it's known that ikemen performs worse than mugen. Similar ticket already exists.
