### ISSUE TITLE
TargetBind sometimes doesn't play nicely when characters' LocalCoords are different

### ISSUE THREAD

**Issue by UltraCombo3000** [ikemen-engine/Ikemen-GO#1746]
### Describe the bug

When a TargetBind is triggered and the attacker and the target have different LocalCoords, the target may not always be bound to the correct location.

### To Reproduce

The most obvious example is found when attempting to use Shippu Nagareboshi (done by inputting QCB + any two of the three kick buttons) from Ichida/Vinnie's Yosuke Hanamura on any character whose LocalCoord is set to a higher resolution than 320x240 (ex: KFM720, any of Kazecat's characters).

### Expected behavior

https://github.com/ikemen-engine/Ikemen-GO/assets/124517004/260ea466-69db-4b0e-b42f-3c096d82fb43

This was done in MUGEN 1.1, and is what should happen.

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/124517004/64f90745-1051-4577-abbd-5f2eabebd835

The above video was taken in IKEMEN GO 0.99.0, and the super works perfectly fine on original KFM (not the 720 one).

https://github.com/ikemen-engine/Ikemen-GO/assets/124517004/31af47c3-abd8-41c5-aad7-d600f76197bc

This is what happens when you use the super on KFM720. I should mention that the final storm of kunai WILL hit if you download Yosuke directly from Vinnie's site and use this move, but my edit showcases what could happen if you have attacks that only connect if all preceding hits do. 

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

### Extra context or search terms

It could have something to do with how the TargetBind is triggered. This one is triggered via movehit = 1, and contains a persistent = 0. The super works somewhat properly if you change it to just movehit and have persistent = 1, but the higher resolution target will briefly teleport across the stage before being bound to the correct spot.

**Comment by K4thos** [comment]
please upload the edited character that showcases this problem, if what is shown in the video doesn't match how the original character behaves. Also consider testing it on nightly build, it's likely already fixed.

**Comment by UltraCombo3000** [comment]
Here is the edit in question: https://www.mediafire.com/file/n7tktvwhskxh9cn/Yosuke.zip/file


https://github.com/ikemen-engine/Ikemen-GO/assets/124517004/a9d2d192-e4a3-49e2-8450-61dbee0d308d

The above video is proof that this still occurs even in the nightly build.


https://github.com/ikemen-engine/Ikemen-GO/assets/124517004/b1ce7605-3a6d-4c27-9240-624b236832a2

I even tested "vanilla" Yosuke, and it also happens here, the only difference being that the enemy isn't permanently frozen in the end.

**Comment by potsmugen** [comment]
This seems to happen because the target is bound first in one localcoord and custom stated second in another one. I'll push a fix later.
