### ISSUE TITLE
Background edge reduction

### ISSUE THREAD

**Issue by weiwangko** [ikemen-engine/Ikemen-GO#1747]
### Describe the bug

In the previous beta version, the background edges were normally displayed completely, but in the recent beta version, the background edges were reduced inward a lot, resulting in incomplete background length.

### To Reproduce

In the previous beta version, the background edges were normally displayed completely, but in the recent beta version, the background edges were reduced inward a lot, resulting in incomplete background length.

### Expected behavior

Want to correct back into a normal full background display

### Engine Version (or source code date)

nightly builds

### Operating system

Windows

### Extra context or search terms

stage

**Comment by K4thos** [comment]
not enough information. This ticket will be closed unless you upload a stage that showcases the issue.

**Comment by weiwangko** [comment]
![Uploading Filmage 2024-04-23_220343_1713881187899.png…]()

**Comment by weiwangko** [comment]
You can compare the two background edges and find some reduction
![Filmage 2024-04-23_220343_1713881187899](https://github.com/ikemen-engine/Ikemen-GO/assets/157288534/bec67aa4-9e73-42c1-81c7-96d7c6e8a550)
![Filmage 2024-04-23_220343_1713881201819](https://github.com/ikemen-engine/Ikemen-GO/assets/157288534/bc51e537-ffb8-4464-a689-b1324600aba6)

**Comment by weiwangko** [comment]
![Filmage 2024-04-23_220343_1713881201819](https://github.com/ikemen-engine/Ikemen-GO/assets/157288534/0c298794-637e-4526-8596-0f0e5fdd575d)

**Comment by weiwangko** [comment]
> not enough information. This ticket will be closed unless you upload a stage that showcases the issue.

Send a picture. You can compare the two background edges and find some reduction

**Comment by weiwangko** [comment]
> not enough information. This ticket will be closed unless you upload a stage that showcases the issue.

Very strange, the previous beta version is still showing normal, now the beta version of the background are indented a little.

**Comment by K4thos** [comment]
The only important thing is if there is a significant difference between mugen 1.1 and the latest nightly build. If no than it works as expected, even if it differs from previous builds. As mentioned this can't be verified by us based on description like this alone.
