### ISSUE TITLE
Certain High Res Stages are bugged....

### ISSUE THREAD

**Issue by Jvsonnn** [ikemen-engine/Ikemen-GO#1756]
### Describe the bug

Certain high res stages that work on Mugen 1.1 don't work properly on Ikemen 0.99 such as Nuclear Testing Site/Nevada 55 by Arias.

The Stage gets all sorts of messed up and has a lot of graphical glitches.

### To Reproduce

Download stage from: http://www.mediafire.com/file/0v75yjnl71v3f8p/

and try it in ikemen 0.99 or later.

### Expected behavior

Visual Glitches and incoherence

### Screenshots / Video

mugen 1.1b
https://github.com/ikemen-engine/Ikemen-GO/assets/139520965/858e9c3e-9c4d-4747-92e0-9ffde4951276

960 x 720
https://github.com/ikemen-engine/Ikemen-GO/assets/139520965/0ffad240-607d-43d9-bd08-bf3992cf44fc

1280 x 720
https://github.com/ikemen-engine/Ikemen-GO/assets/139520965/de6c5d9e-bab1-4433-8a91-025140e6dd2c

### Engine Version (or source code date)

0.99 Stable

### Operating system

Windows

**Comment by potsmugen** [comment]
Same issue in current nightly build.

**Comment by Wftk** [comment]
The xscale parameter in the StageInfo section seems to break the bgdefs delta

**Comment by Kiwi1444** [comment]
Similiar problem on stage [Cell's Arena (Day)](https://mugenarchive.com/forums/downloads.php?do=file&id=117989-cell-s-arena-day-tahattus). Look at flickering trees:

https://github.com/ikemen-engine/Ikemen-GO/assets/56668390/b54c7318-66cb-4902-893e-3eabcb0380e8

...And normal behaviour in Mugen 1.1 (no flickering):

https://github.com/ikemen-engine/Ikemen-GO/assets/56668390/0534df9e-d962-4a05-bd15-fefd4d771770

**Comment by Eiton** [comment]
> Similiar problem on stage [Cell's Arena (Day)](https://mugenarchive.com/forums/downloads.php?do=file&id=117989-cell-s-arena-day-tahattus). Look at flickering trees:
> 
>  Ikemen_GO_dev_64lHyxHDCO.mp4 
> ...And normal behaviour in Mugen 1.1 (no flickering):
> 
>  mugen_WqJwbjqGa0.mp4

This is a different issue. It will be fixed in #1836

**Comment by potsmugen** [comment]
From what I understand from Eiton's post, this one is not fixed but #436 is?

**Comment by Eiton** [comment]
Nuclear Testing Site is fixed in #1840 
Cell's Arena (Day) is fixed in #1836
