### ISSUE TITLE
The character leaves the screen display range when jumping

### ISSUE THREAD

**Issue by softmgr** [ikemen-engine/Ikemen-GO#1758]
### Describe the bug

In a stage with a large boundhigh parameter, when a character jumps or jumps in the air, he may leave the screen display area. See the file "Screenshots.zip" for details. [Screenshots.zip](https://github.com/ikemen-engine/Ikemen-GO/files/15136870/Screenshots.zip)

Files used for testing:  
[chars.zip](https://github.com/ikemen-engine/Ikemen-GO/files/15136871/chars.zip)
[stages.zip](https://github.com/ikemen-engine/Ikemen-GO/files/15136872/stages.zip)

The problem may occur after this update: Camera Movement Revamp
https://github.com/ikemen-engine/Ikemen-GO/commit/67760a3e09704ce7ea783b2c4c57fb3ba6217466

@K4thos @Eiton 

### To Reproduce

Unzip the above chars.zip and stages.zip to the directory where Ikemen-GO is located.
Enter the game, the character jumps, the character jumps in the air.

### Screenshots / Video

![5](https://github.com/ikemen-engine/Ikemen-GO/assets/34020339/d2832441-0a66-437e-8a53-2cd8afa0e612)

### Engine Version (or source code date)

2024-04-27

### Operating system

Windows

**Comment by potsmugen** [comment]
I think this will be fixed by #1757.

**Comment by Eiton** [comment]
> I think this will be fixed by #1757.

It won't. It is not the problem of vertical follow. I'll make a pr fixing this and another regression tmr.
