### ISSUE TITLE
Micro-stutter in camera scrolling

### ISSUE THREAD

**Issue by Kasasagi77** [ikemen-engine/Ikemen-GO#1761]
### Describe the bug

The current camera code causes readily visible micro-stutter.

Tested on [e57a659c].

### To Reproduce

This is related to: #1652, but it most probably **not** only affects `veritcalfollow`.

A new test stage with camera position meters, for easy testing: [camera-test-075.zip](https://github.com/ikemen-engine/Ikemen-GO/files/15099645/camera-test-075.zip).

Test characters (but probably not character-dependent): [test-chars.7z](https://drive.proton.me/urls/6PZ744N3C8#dKkekGQqo2kW).

---

Steps:
1. In Ikemen: jump straight up, observe vertical scrolling micro-stuttering, especially at the top of the jump.
2. In Mugen 1.1:  jump straight up, observe buttery smooth vertical scrolling.
3. In Ikemen:
    a. comment out or remove the causing lines in code and recompile (see below),
    b. jump straight up, observe buttery smooth vertical scrolling.

### Expected behavior

Expected behavior matching Mugen 1.1: buttery smooth vertical scrolling.

### Engine Version (or source code date)

2024-04-26

### Operating system

Linux

### Extra context or search terms

This is the offensing code fragment that causes this for `verticalfollow`: https://github.com/ikemen-engine/Ikemen-GO/blob/e57a659c2f75c41dea22ca0d0ae6ba552c304153/src/camera.go#L262-L265

Hovever there is equivalent snapping code for `ytension` and even for horizontal scrolling.

If I understand this code correctly, then this kind of snapping is even quite explicit in resulting in camera scrolling micro-stutter, considering what it actually does.

Is this behaviour needed from Mugen <1.1 compatibility or something else? Because otherwise I do not think that it is needed - the difference in the height/Y that the camera reaches is negligible (if any at all) after removing this code.

At least Mugen 1.1 does not seem to behave this way.

**Comment by Kasasagi77** [comment]
@Eiton - you may be interested.

**Comment by Eiton** [comment]
I am still not 100% understanding the formula in Mugen 1.1 but I am pretty sure snapping is present in Mugen 1.1.

**Comment by Kasasagi77** [comment]
Hmm... then it must work in some other way, because the scrolling effect in Mugen 1.1 is 100% smooth to my eyes, but not so in current Ikemen sadly.

Maybe it snaps to pixel grid rather then to `targetY`?

**Comment by Kasasagi77** [comment]
Tested it also on the latest [8d3b4a99] and with different characters and the effect seems to be the same.

**Comment by Kasasagi77** [comment]
I just remembered this from the Mugen documentation:
>
> mugenversion = mugen_version
> 
> This parameter sets the target version number of M.U.G.E.N that the stage is designed for. Valid values are 2002,02,14, 1.0 or 1.1. Defaults to 2002,02,14.
> 
> A version number of 2002,02,14 restricts camera movement to whole units of the stage coordinate space, whereas 1.0 and higher allows the camera position to assume fractional values.
> 

And i also tried testing different `mugenversion` values in Mugen 1.1, but even trying different values here, I can not reproduce any non-smoothnes in camera scrolling in Mugen 1.1 - it always looks buttery smooth to my eyes.

That of course does not mean that no snapping is done, just that I can not see it resulting in any stuttering.

**Comment by Eiton** [comment]
It should be closer to how horizontal scrolling is implemented, but with different values.

**Comment by Kasasagi77** [comment]
After a quick test it seems to work well on my end. Thank you very much @Eiton. 🙏
