### ISSUE TITLE
colors for 2.0 24 bit fonts not working in ikemen

### ISSUE THREAD

**Issue by doottah** [ikemen-engine/Ikemen-GO#1763]
### Describe the bug

ikemen can't change font colors 2.0 (24 bit) like mugen 1.1 does

I thought it was my mistake for not having created the sources correctly, but trying with mugen 1.1 it works wonderfully

### To Reproduce

[fonts24bits.zip](https://github.com/ikemen-engine/Ikemen-GO/files/15157082/fonts24bits.zip)

### Expected behavior

that Ikemen can use RGB to change the colors of 2.0 (24bit) fonts like mugen 1.1 does

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/168463181/635d73e7-13a4-4a5b-9c1b-736e17d9bfd7

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

### Extra context or search terms

fonts 2.0 (24 bits)

**Comment by Wftk** [comment]
same issue as #335
