### ISSUE TITLE
Some trees in the stage disappeared for no apparent reason

### ISSUE THREAD

**Issue by softmgr** [ikemen-engine/Ikemen-GO#1765]
### Describe the bug

In this stage, some trees sometimes disappear.
Stage : 
[stage_cellgamesday.zip](https://github.com/ikemen-engine/Ikemen-GO/files/15163721/stage_cellgamesday.zip)

### To Reproduce

After entering this stage, walk a few steps to the right and you will see that some trees sometimes disappear.

### Screenshots / Video

[Screenshot.zip](https://github.com/ikemen-engine/Ikemen-GO/files/15163880/Screenshot.zip)

### Engine Version (or source code date)

2024-04-30

### Operating system

Windows

**Comment by K4thos** [comment]
already reported: #436
