### ISSUE TITLE
I want to change the language of the victory screen.

### ISSUE THREAD

**Issue by mu60** [ikemen-engine/Ikemen-GO#1769]
In mugen 1.1, I was able to change the language by editing the language in mugen.cfg, but in ikemen, there is no mugen.cfg. 
I tried opening the config.json, but I couldn't find any settings related to language. 
Is it possible to change the language?
![mugen000](https://github.com/ikemen-engine/Ikemen-GO/assets/36182207/e77d7cd6-2cce-48d0-8186-b1bcf416b42b)

**Comment by K4thos** [comment]
currently not, maybe in future

**Comment by K4thos** [comment]
implemented in #1923
