### ISSUE TITLE
Problems with character sides/facing directions.

### ISSUE THREAD

**Issue by RaitoADV** [ikemen-engine/Ikemen-GO#177]
This is a problem I found while testing a my new Tag code with an assist move that puts the opponent in a "wall bounce" state.

If I do a move that goes through the enemy _without_ hitting it, while the enemy is facing the same direction I am facing, my character's facing direction becomes messy (facing towards the same direction as the enemy).

This problem gets fixed momentarily when doing an attack like a punch, but comes back whenever I change directions again with my opponent.

Here's some video footage in case you're interested in seeing it on detail:
https://streamable.com/uedqqu

**Comment by Kikasuru** [comment]
Does this happen in normal M.U.G.E.N. too?

**Comment by RaitoADV** [comment]
I'm not quite sure because default MUGEN doesn't have a Tag feature, thus I can't test what I did in the video.

I could use Simul, but I don't have anyone to help me test it right now.

**Comment by Windblade-GR01** [comment]
Can you send the code for the tag mode?
Maybe the problem is because on how you enable `noAutoTurn`

**Comment by Kikasuru** [comment]
> I'm not quite sure because default MUGEN doesn't have a Tag feature
wait i'm stupid and didn't read lmao

**Comment by RaitoADV** [comment]
> Can you send the code for the tag mode?
> Maybe the problem is because on how you enable `noAutoTurn`

Here's the tag code:
https://drive.google.com/file/d/1GIgxWNTzhTh7N1ACfvTH68HYcF2gEze2/view?usp=sharing

And here's the char I used in the video:
https://drive.google.com/file/d/1iK0rHVII8Am6qcFZa-FJp6l2w7qAMVX8/view?usp=sharing

**Comment by K4thos** [comment]
can't reproduce with default tag. Follow how it's coded and make appropriate changes. If you think there is a bug (something working different than mugen) please prepare simple test case using kfm that showcases the issue,
