### ISSUE TITLE
X/Y offsets defined in animations are still incorrectly scaled when placed in a custom state

### ISSUE THREAD

**Issue by UltraCombo3000** [ikemen-engine/Ikemen-GO#1778]
### Describe the bug

This is a very similar issue described in issue #1459, except it's with ChangeAnim2 instead of just ChangeAnim.

### To Reproduce

Use any character that can put an enemy into a custom state that has a ChangeAnim2 in it, where the animation used has a non-zero x or y offset defined in the .air file. For this example I will use Kamekaze's Ultimate Falcon.

1. Have Falcon use his air throw (done with F/B + medium kick) on any character whose LocalCoord is not 320x240 (ex: KFM720).

2. That's it.

### Expected behavior

This:
![Good](https://github.com/ikemen-engine/Ikemen-GO/assets/124517004/6317d1b8-203b-4583-a520-5fbbb073d436)

### Screenshots / Video

Instead, we get this:
![Bad](https://github.com/ikemen-engine/Ikemen-GO/assets/124517004/ba7ee3ee-731f-4c54-930e-1b3ddd7d74f9)

### Engine Version (or source code date)

v0.99.0 and newer

### Operating system

Windows

### Extra context or search terms

Issue 1459 appears to have already been addressed, but it seems like ChangeAnim2 was not accounted for.

**Comment by potsmugen** [comment]
Did you try latest build? The expression used to fix 1459 should also address this. Here's how it looks for me in May 6th build:

![ikemen000](https://github.com/ikemen-engine/Ikemen-GO/assets/107247004/5732bd61-b291-43c6-965d-57ef7a62ed5e)

**Comment by UltraCombo3000** [comment]
It turns out that while I was experimenting with massive edits to this character, I changed the .air file and some TargetBinds to make the transition from the grabbed to the get hit state look smoother. This bug doesn't actually happen on Vanilla Falcon, but it will on this version: https://www.mediafire.com/file/90x0lwy5g4lj6tb/UC.Falcon.zip/file

**Comment by potsmugen** [comment]
You're right. I'm uploading a fix that corrects this without apparently regressing the previous fix.
