### ISSUE TITLE
Credits display and Insert Coin/Press Start on healthbars

### ISSUE THREAD

**Issue by Pacsonic** [ikemen-engine/Ikemen-GO#1779]
You guys should add a display for the credit counter on the healthbars and make it say "Credits (credits)" if attract mode is on and "Free Play" if attract mode is off as well as have the ability to have the insert coin/press start text be displayed on attract mode as well.

**Comment by K4thos** [comment]
The main issue tracker is reserved for bug reports and compatibility issues.
