### ISSUE TITLE
Reversaldef bug on nightly

### ISSUE THREAD

**Issue by RealFoobs** [ikemen-engine/Ikemen-GO#1798]
### Describe the bug

Loganir's Wonder Woman's counter move does not work properly in Ikemen nightly.

### To Reproduce

1. Download Wonder Woman from[ Loganir's site ](https://loganir.blogspot.com/p/wonder-woman.html)
2. Use her "Amazon Aegis" move (QCB+P) against any random character's attack. Most of the time it won't work.

https://github.com/ikemen-engine/Ikemen-GO/assets/115939744/7837c14a-be20-4ca9-88fc-56f0eb72becd

### Expected behavior

This is how the move behaves in 1.1

https://github.com/ikemen-engine/Ikemen-GO/assets/115939744/06e81ed1-a862-4740-b04d-469cef2de3a7

### Engine Version (or source code date)

Current nightly (2024-05-19)

### Operating system

None

### Extra context or search terms

I brought this up on the MFG discord, and apparently the bug doesn't happen in stable 0.99. @potsmugen mentioned it might be a side effect of a recent bugfix.

**Comment by potsmugen** [comment]
I think it's a regression introduced when fixing #1410 (a bigger issue).

To clarify, it's not an issue with Reversaldef. This move uses Hitoverride. What's happening is she overrides the hit then hits back the opponent with a grab. The grab is checking for attack priority when it shouldn't.

Edit: Think I got it. PR after more testing.

**Comment by UltraCombo3000** [comment]
I want to point out that ReversalDef actually IS bugged in nightly. It does not work at all.

**Comment by potsmugen** [comment]
> I want to point out that ReversalDef actually IS bugged in nightly. It does not work at all.

Can you make a new ticket with reproduction steps? All my test cases seem to be working correctly.
