### ISSUE TITLE
Some moves no longer chain when using "ikemenversion" (cvkyoukenwakamoto)

### ISSUE THREAD

**Issue by avo323** [ikemen-engine/Ikemen-GO#1809]
### Describe the bug

I wanted to try out adding some Ikemen-Go features to cvkyoukenwakamoto. It's a character that works fine in Mugen 1.1 and Ikemen-Go's Mugen compat mode. The moment I changed its "versiondate = 1,6,2008" to "ikemenversion = 1.0", without any other change, it stopped being able to chain certain moves.

This only happens in the nightly build (I've only tested it in 2024-05-24 nightly). On ikemen-go v0.99.0 it keeps working as expected.

### To Reproduce

1. Download character form https://mugenarchive.com/forums/downloads.php?do=file&id=1097-cv-kyouken-wakamoto-2chan-crew
2. Edit its def file replacing "versiondate = 1,6,2008" with "ikemenversion = 1.0"
3. Start a match and try to perform "crouching A -> croching Y" or "crouching X -> crouching Y"
4. Try the same with the unmodified character

### Expected behavior

Those moves should chain

### Screenshots / Video

First part uses the character with "ikemenversion = 1.0", second part uses the untouched one.

https://github.com/ikemen-engine/Ikemen-GO/assets/32247963/7d309ded-1d24-4287-8d72-b88cbcfe076b

### Engine Version (or source code date)

nightly (2024-05-24)

### Operating system

Windows

**Comment by potsmugen** [comment]
This is intentional. You shouldn't add `ikemenversion` to characters without good reasons.

In this specific example, you should increase hittimes by 1. This is similar to what happened between Winmugen and Mugen 1.0.

https://github.com/ikemen-engine/Ikemen-GO/wiki/Miscellaneous-info#guard-mechanic
