### ISSUE TITLE
Damage overflow in targetlifeadd

### ISSUE THREAD

**Issue by netyzh** [ikemen-engine/Ikemen-GO#1813]
### Describe the bug

Damage overflows when use big damage instant kill skill "Black_In_Mind" and recover enemy's life.

### To Reproduce

Character:Eddie
Author:Muteki
Download:https://onedrive.live.com/?authkey=%21AHiQCBHj6az5zwg&cid=495747B6F9328805&id=495747B6F9328805%21198&parId=495747B6F9328805%21125&o=OneUp

Use"a+b+x+y" or "c+z"(stateno 4000)-"2626b"(stateno 4001)-hit and changestate to stateno 4002

codes in statedef 4002:
[State 200, 2]
type = targetlifeadd
trigger1 = time = 0
value = -9999999999999
absolute = 1

### Expected behavior

Big damage is working.

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/38396687/73a5473a-2dcc-4e68-a664-4a7fe31d8dc2

### Engine Version (or source code date)

nightly build(20240524)

### Operating system

Windows

**Comment by potsmugen** [comment]
Duplicate with #971
