### ISSUE TITLE
Helper var don't change,causes vast damage

### ISSUE THREAD

**Issue by netyzh** [ikemen-engine/Ikemen-GO#1814]
### Describe the bug

helper(20000),var(0) and  helper(20000),var(1) don't change
so triggers Projectile each frame, cause vast damage

### To Reproduce

Character:Saki Mitonoya
Author:chikuchikugonzalez
Download:https://mugenarchive.com/forums/downloads.php?do=file&id=31127-saki-mitonoya-chikuchikugonzalez or https://www.mediafire.com/file/xip3adg5b1uodyo/Saki-20140510-mugen1.0.zip/file

choose 1P
press 3x in the match and let support hit enemy.

codes in helper statedef 20220:
;-------[ Projectile Control ]-------;

[State 20220:           Reset Hit Flag]
type     = VarSet
trigger1 = Time = 0
trigger2 = var(0) > 16
v        = 0
value    = 0

[State 20220:           Reset Hit Count]
type     = VarSet
trigger1 = Time = 0
v        = 1
value    = 0

[State 20220:           Hit Time]
type     = VarAdd
trigger1 = var(0)
v        = 0
value    = 1

[State 20220:           Hit Flag]
type       = VarSet
triggerall = !var(0)
trigger1   = Root,NumProjID(20220)
trigger1   = Root,ProjContactTime(20220) = 1
v          = 0
value      = 1

[State 20220:           Hit Count]
type     = VarAdd
trigger1 = var(0) = 1
v        = 1
value    = 1

;-------[ Projectiles ]-------;

[State 20210:           Projectile, 1]
type             = Projectile
triggerall       = !Root,NumProjID(20220)
triggerall       = !var(0)
triggerall       = var(1) < 4
trigger1         = AnimElemTime(4) >= 0
projid           = 20220
projanim         = 20225
projhitanim      = -1
projremanim      = -1
projremove       = 0
projremovetime   = 2
projhits         = 1
projpriority     = 1
projsprpriority  = 10
offset           = 0, 0
velocity         = Vel X, Vel Y
animtype         = Medium
attr             = S, NA
damage           = 22, 0
hitflag          = MAF
guardflag        = MA
pausetime        = 8, 8
sparkno          = S6000 + Random % 8
guard.sparkno    = S6061
sparkxy          = Floor(50 * const(size.xscale)), Floor(-120 * const(size.yscale))
hitsound         = S7, 2
guardsound       = S8, 1
ground.type      = High
ground.hittime   = 18
ground.slidetime = 17
ground.velocity  = -3 * Root,fvar(31), -2 * Root,fvar(31)
guard.ctrltime   = 16
guard.velocity   = -7 * Root,fvar(31)
air.hittime      = 17
air.velocity     = -2 * Root,fvar(31), -3 * Root,fvar(31)
air.juggle       = 0
air.fall         = 1
fall.recover     = 0
id               = 20220

The value of helper var(0) and var(1) keeps 0 in the video bottom-left.
Maybe something wrong with ProjContactTime？

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/38396687/0bb445fa-d474-4528-ab4e-e806f1e344f4

### Engine Version (or source code date)

nightly build(20240524)

### Operating system

Windows

**Comment by Wftk** [comment]
Tested, and it happens in ikemen 0.98 and latest versions as well

**Comment by ghost** [comment]
There's a reason for that, in official builds of mugen, all projectiles are treated as if they are being managed by the root, because the same memory buffer is shared across all helpers that have that root (or main owner), because of that, characters that rely on this redirection to work properly break and become possibly unplayable or overly cheap because the helper is now the owner of that projectile, due to how Ikemen GO implemented projectiles (they all have their own projectile memory).
This is easily fixed by removing the root redirections within that helper's state.

**Comment by potsmugen** [comment]
The projectiles and root issue has been addressed before in other reports. This one has to do with the inner workings of projectiles in Mugen. The challenge as usual will be to fix it without breaking other characters.
