### ISSUE TITLE
Collision Boxes are misaligned in non-standard resolutions

### ISSUE THREAD

**Issue by SaltAddict** [ikemen-engine/Ikemen-GO#1817]
### Describe the bug

Using non-standard resolutions (512x448 in this case) will cause the collision boxes to appear seriously misaligned.

512x448:
![ikemen004](https://github.com/ikemen-engine/Ikemen-GO/assets/62810901/9309afda-38ad-4aee-bc4e-c1379c8c3255)

640x480
![ikemen005](https://github.com/ikemen-engine/Ikemen-GO/assets/62810901/773fa924-048e-447a-b448-a7321381b6e2)

### To Reproduce

Set resolution to something non-standard
Hit Ctrl+C
Clsn are misaligned

### Expected behavior

The Clsn to be the same position regardless of resolution

### Engine Version (or source code date)

nightly

### Operating system

Windows

**Comment by potsmugen** [comment]
I was afraid this would be related to some Clsn display changes I did, but as I like to say the good news is that this is at least not a regression. The same thing happens in 0.99 and 0.98.2.

It looks like the lifebars are also all out of whack.
