### ISSUE TITLE
ReversalDef doesn't always work properly

### ISSUE THREAD

**Issue by UltraCombo3000** [ikemen-engine/Ikemen-GO#1823]
### Describe the bug

ReversalDefs do not work at all if a character has blue Clsn during the move, but no NotHitBy or HitBy SCTRLs. This does not occur in Mugen 1.1.

### To Reproduce

1. Start a match with any character VS [this Yosuke Hanamura](http://www.mediafire.com/file/ka2ugzm6hy799u0/Yosuke.zip)
2. Have Yosuke use his counter, done by hitting medium kick + heavy kick (aka the B and C buttons)
3. Have the other character hit Yosuke with any non-projectile attack (as demonstrated in the videos below)

Note: The reason why I specified non-projectiles is because it actually DOES work properly against things like Hadokens and bullets. This is because this counter is programmed with a HitOverride against them, while it ReversalDefs against everything else.

### Expected behavior

This is what happens in Mugen 1.1:

https://github.com/ikemen-engine/Ikemen-GO/assets/124517004/1d602f8b-176e-4ef4-9d33-ad3784d7868d

### Screenshots / Video

This is what happens in nightly (unsure about other versions):

https://github.com/ikemen-engine/Ikemen-GO/assets/124517004/b4d5af78-2964-42fc-81cc-f61cc074852b

### Engine Version (or source code date)

nightly

### Operating system

Windows

### Extra context or search terms

I found that ReversalDefs that are either combined with NotHitBy or just don't have any blue Clsn at all work properly.

**Comment by potsmugen** [comment]
It's tough getting _every_ test case to work simultaneously. That said this seems to be caused by a part of the code that may be obsolete. I'll make a PR after more testing.
