### ISSUE TITLE
external/script/main.lua:714: <game end> , crash on uncommenting system.def modes

### ISSUE THREAD

**Issue by iamno1one** [ikemen-engine/Ikemen-GO#1828]
### Describe the bug

game crashes to desktop if you edit select.def and very first mode is uncommented, 

by moving a valid mode to the top spot ie
menu.itemname.menuversus.teamversus = "TEAM"

will prevent the crash.

errorlog

external/script/main.lua:714: <game end>
stack traceback:
	[G]: in function 'refresh'
	external/script/main.lua:714: in function 'f_refresh'
	.\external\script\start.lua:2246: in function 'f_selectScreen'
	.\external\script\start.lua:1421: in function 'f'
	external/script/main.lua:3106: in function 'loop'
	external/script/main.lua:3190: in function 'loop'
	external/script/main.lua:4157: in main chunk
	[G]: ?

### To Reproduce

in system.def

if you uncomment the very first item , game will crash to desktop

; Submenu: Versus
menu.itemname.menuversus = "VERSUS"
menu.itemname.menuversus.versus = ""
menu.itemname.menuversus.teamversus = "TEAM"
menu.itemname.menuversus.versuscoop = "CO-OP"         ;Ikemen feature
menu.itemname.menuversus.freebattle = ""          ;Ikemen feature
menu.itemname.menuversus.back = "RETURN"  

will crash if you have the uncommented item at the very top 

### Expected behavior

; Submenu: Versus
menu.itemname.menuversus = "VERSUS"
menu.itemname.menuversus.teamversus = "TEAM"
menu.itemname.menuversus.versus = ""
menu.itemname.menuversus.versuscoop = "CO-OP"         ;Ikemen feature
menu.itemname.menuversus.freebattle = ""          ;Ikemen feature
menu.itemname.menuversus.back = "RETURN" 

will not crash

but as menu.itemname.menuversus.versus = ""

is above "coop"  & "return"
"coop" nor "Return" is not procesed and game goes straight into teamversus  mode.

### Engine Version (or source code date)

latest nightly

### Operating system

Windows

**Comment by potsmugen** [comment]
You should probably actually comment them instead of making their names blank.

EDIT: Oh, according to Mugen's files that should work too. I guess it should be fixed but you can get around it in the meantime with commenting/erasing the whole line.

**Comment by K4thos** [comment]
already reported #1407
