### ISSUE TITLE
Fullscreen Aspect Ratio

### ISSUE THREAD

**Issue by CTRL-ALT-DEL-80** [ikemen-engine/Ikemen-GO#183]
Hello, i'm trying to make Ikemen go keepong the 4:3 aspect ratio in fullscreen, but i dont find anything in config.json...

There another way to do that?

Thank!

**Comment by Windblade-GR01** [comment]
Do you have the game set up as 4:3 resolution?
When you enter fullscreen the image stretches?

**Comment by K4thos** [comment]
this is something that your GPU handles, not ikemen. In nvidia GPU use following settings to prevent your GPU from stretching the 4:3 image on fullscreen: 
![Untitled](https://user-images.githubusercontent.com/8928195/126684843-c23283fd-5abd-4c83-8355-f5bb8c6693f8.png)

AMD should have similar option too.
