### ISSUE TITLE
Can't go fullscreen on 320x240 Resolution

### ISSUE THREAD

**Issue by shoddydev** [ikemen-engine/Ikemen-GO#1841]
When setting the resolution to 320x240 it'll display the screen on the bottom left corner and black bars to expand it.

![ikemen001](https://github.com/ikemen-engine/Ikemen-GO/assets/42045893/66c405f2-7dc5-4a9b-ac76-ad17fe555d72)

I think I know what's going on. When we change the resolution setting, it changes the Desktop resolution to match it. But because most monitors can't go down to 320x240 it instead changes the res to 640x480 while the game res is 320x240. Is there a alternate way to make it go fullscreen without changing the desktop resolution? Such as maximizing the window

**Comment by SuperFromND** [comment]
This is largely a hardware limitation more than anything (most graphics drivers on modern OSes, and many modern monitors as well, simply do not support 320x240 fullscreen properly).

That being said, this might be fixed now in latest nightly since I've added the ability to resize the window independently of game resolution.

**Comment by shoddydev** [comment]
> This is largely a hardware limitation more than anything (most graphics drivers on modern OSes, and many modern monitors as well, simply do not support 320x240 fullscreen properly).
> 
> That being said, this might be fixed now in latest nightly since I've added the ability to resize the window independently of game resolution.

Thank you. I'm targeting a PlayStation Classic which is a linux armv7 device, and playing it at 320x240 I am able to get 60fps on most games so that's why I really wanted this feature. Would it be possible to add this to SDL2? I'm using leonkasovan's SDL2 fork of it here:

https://github.com/leonkasovan/Ikemen-GO/tree/SDL2/src

I was unable to get GLFW to launch. But SDL2 works on the PSC.

**Comment by SuperFromND** [comment]
You'll have to ask the people maintaining that fork, I don't believe we have plans to support SDL2 in the main repo at the moment. (I could very well be wrong and/or this could change in the future!)

**Comment by shoddydev** [comment]
no worries. btw i noticed in some of the code, the k in keepAspect is uppercase and some it's lowercase. like in main.go there's
sys.keepAspect = tmp.KeepAspect

while in system.go it's
keepAspect:        true,

and in main.go it's
KeepAspect                 bool

Is that correct? just want to make sure it doesn't cause any conflicts

**Comment by shoddydev** [comment]
leonkasovan updated his fork of it and it's working now. i'm so happy i've been trying to get this to work for 5 months lol
