### ISSUE TITLE
Dumb Question

### ISSUE THREAD

**Issue by skoolag3** [ikemen-engine/Ikemen-GO#1844]
How to disable "DrawShadows" and choose the renderer="directx or opengl"

**Comment by SuperFromND** [comment]
We don't currently have a DirectX renderer in Ikemen; you can only use OpenGL. Same goes for the DrawShadows option; `save/config.json` has no equivalent.

**Comment by potsmugen** [comment]
DrawShadows would probably be easy enough to implement. But would there be much of a performance gain? Especially compared to fantasma's renderer branch.
