### ISSUE TITLE
Lifebar font transparency is broken when using AllPalFX

### ISSUE THREAD

**Issue by zzzz0424** [ikemen-engine/Ikemen-GO#1847]
### Describe the bug

There is a bug that breaks the transparency of the font in the life bar when using AllPalFX in the current nightly.
This problem occurs in both def and fnt files, so it does not matter what font standard is used.

### To Reproduce

Add the following code to [Statedef -3] in KFM
```
[State -3, AllPalFX]
type = AllPalFX
trigger1 = RoundState = 2
time = 2
add = 50,50,50
mul = 256,256,256
sinadd = 0,0,0,1
invertall = 0
color = 256
```
I made the effect a little brighter for clarity.

### Expected behavior

Maintain font transparency when using AllPalFX as in v0.99 and previous versions

### Screenshots / Video

Without AllPalFX
![ikemen096](https://github.com/ikemen-engine/Ikemen-GO/assets/60909119/c7abfe55-0d5e-49de-974b-8cfeab094127)

State using AllPalFX
![ikemen095](https://github.com/ikemen-engine/Ikemen-GO/assets/60909119/38acdbd8-b04d-4741-a880-83a6830b243b)

### Engine Version (or source code date)

nightly

### Operating system

Windows

**Comment by Wftk** [comment]
I'l fix that issue. Btw seems like fonts still using legacy code which changes palette due to palfx itself.
