### ISSUE TITLE
Joe: Hyper freezing issues

### ISSUE THREAD

**Issue by waspennator** [ikemen-engine/Ikemen-GO#1849]
### Describe the bug

Tested on the latest nightly build, for some reason when performing any of his hypers save for his Spook note and No Touchy hypers, Ikemen GO will freeze up, the window becomes non responsive, my cpu starts ramping up to the point the fans start spinning and I have to manually kill the process, does not happen with any of his hypers on Mugen 1.1b

### To Reproduce

1: Download Joe from here (https://www.mediafire.com/file/dzhn41qb7zj7g5q/Joe_v3.2.zip/file)
2: Perform Joe's Bucket-a-GAS hyper (D, DF, F, D, DF, F, LK+MK Costs 2000 Power)
3: After a second or two, Ikemen GO should freeze up.

### Expected behavior

Performing Joe's hyper moves like his Bucket-a-GAS hyper should not freeze up Ikemen GO.

### Engine Version (or source code date)

Nightly Build 6/20/24

### Operating system

Windows

**Comment by potsmugen** [comment]
This doesn't happen in a build from June 2nd or if you remove the sound loop in line 8820.

**Comment by Jesuszilla** [comment]
Found the issue. The StreamLooper logic was kicking in too early because the sound was a very short length, causing it to infinitely seek to the beginning because loop points were added to PlaySnd recently (using the same BGM looper logic). I'll have a PR up to fix this in a bit!
