### ISSUE TITLE
The State controller for zooming behaves differently from MUGEN 1.1.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#1858]
### Describe the bug

The State controller for zooming behaves differently from MUGEN 1.1.

### To Reproduce

1.Download Xinkeniang in 小泥巴.
2.Select Xinkeniang in either mode.

### Expected behavior

The zoom during the intro differs from MUGEN 1.1.

### Engine Version (or source code date)

v0.99.0 and nightly

### Operating system

Windows

**Comment by Wftk** [comment]
Zoom sctrl in Mugen 1.1 wasn't finished and bugging a lot, i don't think keeping that broken behavior even if its for compatability have any sense.

**Comment by Kuroteba** [comment]
Understood.
