### ISSUE TITLE
PlaySnd with lowpriority=1 will no longer play.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#1859]
### Describe the bug

PlaySnd with lowpriority=1 will no longer play.

### To Reproduce

1.Prepare PlaySnd with Channel set to 0 and lowpriority set to 1.
2.While playing PlaySnd with Channel of 0, it is attacked and playback is stopped.
3.PlaySnd with Channel of 0 and lowpriority of 1.

### Expected behavior

PlaySnd audio does not play when it should have been executed in 3 of To Reproduce.

### Engine Version (or source code date)

6/20/2024 - nightly

### Operating system

Windows

### Extra context or search terms

This bug did not occur in 0.99.

**Comment by potsmugen** [comment]
Did you try latest nightly? There were some related bugs fixed very recently.

EDIT: Nevermind. It also happens there. This doesn't happen in June 2d build but happens in June 17th build. I suspect it started when I added the StopOnGetHit parameter. I'll upload a fix later.
