### ISSUE TITLE
The End Stage: Broken Mushroom Cloud Explosion

### ISSUE THREAD

**Issue by waspennator** [ikemen-engine/Ikemen-GO#1863]
### Describe the bug

Stage works fine up until the actual nuclear explosion shift of the stage, at that point the mushroom cloud explosion in the background seems to be missing it's middle part, believe if you jump with both characters high enough, you can see the middle part barely, seems to render in and out when you jump up and down, it's especially noticable if you get both fighters close enough then double jump.

### To Reproduce

1: Download the stage from here, stages, TheEnd.rar
https://www.mediafire.com/folder/ee98115pqt4eq/Amanojaku's_Mugen_Creations#blc1q7jfdqo43
2: Setup stage in Ikemen GO, start a match and wait for the explosion shift to happen.
3: Setup stage in mugen, start a match there and wait for the same to happen, notice the difference

### Expected behavior

The mushroom cloud should look identical to how it does on mugen, not missing its middle part.

### Screenshots / Video

Ikemen GO Nightly:
![Screenshot 2024-06-29 021305](https://github.com/ikemen-engine/Ikemen-GO/assets/78768499/0078beb5-e946-48cc-b37b-0ad770b5f8d0)

Mugen 1.1b:
![Screenshot 2024-06-29 021432](https://github.com/ikemen-engine/Ikemen-GO/assets/78768499/e68c30d5-ac65-47dd-970b-b66d4e16ffc1)

### Engine Version (or source code date)

Nightly Build 6/27/24

### Operating system

Windows

**Comment by Wftk** [comment]
same issue with window/windowdelta params as #1862
