### ISSUE TITLE
Attack doesn't work against characters in movetype = A

### ISSUE THREAD

**Issue by CobraCaddie** [ikemen-engine/Ikemen-GO#1879]
### Describe the bug

I have a character who attacks opponents with a ground.type = n hitdef in order to not interrupt the opponents movement or attack, but will still subtract their life. To do this, the character has to read gethitdef(id) of their opponent.

In the nightly build of IKEMEN, in order for a character or helper to read gethitdef(id), the character or helper has to have movetype = a. This is bad say if a character initiates the hitdef but a helper is reading the gethidef(id). Secondly, even if the character or helper has movetype = a, it still won't read an opponents gethitdef(id) if the opponent is in a state with movetype = a.

Issue is NOT present in the last stable build of IKEMEN, the move works as intended regardless of the enemies state.

### To Reproduce

Character is unreleased, issue can be recreated in single mode with this coding:

[State 200, hitdef]
type = HitDef
trigger1 = time = 0
attr = S, NA                     ;Attribute: Standing, Normal Attack
damage = 20, 0                   ;Damage that move inflicts, guard damage
animtype = Light;Light                 ;Animation type: Light, Medium, Heavy, Back (def: Light)
guardflag =                    ;Flags on how move is to be guarded against
hitflag = MA;MAF                    ;Flags of conditions that move can hit
priority = 7, Hit                ;Attack priority: 0 (least) to 7 (most), 4 default
;Hit/Miss/Dodge type (Def: Hit)
pausetime = 0, 0                 ;Time attacker pauses, time opponent shakes
sparkno = -1                      ;Spark anim no (Def: set above)
sparkxy = 0, 0               ;X-offset for the "hit spark" rel. to p2,
;Y-offset for the spark rel. to p1
hitsound = S1000, 1                  ;Sound to play on hit
;guardsound = 0, 0                ;Sound to play on guard
ground.type = n            ;Type: High, Low, Trip (def: Normal)
ground.slidetime = 0             ;Time that the opponent slides back
ground.hittime  = 0             ;Time opponent is in hit state
ground.velocity = 0             ;Velocity at which opponent is pushed
airguard.velocity = 0,0     ;Guard velocity in air (def: (air.xvel*1.5, air.yvel/2))
air.type = None                  ;Type: High, Low, Trip (def: same as ground.type)
air.velocity = 0,0           ;X-velocity at which opponent is pushed,
;Y-velocity at which opponent is pushed
air.hittime = 0
;palfx.time = 2
;palfx.mul = 255,255,255
;palfx.add = 32,32,32
hitonce = 1
id = 4301

[state 200,var1] 
type = varset
trigger1 = player(1), gethitvar(id) != 0
v = 1
value = player(1), id

[state 200,var2] 
type = varset
trigger1 = player(2), gethitvar(id) != 0
v = 1
value = player(2), id

[State 200, life]
type = lifeadd
trigger1 = var(1) != 0
value = -20
RedirectID = var(1)

Then try to hit the opponent when they are attacking.

### Expected behavior

Move should effect opponent regardless of opponents movetype

### Screenshots / Video

![ikemen004](https://github.com/ikemen-engine/Ikemen-GO/assets/174930968/547b64eb-d054-49e0-abbb-46220203c17e)

### Engine Version (or source code date)

Nightly

### Operating system

Windows

**Comment by CobraCaddie** [comment]
https://github.com/ikemen-engine/Ikemen-GO/assets/174930968/14bc0804-55df-4ac5-94fb-03a32a3a7f82

Video

**Comment by potsmugen** [comment]
The test case behaves the same way in stable 0.99 and Nightly. This is a byproduct of char processing order. I think the same thing will happen in Mugen if you manage to adapt the code somehow.

The sequence of events in the videos is somewhat like this:

Hit detection happens -> GetHitVar(ID) is set -> next frame
KFM runs first because of movetype A -> GetHitVar cleared because movetype != H -> bullet runs -> Contra Team runs

**Comment by K4thos** [comment]
If it's related to processing order, which now behaves like Mugen, I assume we can close this ticket. Please let me know if it should be considered a bug, and I will reopen it then.
