### ISSUE TITLE
When opening ikemen go nightly even with msaa disabled i get a black screen 

### ISSUE THREAD

**Issue by youssefmine** [ikemen-engine/Ikemen-GO#1901]
I get a black screen when I open ikemen go nightly with msaa disabled

**Comment by SuperFromND** [comment]
What GPU and OS are you using?

**Comment by SuperFromND** [comment]
Actually, while you're here:
~~If you can, could you replace your `Ikemen_GO.exe` with this version? Does this display correctly?
[Ikemen_GO_nightly_with_membarrier.zip](https://github.com/user-attachments/files/16340244/Ikemen_GO_membarrier.zip)~~

EDIT: someone else with this same problem tested, same issue, so this isn't necessary for you to test anymore.

Some further notes:
- This seems to only happen on new/fresh installs, and only if Ikemen *isn't* being launched for the first time (i.e. older installs that update to latest nightly).
- This also doesn't happen for me at all, so it likely only affects a specific OS/GPU vendor/something else?
- A temporary workaround is... running Ikemen GO in _administrator mode_? (thank you inktrebuchet for informing me of all this)

**Comment by youssefmine** [comment]
I am using windows 10 and intel hd graphics 5500

**Comment by SuperFromND** [comment]
Thank you for letting me know that! The other people with this issue seem to all be on Intel HD as well, so I can only assume this is something wrong with either Intel's drivers or a very weird graphical edge case that AMD/Nvidia gloss over.

**Comment by youssefmine** [comment]
No problem, Hope you find a way to fix it
