### ISSUE TITLE
Specific combo not working in v0.99.0 release version

### ISSUE THREAD

**Issue by Lukaswbrr** [ikemen-engine/Ikemen-GO#1905]
### Describe the bug

One of the combo of SSJ Goku that used to work on a stable v0.98.2 version no longer works in stable v0.99.0 due to heavy kick's 2nd hit not connecting in mid combo.

### To Reproduce

1. Download SSJ Goku from https://network.mugenguild.com/balthazar/hyperdbz/characters.html
2. Perform the following combo: 5A > 5B > 5C (x2) > 236X (x3) > 214Z > 5X > 2X > 5Y > 5Z (x2) > jump > j.5A > j.5B > j.5C > 5C (x2) > 623Z (the 623Z part ins't necessary since the combo drops on the second hit of 5C)
3. After the teleport, the heavy kick's 2nd hit doesn't connect

### Expected behavior

The heavy kick's 2nd hit from the combo should work normally just like from v0.98.2 version

### Screenshots / Video

First video is from Hyper DBZ 5.0d [Mugen 1.0]

https://github.com/user-attachments/assets/0f151cf2-1089-41e9-860c-17dbbabefcbe

Second video is from Ikemen GO v0.98.2 [Release version]

https://github.com/user-attachments/assets/4f42382a-4cfb-4b31-9141-069b25bac175

Third video is from Ikemen GO v0.99.0 [Release version]

https://github.com/user-attachments/assets/172721ab-abcf-416b-9355-aeafff5e0c6d

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

**Comment by potsmugen** [comment]
Have you tried on the nightly build?

**Comment by Lukaswbrr** [comment]
> Have you tried on the nightly build?


https://github.com/user-attachments/assets/845c08c6-a68e-41ce-9b86-7b4cd6ce6bcf


I tried the nightly build and the issue is still there

**Comment by potsmugen** [comment]
Thanks. I know what the problem is now.
