### ISSUE TITLE
''here comes a new challenger '' no sound ,new bug in newest nightly.

### ISSUE THREAD

**Issue by weiwangko** [ikemen-engine/Ikemen-GO#1908]
### Describe the bug

''here comes a new challenger '' no sound ,new bug in newest nightly.

### To Reproduce

''here comes a new challenger '' no sound ,new bug in newest nightly.

### Engine Version (or source code date)

nightly

### Operating system

Windows

**Comment by potsmugen** [comment]
Fixed by #1909
