### ISSUE TITLE
Mikage's th123 character's card system disappeared.

### ISSUE THREAD

**Issue by netyzh** [ikemen-engine/Ikemen-GO#1910]
### Describe the bug

No card appears at the bottom of screen.

### To Reproduce

Download character from:https://onedrive.live.com/?cid=0ED0CD50727D58FD&id=ED0CD50727D58FD%21607&parId=ED0CD50727D58FD%21135&o=OneUp
Then start a match.

### Screenshots / Video

In Ikemen-go:
![ikemen014](https://github.com/user-attachments/assets/bd1fbb8b-8fd1-45ce-939e-982a64e523d0)
Same characters in mugen 1.1:
![mugen021](https://github.com/user-attachments/assets/02204244-6d6b-4403-a97a-e0e7de4a35b5)

It seems works correctly in previous ikemen version.

### Engine Version (or source code date)

nightly build(20240724)

### Operating system

Windows

**Comment by potsmugen** [comment]
My bad. Will fix soon.
