### ISSUE TITLE
Ikemen go window nighty build July 25,2024

### ISSUE THREAD

**Issue by OldGamers** [ikemen-engine/Ikemen-GO#1911]
### Describe the bug

Not a bug per say but when you try to extend the window with Ikemen go window 99.0 nightly build you get a Transparent double minor flicker Image on left boarder side of the screen. 

https://github.com/user-attachments/assets/d15762af-0269-4683-af12-ab98bea6153a

### To Reproduce

 not fully expand for the window screen

### Expected behavior

the behavior of Ikemen go 99.0 nightly engine does not fully expand for the window screen by this create an after image flicker 

### Screenshots / Video

![Untitled](https://github.com/user-attachments/assets/2ae5482a-738c-45ab-aea0-700bb8751e8d)

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

### Extra context or search terms

 not fully expand for the window screen

**Comment by SuperFromND** [comment]
Ah, I think I know what's causing this; we never clear the entire window when drawing new frames after resizing.

Shouldn't be *too* hard to fix in theory?
