### ISSUE TITLE
My Kyo-213's Raging Demon doesn't pause when Kanji BG

### ISSUE THREAD

**Issue by jankespro12** [ikemen-engine/Ikemen-GO#1915]
### Describe the bug

When i was using my Edit of Kyo-213, for some reason, using the Raging Demon Super and KO the Opponent, for some reason, match doesn't pause on Kanji BG

### To Reproduce

1. Download My Edit of Kyo-213 https://drive.google.com/file/d/1UUTua8PYPbqnRP7OGkKC4_xMGvP7p_MS/view?usp=sharing
2. Got to versus mode and Pick Kyo-213, set opponents life to 1 and do Raging demon on that opponent
3. Match doesn't pause on Flaming Kanji Animation

### Expected behavior

It supposed to pause during the Flaming Kanji animation

### Screenshots / Video

https://github.com/user-attachments/assets/b637e0f0-48a3-497e-9d0c-86016be16183

### Engine Version (or source code date)

Nightly (2024-07-24)

### Operating system

Windows

**Comment by potsmugen** [comment]
It's working correctly in my development build, so it was probably related to another bug. Will be fixed in a few days.
