### ISSUE TITLE
Strange cloning bug on nightly

### ISSUE THREAD

**Issue by DolphinDan400** [ikemen-engine/Ikemen-GO#1920]
### Describe the bug

On the latest nightly build (July 24th 2024), An issue with certain characters producing clones started occuring, the biggest example I've found is with y.y's Hol Horse, as pressing any direction while he's shooting his gun will turn the bullet into a clone.

### To Reproduce

1. Download y.y's Hol Horse from here: https://www.mediafire.com/file/8nq5o5yfkm4rlzm/hol2.zip
2. During gameplay, perform a fireball motion (or any other move that shoots a bullet) and press any direction during the animation (easier done by not letting go the direction)

### Expected behavior

The bullet is not supposed to turn into a clone while it's being shot.

### Screenshots / Video

https://github.com/user-attachments/assets/cc17f3e3-a2fc-4f92-876a-05528a052c1d

(audio muted due it being way too loud)

### Engine Version (or source code date)

nightly 24/7/24

### Operating system

Windows

### Extra context or search terms

It seems this started happening sometime after nightly 3/7/24 because I have a different, slightly older build from that date that doesn't present this issue.

**Comment by jankespro12** [comment]
I believe Eliza from Divinewolf has that same problem as well.

**Comment by potsmugen** [comment]
It's working on my dev build so probably the same regression as another report. Will be fixed in next engine updates.
