### ISSUE TITLE
GNSK's Kazama Kotaro can't run out of screen in tag mode.

### ISSUE THREAD

**Issue by netyzh** [ikemen-engine/Ikemen-GO#1925]
### Describe the bug

GNSK's Kazama Kotaro can't run out of screen in tag mode and you can't use D or W to switch her.
The same bug appeared in some other characters in 20240724 version but they got repaired in 20240731 version,except Kazama Kotaro.

### To Reproduce

Download character from https://onedrive.live.com/?authkey=%21AKRaUlCkidIYrJQ&cid=0ACFAD20A0B82143&id=ACFAD20A0B82143%21194&parId=ACFAD20A0B82143%21136&o=OneUp
Practice in tag mode

### Screenshots / Video

https://github.com/user-attachments/assets/85126441-47f2-4736-949b-69e6cdf825e0

### Engine Version (or source code date)

nightly build(20240731)

### Operating system

Windows

**Comment by potsmugen** [comment]
Not all characters will work 100% with the default tag. You can try modifying them or using alternative tag codes. That said maybe we could cover this particular case.

**Comment by netyzh** [comment]
> Not all characters will work 100% with the default tag. You can try modifying them or using alternative tag codes. That said maybe we could cover this particular case.

OK,I found the code in kotaro-2.cns

;●画面端で相手を飛び越えると裏回りするかどうかを設定します
[State -2, 画面端裏回り]
type = VarSet
trigger1 = 1
var(22) = 1      ;0:裏回りしない　 1:裏回りする

Change var(22) to 0 can solve the problem.
