### ISSUE TITLE
Charge Inputs not working correctly on keyboard

### ISSUE THREAD

**Issue by DolphinDan400** [ikemen-engine/Ikemen-GO#1926]
### Describe the bug

In the current Nightly version (July 31st 2024), performing charge inputs on keyboard has become unreasonably strict, this wasn't the case in the previous versions of the engine, nor in the original Mugen 1.0.

### To Reproduce

1. Download Ia from here: http://valgallah77.web.fc2.com/characters/ (near the bottom of the page), or try any other character with charge inputs like Guile.
2. Try to perform any charge input. (for example, hold back, then forward + punch)

### Expected behavior

There should be a small window of input leeway when performing charge moves instead of being seemingly frame perfect.

### Screenshots / Video

https://github.com/user-attachments/assets/21c6bc51-c2e9-4943-84bb-0f833acc9278

### Engine Version (or source code date)

nightly 31/7/24

### Operating system

Windows

### Extra context or search terms

Note that this issue doesn't happen when playing using a Joystick, it's seemingly a keyboard-only issue.

**Comment by potsmugen** [comment]
The issue is that you can't release back and press forward in the same frame, which is why it doesn't work on keyboard but works on a pad. I've located the problem and will fix later.
