### ISSUE TITLE
Majin Vegeta 214PP faster on Ikemen

### ISSUE THREAD

**Issue by Junny4444** [ikemen-engine/Ikemen-GO#1928]
### Describe the bug

In Hyper DBZ, the majin vegeta character has a lariat that switches sides with the opponent, on ikemen the process that takes place on hit ends earlier and lets him act faster, changing combo timings. on Mugen this does not occur

### To Reproduce

1.Download Hyper DBZ, (Discord Beta)
2. Play as majin vegeta and use 214PP

### Expected behavior

Slower animation on hit

### Screenshots / Video

What happens on Ikemen:

https://github.com/user-attachments/assets/acf341a5-1acb-45ed-b99d-96621c031eda

What happens on Mugen (Intended Behavior):

https://github.com/user-attachments/assets/999a79c1-d902-48fc-bfc7-9d811cfe801b

### Engine Version (or source code date)

0.99

### Operating system

None

**Comment by potsmugen** [comment]
Looks like the same issue as #1550

**Comment by K4thos** [comment]
Closing as a duplicate for maintenance.
