### ISSUE TITLE
Damage counter

### ISSUE THREAD

**Issue by Blac-Dragoon** [ikemen-engine/Ikemen-GO#1930]
### Describe the bug

During combos, the damage is displayed as 0/0% and not the actual number.

### To Reproduce

Use current nightly build with any motif that has damage display during combos in FIGHT.def.

### Expected behavior

As mentioned above, the damage displayed in combo display is always 0/0%.

### Screenshots / Video

![ikemen180](https://github.com/user-attachments/assets/ed90f934-3a8e-4064-bf6a-1484a55e38df)

### Engine Version (or source code date)

v.0.99 nightly

### Operating system

Windows

**Comment by potsmugen** [comment]
How recent is your build? There was a bug like that a couple months ago.

**Comment by Blac-Dragoon** [comment]
The most recent from July 31 of this year.

**Comment by potsmugen** [comment]
Can't reproduce currently. Have you tried a clean install? Or do you mean specifically in demo mode?

![ikemen004](https://github.com/user-attachments/assets/fd5d0b3e-79cd-4945-b2f6-e6924f78c8e1)

**Comment by Blac-Dragoon** [comment]
I have done a clean install. I'll try a different folder to see if it'll work.

UPDATE:
I got it working. It turns out I've used an older build (and didn't know it) and I needed to update my copy of Go.
![ikemen181](https://github.com/user-attachments/assets/5f2e63b8-6e2c-4edf-a3c6-267e9035ed8a)

Thanks anyway.
