### ISSUE TITLE
An error occurred in the value2 under Nothitby

### ISSUE THREAD

**Issue by netyzh** [ikemen-engine/Ikemen-GO#1938]
### Describe the bug

The attribute specified by value2 under nothitby does not match the actual behavior

### To Reproduce

Download character from https://onedrive.live.com/?authkey=%21HO7Cd3cUzJw%24&cid=92E21E27C50DFCD7&id=92E21E27C50DFCD7%21201&parId=92E21E27C50DFCD7%21102&o=OneUp
I found out that this character cannot be hit by more than 1 hit on the ground.

### Screenshots / Video

https://github.com/user-attachments/assets/2064eec3-aad2-4e5a-9b28-541ae580daa8

I found the codes in Sakuya_-2.st, only throw attack should not be hit.
[State -2, NotHitBy]
Type = NotHitBy
Trigger1 = StateNo = [5000, 5030]
Trigger1 = StateType != A
Value2 = , NT
Time = 8
IgnoreHitPause = 1

Change Value2 to Value can solve the problem

https://github.com/user-attachments/assets/d5aa0423-25ce-4cae-a889-c637d809415f

### Engine Version (or source code date)

nightly build(20240807)

### Operating system

Windows

**Comment by potsmugen** [comment]
Found the issue. Thanks for reporting.
