### ISSUE TITLE
Specific character makes (almost) invincible

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [ikemen-engine/Ikemen-GO#1940]
### Describe the bug

Strangely, specific characters don't take damage when it's supposed to do. I don't know what's causing this, but in mugen it takes damage.

### To Reproduce

1. Download character from https://drive.google.com/file/d/1jCwAZ7HFPKVcyBgT1NE9RisKYqyBxopo/view
2. Start the match and opponent attacks.
3. See Error

### Expected behavior

Specific characters do damage like normallly do in mugen.

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

**Comment by potsmugen** [comment]
Looks like an issue with the minimum value for LifeAdd. I'll fix it in my next PR.
