### ISSUE TITLE
Hitbox not connecting when behind opponent?

### ISSUE THREAD

**Issue by RagingRowen** [ikemen-engine/Ikemen-GO#1941]
### Describe the bug

Seems to be an issue with the newest nightly. Hitboxes that come out behind P2 which at point blank don't seem to hit, unlike in normal MUGEN.

### To Reproduce

Use Ash Crimson by KarmaCharmeleon (https://www.mediafire.com/folder/f4qxixm5h39cu) and try to use his (charge) B,F,k move up-close.

### Expected behavior

Move will successfully hit.

### Screenshots / Video

![Screenshot 2024-08-10 131921](https://github.com/user-attachments/assets/8b446fee-47ba-4125-9330-93664ed496fe)

### Engine Version (or source code date)

Nightly, 2024-08-07

### Operating system

Windows

**Comment by potsmugen** [comment]
This is because Ikemen runs hit detection first and pushes characters away from each other second. I thought that was strange before but didn't have a particular reason to change it. Will be fixed in next PR.
