### ISSUE TITLE
Characters stuck on 5110 state before win animation plays

### ISSUE THREAD

**Issue by ynass757** [ikemen-engine/Ikemen-GO#1942]
### Describe the bug

When winning a match in either Arcade or VS. Mode, characters are staying idle for a period of 15-20 seconds before win animations properly play.

Confirmed does not occur on M.U.G.E.N. 1.1. Issue seems to be triggered when I have them use common1.cns.zss, and is avoided when using my own common1.cns file from an old M.U.G.E.N. 1.1 build, which is no different from the standard common1.cns file.

### To Reproduce

1. Download character here: [https://www.mediafire.com/file/ftoxzy5ib2fgk04/ryu_cvs.zip/file](url)
2. Add to your I.K.E.M.E.N. Go build and proceed to either Arcade or VS. Mode.
3. Win the match.

### Expected behavior

Once any character is defeated, it should hope over to win animation seamlessly. Additionally, defeated character in 5110 state should not slide.

### Screenshots / Video

https://github.com/user-attachments/assets/171df7df-d8af-439c-a7cc-466ca6dcfc98

https://github.com/user-attachments/assets/36ad6353-8d68-423d-bb32-9d80ec413246

https://github.com/user-attachments/assets/38e13922-dd94-4b13-afaa-db2ccddfa45c

### Engine Version (or source code date)

v0.99

### Operating system

Windows

**Comment by ynass757** [comment]
Just as an added extra, here is my builds common1.cns.zss file: [https://www.mediafire.com/file/9eax74oq28krftc/common1.cns.zss/file](url)

**Comment by potsmugen** [comment]
The char is using state 5160, which doesn't exist. Even if it did exist, Mugen/Ikemen only proceed with the round over when the char is specifically in state 5150.

**Comment by ynass757** [comment]
Thanks PoTS. I'm make the needed changes to address this.
