### ISSUE TITLE
IKEMEN Go crashes if too many player type helpers spawn at once

### ISSUE THREAD

**Issue by SLIFINITY** [ikemen-engine/Ikemen-GO#1944]
### Describe the bug

I love playing around with sadclaps code but this is something that has not happened before in a older nightly version, so something's wrong in the code that leads to this

### To Reproduce

1. Add the Sad Claps code template to a character, such as Wucash's Silver Surfer, or DDR's characters like Captain Caveman, Marvin, etc.
2. Do any move that would spawn a player helper, if using Wucash's Silver Surfer
3. Game instantly crashes with a runtime error. or shortly after one of DDR's character intros play

### Expected behavior

IKEMEN Go should handle everything as normal, like the previous nightlys have before, could this be due to a rework in processing order that causes it? This obviously may be a stability regression

### Screenshots / Video

![Sadclaps IKEMEN Go crash](https://github.com/user-attachments/assets/1e73810c-958d-4fcf-9ca6-72e3aec24d0c)

### Engine Version (or source code date)

latest nightly

### Operating system

Windows

**Comment by potsmugen** [comment]
Can you provide a modified char that makes it crash all the time? It's odd because the line the error points to uses a feature exclusive to Ikemen, which Mugen chars shouldn't be calling. You sure it's the latest nightly?

**Comment by SLIFINITY** [comment]
Whoops sorry, I didn't realize there was an update, I was out of date...its already fixed.
