### ISSUE TITLE
Problem with the tag switch with specific char

### ISSUE THREAD

**Issue by shin258** [ikemen-engine/Ikemen-GO#1955]
### Describe the bug

The tag switch don't work with the char myuu (neko) release in 2002 she is the only char to have this issue.See this with the video and the picture.
Also if you select her at first the switch button does not work but the second char don't show (it's normal).(see pictures below)

### To Reproduce

https://www.andersonkenya1.net/files/file/33929-myuu/

Select the first char and select her in second and start the fight and get the same as i have. If you select her at first the button don't work too.

### Expected behavior

Just if possible to get the tag witch work with her.

### Screenshots / Video

Video (just download it due of hevc format)
https://github.com/user-attachments/assets/756e6ae8-2945-4bda-b4bc-16687f6bc3f6

Pictures:
if you select her in first:
![the witch button not work at all](https://github.com/user-attachments/assets/271078af-6bef-4c23-9910-18f6bf1a2667)

if you select her in second:
![Tag not work](https://github.com/user-attachments/assets/dac14c67-94c3-4ac4-ad15-5d6a17cd79a4)

### Engine Version (or source code date)

v.0.99 and dev.2024-08-15

### Operating system

Windows

### Extra context or search terms

Tag

**Comment by K4thos** [comment]
tag is not meant to be comptible with all characters. It's not considered an engine bug.
