### ISSUE TITLE
IsHomeTeam always returns 1.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#1958]
### Describe the bug

IsHomeTeam always returns 1.

### To Reproduce

1.Download g.rugal of Warusaki3.
2.g.rugal on the 2p side.
3.In mugen, the transition to two random intros is always one pattern.

### Expected behavior

The description of the intro of g.rugal.

[State -2, 3]
type = ChangeState
trigger1 = Time = 0
value = ifelse(random<125||(IsHomeTeam && Roundstate = 0 && Pos X > 0),192,191)

### Engine Version (or source code date)

v0.99.0 and nightly

### Operating system

Windows

**Comment by potsmugen** [comment]
Maybe IsHomeTeam works a bit different from Mugen, but it doesn't always return 1. In which game mode did you notice this difference?

**Comment by Kuroteba** [comment]
watch mode.

**Comment by potsmugen** [comment]
I see. In Mugen the left side is the home team, like in Versus, while in Ikemen it's the right side, like in Arcade. This is kind of a non-issue though.
