### ISSUE TITLE
ikemen 0.99 rc6 bug with the def mul set on transformation

### ISSUE THREAD

**Issue by ChuiAuMax** [ikemen-engine/Ikemen-GO#1992]
### Describe the bug

the def mulset in ikemen 0.99 rc6 doesn t work on transfomation

https://github.com/user-attachments/assets/9b61c629-c7a1-41ae-a2b6-36b4a9301225

https://github.com/user-attachments/assets/f99bc03b-d36b-4b75-8df7-8281f4c5a513

you can see same char on ikemen 0.98 rc2 et 0.99 rc6

see on debug goku iadrat have 300 attack 300 def and when he transform his value of mulset is x2 or  on ikemen 0.99 we have 600/300 instead of 600/600

### To Reproduce

transform with a defmulset 

### Engine Version (or source code date)

v0.99 rc6

### Operating system

Windows

**Comment by potsmugen** [comment]
Try the Nightly build. I recall a similar issue.

https://github.com/ikemen-engine/Ikemen-GO/releases/tag/nightly

**Comment by ChuiAuMax** [comment]
always the same bug in nightly version :s 

i hope that can be fix in ikemen 1.0 because we can't play  a transform char with this bug

**Comment by potsmugen** [comment]
Please upload the char in that case.

**Comment by ChuiAuMax** [comment]
all my transform char have the same problem

goku iadrat
https://drive.google.com/drive/folders/1FbXa8tg4It6uLE5ofDXALS9vlwomNO0E?usp=sharing         

the attack def value is 300/300 in base form and need to pass at 600/600 when transform

check it  and say if it s the code or ikemen 0.99

thx

**Comment by potsmugen** [comment]
The char seems to take the exact same damage as in Mugen. This is because `DefenceMulSet` is bugged in Mugen.

**Comment by K4thos** [comment]
https://github.com/ikemen-engine/Ikemen-GO/wiki/Character-features#ikemenversion
