### ISSUE TITLE
Can't pass Fall.Envshake.Ampl value to target if target is hit by ReversalDef

### ISSUE THREAD

**Issue by beterhans** [ikemen-engine/Ikemen-GO#2012]
### Describe the bug

My Goal is pass the Player ID value to Fall.Envshake.Ampl, 
so the target able to tell who hit then, and able to react if the attacker is stopped or not.

This works fine in MUGEN 1.1
but in IKEMEN GO doesn't work.
also I try hit the target again by hitdef, but the Fall.Envshake.Ampl won't update on enemy.

### To Reproduce

[State 3111, ReversalDef]
type = ReversalDef
trigger1 = var(5) = 1
reversal.attr = SCA,AA,AP,AT
pausetime = 8,0
;hitsound = S2,30
;p1stateno = 30170
p2stateno = 3113
ID = 3113
Fall.Envshake.Ampl = ID * 2;ID x 2

at target side
GetHitvar(Fall.Envshake.Ampl)
returns 0

### Expected behavior

at target side
GetHitvar(Fall.Envshake.Ampl)
returns  the value you pass in like the player id

### Engine Version (or source code date)

2024-08-27

### Operating system

Windows

**Comment by potsmugen** [comment]
I can add this in the next PR. The GetHitVars that ReversalDef can pass are different from HitDef, so let us know if you find more.

Working on this I noticed that GetHitvar(Fall.Envshake.Ampl) can assume different values than expected when chars have different localcoords from each other, which may interest you.

**Comment by beterhans** [comment]
> I can add this in the next PR. The GetHitVars that ReversalDef can pass are different from HitDef, so let us know if you find more.
> 
> Working on this I noticed that GetHitvar(Fall.Envshake.Ampl) can assume different values than expected when chars have different localcoords from each other, which may interest you.

Thanks for the fix

for the finding I noticed in Mugen 1.1 also. when game size is 1080p the parameter can only pass even number,
so as a workaournd, I will use Original player ID *2, then the target try to get this value target will /2.
