### ISSUE TITLE
ko.top in fight.def

### ISSUE THREAD

**Issue by ElGalvao** [ikemen-engine/Ikemen-GO#2019]
### Describe the bug

ko.top    failing?

### To Reproduce

ko whit fightfx sprite

### Expected behavior

anim on top

### Screenshots / Video

![Sem título](https://github.com/user-attachments/assets/00f26eb8-b8b9-47a4-b973-da70cd6b54af)

### Engine Version (or source code date)

v99

### Operating system

Windows

### Extra context or search terms
By adding the line ko.top in fight.def, supposedly the 'KO' animation should appear above any sprite from fightfx.def, right? If so, there's the problem. Tested whit some chars. check screenshot

**Comment by potsmugen** [comment]
Can you link or upload the lifebars?

**Comment by ElGalvao** [comment]
[Lifebar.zip](https://github.com/user-attachments/files/17090208/Lifebar.zip)
@potsmugen

**Comment by ElGalvao** [comment]
this files are original. not contain ko.top.

**Comment by K4thos** [comment]
I don't understand this report

**Comment by ElGalvao** [comment]
> I don't understand this report

By adding the line ko.top in fight.def, supposedly the 'KO' animation should appear above any sprite from fightfx.def, right? If so, there's the problem.

**Comment by K4thos** [comment]
no. To make it render on top of char you need to add KO.layerno = 2
