### ISSUE TITLE
Music with loops included or made in the (stagename).def doesnt work.

### ISSUE THREAD

**Issue by FrankSP7ps** [ikemen-engine/Ikemen-GO#2023]
### Describe the bug

Apparently now the stages.def that have loops included for the specific song, doesnt work propely, it just get silenced instanly affter pass the second where the loop starts.

### To Reproduce

Any stage as long has 
"bgmloopstart = "
"bgmloopend = "

with any number

### Expected behavior

After the music gets on the specific second where the loop should happen, instead, it just stops.
No music literally.

Not even restarting the round with F4 or ctrl + F4.

Until you quit the round and re-enter.

### Screenshots / Video

https://github.com/user-attachments/assets/17afe576-329e-4ee3-9fe1-24c29a67e51f

### Engine Version (or source code date)

Nightly build (the most recent one from yesterday)

### Operating system

Windows

**Comment by Jesuszilla** [comment]
How did you launch the fight? From screenpack or command line? It works from command line so if it happens from the screenpack, I'll need to check elsewhere.

Also, not sure why it's happening for you because looping works fine for me on macOS, even from screenpack.

**Comment by FrankSP7ps** [comment]
Directly from .exe
You know, saved already adjusted to the specific screenpack folder that im using.

Honestly let me see on try it on a clean build, not my first rodeo that the screenpack is doin his own bug crap.

**Comment by FrankSP7ps** [comment]
My apologies for this later answer, almost forgot about it due to other stuffs that happend the past week.

Huh, not even loading the default SP and even a clean build, haves any result.
https://files.catbox.moe/e6opt3.mp4

I include the date of the nightly build that I have, just in case.
![imagen](https://github.com/user-attachments/assets/fb6ba687-c775-4af5-b9f5-99bed2c0e1d7)
