### ISSUE TITLE
Behavior when you hit opponent multiple times in statetype = L is broken in the latest nightly

### ISSUE THREAD

**Issue by Kiwi1444** [ikemen-engine/Ikemen-GO#2026]
### Describe the bug

In the latest nightly build you can hit lying opponent infinite number of times and he won't be able to get up. There is no such error in v0.99

### To Reproduce

1. Choose character, that can hit lying opponent multiple times or just remove juggle points limitaion for crouching light kick of Kung fun man
2. Try to hit your downed opponent as many times as possible

### Expected behavior

As in Mugen 1.1

### Screenshots / Video

Normal Mugen behaviour (opponent can stand up):

https://github.com/user-attachments/assets/55cffc73-d057-4249-ab04-6914054ef311

Latest nightly: 

https://github.com/user-attachments/assets/9cadad15-237d-4537-b0f5-74c777d227ab

### Engine Version (or source code date)

Nightly 2024-09-03

### Operating system

Windows

**Comment by potsmugen** [comment]
I see. It keeps resetting to the max value. Technically it's not an infinite because you can jam buttons to stand up.

Think I'll make the recovery time be able to go down but not up. Thanks for the report.
