### ISSUE TITLE
Crash when selecting language on option screen

### ISSUE THREAD

**Issue by Finally1994** [ikemen-engine/Ikemen-GO#2028]
### Describe the bug

If you set a language other than English "en" in system.def and use the right or left button when selecting the language on the options screen, it will crash.
This is the latest nightly build.

Until the recent Go V1.20 support, it was not possible to start it on Windows 7, so it is unclear when this problem started.

### To Reproduce

In the latest nightly build, this occurs when you add
languages ​​= ja
ja = "Japanese"
to [Languages] in system.def, start the game, and then change the game settings on the options screen to something other than English.

### Expected behavior

If there are no problems, Japanese should be selected.

### Screenshots / Video

![0926A](https://github.com/user-attachments/assets/d4852eaf-5cb6-4708-999f-e70d81eaf8bc)
![0926B](https://github.com/user-attachments/assets/c31f12a6-d454-4acd-b579-e996aa09536e)
![0926](https://github.com/user-attachments/assets/45d0daa0-78f6-449f-9818-484f7735ef70)

### Engine Version (or source code date)

nightly build 240923　

### Operating system

Windows

**Comment by K4thos** [comment]
Related to #1923 changes, @Orange-Dolphin

**Comment by Orange-Dolphin** [comment]
> Related to #1923 changes, @Orange-Dolphin 

I believe I know why this is happening, an oversight caused by not having English as an option, I will fix this issue soon, and update the code to only use whatever languages are available in the screen pack. Thanks for letting me know.
