### ISSUE TITLE
"title.uppercase" in select screen

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#2037]
### Describe the bug

The uppercase parameter doesn't work for the title of the select screen, which is one of the places where it'd be the most useful (since it can have many titles).

Additionally, a quick suggestion in that it could have some parameter to override all game mode names. In case you just want it to say "Character Select" for instance.

### To Reproduce

1. Open the base system.def file
2. Add `title.uppercase = 1` under `[Select Info]`

### Expected behavior

All caps title.

### Engine Version (or source code date)

30/09/2024

### Operating system

Windows

**Comment by potsmugen** [comment]
I guess this is close enough to #1359 that I probably could've skipped it. Will close but leave the link to here. The `uppercase` parameter seems inconsistent overall. It will work perfectly fine in movelists for instance.

**Comment by K4thos** [comment]
title.uppercase is not a valid parameter for [Select Info]. Since title text values are controlled through title.text.<modeName>, an uppercase option is unnecessary.

**Comment by potsmugen** [comment]
Maybe it ought to be then. In the case of the select screen, the alternative is manually editing all game mode titles to upper case, isn't it? And some titles you can't even predict, such as modules with extra game modes.

**Comment by K4thos** [comment]
that would have to be new parameter. So a feature request rather than bug report.
