### ISSUE TITLE
"Attempt to call a non-function object" error.

### ISSUE THREAD

**Issue by FailureBiWinning** [ikemen-engine/Ikemen-GO#2041]
### Describe the bug

Upon running the executable, IKEMEN opens a blank window and sits very briefly before displaying an error message (pictured in screenshot). Clicking OK closes the program, so I'm unable to proceed any further, and I can't be certain if there are any additional issues immediately pertaining to this.

### To Reproduce

1. Just run the Ikemen_GO.exe and wait.

### Expected behavior

It should just proceed directly to the screenpack's main menu.

### Screenshots / Video

![ERROR](https://github.com/user-attachments/assets/bc7b29b9-255e-4917-b147-5c12d0dffbfa)

### Engine Version (or source code date)

Nightly build, recent as of 2024-09-30

### Operating system

Windows

### Extra context or search terms

I actually attempted to diagnose this on my own by commenting out the line in main.lua indicated in the error message (1524) and seeing what happens, and while that did allow me to proceed to the main menu, selecting anything caused another error message to appear that indicated problems in other lines (2463, 3129, 3253, 4220). I'm not particularly well-versed in Lua, so trying my hand at fixing things probably wasn't the best idea.

**Comment by potsmugen** [comment]
Is this on a clean install?

**Comment by FailureBiWinning** [comment]
No, but I did check with a separate clean install afterwards and it happens there too.

**Comment by potsmugen** [comment]
Can confirm. Seems related to the `framespercount` trigger refactor.

@K4thos tag.zss needs a small update too:
`let rootId = getPlayerId(teamSide);` -> `let rootId = player(teamSide), Id;`

**Comment by MxRemy** [comment]
This still seems to be happening to me. I'm brand new to Ikemen, so maybe I just don't know what I'm doing? I'm on Linux, and it happens on a bunch of different games (Battle Craze, One Piece Fighting Adventure, etc). Happens with both the stable and dev builds.
