### ISSUE TITLE
Miscellaneous Lua refactor/redundancy things

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#2051]
### Describe the bug

@K4thos I figured here is a better place than Discord. Found a few recently after looking at the clipboard code again:

- Debug animation info currently stopped working because animelemlength() was removed in favor of animframe("time")
- AnimOwner in Lua exists in ZSS as AnimPlayerNo (name difference is mostly because StateOwner is a redirect in ZSS)
- SpriteGroup in Lua exists in ZSS as AnimFrame(Group)
- SpriteNumber in Lua exists in ZSS as AnimFrame(Image) (image is the Elecbyte term)

### To Reproduce

Enable debug mode

### Engine Version (or source code date)

02/10/2024

### Operating system

Windows

**Comment by K4thos** [comment]
thanks, I will make those changes
