### ISSUE TITLE
Helper only Explod reference redirection is broken.

### ISSUE THREAD

**Issue by zzzz0424** [ikemen-engine/Ikemen-GO#2065]
### Describe the bug

Using redirect in Explod expression in Helper is no longer reflected
For example:
facing=ifelse(root,teamside=1,1,-1)
is reflected in MUGEN, but not in the current build.

### To Reproduce

1.Download any of the characters from the CVS series created by [warusaki3](https://mugedoso.web.fc2.com/warusaki3/index.html)
2.Select the downloaded character on the 2P side
3.Notice the GP's HUD that comes out at the start of the match.

### Expected behavior

Fixed to reflect like previous builds.

### Screenshots / Video

Ikemen nightly:
![ikemen151](https://github.com/user-attachments/assets/2a548f88-6127-4528-bcc5-48453fb1f5bc)

older Ikemen or MUGEN:
![ikemen000](https://github.com/user-attachments/assets/9fb0ead9-3dad-45cc-b87a-2d052fb56421)

### Engine Version (or source code date)

08/10/2024

### Operating system

Windows

**Comment by potsmugen** [comment]
It looks like some of our explod logic was hinged on the fact we were importing a Mugen bug, which was removed recently. Wonder if it's better to reimport the bug and limit ModifyExplod functionality, or correct the logic and risk some Mugen explods being displayed the wrong way.
