### ISSUE TITLE
Power resets upon blocking

### ISSUE THREAD

**Issue by DolphinDan400** [ikemen-engine/Ikemen-GO#2074]
### Describe the bug

As of the latest nightly version (12/10/24), blocking most attacks will reset the power meter of one or both fighters to zero.

### To Reproduce

1. Download or compile the latest nightly version.
2. Select Kung Fu Man for both players in any game mode.
3. Press F3 to fill the power meter of both players.
4. Have one player attack be blocked by their opponent, the power meter will reset to zero.

### Expected behavior

Blocking an attack shouldn't drain the power of both players to zero.

### Engine Version (or source code date)

nightly 12/10/24

### Operating system

Windows

### Extra context or search terms

This issue seems to depend on the character too, some drain only one meter while others drain both.

**Comment by potsmugen** [comment]
An oversight in my previous contribution. My bad. Thanks for reporting.
