### ISSUE TITLE
Gravity appears incorrect when using some skills

### ISSUE THREAD

**Issue by netyzh** [ikemen-engine/Ikemen-GO#2087]
### Describe the bug

Gravity appears incorrect when using some skills

### To Reproduce

Download the character from https://www.mediafire.com/file/fqmt2dztv28b4sg/Hakuowlo.rar/file
Start a match and press 236y

### Screenshots / Video

In Ikemengo:

https://github.com/user-attachments/assets/c9fd3b81-3a0f-43d7-acc2-a4178275d722

In Mugen:

https://github.com/user-attachments/assets/f1c63705-0180-4dff-aba3-2d0ff04886e3

### Engine Version (or source code date)

nightly build(20241020)

### Operating system

Windows

**Comment by potsmugen** [comment]
Looks like a localcoord conversion issue in projectiles specifically.

Edit: Yep. Will push the fix later.
