### ISSUE TITLE
"Fragment shader failed to compile" error.

### ISSUE THREAD

**Issue by FailureBiWinning** [ikemen-engine/Ikemen-GO#2101]
### Describe the bug

Attempting to run Ikemen GO immediately tosses up an error message (image attached below).

### To Reproduce

1. Just run the executable.

### Expected behavior

Ikemen should proceed to the main menu as normal.

### Screenshots / Video

![FragmentShaderError](https://github.com/user-attachments/assets/582df254-d2d6-4d4b-9fd9-baccc27c189c)

### Engine Version (or source code date)

Testing with the newest nightly build, as of 2024-11-05, though it also happened in the previous nightly.

### Operating system

Windows

### Extra context or search terms

This was tested on a fresh install (I made sure not to overwrite the nightly I had been using with either of the nightlies I had been testing). Also, not so much additional context, but a question - might this error be related to the shader issue that recently got fixed in the MacOS build?

**Comment by FailureBiWinning** [comment]
Just tried the (at the time of this writing) most recent nightly build. The error message no longer pops up, but the problem persists in another form. Now the program just closes immediately when I run it.

**Comment by Eiton** [comment]
Could you post the content of Ikemen.log?
Or run the exe in PowerShell, it should print the error message.

**Comment by FailureBiWinning** [comment]
I ran it in command line, and this is what comes up: 
![CommandLine](https://github.com/user-attachments/assets/776c7093-9276-4558-bc87-a76bd3ce2cea)

**Comment by FailureBiWinning** [comment]
Just tried the newest nightly - still immediately closes without displaying an error message. I ran it through command line and got the following, which I initially thought was the exact same output as last time, but I do notice some differences and I'm not entirely sure how significant those are: 
![CommandLine2](https://github.com/user-attachments/assets/33019d56-f677-4ece-ba89-106c9553cb22)

**Comment by Eiton** [comment]
What is your GPU? have you tried update the GPU driver?

**Comment by FailureBiWinning** [comment]
I'm running with on-board graphics - ATI Radeon HD 4200, which Ikemen had been working relatively fine with until the past couple of nightlies. The driver is as up-to-date as it's going to get, and circumstances beyond my control make upgrading my hardware highly unlikely.

**Comment by Eiton** [comment]
[Ikemen_GO.zip](https://github.com/user-attachments/files/17663354/Ikemen_GO.zip)
Could you try this build?

**Comment by FailureBiWinning** [comment]
Attempted to run the build you've provided - it still closes immediately upon opening. Running it in command line produces the following results:
![CommandLine3](https://github.com/user-attachments/assets/03ee2141-2969-4d7c-8253-23616dbfd769)

**Comment by Eiton** [comment]
[Ikemen_GO.zip](https://github.com/user-attachments/files/17679164/Ikemen_GO.zip)
Could you run this build in command line? It should give a different error message.

**Comment by FailureBiWinning** [comment]
![CommandLine4](https://github.com/user-attachments/assets/9630017f-7e25-4482-8bfa-5e53b22fefb8)

**Comment by Eiton** [comment]
Please try this build.
[Ikemen_GO.zip](https://github.com/user-attachments/files/17685939/Ikemen_GO.zip)

**Comment by FailureBiWinning** [comment]
Just tried your build - looks like it's working now.
![ConfirmedWorking](https://github.com/user-attachments/assets/36080343-7720-4b46-868f-4c4d326bad3c)

**Comment by Eiton** [comment]
I turned off dynamic shadow in this build.
Unfortunately your GPU does not support the features required for dynamic shadow in 3d stage.
The option to turn off dynamic shadow in nightly build will be available later.
