### ISSUE TITLE
Hittime is greater by 1, than indicated in hitdef

### ISSUE THREAD

**Issue by Kiwi1444** [ikemen-engine/Ikemen-GO#2113]
### Describe the bug

When you hit someone, hittime will be greater by 1, than indicated in hitdef. Problem is present since v0.99 (I didn't checked candidate releases).

### To Reproduce

1. Add this code to KFM negative state:
`[State -2, DTC]`
`type = DisplayToClipboard`
`trigger1 = 1`
`ignorehitpause=1`
`text = "hittime = %d"`
`params = GetHitVar(hittime)`
2. Start KFM vs KFM match
3. Hit KFM with Stand light punch
4. DTC should show 10 on first tick of impact (as hittime of KFM LP is 10), but will show 11

### Expected behavior

As in Mugen

### Engine Version (or source code date)

Nightly 2024-10-24

### Operating system

Windows

### Extra context or search terms

Hittime, hitdef

**Comment by potsmugen** [comment]
The output is +1 but the frame advantage is the same. This is a deliberate change to fix an old critical Mugen issue. See https://github.com/ikemen-engine/Ikemen-GO/wiki/Miscellaneous-info#guarding-and-frame-advantage

**Comment by Kiwi1444** [comment]
> The output is +1 but the frame advantage is the same. This is a deliberate change to fix an old critical Mugen issue. See https://github.com/ikemen-engine/Ikemen-GO/wiki/Miscellaneous-info#guarding-and-frame-advantage

Oh, I completely forgot about this change. I'll have to change my character trigger, so that it works on both Mugen and Ikemen Go
