### ISSUE TITLE
character support

### ISSUE THREAD

**Issue by doottah** [ikemen-engine/Ikemen-GO#2140]
### Describe the bug

When switching to ikemen (all versions, Nightly included) I noticed that it doesn't read some things concisely, I thought it was my character that had something in the code, but I realized that with other characters (in this case Ahuron's Ultimate and Megaman) the same thing happened. , ikemen does not read or skip something in the code, causing it to not work well

### To Reproduce

Download the character, test it on mugen and shoot. now try it on ikemen and shoot (you will notice the difference)
[Zero.zip](https://github.com/user-attachments/files/17879987/Zero.zip)

### Expected behavior

that the shot works well in all its ikemen versions

### Screenshots / Video

https://github.com/user-attachments/assets/80e58bf1-ae33-422f-8264-5b2880caf24f

### Engine Version (or source code date)

0.99

### Operating system

Windows

### Extra context or search terms

What I mean about the problem is that Zero shoots, and it has 3 levels, normal shot, charged shot and the maximum shot, depending on how the code is, 1 or the other works.

**Comment by potsmugen** [comment]
Have you tried on the [Nightly build](https://github.com/ikemen-engine/Ikemen-GO/releases/tag/nightly)?

**Comment by doottah** [comment]
> Have you tried on the [Nightly build](https://github.com/ikemen-engine/Ikemen-GO/releases/tag/nightly)?

yes, since version 98, 99 nightly and the recent one, they all give me the same problem :(

**Comment by K4thos** [comment]
@doottah, why did you close the issue? Was it a false alarm, or did Mugen behave the same way? If there is a difference, the ticket should remain open.

**Comment by doottah** [comment]
> @doottah, why did you close the issue? Was it a false alarm, or did Mugen behave the same way? If there is a difference, the ticket should remain open.

With a friend from Japan we reviewed the versions of why this happened, since he used the same method as mine, we realized that changing the value of a variable works well, but it is strange since in Mugen this did not happen, of course In the same way we were able to solve the problem with compatibility, that's why I closed the topic, my apologies if I didn't post it sooner.
