### ISSUE TITLE
Input error when I plug in external keyboard

### ISSUE THREAD

**Issue by Mustardnote3943** [ikemen-engine/Ikemen-GO#2141]
### Describe the bug

This bug prevents me from launching ikemen go when my external keyboard is plugged into my laptop. I did try plugging it in while ikemen go was running, but it doesn't input correctly.

here are the ikemen.log which contains the error:

runtime error: index out of range [1] with length 1
goroutine 1 [running, locked to thread]:
github.com/yuin/gopher-lua.(*LState).PCall.func1()
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/state.go:1988 +0x212
panic({0x984480, 0xc0046a5e00})
	/opt/hostedtoolcache/go/1.20.14/x64/src/runtime/panic.go:884 +0x213
main.JoystickState(0x1, 0xa)
	/home/runner/work/Ikemen-GO/Ikemen-GO/src/input.go:224 +0x5ea
main.KeyConfig.U(...)
	/home/runner/work/Ikemen-GO/Ikemen-GO/src/input.go:322
main.(*InputReader).LocalInput(0x0?, 0x1)
	/home/runner/work/Ikemen-GO/Ikemen-GO/src/input.go:466 +0x708
main.(*CommandList).Input(0xc000881bc0, 0x1, 0x1, 0x0?, 0x0)
	/home/runner/work/Ikemen-GO/Ikemen-GO/src/input.go:2113 +0x43c
main.systemScriptInit.func37(0xc00014c430?)
	/home/runner/work/Ikemen-GO/Ikemen-GO/src/script.go:780 +0xd1
github.com/yuin/gopher-lua.callGFunction(0xc00013e000, 0x0)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/vm.go:202 +0x37
github.com/yuin/gopher-lua.init.3.func26(0xc00013e000, 0xc080000?, 0xc000140000?)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/vm.go:821 +0x379
github.com/yuin/gopher-lua.mainLoop(0xc00013e000, 0xc000786a00?)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/vm.go:31 +0xfa
github.com/yuin/gopher-lua.(*LState).callR(0xc00013e000, 0x0, 0xffffffffffffffff, 0xc000170118?)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/state.go:1211 +0x1b4
github.com/yuin/gopher-lua.(*LState).Call(...)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/state.go:1967
github.com/yuin/gopher-lua.(*LState).PCall(0xc00013e000, 0x0, 0xc000786a00?, 0x0)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/state.go:2030 +0x145
github.com/yuin/gopher-lua.(*LState).DoFile(0xc00013e000, {0xc0001c4888?, 0x0?})
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/auxlib.go:396 +0x6b
main.main()
	/home/runner/work/Ikemen-GO/Ikemen-GO/src/main.go:106 +0x278

stack traceback:
	[G]: in function 'commandInput'
	external/script/main.lua:115: in function 'f_cmdInput'
	external/script/main.lua:131: in function 'f_cmdBufReset'
	external/script/main.lua:3873: in function 'f_frameChange'
	external/script/main.lua:4094: in function 'f_menuCommonDraw'
	external/script/main.lua:3164: in function 'loop'
	external/script/main.lua:4220: in main chunk
	[G]: ?

### To Reproduce

1. plug in a USB keyboard (my keyboard Razer Huntsman mini)
2. Launch Ikemen go
3. error preventing you from launching Ikemen go

### Expected behavior

it should work as intended without any input error

### Engine Version (or source code date)

DEV/NIGHTLY

### Operating system

Linux

**Comment by Mustardnote3943** [comment]
the error is gone but the other problem isn't fixed and it's when I try navigating the menus. when I move down, It does both movement and action. I'm basically hitting S for down but it also pressing F which I configured as A action.

**Comment by K4thos** [comment]
New problem, new topic. As for default bindings having conflicts, that's to be expected—you'll need to change them manually if necessary. If this is not what you're reporting, then consider creating a new ticket.

edit: unless it's the same problem as reported here: #2146
