### ISSUE TITLE
ReversalDef doesn't work again

### ISSUE THREAD

**Issue by UltraCombo3000** [ikemen-engine/Ikemen-GO#2147]
### Describe the bug

I made a bug report before where ReversalDefs failed to work in a specific scenario when a character had blue CLSN during the move, but no invincibility coded in, and it was eventually fixed. Now, in the latest nightly version, this issue appears to have returned.

### To Reproduce

1. Use any character with a counter or counter-like move that uses ReversalDef and also has blue CLSN (Ex: Ichida's/Vinnie's Yosuke and Hakumen, OHMSBY's Kuroko, Akatsuki, and Blitztank)
2. Attempt to counter any of the opponent's non-projectile attacks. This is important because these kinds of moves do work against these characters (For most of them, they have HitOverride for projectiles and this works. For Hakumen, projectiles are supposed to phase through him).
3. Depending on the existence of blue CLSN or NotHitBy during the counter, the character using the counter will either get hit, or the opponent's attack will whiff entirely (from what I've tested, the whiffing part only seems to happen with Hakumen, as he is the only one with a NotHitBy during his counter).

### Expected behavior

It should work exactly as it does in Mugen 1.1 as well as after the update where I mentioned this the first time.

### Engine Version (or source code date)

nightly

### Operating system

Windows

### Extra context or search terms

Note: I originally thought ReversalDefs were broken entirely, but after some further testing that's not the case.

**Comment by potsmugen** [comment]
Is it really the latest nightly? As in the one that's up now? I only have Yosuke in my test cases but his counter works.

**Comment by UltraCombo3000** [comment]
I redownloaded the latest nightly and it does work now. I'm not really sure how this happened. I swear I had the latest version before, but maybe I didn't.
