### ISSUE TITLE
3D backgrounds do not display properly on MACOS

### ISSUE THREAD

**Issue by weiwangko** [ikemen-engine/Ikemen-GO#2152]
### Describe the bug

![QQ20241129-135847](https://github.com/user-attachments/assets/efd39a62-3546-4860-9961-71cb12a57b4e)

The background will be black screen, whether it is the macOS version or the Win11 simulated by parallels desktop, it is black screen, before the 3D switch is still normal, and now it is black and no longer displayed, this is not a negative optimization......

### To Reproduce

3D stage blank screen

### Engine Version (or source code date)

nightly

### Operating system

macOS

**Comment by K4thos** [comment]
from Eiton:
> This is because the current macos build is using GL2.1, which is a regression.
> It will be fixed when the renderer switch is merged.
