### ISSUE TITLE
Game crashing after about 7-8 characters (depending on each characters Size) have been loaded

### ISSUE THREAD

**Issue by Sillydeviant** [ikemen-engine/Ikemen-GO#2156]
### Describe the bug

My game crashes when about 7 characters have been loaded

Usually I just play the game normally, after 7 or more or less characters have been loaded and im about to start another match with a new set of characters, i get an AMD Driver TImeout Error and the game crashes. (English isnt my first Language so i dont know if i said this right)

this has happened on 0.99 and nightly 

### To Reproduce

How it usually goes
1. (i usually play 3v3 tag mode)
first match is fine
2.  new sets of characters and a different stageabout to play second match
3. (game crashes when loading)+ amd driver timeout

### Expected behavior

I get to play more 3v3 tag matches

### Screenshots / Video

![1 -AMD-Driver-Timeout](https://github.com/user-attachments/assets/8f5ca5d0-d913-4acf-8b8f-95f42d3d8cc1)

### Engine Version (or source code date)

v0.99

### Operating system

Windows

### Extra context or search terms

i thought it was something to do with amds problematic drivers but i downgraded and the issue still happens

**Comment by Sillydeviant** [comment]
i figured it out, my ikemen is having a memory leak. i dont know how to fix now

**Comment by K4thos** [comment]
I assume it's the same problem as #265. No solution has been found yet. I'm closing this one as a duplicate.
