### ISSUE TITLE
Ikemen_GO_GL32.exe won't launch

### ISSUE THREAD

**Issue by Kiwi1444** [ikemen-engine/Ikemen-GO#2160]
### Describe the bug

When I trying to launch Ikemen_GO_GL32.exe, Ikemen Go window appears briefly and then disappears. Nothing happens. No crashlogs (Nor in WIndows, nor in Ikemen Go). Tested it on 2 machines:

Windows 7, AMD FX-8350, 8 GB RAM, Geforce 1650.
Windows 10 21H2, AMD Ryzen 3 3250U, 8GB DDR4, AMD Graphics

### To Reproduce

1. Download the latest nightly and try to launch Ikemen_GO_GL32.exe

### Engine Version (or source code date)

Nightly 2024-11-28

### Operating system

Windows

**Comment by Orochikyocr** [comment]
I can confirm new Ikemen Go nightly build (12/24) is working well with openGL 3.2 selected in the config options. 2.1 still throws the Shadow Map Shader warning but I think that is expected.

**Comment by Kiwi1444** [comment]
OpenGL 3.2 now works.
