### ISSUE TITLE
open save/config.json: Access is denied

### ISSUE THREAD

**Issue by PlucktheDragon** [ikemen-engine/Ikemen-GO#2165]
### Describe the bug

My Norton 360 anti-virus has blocked my access to play Ikemen GO in nightly build.

### To Reproduce

1. I installed the EVEBattle screenpack to Ikemen GO nightly build.
2. In data/EVEBattle/select.def, I added the Street Fighter II characters and stages, then saved.
3. I open Ikemen_GO.exe

### Expected behavior

My Norton 360 anti-virus blocked my access to Ikemen_GO.exe as a threat.

### Screenshots / Video

I.K.E.M.E.N Error :.
![Capture d’écran 2024-12-04 212608](https://github.com/user-attachments/assets/5ac1f31f-fec7-4e7f-ba64-dfac8eafdd92)

Norton 360 :.
![Capture d’écran 2024-12-04 211832](https://github.com/user-attachments/assets/6ab86aa8-a20a-4933-8c75-7ed425e18b08)

### Engine Version (or source code date)

Nightly

### Operating system

Windows

**Comment by K4thos** [comment]
not an engine problem
