### ISSUE TITLE
Ikemen is only showing up in bottom left corner

### ISSUE THREAD

**Issue by coaster19** [ikemen-engine/Ikemen-GO#2171]
### Describe the bug

I'm playing on the MacOS version and every time I try to play the game, the game is shown in a smaller aspect ratio while the rest of the screen is just black. I've tried a ton of different resolutions, and everything either keeps it in the corner or zooms in the game way too far. Any ideas on how to fix this?

### To Reproduce

The game was fine at first, but I'm not sure what I did to create the error.

### Screenshots / Video

![Screenshot 2024-12-07 at 8 39 06 PM](https://github.com/user-attachments/assets/b9d90733-0077-48d6-827e-05df95587ec2)

### Engine Version (or source code date)

v0.99.0

### Operating system

macOS

**Comment by K4thos** [comment]
#649
