### ISSUE TITLE
Gravity behaves abnormal

### ISSUE THREAD

**Issue by netyzh** [ikemen-engine/Ikemen-GO#2175]
### Describe the bug

The character Karulau exhibits abnormal gravity behavior when hitting or being hit by an opponent.

### To Reproduce

Two character‘s link:
https://www.mediafire.com/file/bzvsekuxd6ktd2s/Karulau.rar/file
https://www.mediafire.com/file/jc4zjjz1ty8ame8/586_minagi.rar/file
Minagi Tohno use 426c when the IC bar on the top is red or light blue and hits Karulau.(But she behaves normal when hit kfm)
Karulau use B+C and hit Minagi Tohno to the backedge.
They fly too high than it behaves in mugen

### Screenshots / Video

https://github.com/user-attachments/assets/512b072b-c9b1-48da-bdce-0813e9f2e773

### Engine Version (or source code date)

nightly build

### Operating system

Windows

**Comment by potsmugen** [comment]
This is very similar to a recent bug. Are you on the nightly build released today?

**Comment by netyzh** [comment]
> This is very similar to a recent bug. Are you on the nightly build released today?

This bug has been present in the previous version, but it has not been fixed in today's updated version.
I usually wait for a version to see if the bug will be fixed or not,then start a new issue.

**Comment by potsmugen** [comment]
This is actually a blatant regression because you can reproduce it even with just KFM and KFM720. Luckily it was a simple oversight and I already figured it out.
