### ISSUE TITLE
Saber's last arc makes the opponent's helper(?) appears

### ISSUE THREAD

**Issue by netyzh** [ikemen-engine/Ikemen-GO#2176]
### Describe the bug

Saber's last arc makes the opponent's helper(?) appears and causes only 4 damage.

### To Reproduce

Download character from:https://www.mediafire.com/file/pptlabs8ppawoni/Saber.rar/file
I changed the conditions then just press "z" can trigger the last arc in trainning mode. 

### Screenshots / Video

https://github.com/user-attachments/assets/111b7f21-b48d-4f6f-8b5a-ee83fe2fa953

### Engine Version (or source code date)

nightly build

### Operating system

Windows

**Comment by potsmugen** [comment]
Also fixed by #2177.

The way this move uses `GetHitvar(Fall.Envshake.Ampl)` feels like it could break at any moment though. @beterhans why not use one of the parameters that ignore localcoord, like time, frequency of phase? Time is even an int already.

**Comment by beterhans** [comment]
@potsmugen thanks for the suggestion.
