### ISSUE TITLE
Tien Kikoho restands in Ikemen 

### ISSUE THREAD

**Issue by Junny4444** [ikemen-engine/Ikemen-GO#2188]
### Describe the bug

Using tiens super move Kikoho restands the opponent in ikemen go, this will not allow the super to combo into its other hits. In mugen the super keeps the opponent grounded and allows for followup hits

### To Reproduce

1. download tien
2. use kikoho

### Expected behavior

In ikemen:

https://github.com/user-attachments/assets/95308238-deaa-464e-bf12-52c3758c45d2

In mugen:

https://github.com/user-attachments/assets/428c593a-5f5b-4b87-a7d7-df625fb61507

Link to tien:
download this and get the tenshinhan z2 chara folder out of it https://www.justnopoint.com/hdbz/HyperDBZ5_9BETA.zip

### Engine Version (or source code date)

Latest Nightly

### Operating system

Windows

**Comment by potsmugen** [comment]
When a character is hit off the ground they get a position offset in both Mugen and Ikemen. A micro difference in the timing when this offset is applied is breaking this code:

```
[State juggle targetstate]
type = targetstate
triggerall = cond(numtarget,!(target,ishelper),0)
trigger1 = movehit && target,pos y < 10
value = 2014
ID = 2113
ignorehitpause = 1
persistent = 0

[State 2103, TargetState]
type = TargetState
trigger1 = MoveHit
trigger1 = NumTarget;()
trigger1 = !(target, isHelper)
trigger1 = Target, pos y >= 10 
value = 2012	;custom state, go to supers.cns
ID = 2113
ignorehitpause = 1
persistent = 0
```

(Doing it in a single block of code would've avoided the issue but that's besides the point)
