### ISSUE TITLE
Stage not displaying correctly on Nightly.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#2189]
### Describe the bug

Some of the stage's elements are missing or being displayed pink.

### To Reproduce

Download the stage and install it on a Nightly build. [stages.zip](https://github.com/user-attachments/files/18148800/stages.zip)

### Screenshots / Video

![THE KING OF FIGHTERS Ultimate Match 2024-12-16 07-46-01](https://github.com/user-attachments/assets/e083f505-2ae0-4512-bfef-99109a477a6f)
Nightly

![Ikemen_GO 2024-12-16 07-49-52](https://github.com/user-attachments/assets/b87ffef5-f310-4348-9f0f-6644f2f14301)
v0.99.0

### Engine Version (or source code date)

Nightly

### Operating system

Windows

**Comment by Wftk** [comment]
not an engine issue but stage. Because this pink bg appears in mugen 1.1 too:
![mugen415](https://github.com/user-attachments/assets/0d29ddf1-6b4a-46b7-9f11-2463a24054dc)

actually 0.99. is buggy one cuz mask param dont work there same as in 1.1, in nightly it got fixed.
