### ISSUE TITLE
Stage shows different color boundaries when envshake is used compared to mugen

### ISSUE THREAD

**Issue by Junny4444** [ikemen-engine/Ikemen-GO#2190]
### Describe the bug

When envshake happens, the stage will show its bounds at a diferent color compared to mugen 1.0

### To Reproduce

1. download this stage
[baba palace.zip](https://github.com/user-attachments/files/18158792/baba.palace.zip)
2. use a move with envshake on it

### Expected behavior

1. Will not show pink stage bound color when envshake happens

### Screenshots / Video

comparison:
[2024-12-16 19-08-20.zip](https://github.com/user-attachments/files/18158798/2024-12-16.19-08-20.zip)

### Engine Version (or source code date)

nightly

### Operating system

Windows

**Comment by UrsoManso** [comment]
Change debugbg = from 1 to 0.

**Comment by K4thos** [comment]
already reported: #1300
