### ISSUE TITLE
Nightly build around 2024-Dec-22 unable to run Akiha by Eiton, have problem on rand?

### ISSUE THREAD

**Issue by beterhans** [ikemen-engine/Ikemen-GO#2200]
### Describe the bug

always give this error after load Akiha

![11](https://github.com/user-attachments/assets/04ff1218-e246-487a-8cf7-ac278aeec05e)

invalid data: rand

Im not good at zss, I tried to delete one rand() line, but the next rand will report the same error.

### To Reproduce

download nightly build around 2024-Dec-22
download akiha from Eiton's post
https://mugenguild.com/forum/msg.2543563

you will see the error

### Expected behavior

character run as intended.

### Screenshots / Video

![11](https://github.com/user-attachments/assets/04ff1218-e246-487a-8cf7-ac278aeec05e)

### Engine Version (or source code date)

2024-Dec-22

### Operating system

Windows

**Comment by beterhans** [comment]
OK I think I found out

rand is removed and should use RandomRange
MajorVersion is removed and should use MugenVersion 
DrawPalNo is removed, but no idea what does it do, I Just use PalNo instead now she is working

I uploaded an working edit in the release post
https://mugenguild.com/forum/msg.2543563

**Comment by potsmugen** [comment]
DrawPalNo had an extremely situational use with very little benefits, so it was just more or less integrated into PalNo.

**Comment by beterhans** [comment]
Close, since it's character used old trigger.
