### ISSUE TITLE
The CPU keeps doing the same action after the end of the round.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#2202]
### Describe the bug

A CPU-controlled character not yet equipped with AI may continue to perform the same action after the end of a round until the opponent is defeated.

### To Reproduce

1. Download a character that does not have AI.
2. Play that character in WATCH mode.
3. After the round ends, the winning character may continue to repeat the same action until the opponent is defeated.

### Engine Version (or source code date)

12/02/2024 - nightly

### Operating system

Windows

### Extra context or search terms

This bug can occur even if you keep asserting NoInput in AssertSpecial.

**Comment by potsmugen** [comment]
Sounds like a character issue. Can you post more specific reproduction steps?

**Comment by Kuroteba** [comment]
I cannot explain any further. This bug occurs no matter which character I use.

**Comment by Kiwi1444** [comment]
https://github.com/user-attachments/assets/063974df-cf69-455a-9435-c5c6909a44e4

Something like this? Here I catched a moment when KFM walking forward and disabled his AI. Seems like not only character related problem but problem of Mugen overall. But I couldn't reproduce it in Ikemen Go

**Comment by Kuroteba** [comment]
No, it means that when a match ends in WATCH mode, the same action (technique, etc.) continues to be repeated.

**Comment by potsmugen** [comment]
OK it's easy enough to reproduce with 4v4 KFM in Simul. Maybe the command that the AI cheated just stays on when the round ends.

Edit: Yeah. Will push the fix later.
