### ISSUE TITLE
On some characters AI can't be deactivated even if they support manual mode

### ISSUE THREAD

**Issue by Kiwi1444** [ikemen-engine/Ikemen-GO#2204]
### Describe the bug

Problem related to both Mugen 1.1 and Ikemen Go. On some characters AI can't be deactivated even if they support manual mode. Nor through menu, nor through hotkey (ctrl+1/ctrl+2/ctrl+3/ctrl+4). For example: [Guts by OGGY](https://mugenarchive.com/forums/downloads.php?do=file&id=6900-guts-oggy), [Shermie by QY China](https://mugenarchive.com/forums/downloads.php?do=file&id=65548-mmd-shermie-qychina). 
Interesting case with [Eternal Champion by supermystery](https://mugenarchive.com/forums/downloads.php?do=file&id=18403-eternal-champion-supermystery). If you try to deactivate his AI, when he's moving forward, he'll keep moving despite the deactivated AI.

### To Reproduce

1. Download and install one of the characters mentioned above
2. Try to enable his/her AI, then disable it

### Engine Version (or source code date)

Nightly

### Operating system

Windows

**Comment by potsmugen** [comment]
> Problem related to both Mugen 1.1 and Ikemen Go

Just from that one would usually say it's not a problem. These characters probably use old AI activation codes, which normally do not turn off once AI input is detected.

**Comment by Kiwi1444** [comment]
Will there be added in the future a function to force stop such characters?

**Comment by potsmugen** [comment]
I don't think so because the characters are specifically coded to be that way. You can probably fix them with something like this:

```
[State -2, AI off]
type = varset
trigger1 = var(59) != 0
trigger1 = AIlevel = 0
var(59) = 0
```
Assuming var(59) is the AI flag, which is very common.

**Comment by Kiwi1444** [comment]
Okay, then I'll close the issue.
