### ISSUE TITLE
Zoom Issue

### ISSUE THREAD

**Issue by KING-OB88** [ikemen-engine/Ikemen-GO#221]
Characters with Zoom controller state under their specials creates a Black field, when using the attack
Here's a char with zoom Bug: (https://mugenarchive.com/forums/downloads.php?do=file&id=110145-vegeta-scouter-jus-update-magovango-allofmugen)

**Comment by Orochikyocr** [comment]
I can confirm this. Zoom at the start of the state sets a black background hiding everything else including characters.

**Comment by K4thos** [comment]
can't reproduce while frame skipping, so I assume it's already fixed

https://user-images.githubusercontent.com/8928195/175830236-38dc07a5-d499-42ce-95bb-104163d6ba34.mp4
