### ISSUE TITLE
Inputs sometimes breaking on character select screen in certain VS modes

### ISSUE THREAD

**Issue by UltraCombo3000** [ikemen-engine/Ikemen-GO#2214]
### Describe the bug

Basically what it says in the title. This happens on the latest nightly and I have confirmed this bug exists by redownloading a fresh copy multiple times. What's interesting is that this seems to happen at random, and won't always occur on every boot up. I have genuinely no idea why this happens.

Something else that seems to be a sort of side effect of this bug is that if it occurs, the training mode dummy will sometimes not be able to be controlled manually.

### To Reproduce

1. Boot up Ikemen_GO.exe

2. Using the controls for Player 1 on keyboard (cannot confirm if gamepad/joystick controls are broken as I do not have either of those), go straight into any VS mode that involves two human players (either 1P VS 2P or Team Versus) without going anywhere else on the main menu.

3. From what I've seen, if done correctly, one of the following things will happen on the character select screen:
- Player 1's controls will work fine, but they will be controlling Player 2's side, while Player 2 cannot do anything.
- Player 1's attack buttons (A, B, C, X, Y, Z) will work as intended, but their directional keys will not. Player 2 still cannot do anything.
- Nothing except the ESC key will work.

### Expected behavior

None of this to happen at all

### Engine Version (or source code date)

nightly

### Operating system

Windows

**Comment by potsmugen** [comment]
I've experienced something similar where P2 keyboard will only start working after you go into input config and exit. Seemingly anyway.

Update: Running from command line I've also experienced P1's keys controlling P2 as well as neither of them working.
