### ISSUE TITLE
Problem with Tag

### ISSUE THREAD

**Issue by evildarklxs** [ikemen-engine/Ikemen-GO#225]
many characters are left walking or running when changing

Version: Ikemen v0,96 last of 2020

https://user-images.githubusercontent.com/78336781/106417611-42195c00-6433-11eb-9eaa-f60534736f57.mp4

**Comment by Orochikyocr** [comment]
Says the video is not supported. Can you upload the video the streamable, it is easy to use and it wont ask you to register.

**Comment by K4thos** [comment]
@evildarklxs, please reupload the video, post links to problematic characters or post more details. There is nothing we can do with such vague explanation.

**Comment by K4thos** [comment]
feel free to reopen the ticket after providing a way to reproduce it.
