### ISSUE TITLE
Super jump and corner pushback issues.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#228]
https://user-images.githubusercontent.com/77592586/106555535-858bcd00-64fc-11eb-9ff2-b85e1d11ef28.mp4

Video above tells it all about the pushback issue.

https://user-images.githubusercontent.com/77592586/106555596-a48a5f00-64fc-11eb-935b-a3672204f548.mp4
Ikemen GO

https://user-images.githubusercontent.com/77592586/106555618-af44f400-64fc-11eb-9480-d47e99c4b753.mp4
Mugen 1.1

On Ikemen the super jump command of tapping down and jumping isn't working properly, the super jump only functions correctly by running and then jumping.

The character in question is: https://www.sendspace.com/file/jkcshu

**Comment by K4thos** [comment]
I can't reproduce this problem on 0.98.2 RC4
char: [Uploading Kyo.zip…]()

https://user-images.githubusercontent.com/8928195/148869422-658bcbe3-4496-4614-901c-bfd711a263d7.mp4

**Comment by UrsoManso** [comment]
Just tried it on the RC3 build and indeed both issues a gone, but I've noticed another issues. If you press back+down or back+forward fast the character will perform backdashes sometimes, which doesn't happens on 98.1. Also I'm not being able to perform backrolls, only regular rolls. The command for backroll is lp+lk while pressing back.

**Comment by K4thos** [comment]
can't reproduce on RC4 (unrelased but I don't remember changes that could be rleated)

https://user-images.githubusercontent.com/8928195/148872276-cc9a4613-63af-4c79-8ec4-af3312efe9e4.mp4

)

**Comment by UrsoManso** [comment]
Did some more testing and this issue apparently only happens on training mode, and p1 only.

**Comment by K4thos** [comment]
just tried on RC3 - can't reproduce, regardless of mode

**Comment by UrsoManso** [comment]
Guess i'll just wait for RC4. About the backdash issue, did you checked it?

**Comment by K4thos** [comment]
as I said I can't repricue it on RC3 so RC4 won't change anything here

**Comment by UrsoManso** [comment]
Well that's just weird, because the backdash issue is specific of RC3 on my end, 98.1 works just fine.

**Comment by UrsoManso** [comment]
Okay so... the backroll issue is indeed for some reason related to my keyboard, but the backdash issue persisted, and I've realized that inverting the commands makes the character run instead, example: if tap back+forward kickly he will perform a backdash, if I tap forward+back he will run. Really weird. So that means if I tap back or forward and another directional fast, for some reason it will read as a double tap I guess.

**Comment by K4thos** [comment]
I was able to reproduce backdash behavior, not the way you've mentioned (2 buttons pressed at the same time) but by quickly pressing first pressing back than forward. Than Kyo tends to hop backward, regardless of how many frames lasted since the last presses like this, so I assume previous back input was not dropped.

I assume it's due to this commit since I can't reproduce it anymore after reverting it: https://github.com/K4thos/Ikemen_GO/commit/f7a420e36b8675a8e7a06e15c6b3d84be2f827b5
I will ask Gacel if it's intended.

**Comment by UrsoManso** [comment]
> I was able to reproduce backdash behavior, not the way you've mentioned (2 buttons pressed at the same time) but by quickly pressing first pressing back than forward, one after another. 

That's what I meant, maybe I expressed myself wrongly.

Btw this executable fixes this issue but restores the orignal super jump issue so we're back to square one.

**Comment by Blac-Dragoon** [comment]
I've been having this same problem recently. When trying an SNK style input (ex F,DF,D,DB,B,F+2P), my character would perform a dash forward or back instead. Same with charge moves (namely Charge B,F+P) won't work unless I use DB only. It's kinda annoying when attempting these moves after one of the recent updates.

**Comment by potsmugen** [comment]
I can't reproduce the cornerpush bug either in 0.99. The input issues sound like the fairly known ones.
