### ISSUE TITLE
Stage not working

### ISSUE THREAD

**Issue by LasombraDemon** [ikemen-engine/Ikemen-GO#239]
Tried this in 1.0 and works fine. In the latest Ikemen iteration, it just gives me a black screen *on top* of the sprites and the characters.

Weird.

[alexkidd.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/6095561/alexkidd.zip)

**Comment by Lazin3ss** [comment]
One problem I'm seeing with this stage is that, since mugenversion isn't specifed, fight never starts. Also, stage is misplaced on the y-axis compared to mugen 1.1, that should be checked too.
