### ISSUE TITLE
Bug with turning at round end.

### ISSUE THREAD

**Issue by Windblade-GR01** [ikemen-engine/Ikemen-GO#277]
https://user-images.githubusercontent.com/11762096/122310997-de219c80-ced6-11eb-8051-fcdc9b4d928f.mp4

**Comment by K4thos** [comment]
how to reproduce:
[ananzi.zip](https://github.com/ikemen-engine/Ikemen-GO/files/8986201/ananzi.zip)
Arachnid requiem (QCF+2K). Problem at Win state 186.
