### ISSUE TITLE
It doesn't get good at 16:10

### ISSUE THREAD

**Issue by Gaelcraft** [ikemen-engine/Ikemen-GO#278]
Hello, these are trying to set ikemen go to 16:10 but the resolution stretches a little badly and in other versions it was fine

**Comment by Windblade-GR01** [comment]
Hello.
I need more info about this.

Does this happens only on exclusive fullscreen?
What OS are you using?
Can you send screenshot of it if posible to see what exactly happens?

**Comment by Gaelcraft** [comment]
Sorry for answering late, what happens is that my 16:10 1440x900 monitor does not look good with Ikemen Go and I do not know if any custom resolution will work and the gpu is integrated graphics and I think it is only in full screen
