### ISSUE TITLE
no zoom and stage not working in 1280x270 fullscreen, i'm using windows7 32bit, ikemen v0.97

### ISSUE THREAD

**Issue by syafiqwhy91** [ikemen-engine/Ikemen-GO#283]
![Video_2021-06-19_085813 wmv_snapshot_00 04 604](https://user-images.githubusercontent.com/86135295/122626593-00393b80-d0de-11eb-9633-a64d9bde9c39.png)

**Comment by K4thos** [comment]
please provide link to problematic content. Always.
