### ISSUE TITLE
Issues editing the character select?

### ISSUE THREAD

**Issue by JomSpoons** [ikemen-engine/Ikemen-GO#284]
I'm quite fond of the default screenpack Ikemen GO comes with, so I'd like to keep using it if possible. However, I'm experiencing some issues when trying to edit the character select screen. The main issue I have is that the size of the cells don't seem to resize properly. When I try to change the size of them, they don't seem to actually change in scale, with the only real difference being the spacing between the cells because the game thinks they're smaller but actually aren't.
![image](https://user-images.githubusercontent.com/42208891/122800990-3535c180-d289-11eb-9458-4fdf974af820.png)

Another issue I'm facing is trying to scale the dark box that's behind the cells by default. You'll notice how the previous screenshot is missing it entirely, and that's because I decided to disable it unless I can scale it properly. I was able to scale the box horizontally using the _window_ parameter on line 540 of the system.def file, but I couldn't figure out how to make it bigger vertically.
![Ikemen_GO_5Z3bnfOHeR](https://user-images.githubusercontent.com/42208891/122801968-6b277580-d28a-11eb-9cf0-6c01b981dd17.png)
Here is the system.def this particular screenshot has:
[system.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/6688402/system.zip)

Any help is greatly appreciated. Thanks.

**Comment by K4thos** [comment]
1. To change how cell looks you need to edit not only cell.size and cell.spacing but each element that renders on cell (cell.bg, cell.random, p1.cursor.active, p1.cursor.done, p2.cursor.active, p2.cursor.done). Each of them accepts optional .scale suffix, if you need to scale those sprites. I suggest downloading some screenpacks for a reference. This tutorial may be also useful: reddragoncats17.weebly.com/getting-started-on-mugen.html

2. It's a sprite group 100, index 1 at system.def. Window parameter is not for scaling but for cropping image. Docs: http://www.elecbyte.com/mugendocs/bg-tut.html
