### ISSUE TITLE
Issue with the char Alessi by Nimame.

### ISSUE THREAD

**Issue by Windblade-GR01** [ikemen-engine/Ikemen-GO#289]
The user Reda reported that in the char Alessi created by Nimame in a attack that can transform the enemy into a child, but in Ikemen it does not work correctly, it does not display sprite and the opponent becomes invisible until is hit again and put out of the custom state.

**Comment by EgyLynx** [comment]
So which version Ikemen go is q?

**Comment by K4thos** [comment]
already fixed
