### ISSUE TITLE
Font/Text artifacts

### ISSUE THREAD

**Issue by CitrusHappy** [ikemen-engine/Ikemen-GO#291]
![image](https://user-images.githubusercontent.com/36286623/124578857-725e8f80-de03-11eb-97f5-7e13fe68d16b.png)

Tested with multiple fonts. Let me know if you need a copy of the motif or any other files.

**Comment by CitrusHappy** [comment]
[motif with this issue](https://www.mediafire.com/file/g367579pqn5qm13/motif.zip/file)

**Comment by K4thos** [comment]
it's a know compatibility problem with ttf fonts that happens on some pc configurations. I suspect it's a bug in glfont library that we're using for ttf rendering. Considering we have no way to reproduce it locally I wouldn't count on a fix any time soon.

**Comment by K4thos** [comment]
another example, again lines starting from upper left corner, regardless of what ttf font is used:
![ikemen000](https://user-images.githubusercontent.com/8928195/124678566-152a1300-dec3-11eb-8a75-1fa3b44c2e76.png)
Reported by someone with AMD gpu.
I will link to this ticket on glfont repository, maybe author will have some idea how to solve it or what is causing it.

**Comment by K4thos** [comment]
CitrusHappy, please test if the problem still happens in this build (if yes I will upload more builds)
https://www.dropbox.com/s/yodq5iqtzj6yhzm/Ikemen_GO_test1.zip?dl=1
