### ISSUE TITLE
Many problems with the stages

### ISSUE THREAD

**Issue by evildarklxs** [ikemen-engine/Ikemen-GO#298]
- Many stages are lower than normal (problems with the upper edges)
- It has a movement effect (if it is observed in the video, in the intro of the stadium it has a movement effect, but in ikemen it is activated)
- Separated sprites (a separation line is appreciated when moving - Pokemon Stadium)
- Stage with problem when moving (the stage goes crazy - CvS 2 London - Evening)

I've to add +2500 and many many have those problems 

Test on Mugen 1.1b and Ikemen Go 0.97, with the same stages, Example:
https://youtu.be/FkbD0mnmaew

Files:
https://www.mediafire.com/file/udvc49103ugncml/stages.rar/file

**Comment by K4thos** [comment]
> Stage with problem when moving (the stage goes crazy - CvS 2 London - Evening)
this one (delta) is fixed already

**Comment by K4thos** [comment]
> It has a movement effect (if it is observed in the video, in the intro of the stadium it has a movement effect, but in ikemen it is activated)

fixed in above commit

as for the rest (envShake black fade being applied when it shouldn't and not accurate y pos on some stages) I didn't managed to fix them, maybe someone else, who can comprehend math behind those calculations will do so in future.

**Comment by CitrusHappy** [comment]
regarding #172, a temporary fix is to shift all sprites in fighter factory using the align tool upwards. this has to be done manually for each stage so is not a viable long term fix.

**Comment by K4thos** [comment]
remaining issues should be fixed by #605
