### ISSUE TITLE
Weird AI behavior on tag mode.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#307]
So, I've run into issues regarding some character's AI on tag mode.

https://streamable.com/knzkji
First one: The character's AI activates by itself on tag mode after performing certain moves, while in single and turns mode everything is fine. Character: [Clark.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/6872671/Clark.zip)

https://streamable.com/63b7e6
Second one: It happens with characters that have brutal AI, basically the AI stops attacking whenever the enemy is down to the last character on tag mode, they will still move, guard, tag out, but won't attack at all. Character: [Daimon.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/6872672/Daimon.zip)

**Comment by K4thos** [comment]
can't reproduce either of these reports on latest github build.

In Clark case I assume it may have been a problem with cleaning variables between fights or badly coded winmugen AI activation that can happen in simul/tag. As for Daimon, it didn't happen in multiple fights I've tested. Here is one of them:

https://user-images.githubusercontent.com/8928195/176792331-e3090ee7-7299-47e0-9fc5-6400da4e899c.mp4

**Comment by UrsoManso** [comment]
It was indeed bad AI activation, I fixed it by commenting the activation code for simul.
