### ISSUE TITLE
Linux Network

### ISSUE THREAD

**Issue by formula1** [ikemen-engine/Ikemen-GO#310]
EDIT: I'm using Ubuntu

When I enter network
it gives me `HOST GAME`, `JOIN GAME` and `BACK`

---
When I choose `JOIN GAME`
It gives me `NEW ADDRESS` and `BACK`
When I choose `NEW ADDRESS`
```
Enter Host display name e.g. John.
Existing entries can be removed with DELETE button
```
However I have no where to enter the host name

---
When I choose `HOST GAME`
It tells me
```
Waiting for player 2... (7500)
```
Am I supposed to share my IP address with the other person?

**Comment by EVILEDLIBRE** [comment]
I could be wrong, and sorry if I am, but to the best of my knowledge this is how things work. Yes. Because there really is no matchmaking system. So, like in the old days of Doom 1993, you essentially need to 'direct dial' the IP Address of the person you're playing with. So, make sure you trust them.

**Comment by formula1** [comment]
When I `Host Game`, it does not provide me with the IP address and when I choose `Join Game` I have no place to put the address.

**Comment by EVILEDLIBRE** [comment]
I assume, again could be wrong, that the host IP address is your gateway address. You'll likely have to port forward like hosting a server for any other game manually. When joining, just type the ID address. It starts to appear under the other text.

**Comment by kwadroke** [comment]
> ```
> Enter Host display name e.g. John.
> Existing entries can be removed with DELETE button
> ```
> 
> However I have no where to enter the host name

You just have to type it in, there's no "box" for it. The info you entered should display on the screen. 

> When I choose `HOST GAME`
> It tells me
> 
> ```
> Waiting for player 2... (7500)
> ```
> 
> Am I supposed to share my IP address with the other person?

You can get your IP address in a web browser from [DuckDuckGo](https://html.duckduckgo.com/html?q=my+ip+address),  Google or your favorite search engine - search for "My IP Address". Give that IP to the remote player _after_ opening a hole in your firewall for **TCP** port **7500**. You may need to search for how to open a port on your firewall/router as each brand & model is different. Be aware that not all routers/firewalls can have a hole opened. Especially ISP provided routers. Make sure you close the port on the router after you're done playing for security reasons, just in case. [Hamachi](https://www.vpn.net/) or another gaming VPN service might be another solution for you.

Disclaimer: I'm not an expert on Ikemen or MUGEN. I just follow the GitHub repo. I did a fresh pull & build on Debian Linux which should be the same as Ubuntu.

**Comment by EVILEDLIBRE** [comment]
Thank you @kwadroke. You explained it way better than I did. I hope this helps him on the networking stuff.

Another key point I think needs to be mentioned is that you have to mirror the game set up between you and the other player. They need to have the same Ikemen Go Engine version, characters, stages, and possibly the same pertinent settings as well. Essentially, you need to be sharing the same copy of the game.

That said, they should be able to play on different Operating Systems; given that the binaries are from the same Source Code (The same exact version of the Ikemen Go Engine.)

So, for instance, if you're playing on GNU + Linux and someone else is playing on windows you should be fine as long as everything else is the same.

**Comment by K4thos** [comment]
https://github.com/K4thos/Ikemen_GO/wiki/Miscellaneous-Info#netplay
