### ISSUE TITLE
Multiplayer black frames issue, almost unplayable. 

### ISSUE THREAD

**Issue by notkidgamer23** [ikemen-engine/Ikemen-GO#32]
So I've tested not only your branch of Ikemen_GO (which is very nice and I must thank you for carrying on the torch so to speak) but also on all the other branches I could find. And as far as I can tell, this seems to be persistent on all of them. Basically singleplayer is flawless, lag free, perfect. But as soon as I open multiplayer, a single frame out of, a variable amount of frames goes black. So for example, doing a local multiplayer test only 1 out of 60+ frames will go black very briefly and is almost unnoticeable. However as soon as I try to play with my friend, 1 out of 20 frames or so goes black. When I play with my pals outside the country, then 1 out of 3-5 frames turn black making it almost unplayable... Not sure what causes this, but if you have any ideas it'd be really appreciated...

**Comment by nckgriva** [comment]
system.go, line 368.
Removing this line fixes the issue but it is needed for clearing the screen every frame. I'll see what i can do.

**Comment by Spynathan** [comment]
Much thanc, good to know it wasn't on my end. Keep up de good work.

**Comment by Windblade-GR01** [comment]
Well I did start by disabling the screen clear while online with:
```GO
if s.netInput == nil {
	gl.Clear(gl.COLOR_BUFFER_BIT)
}
```
But it seems that it still clears the screen for some reason (At least on the menus) and removes the black frames.
It's a start, but we still have to check if this "fix" introduces other problems with the drawing while online.

**Comment by Spynathan** [comment]
Been playing with my m8 and it's working great so far! No issues I can see.

**Comment by Windblade-GR01** [comment]
So after some tests I could not find anything wrong with the drawing while online.
If someone finds a drawing bug while in online mode please inform us.
Closing for now.

**Comment by Windblade-GR01** [comment]
Opening this again.
TheFclass97 has reported it happens on his end.

**Comment by K4thos** [comment]
I assume it's fixed by #806
