### ISSUE TITLE
Toggling Fullscreen on and off erroneously offsets the viewport until the game is restarted

### ISSUE THREAD

**Issue by SuperFromND** [ikemen-engine/Ikemen-GO#324]
**Specs:** Windows 7 Professional x64, AMD Radeon 7500M/7600M
**IKEMEN GO version:** v0.97
**Repro Steps:**
- Start up IKEMEN GO in windowed mode, at 640x480.
- Go into the Options menu, then to Video Settings.
- Toggle Fullscreen on.
- Toggle Fullscreen off.
- Observe the viewport's location.

![fullscreen weirdness thing](https://user-images.githubusercontent.com/22881403/128612871-49a98745-86c1-47be-ab72-9a51c511f59d.png)

Interestingly enough, this does **not** happen at odd-ball resolutions (960x720, 320x240), but does seem to happen with more common resolutions (640x480, 1280x720).  This offset error fixes itself whenever the game is restarted, so this is most likely a bug with the code that handles toggling between fullscreen and non-fullscreen.

It's worth noting the oddball resolutions, while not affected by this in the same way, are still somewhat bugged as they do not properly fill the screen when fullscreened (instead displaying in the bottom-left corner of the screen, at the nearest full-screen resolution Windows allows).  This is almost certainly due to Windows itself though, as Windows does not allow arbitrary resolutions when fullscreening games.

**Comment by K4thos** [comment]
can't repoduce it, windows 10, nvidia card

**Comment by lovelydumpling** [comment]
I notice you've got a glass aero theme. Is this because you're using Windows 7, or do you have a themer like Windowblinds set up? If the latter, can you see if it still happens with it off? I use a virtually identical theme in Windowblinds and it often has weird effects like this on certain games and applications.

**Comment by SuperFromND** [comment]
Closing as this issue's been rendered moot, given that latest nightly doesn't run on Windows 7 and it was almost certainly fixed by my own changes to window scaling anyways.
