### ISSUE TITLE
How to switch Tag animations?

### ISSUE THREAD

**Issue by SlopeheadKing** [ikemen-engine/Ikemen-GO#328]
For all of my characters, the animations for tag in, tag out and after the match is done, they fly all the way up for no reason. Where in the code can I replace the required animations at?

**Comment by K4thos** [comment]
data/common.const
```ini
; tag.zss anims
AnimTagEnteringScreen = 100
AnimTagLeavingScreen = 100
AnimTagJumpingIn = 42
AnimTagLanding = 47```
they can be overriden on per character basis via: https://github.com/K4thos/Ikemen_GO/wiki/Character-features#cns_constants

that being said, "fly all the way up for no reason" is to vague explanation of what is happening. Upload character that showcases the issue, maybe it's not a problem with animation.

**Comment by SlopeheadKing** [comment]
Ok! Thanks!

**Comment by SlopeheadKing** [comment]
[Goku_Base.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/6987299/Goku_Base.zip)
here's the char

**Comment by K4thos** [comment]
fixed here: https://github.com/K4thos/Ikemen_GO/commit/d927c714dfaaad495ed68d8c9d632961761ffb9b
