### ISSUE TITLE
Char FX Bug

### ISSUE THREAD

**Issue by streamfrost** [ikemen-engine/Ikemen-GO#333]
Chat fx not working correctly in ikemen for some unknown reason

[Char](https://www.youtube.com/watch?v=sr0QnNvC_As)

Ikemen:
![ikemen000](https://user-images.githubusercontent.com/89158110/129953014-0d4fd806-183d-42a4-9f4c-10a3e82854a1.png)
![ikemen001](https://user-images.githubusercontent.com/89158110/129953023-7f358cb4-8fda-43e1-850b-366ebdb608c5.png)
![ikemen003](https://user-images.githubusercontent.com/89158110/129953026-03dd0f64-0992-47f3-b414-ebc10bb32620.png)
![ikemen004](https://user-images.githubusercontent.com/89158110/129953032-cd49f791-b3b3-4572-b9c8-72dbb75b8a4b.png)
![ikemen006](https://user-images.githubusercontent.com/89158110/129953034-c696b44b-e278-4b8d-bdeb-3466cf6e7b46.png)
Mugen1.1:
![mugen000](https://user-images.githubusercontent.com/89158110/129953108-68d92f23-f636-42cd-8dc0-68320d4dd65f.png)
![mugen001](https://user-images.githubusercontent.com/89158110/129953122-869cefcb-c110-45c1-8460-0f7a5716b588.png)
![mugen003](https://user-images.githubusercontent.com/89158110/129953130-01651324-3ee9-4345-a80c-4c8b584cd1ca.png)
![mugen005](https://user-images.githubusercontent.com/89158110/129953136-2622131c-672e-462e-97e3-401ad05ed9d4.png)

and i also have a question
How can i disable stages zoom?

**Comment by K4thos** [comment]
already reported: https://github.com/Windblade-GR01/Ikemen-GO/issues/288

**Comment by K4thos** [comment]
not solved yet, the ticket is closed for maintenance reasons - duplicate report
