### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by streamfrost** [ikemen-engine/Ikemen-GO#341]
How can I enable black borders? why ikemen reduces the space of the stages?
Mugen 1.1
![Sin título](https://user-images.githubusercontent.com/89158110/130703898-989decc5-02e1-41c8-87b3-d139a2983987.png)
Mugen 1.1
![mugen001](https://user-images.githubusercontent.com/89158110/130703942-9e0369d0-1c57-4bdf-a490-7ad86a3bc5dc.png)
Ikemen
![ikemen000](https://user-images.githubusercontent.com/89158110/130703964-5e3a2276-9f86-4831-8b44-91a2587e6231.png)

**Comment by K4thos** [comment]
already reported: https://github.com/ikemen-engine/Ikemen-GO/issues/170
