### ISSUE TITLE
[ADVICE REQUEST] Multiplayer / Netplay Online Mismatch

### ISSUE THREAD

**Issue by CSAndrew** [ikemen-engine/Ikemen-GO#353]
# The Problem
A friend and I are modifying an Ikemen GO build found on YouTube, I'll link our zipped version down below (if you're security conscious, you could just run it in a VM). When we play online, we're playing from the same version / zipped archive w/ the same roster, but for whatever reason, there are odd problems.

#### Notes:
I understand the Ikemen GO team didn't create the exact game client that we're using, but any help is appreciated nonetheless.

## Character Select
The game is showing our cursors on different character panels.

## In-Game
Each client shows us having different characters and fighting different characters on each of our screens. For example, in a 2v2 simul, our characters will be different on each of our clients and so will the opponents'.

## Connection
We're connected using ZeroTier, but it seems to happen on Hamachi as well (albeit with much worse latency).

## Link to The Ikemen GO we're using
https://mega.nz/file/FZtAyDCI#KI54Z_bi7y6XKvoYK4NgDODsGJu4x8ex0REkjJUxRLg

**Comment by K4thos** [comment]
most likely cause by outdated scripts (versions older than 0.97 had problem with resetting some data, which could lead to problems you've described). Upcoming 0.98 build also has additional fix related to this (desync problem due to randomselect slot not being reset correctly between matches).

Please let us know if you still experience these problems after 0.98 release goes public and you update your game.

**Comment by CSAndrew** [comment]
Speaking of updating the Ikemen, we don't have the original source code, for lack of a better term (as far as I know) to the actual client + screenpack. I'm planning on reading more of the documentation, and not to ask obvious questions, but it is possible to add the new features from 0.97 (This one is on 0.96) with UI edits and add the supporting changes / patches coming up and update the game, without the earlier files?

That, or would we have to rebuild / compile a new version from source (here) and port over the screenpacks, UI, options, characters, assets, etc, into the new 0.98 client?

**Comment by K4thos** [comment]
No need to manually compile the engine or edit any scripts. As long as your motif (gui layout) is portable updating to newer engine is a matter of minutes (downloading release package overwriting old files or moving your folders). Read this article: https://github.com/K4thos/Ikemen_GO/wiki/Miscellaneous-Info#installing_customizing
google search "mugen screenpack tutorial" for general info how to edit motifs (often called screenpacks and lifebars).

Compatibility fixes with mugen motifs implemented in upcoming 0.98 may require some changes in your system.def (update notes listing necessary changes will be added to release page).

**Comment by K4thos** [comment]
closing the ticket since I can't reproduce it on latest build. There are many players from Ultimate Mugen Team using it without reporting such problems. Feel free to re-open it if it still happens.
