### ISSUE TITLE
Rare Akuma dies by the F1 button in debug mode

### ISSUE THREAD

**Issue by cyliamargatroid** [ikemen-engine/Ikemen-GO#354]
An odd thing about how Rare Akuma getting killed is when paused before doing supers, Pressing F1 actually kills Rare Akuma in IKEMEN.

in MUGEN, he's normally Immune to F1 button.

Link: https://network.mugenguild.com/pots/chars.html

**Comment by Windblade-GR01** [comment]
F1 is **debug** commands.
Used for debugging.

Chars should not interfere with that.
I do not consider replicating this a high piority.

**Comment by potsmugen** [comment]
For what it's worth this no longer happens in the current version of the engine.
