### ISSUE TITLE
Pallete Selector For IKEMEN GO!

### ISSUE THREAD

**Issue by DJPilouDevelopersandmore** [ikemen-engine/Ikemen-GO#357]
ok guys! i using this select screen when i pressing select a character and pallete and alternative characters i hope you enjoy this!

here:
https://www.youtube.com/watch?v=oQ39x1x6UHQ

**Comment by K4thos** [comment]
it's just a mock-up, not real thing. Not even meant for ikemen but mugen hook (which doesn't support anything like that either)
