### ISSUE TITLE
BUG portrait.anim P2 no MIRROR in select

### ISSUE THREAD

**Issue by shurato** [ikemen-engine/Ikemen-GO#362]
Player 2 needs to be fixed and mirrors the photo, when the cells are divisible by 2,

12/2 = 6
6 first cell =p1 normal
next 6 = p2 mirr
![print 2](https://user-images.githubusercontent.com/7958164/135362289-defb24d1-8b12-4d72-8b72-6c3a06a192f6.jpg)
![print1](https://user-images.githubusercontent.com/7958164/135362263-b95787f6-f5a1-4c91-8b15-d60b5a64838e.jpg)
or

**Comment by K4thos** [comment]
I don't understand this ticket. Is this bug report or feature request?

**Comment by shurato** [comment]
is this bug. see 
https://www.youtube.com/watch?v=ksW2df7b7Uc

**Comment by K4thos** [comment]
fixed, thanks
