### ISSUE TITLE
Some weird control consistency issues between Mugen and Ikemen GO with commands (State -1)

### ISSUE THREAD

**Issue by VinVulpis** [ikemen-engine/Ikemen-GO#365]
So, I decided to give Ikemen GO a shot, and I really like all the new features. The characters I've been creating in Mugen 1.1b generally work great in Ikemen GO, but there is a weird issue I've encountered.

Here in these video, Ikemen Go is top right, Mugen is bottom left. I had them both running and controlled at the same time to show how they both react to my inputs at the same time.

As an additional note. I'm breaking a lot of the usual rules with Mugen, and allow my characters to turn freely, and jump with a button, and that's where I'm running into issues.

Issue one, Command Buffer.time issues
https://user-images.githubusercontent.com/66293146/136507136-39ea9f23-ce51-42e0-969d-852c2f08c4a3.mp4
So, here, my had my default.buffer.time=4. I have the "a" button as my jump button, and it is operating on the default buffer time.
In Mugen, it seems to work as indended, I can short-hop, no problem.

In Ikemen Go, I cannot short hop at all. Now, I do know that my jump squats ate 4 frames. and with a 4 frame buffer, I suppose it makes sense he's still full jump on a slight tap. So is Mugen's buffer in this situation broken? Or is Ikemen doing something different with these numbers. It's an interesting note of consistency and I'm curious. I was able to fix this just by lowering the buffer input for the jump command. 

Someone told me that the default.buffer.time thing was broken and overridding ones sets for specific commands? But I haven't noticed this.

Issue 2, the important one: Turning
https://user-images.githubusercontent.com/66293146/136507824-2e55bd00-9f97-4e8b-a116-e822e2ca086b.mp4
As I noted, my character can freely turn and have "noautoturn" permanently asserted.
The issue comes with a certain conflict with one of my special commands to be turn-dashing function smoothly.
```
[Command]
name = "dash"     ;For turn runs
command = ~B, F
time = 8
```
In Mugen 1.1 this is working fine. If I just press and hold "B", my character will turn, then walk in that direction, then if I want to dash that way, I can just double tap B, B (or B, F as the game will read it during the turning animation)
In Ikemen GO, it it forcing my character to Dash in the turned direction. As if it thinks I'm pressing 2 buttons, when I'm just simply pressing and holding.

I've tryed messing with buffer.time and time, but nothing works to fix this, other than breaking the ability to turn-dash, instead needing to triple tap that direction. once to turn, and then two more times to dash.

So, I'm just posting this issue if there is something up with the way Ikemen reads commands, and if there is some way I can fix this with a quick code rework. I know my play system is weird by Mugen standards, but I've been kinda prototyping concepts with it for later use. Ikemen seems like a nice upgrade, so I'm eager to use it if I can get to the route of this issue.

EDIT: Further testing. Yeah, it seems like MUGEN is reading double inputs when a character turns instead of preserving the last input as the character turns. When I dash and do a QC (D,F) input for a fireball in the reverse direction in mugen, I got a fireball, but when I do the same in IKEMEN GO, it's reading it as a DP motion (F, D, DF) It's holding the forward from my dash's turn slide.
https://user-images.githubusercontent.com/66293146/136642977-ddd6700e-eaec-4df2-9eb7-af1f66582302.mp4
(I have my camera controller helper active in this video's mugen window, which also is broken in Ikemen for some reason, likely because of camera function differences, but the helper will not move at all in IKEMEN)

Thanks much and great work on this project either way!

**EDIT:** STAGE ISSUE: Tension
https://user-images.githubusercontent.com/66293146/136639376-0d15e6b9-5549-47e8-ab91-f544a3236aba.mp4
```
[Camera]
startx = 0
starty = 0

boundleft = -560
boundright = 560
boundhigh = -420
boundlow =  20

tension = 360
tensionhigh = 220
tensionlow =  100
;verticalfollow = .2
;floortension = 20

overdrawhigh = 180
overdrawlow = 180

cuthigh = 0
cutlow = 0

startzoom = .5
zoomout = .5
zoomin = .75
```
Adding this at the end because it's another issue I've encountered. It seems like the stage camera controllers for "tensionhigh" and "tensionlow" do not work at all. as my characters can jump up off screen whenever characters are close together. Verticalfollow and floortension also seem to have issues. It feels like the engine is doing it's own setting and ignoring these completely, especially when I have the zoomin setting to .75. (1 is too close for my tastes, especially with a 16:9 display window.) It's forcing me for the time being to keep my camera zoomed out more permanently until this issue is fixed.

EDIT 2: So I did figure out a work around to make my unique controls work consistently between engines by using a fixed hidden helper to read player inputs based on Left and Right inputs and comparing them to facing and it works. Even better than before, actually. But, I hope the details of the input differences helps you guys either way.

**Comment by Windblade-GR01** [comment]
The Ikemen parser has been problematic and a rewrite of it is in the works.

I'll look about the `Tension` issue.
Thanks for reporting it.

**Comment by agrastiOs** [comment]
The tension issue makes it really painful to play 2v2.

**Comment by Lazin3ss** [comment]
About tensionhigh/tensionlow: its behavior was changed for 0.99, in order to be more accurate to MUGEN 1.1 (though not completely), so this specific problem should be solved. Also, declaring tensionhigh/tensionlow overrides verticalfollow/floortension behavior.

Input parser is still in the works, though.

**Comment by VinVulpis** [comment]
Ideally, I'd love to get IkemenGo's camera looking super smooth flowing like I did in Mugen1.1 with the use of a camera helper a made. My camera helper just breaks the camera in IkemenGo so far. You can see how smooth I made the camera movement and zoom work in the 3rd video's mugen side. I used the helper's width to control the zoom, since the zoom STCTRL is broken. 

Would be awesome if IkemenGo eventually gets more camera options, but I understand there are priorities for the devs. I just have a certain fixation on "presentation" for certain things.

**Comment by Isakku** [comment]
Sorry I didn't notice this issue already existed.
 I noticed this before in  https://github.com/ikemen-engine/Ikemen-GO/discussions/862 but it was closed, so I thought it was considered as "solved".
 
 I'm having this issue on Linux. It seems to happen in a weird way, inconsistent from the Windows version (at least that was how it was for me in v0.98, 0.99 doesn't work on Windows for me but it does work on Linux.

In some cases, some button combinations such as holding X and pressing forward or backwards, brings back the bug.
As I mentioned in that discussion, pressing directionals such as "forward" was giving the same result as double forward "FF"
my char couldn't walk, it could only dash. Well, now it works well unless I'm holding down another button such as "X"

I also noticed that button combinations such as:
triggerall = command = "x" && command = "y" && command = "z"

are much harder to perform, as if MUGEN had a more tolerant input buffer than Ikemen and allowed a few more milliseconds between key presses.

**Comment by K4thos** [comment]
From PotS:

> This report is a bit long winded and without reproduction steps so it's hard to say for sure. But that "dash" command by itself seems to work the same between Mugen and nightly

**Comment by VinVulpis** [comment]
I've long since rewritten how my free-turning works by using a helper to convert "forward" and "back" inputs to "left" and "right" for most things. I've noticed in the more recent builds that commands do feel better than they used to either way but I haven't compared anything to Mugen for a long time now. 

I think the simple way to reproduce this problem I had was to make a character have noautoturn asserted in -2. Make a back input turn the character and see if the turn is reading that as "~B" input then a F, rather than just 1 input like Mugen SEEMED to.
