### ISSUE TITLE
Stretch aspect ratio

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#367]
![480p](https://user-images.githubusercontent.com/77592586/137447502-aa61c86c-c470-4595-84d3-be378e03cf3d.png)
![720p](https://user-images.githubusercontent.com/77592586/137447504-86adc1c5-0ab0-4679-9648-86600692b117.png)

Winmugen does that, as you can see if I use a 4:3 screenpack in 16:9 resolution everything is stretched to proper aspect ratio. Just thought it would be a nice feature to have on Ikemen.

**Comment by randomarcadedude** [comment]
This would be an awesome feature to have in Ikemen, since it means more options would be available because of how many great 4:3 stages there are already

**Comment by UrsoManso** [comment]
I just found out that if you fullscreen in 640x480 resolution it automatically stretches, maybe this could be used to implement for windowed resolutions as well.

**Comment by UrsoManso** [comment]
Changing localcoord works well for characters but its a different deal for screenpacks and stages. Being able to automatically stretch to window resolution would make everything work flawlesly right off the bat without having to manually edit everything.

**Comment by K4thos** [comment]
already reported: #170
