### ISSUE TITLE
Layered conds don't work fully.

### ISSUE THREAD

**Issue by jenngra505** [ikemen-engine/Ikemen-GO#377]
In Mugen it is possible to make countless layers of cond and have them all be read at once although there seems to be a limit before it starts ignoring them in IKEMEN.
Here's an example created because of the multiple different freeze animations in Mugen.
[State 820, 1]
type = ChangeAnim
trigger1 = Anim != 7698 && Anim != 7990 && Anim != 9016 && Anim != 5015
value = cond(AnimExist(7990),7990,cond(AnimExist(9016),9016,cond(AnimExist(7698),7698,5015)))
While a character with a freeze animation will still work as intended, an incompatible character will freeze in their current animation instead of going to Anim 5015.

**Comment by K4thos** [comment]
can't reproduce by pasting the code to kfm, so I assume it's already fixed

**Comment by jenngra505** [comment]
It still bugs out when used in my Numbuh 3 for some reason which can be found here. https://1drv.ms/u/s!AqN1Ini5-I2Ig9MLCMB6UbdIL2xUSQ?e=daoFwS
