### ISSUE TITLE
[Feature] Ikemen Version and non forcefull compatibility coding

### ISSUE THREAD

**Issue by Amidweiz** [ikemen-engine/Ikemen-GO#384]
`ikemenversion = 0.98` This would be a simple addition to the Def file that would be similar to `mugenversion =` but would rather define that a character is specifically made for ikemen GO in mind since other than non existent Sctrls erroring out mugen, there is no proper way to distinguish the two. With `ikemenversion` in the def file, said character would adopt fixes to legacy issues such as the recently brought up "bug" of defmulset

![Screenshot](https://cdn.discordapp.com/attachments/742894608006250588/905390714605690910/image0.png)

`And at line 5705
            crun.customDefense = exp[0].evalF(c)
Change this to
            crun.customDefense = 1/exp[0].evalF(c)`

with it's behavior currently being correct to what the sctrl implies, multiplying the defense value by what is set in the sctrl rather than mugens legacy behavior of dividing it instead. With the opposite if `mugenversion` is only present, use the legacy behavior. It would also have the feature like it did in mugen telling the user who downloaded the content what version of ikemen it is for.

**Comment by Orochikyocr** [comment]
TBH Ikemen Go is far away from being a final product and development will continue. Newer updates breaking old stuff are quite expected, this is one of the foreseen consequences of using an alpha/beta product.

You can say it is a simple addition... from our view of point, but to implement this devs maybe have to make huge changes in the GO/LUA code.

**Comment by K4thos** [comment]
ikemenversion has been implemented in 0.98.2
