### ISSUE TITLE
Remap bug

### ISSUE THREAD

**Issue by dbaldan** [ikemen-engine/Ikemen-GO#387]
I got a bug to share:
On this animation, the helpers use RemapPal to change their colors and check the root position to move towards the root, so the animation can end.

On the video, we have 3 cases:
1 - Mugen 1.0, 4:3 - Works both the position and the remap
2 - Ikemen 0.98.1 (OS X) 4:3 - Position works, but not the remap
3 - Ikemen 0.98.1 (OS X) 16:9 - Neither position nor remap works

https://www.youtube.com/watch?v=3N2xErlk2-o

The remap code isn’t a big deal:

```
[State 0, RemapPal] 
type = RemapPal
trigger1 = !time
source = 1,1
dest = 2, 1
```

And the position code:

```
[State 0, Velset] 
type = Velset
triggerall = vel x > 0
trigger1 = teamside = 1
trigger1 = pos x >= root, pos x
trigger2 = teamside = 2
trigger2 = pos x <= root, pos x
x = 0

[State 0, PosSet]
type = PosSet
trigger1 = animelemtime(5) >= 0
trigger1 = vel x = 0
x = floor(root, pos x)

[State 192,11]
type = destroyself
trigger1 = pos x = root, pos x
trigger1 = vel x = 0
```

**Comment by K4thos** [comment]
please upload character showcased in the video, so that it can be used for testing

**Comment by K4thos** [comment]
found it:
[Darkman_RMM.zip](https://github.com/ikemen-engine/Ikemen-GO/files/8953766/Darkman_RMM.zip)

Problem with palette was a combination of buggy source and character code. On character side it's this code from -2 running on helper that has var(58) = 0

```[State 0, RemapPal] ;Revert to original player selected palette when var(57) is reset to zero
type = RemapPal
trigger1 = !var(57)
trigger1 = time % 8 = 0 ;It's needed believe it or not, makes the palfx actually work along-side/with the palette change
source = 1, 1
dest = 1, var(58)````

**Comment by K4thos** [comment]
both problems have been fixed
