### ISSUE TITLE
vansreflector when reflecting the reflected projectile not working properly in IKEMEN GO

### ISSUE THREAD

**Issue by Krudelu** [ikemen-engine/Ikemen-GO#388]
When I tested vansflector for IKEMEN GO v0.98.1 (using the updated .exe file you recently posted), reflecting back the reflected projectile doesn't work

But in MUGEN, it works just fine

I'm using Rugal by Vans in this video to show the issue. I slowed down the fireball speed so I can try to pingpong reflect better here. No other modifications to the projectile and reflected projectile codes

Here's the video that shows it
https://youtu.be/8TZgQ9zljxM

here's the character with slowed down projectile to make reproducing the issue easier
[Rugal_LB.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7532743/Rugal_LB.zip)

also, for the code used for vansreflector, here's the link to MFG instructions in regards to it
https://mugenguild.com/forum/topics/tutorial-%E9%A3%9B%E3%81%B3%E9%81%93%E5%85%B7%E3%82%92%E8%B7%B3%E3%81%AD%E8%BF%94%E3%81%97%E6%96%B9%E6%B3%95-projectile-reflection-178433.0.html

**Comment by K4thos** [comment]
@NeatUnsou, looks like #553 introduced different compatibility problem with Vans Rugal reflector. After af743f2aaffc972501a645aea3d1aa1f34b5ee1e reflector now duplicates projectile:
https://user-images.githubusercontent.com/8928195/176316871-3657b0ef-683b-4e8d-91aa-ac9749743e41.mp4
