### ISSUE TITLE
Mugen 1.1 stage parallax paramater perspective distortion not working/supported

### ISSUE THREAD

**Issue by PotofWeed** [ikemen-engine/Ikemen-GO#393]
Mugen 1.1 Animations using the "Parallax" Parameter in combination with the non-deprecated parameters of "width", scalestart etc do not work. 
In Mugen 1.1,  animation sequences using the Parallax Parameter in combination with
 width = top_width, bottom_width ; (int, int), creates a trapezoid perspective distortion effect to achieve Parallax.

In Ikemen Build 0.98.1 and lower, the same working values from a Mugen 1.1 coded stage, will display the original image as a flat with no perspective distortion (aka parallax) whatsoever.
I have provided visual examples for the Mugen 1.1 version of this working, and the Ikemen version with the error at the link below:

https://www.newagemugen.com/t4148-official-ikemen-go-thread-current-build-0-98-released-29-10-21#36024

Code mentioned also below:

`[BG FLOOR]
type			= parallax
**actionno		= 1**
start			= 0,660
tile			= 1,1
tilespacing	= 3000,1080
delta	        = 0.2100512259, 1
mask	        = 1
width	        = 3000,30000
scalestart		= 0.35,0.35
ID			 = 100`

**Comment by Orochikyocr** [comment]
Saying this feature isn't supported by testing just one stage is an understatement.
It seems you were not using the same zoom options in Mugen and Ikemen Go.
Devs always like you to provide a link to the stage/characters with the issue.

**Comment by Orochikyocr** [comment]
https://www.youtube.com/watch?v=C9FXOP2TZFM
This is Doom Stage working on Ikemen Go, using parallax. That is way important to provide links.
Street Fighter IV training stage
https://streamable.com/eyrmi4
Also, IET Arcade is using parallax in his stages for his commercial game.
https://www.youtube.com/watch?v=TziZR0vwwNI

So this is the reason providing links is very important.
Try turning Ikemen Go Zoom OFF in the config.json

**Comment by PotofWeed** [comment]
> 
> 
> Saying this feature isn't supported by testing just one stage is an understatement. It seems you were not using the same zoom options in Mugen and Ikemen Go. Devs always like you to provide a link to the stage/characters with the issue.

This test is based on the testing of 17 stages using the parallax function in combination with the actionno/begin action parameters. My mistake was not specifying clearly that the issue relates to ANIMATION(anim) sequences and not static sprites.
I have updated the original description accordingly

**Comment by Orochikyocr** [comment]
We heavily discussed this issue in the past on the discord channel.
Still, if you can share one of those stages so we can conduct our own tests. This way we can help devs better.

**Comment by PotofWeed** [comment]
> 
> 
> https://www.youtube.com/watch?v=C9FXOP2TZFM This is Doom Stage working on Ikemen Go, using parallax. Street Fighter IV training stage https://streamable.com/eyrmi4 Also, IET Arcade is using parallax in his stages for his commercial game. https://www.youtube.com/watch?v=TziZR0vwwNI
> 
> So this is the reason providing links is very important. Try turning Ikemen Go Zoom OFF in the config.json

These examples are all using "type = normal" parameter and not "type = anim" parameter.
Zoom was never a factor in the issue appearing/not appearing.
Setting zoom to true/false yields the same results.

If you would like to an example of the error in a publicly available stage where the bug was first discovered, please use the stage at the link below which also uses a fully animated parallax floor via type=anim/actionno as opposed to type=normal/spriteno=

Link 1:
https://www.andersonkenya1.net/files/file/9644-mmv-a-p-o-r-a-v-e-9-5mm/

link 2:
https://www.newagemugen.com/t3000-mugen-1-1-ultra-zoom-stagemm-v-a-p-o-r-a-v-e-9-5-mm-by-negative-edge-newagemugen#29127

link3:
https://mugenarchive.com/forums/downloads.php?do=file&id=68718--4k-mm-v-a-p-o-r-a-v-e-9-5-mm-negative-d-

Alternatively any senior coder you could recreate the issue in any of the above mentioned stages by swapping type=normal with type=anim and creating an actionno with .air sequence instead of using a static type=normal spriteno=

I hope this explains the issue more clearly

**Comment by K4thos** [comment]
please post direct links to stages that showcases the issue here. I'm not going to to register on newagemugen or andersonkenya1 to get them. This feature will most likely work correctly in 0.98.2, but I need a testing sample to see if my code works correctly.

**Comment by K4thos** [comment]
most likely already fixed. If no (when using latest github build, not 0.98.2) than feel free to reopen the ticket, but this time upload stages by drag and dropping them directly to issue page, instead of using external hosting that requires registration.
