### ISSUE TITLE
Zoomdelta Acts Like Regular Delta when zoomdelta < 1

### ISSUE THREAD

**Issue by PeeJayBonobo** [ikemen-engine/Ikemen-GO#400]
# Issue

When I zoom in or out, I expect anything with a zoomdelta lower than 1 to stay in place while zooming (or not zooming at all if it's 0), but instead, it adds a regular delta to it depending on whether it's a negative or positive value.

# Code

```
[BG Star Animation 1]
type = anim
actionno = 0
start = -640,0
delta = .025,.025
mask = 1
tile = 50,50
tilespacing = 30,28
zoomdelta = .025

[BG Star Animation 2]
type = anim
actionno = 1
start = -640,0
delta = .025,.025
mask = 1
tile = 50,50
tilespacing = 30,28
zoomdelta = .025

[BG Sun]
type = anim
actionno = 2
start = 160,120
delta = .05,.05
mask = 1
zoomdelta = .05
```

# Video Example

https://user-images.githubusercontent.com/3814426/145084677-317eb6a0-4d12-4e2c-abd0-b9d85ea70402.mp4

**Comment by K4thos** [comment]
fixed in latest github build
