### ISSUE TITLE
Can't run on Mac

### ISSUE THREAD

**Issue by alicenl** [ikemen-engine/Ikemen-GO#411]
I have done everything I can to get it to run on Mac, but to no avail
I keep getting the main.lua error thing
external/script/main.lua:669: <game end>
stack traceback:
	[G]: in function 'refresh'
	external/script/main.lua:669: in function 'f_refresh'
	.\external\script\start.lua:2191: in function 'f_selectScreen'
	.\external\script\start.lua:1415: in function 'f'
	external/script/main.lua:3019: in function 'loop'
	external/script/main.lua:3103: in function 'loop'
	external/script/main.lua:4081: in main chunk
	[G]: ?

How do I fix this?

**Comment by Windblade-GR01** [comment]
What version of the engine are you trying to run?
