### ISSUE TITLE
Implement a poison move feature / try to exactly replicate MUGEN reversaldef?

### ISSUE THREAD

**Issue by austinsanims** [ikemen-engine/Ikemen-GO#412]
In MUGEN (all the way through to 1.1) there's somewhat buggy reversal code that allows for poison-based moves.

https://user-images.githubusercontent.com/27598408/147609686-c82c4ef8-342c-4888-b6ca-da563cac9ccf.mp4

However, this does not translate over to IKEMEN Go.

https://user-images.githubusercontent.com/27598408/147609879-79c37a26-8055-410f-9936-762a7dd95d93.mp4

It would be interesting to see either compatibility for the characters that use this code, or an entire intentional poison mechanic.

**Comment by austinsanims** [comment]
to add here's how the code works


`;---------------------------------------------------------------------------
; SuperMove
[Statedef 3050]
type    = S
movetype= A
physics = S
juggle  = 0  ;0
velset = 0,0
anim = 3050
ctrl = 0

[State 0, Helper]
type = Helper
trigger1 = time = 0
helpertype = normal ;player
ID = 6008
stateno = 6008
ownpal = 1
supermovetime = 9999

[State 3000, Super A]
type = SuperPause
trigger1 = Time = 0
sound = s7,1
anim = -1
time = 50
movetime = 50
darken = 0
unhittable = 0
poweradd = -2000

[State 0, Explod]
type = Explod
trigger1 = time = 0
anim = 6010
pos = 0,20
postype = back  ;p2,front,back,left,right
supermovetime = -1
scale = .5,.5
sprpriority = -70
ownpal = 1
vel = 1,0

[State 0, Explod]
type = Explod
trigger1 = time = 0
anim = 6013
pos = 0,20
postype = back  ;p2,front,back,left,right
supermovetime = -1
scale = .5,.5
sprpriority = -71
ownpal = 1
vel = .8,0

[State 0, Explod]
type = Explod
trigger1 = time = 0
anim = 6012
pos = 0,20
postype = back  ;p2,front,back,left,right
supermovetime = -1
scale = .5,.5
sprpriority = -72
ownpal = 1
vel = .6,0

[State 0, Explod]
type = Explod
trigger1 = time = 0
anim = 6005
pos = 0,-30
postype = p1  ;p2,front,back,left,right
supermovetime = -1
scale = 1,1
sprpriority = 60
ownpal = 1

[State 0, Explod]
type = Explod
trigger1 = time = 0
anim = 6006
pos = 0,-30
postype = p1  ;p2,front,back,left,right
supermovetime = -1
scale = 1,1
sprpriority = 61
ownpal = 1

[State 0, Explod]
type = Explod
trigger1 = time = 0
anim = 6007
pos = 0,-30
postype = p1  ;p2,front,back,left,right
supermovetime = -1
scale = 1,1
sprpriority = -60
ownpal = 1

[State 0, Helper]
type = Helper
trigger1 = animelem = 3
helpertype = normal ;player
ID = 3050
stateno = 3055
pos = 30,0
postype = p1    ;p2,front,back,left,right
facing = 1
keyctrl = 0
ownpal = 1

[State 0, PlaySnd]
type = PlaySnd
trigger1 = animelem = 3
value = S3050,0

[State 0, PlaySnd]
type = PlaySnd
trigger1 = animelem = 3
value = S3050,1

[State 0, Explod]
type = Explod
trigger1 = animelem = 3
anim = 3051
pos = 30,0
postype = p1  ;p2,front,back,left,right
vel = 3,0
removetime = -2
pausemovetime = 0
scale = .5,.5
sprpriority = 5
ownpal = 1

[State 0, Explod]
type = Explod
trigger1 = animelem = 3
anim = 3052
pos = 0,0
postype = p1  ;p2,front,back,left,right
vel = 0,0
removetime = -2
pausemovetime = 0
scale = .5,.5
sprpriority = 5
ownpal = 1

[State 1000, 3]
type = ChangeState
trigger1 = AnimTime = 0
value = 0
ctrl = 1

;---------------------------------------------------------------------------
; SuperMove
[Statedef 3055]
type    = S
movetype= A
physics = N
velset = 3,0
anim = 3055
ctrl = 0

[State 210, 2]
type = HitDef
trigger1 = time = 0
attr = A, SP
animtype  = Hard
damage    = 65,5
guardflag = MA
pausetime = 0,0
guard.sparkno = s6070
sparkno = s6060
sparkxy = -10,-50
hitsound   = s3050,2
guardsound = s6,0
ground.type = Low;High
ground.slidetime = 12
ground.hittime  = 13
ground.velocity = -3
air.velocity = -3,0
p1stateno = 3056
p2stateno = 3060
forcestand = 1
forcenofall = 1
mindist= 0,0
maxdist = 999,0

[State 0, DestroySelf]
type = DestroySelf
trigger1 = animtime = 0

;---------------------------------------------------------------------------
; SuperMove
[Statedef 3056]
type    = S
movetype= I
physics = N
velset = 0,0
anim = 3056
ctrl = 0

[State 0, Explod]
type = Explod
trigger1 = time = 0
anim = 3053
pos = 0,-50
postype = p2  ;p2,front,back,left,right
facing = 1
vfacing = 1
bindtime = 1
vel = 0,0
accel = 0,0
random = 0,0
removetime = -2
pausemovetime = 0
scale = .5,.5
sprpriority = 50
ontop = 1
shadow = 0,0,0
ownpal = 1
removeongethit = 0

[State 0, Explod]
type = Explod
trigger1 = time %8= 0
anim = 3054
pos = 0,-50
postype = p2  ;p2,front,back,left,right
facing = 1
vfacing = 1
bindtime = 1
vel = 0,-1
accel = 0,0
random = 60,60
removetime = -2
pausemovetime = 0
scale = .25,.25
sprpriority = 50
ontop = 1
shadow = 0,0,0
ownpal = 1
removeongethit = 0

[State 0, ReversalDef]
type = ReversalDef
trigger1 = time = 0
reversal.attr = C,HP
guard.sparkno = s6070
sparkno = -1
hitsound = -1
numhits=0

[State 0, TargetLifeAdd]
type = TargetLifeAdd
trigger1 = time % 3 = 0
value = -1
kill = 0
absolute = 1

[State 0, DestroySelf]
type = DestroySelf
trigger1 = time >= 600

;p2 state
[Statedef 3060]
type    = S
movetype= H
physics = N
velset = 0,0
ctrl = 0

[State 0, PosSet]
type = PosSet
trigger1 = 1
y = 0

[State 200, 1]
type = HitDef
trigger1 = time = 0
attr = C, HP  ;uncommon attribute
damage = 0, 0                   ;Damage that move inflicts, guard damage
guardflag =                    ;Flags on how move is to be guarded against
hitflag = F-                    ;Flags of conditions that move can hit
priority = 1, Hit                ;Attack priority: 0 (least) to 7 (most), 4 default
;Hit/Miss/Dodge type (Def: Hit)
pausetime = 0, 0                 ;Time attacker pauses, time opponent shakes
guard.sparkno = s6070
sparkno = -1                      ;Spark anim no (Def: set above)
hitsound = -1                  ;Sound to play on hit
guardsound = -1                ;Sound to play on guard
ground.type = Low;High               ;Type: High, Low, Trip (def: Normal)
ground.slidetime = 0             ;Time that the opponent slides back
ground.hittime  = 0             ;Time opponent is in hit state
ground.velocity = 0             ;Velocity at which opponent is pushed
air.type = Low;High                  ;Type: High, Low, Trip (def: same as ground.type)
air.velocity = 0,0           ;X-velocity at which opponent is pushed,
;Y-velocity at which opponent is pushed
air.hittime = 0                 ;Time before opponent regains control in air

[State 0, ChangeAnim2]
type = ChangeAnim2
trigger1 = time = 0
value = 3060

[State 0, SelfState]
type = SelfState
trigger1 = time>=54
value = ifelse(alive,0,5110)
ctrl=1`

**Comment by slzero-X** [comment]
I do not think that is necessary anymore, take a look at RedirectID in the wiki.
All you have to do is use a variable to check if the opponent is poisoned, and use RedirectID to make the opponent execute the LifeAdd state controller.
IKEMEN Go specifically added RedirectID to make it a lot easier to make poison effects.

**Comment by K4thos** [comment]
fixed by #556 #553
