### ISSUE TITLE
Paralax stages fail to render properly

### ISSUE THREAD

**Issue by bedlight** [ikemen-engine/Ikemen-GO#422]
every stage that i tried that has paralax in it, ikemen fails to render those stages properly, resulting in:

blackness appearing when jumping or above the stage where it would usually not appear like that in mugen
assets not appearing properly (appear and then reappear like the flowers in beerus planet stage)

link to the stages: https://www.mediafire.com/file/yivdnb5s43h1psu/stages.rar/file

**Comment by K4thos** [comment]
it's already fixed

**Comment by bedlight** [comment]
> it's already fixed

after trying out the latest patch that was released 15 hours ago i can safely say the issue still occurs and has not been fixed

**Comment by K4thos** [comment]
indeed, just tested beerusplanet stage and it has flowers coming in and out. What has been fixed is a regression, with some elements not being rendered at all in 0.98.0/0.98.1, that used to render fine in previous builds. This problem is unrelated to it and also happens in previous engine iterations.

**Comment by bedlight** [comment]
glad you replied: besides the flowers
Wasteland has it's own individual visual bug where if you jump and go forward the stage falls apart, you see blackness
rockyfield has a black square above, while in mugen it hasn't

**Comment by K4thos** [comment]
link is dead. Please reupload by drag and dropping the archive directly to github ticket instead of using external hosting.

**Comment by K4thos** [comment]
I believe it's the same problem as #436, which has more info and working links, so I'm closing this one.
