### ISSUE TITLE
game crashes on startup

### ISSUE THREAD

**Issue by mieucun123** [ikemen-engine/Ikemen-GO#425]
game crashes on startup, it create a blank notepad named Ikemen

**Comment by K4thos** [comment]
1. Try running clean build without adding anything custom (your report is so vague that I don't even know if you are able to run ikemen in the first place)
2. If clean ikemen works for you than try running your problematic game with attached batch file and see if there is anything printed there (exract it in top ikemen directory)
[Ikemen_GO.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7938225/Ikemen_GO.zip)

**Comment by K4thos** [comment]
from lack of reply I assume the problem is already solved
