### ISSUE TITLE
non-ASCII characters are not supported

### ISSUE THREAD

**Issue by WhiteJue** [ikemen-engine/Ikemen-GO#427]
In Mugen1.X, using TrueType font and text in UTF-8 can display non-ASCII characters, but IkemenGo displays nothing.
Is there any way? IkemenGo version 0.98.1

**Comment by samhocevar** [comment]
FYI, this is a limitation of the glfont package which [hardcodes the character range to 32…127](https://github.com/ikemen-engine/glfont/blob/6d774f4f6d0639b7ac7168fb2ba4bb6db47f3ca7/font.go#L58).

**Comment by samhocevar** [comment]
Hi! I made a PR for Ikemen’s glfont fork [here](https://github.com/ikemen-engine/glfont/pull/3).

**Comment by WhiteJue** [comment]
> Hi! I made a PR for Ikemen’s glfont fork [here](https://github.com/ikemen-engine/glfont/pull/3).

Thank you. That's very helpful. I will try your code and rebuild the ikemenGo. That makes localization much easier.
