### ISSUE TITLE
MacOS - screen size startup problem

### ISSUE THREAD

**Issue by erralb** [ikemen-engine/Ikemen-GO#430]
Hi there, I just downloaded and started the 0.98.1 build for the first time, and here is what I'm getting :
<img width="651" alt="Screenshot 2022-02-02 at 18 51 08" src="https://user-images.githubusercontent.com/790992/152209950-6f745566-5202-4e03-bdf5-cd210999177e.png">

Is there a configuration file to modify somewhere or is it a bug ?

I'm running MacOS Monterey with an Intel 16" Macbook Pro

**Comment by Windblade-GR01** [comment]
It's a bug, I'll have it fixed for the next version.

**Comment by K4thos** [comment]
Looks like it's glfw dependency bug. Closing this one since #649 ticket has more info and refers to the same problem.
