### ISSUE TITLE
Mr K4thos  Ask for help Mr K4thos

### ISSUE THREAD

**Issue by kofooxx9876l** [ikemen-engine/Ikemen-GO#433]
.\external\script\start.lua:1402: .\external\script\global.lua:219: 
Invalid argument: over

stack traceback:
	[G]: in function 'isasserted'
	.\external\script\global.lua:219: in function 'loop'
	<string>:1: in function <<string>:0>
	[G]: in function 'game'
	.\external\script\start.lua:1402: in function 'f_game'
	.\external\script\start.lua:1835: in function 'launchFight'
	external/script/default.lua:20: in function <external/script/default.lua:0>
	.\external\script\start.lua:1457: in function 'f'
	external/script/main.lua:3021: in function 'loop'
	external/script/main.lua:3105: in function 'loop'
	external/script/main.lua:4077: in main chunk
	[G]: ?
stack traceback:
	[G]: in function 'game'
	.\external\script\start.lua:1402: in function 'f_game'
	.\external\script\start.lua:1835: in function 'launchFight'
	external/script/default.lua:20: in function <external/script/default.lua:0>
	.\external\script\start.lua:1457: in function 'f'
	external/script/main.lua:3021: in function 'loop'
	external/script/main.lua:3105: in function 'loop'
	external/script/main.lua:4077: in main chunk
	[G]: ?

**Comment by K4thos** [comment]
in order to use latest changes you need to compile executable, not just copy scripts

**Comment by kofooxx9876l** [comment]
Thank you very much for your patience in explaining, I think I seem to understand roughly......
