### ISSUE TITLE
BUG: Stage issues: parser, and Delta Trick with Animations

### ISSUE THREAD

**Issue by LasombraDemon** [ikemen-engine/Ikemen-GO#436]
Some elements are missing, some due to coding of the stage itself (mostly because author declared them as ".3" instead of "0.3" and the MUGEN parser still accepts them), 

and in this specific case I suspect this is an engine malfunction with the famous "delta trick" to attempt 3D adaptation of elements _when combined with scale parameters in animations_.

Tested Cell's Arena (Day), and moved around; trees will flicker in the animations frames that have scaling.

https://mega.nz/#F!sn5yECSZ  key is ksBHQtf6z0DL2YdjScB1qw

**Comment by K4thos** [comment]
fixed by #1836
