### ISSUE TITLE
Infinite Ryu afterimages problem

### ISSUE THREAD

**Issue by Windblade-GR01** [ikemen-engine/Ikemen-GO#437]
[SvK/Infinite Ryu](https://cdn.discordapp.com/attachments/233363722934943744/941499939199004722/Ryu-SvK-RagingRowen_Patch.zip), the after images in his supers don't disappear until you jump while in MUGEN they disappear after the super ends.

https://user-images.githubusercontent.com/11762096/153523171-1faabe2b-6402-4352-92fa-f7115af6bf2f.mp4

**Comment by K4thos** [comment]
fixed by #556
