### ISSUE TITLE
The sound of the entire IKEMEN GO game is interrupted for a moment.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#440]
The sound of the entire game of IKEMEN GO may be momentarily interrupted. (The sound is also interrupted by character selection.)

**Comment by slzero-X** [comment]
Though performance wise it has improved significantly, so audio stuttering is much less frequent, i'll give them that.

**Comment by Kuroteba** [comment]
Neither MUGEN nor IKEMEN had any sound interruptions.
Only IKEMEN GO has sound interruption.

**Comment by samhocevar** [comment]
Hi! I believe this was fixed in the audio engine rewrite (3c3abaf8df09620e345aad36f857c0ec9278bf6e). Audio playback now happens in a completely separate goroutine and cannot be interrupted if e.g. a script is lagging. Can you maybe try again if you have the chance?
