### ISSUE TITLE
BUG: Black Screen on startup

### ISSUE THREAD

**Issue by UserSniper** [ikemen-engine/Ikemen-GO#443]
Hey there!
So I recently got a copy of this software to help develop characters for a game, and it works great on my main PC!
however, it starts with a black screen on my laptop, which has Intel HD Graphics 3000 built in.
i am unsure if it is possible to run the game with this specific graphics chipset, which is why i opened this issue.
Thanks in advance!

**Comment by Windblade-GR01** [comment]
Sounds like a problem with you GPU drivers.
The engine requires OpenGL 2.1 and the Intel HD Graphics 3000 supports up to OpenGL 3.1.

**Comment by K4thos** [comment]
I'm currently playing on HD2000 and it works. Try changing "MSAA" option to false in save/config.json (or delete this file, which will reset everything to default values)

If you're compiling engine yourself make sure that you're using mingw compiler. Alternatives can lead to this error on this integrated GPU:
![unknown](https://user-images.githubusercontent.com/8928195/155481817-09448af3-53c7-41d0-873a-4299ae6ea547.png)

**Comment by UserSniper** [comment]
> I'm currently playing on HD2000 and it works. Try changing "MSAA" option to false in save/config.json (or delete this file, which will reset everything to default values)
> 
> If you're compiling engine yourself make sure that you're using mingw compiler. Alternatives can lead to this error on this integrated GPU: ![unknown](https://user-images.githubusercontent.com/8928195/155481817-09448af3-53c7-41d0-873a-4299ae6ea547.png)

thanks! i'll try that when i use it next.
