### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by UserSniper** [ikemen-engine/Ikemen-GO#446]
hi! so the build of the game i was sent by my team crashes on startup, no matter what i do to try to fix it. (windows 10)
it works perfectly fine on my home PC which runs windows 11, but not at my other one.

here's the error: 
external/script/main.lua:47: attempt to index a non-table object(nil) with key 'decode'
stack traceback:
	external/script/main.lua:47: in main chunk
	[G]: ?

**Comment by Windblade-GR01** [comment]
Seems like a lua script problem. I'll check it.
