### ISSUE TITLE
Bug: TimeElapsed acting wonky

### ISSUE THREAD

**Issue by LasombraDemon** [ikemen-engine/Ikemen-GO#448]
;This bloc if for P2
[State 4101, StayPut]
trigger1 = TimeElapsed = 0
Type = PosSet
x = 1.5 * playerid(getplayerid(2)),const(size.ground.front) + CameraPos X
RedirectID = playerid(getplayerid(2)),ID
[State 4101, StahpIt]
trigger1 = TimeElapsed = 1
Type = ChangeState
RedirectID = playerid(getplayerid(2)),ID
Value = 40
[State 4101, StahpIt]
trigger1 = TimeElapsed = 10
Type = ChangeState
RedirectID = playerid(getplayerid(2)),ID
Value = 50
[State 4101, StahpIt]
trigger1 = TimeElapsed = 11
Type = VelAdd
RedirectID = playerid(getplayerid(2)),ID
x = -3
[State 4101, StahpIt]
trigger1 = TimeElapsed < 60
Type = AssertSpecial
flag = NoInput
RedirectID = playerid(getplayerid(2)),ID

;This bloc if for P1
[State 4101, StayPut]
trigger1 = TimeElapsed = 0
Type = PosSet
x = -1.5 * playerid(getplayerid(1)),const(size.ground.front) + CameraPos X
RedirectID = playerid(getplayerid(1)),ID
[State 4101, StahpIt]
trigger1 = TimeElapsed = 1
Type = ChangeState
RedirectID = playerid(getplayerid(1)),ID
Value = 40
[State 4101, StahpIt]
trigger1 = TimeElapsed = 10
Type = ChangeState
RedirectID = playerid(getplayerid(1)),ID
Value = 50
[State 4101, StahpIt]
trigger1 = TimeElapsed = 11
Type = VelAdd
RedirectID = playerid(getplayerid(1)),ID
x = -3
[State 4101, StahpIt]
trigger1 = TimeElapsed < 60
Type = AssertSpecial
flag = NoInput
RedirectID = playerid(getplayerid(1)),ID

This should trigger at the start of the round, for both players, amirite?
It only triggers for p2. Now, if you change the order of the code and put p1's bloc on top, it will only trigger for p1.
Maybe something's wrong with TimeElapsed?

Wel... If I change the TimeElapsed amount, it triggers!

;Start with all players close up, then jump, then actually start
[State 4101, StayPut]
trigger1 = TimeElapsed = 0
Type = PosSet
x = -1.5 * playerid(getplayerid(1)),const(size.ground.front) + CameraPos X
RedirectID =  playerid(getplayerid(1)), ID
[State 4101, JumpStart]
trigger1 = TimeElapsed = 1
Type = ChangeState
RedirectID =  playerid(getplayerid(1)), ID
Value = 40
[State 4101, Fly]
trigger1 = TimeElapsed = 10
Type = ChangeState
RedirectID =  playerid(getplayerid(1)), ID
Value = 50
[State 4101, GoBack]
trigger1 = TimeElapsed = 11
Type = VelAdd
RedirectID =  playerid(getplayerid(1)), ID
x = -3
[State 4101, NoInput]
trigger1 = TimeElapsed < 60
Type = AssertSpecial
flag = NoInput
RedirectID =  playerid(getplayerid(1)), ID

;Start with all players close up, then jump, then actually start
[State 4101, StayPut]
trigger1 = TimeElapsed = 0
Type = PosSet
x = 1.5 * playerid(getplayerid(2)),const(size.ground.front) + CameraPos X
RedirectID = playerid(getplayerid(2)), ID
[State 4101, JumpStart]
trigger1 = TimeElapsed = 2
Type = ChangeState
RedirectID = playerid(getplayerid(2)), ID
Value = 40
[State 4101, Fly]
trigger1 = TimeElapsed = 11
Type = ChangeState
RedirectID = playerid(getplayerid(2)), ID
Value = 50
[State 4101, GoBack]
trigger1 = TimeElapsed = 12
Type = VelAdd
RedirectID = playerid(getplayerid(2)), ID
x = -3
[State 4101, NoInput]
trigger1 = TimeElapsed < 61
Type = AssertSpecial
flag = NoInput
RedirectID = playerid(getplayerid(2)), ID

https://www.youtube.com/watch?v=1n3mVzGzTwc

**Comment by K4thos** [comment]
not gonna analyze 100+ lines of cns code, sorry, especially without a way to test it. Consider preparing a test case using kfm, showcasing only TimeElapsed problem, without unrelated stuff

**Comment by K4thos** [comment]
I think this ticket can be closed since I assume the reported problem was describing behaviour of changestate stopping further state execution, not timeelaspsed actually having a problem. And the former has been changed here, when used alongside redirectid: d910ac3
