### ISSUE TITLE
Idea: Window SCTRL

### ISSUE THREAD

**Issue by LeanneTM** [ikemen-engine/Ikemen-GO#456]
something that'd be cool to see is a window state controller (working like assertspecial or using "time" maybe?), to not have duplicate sprites with # pixels less.
explods can also benefit from it i guess. could work like the ones used for stages (that aren't added yet at this point). what do you think? :D

**Comment by K4thos** [comment]
a way to crop sprites was already requested here: https://github.com/ikemen-engine/Ikemen-GO/issues/50
