### ISSUE TITLE
Victory portrait not displaying for KOed members.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#457]
https://user-images.githubusercontent.com/77592586/157998183-06ed4f67-e191-4673-876d-0409c93b3b9a.mp4

This is the normal behavior from 98.1

https://user-images.githubusercontent.com/77592586/157998221-c5d7e02d-4aeb-429a-9ad4-63f99edda8f5.mp4

This is from 98.2. The character that gets KOed doesn't has his portrait displayed on victory screen.

Build for testing: https://www.sendspace.com/file/hxnq1d

**Comment by K4thos** [comment]
intended, refer to system.base.def for parameter that controls it.

**Comment by UrsoManso** [comment]
I guess this means the feature wasn't working on previous versions right? Because I had this paramenter since forever but its the first time it actually took effect. Anyway, thanks.
