### ISSUE TITLE
Helpers redirected to the oppoent ignores stateno's that are attached to them

### ISSUE THREAD

**Issue by Amidweiz** [ikemen-engine/Ikemen-GO#458]
I was testing out if redirected helpers with states attached would be able to interact with the opponent, but unfortunately this is not that case as anything I put into the attached statedef that was called by player one in this case does nothing to P2. Even putting redirections in the sctrls in state 1337 does nothing to the P2. This is just a very basic example I was using with KFM

```
[statedef 1337]
type = S
anim = 1337

[State 0, bind to root]
type = bindtoroot
trigger1 = 1

[State 0, DestroySelf]
type = DestroySelf
trigger1 = enemy,stateno = 195

;---------------------------------------------------------------------------
; States that are always executed (use statedef -2)
;--------------------------------------------------------------------------
[statedef -2]
[State 0, Helper]
type = Helper
ownpal = 1
trigger1 = enemy,numhelper(1337) < 1
helpertype = player ;player
name = "no hitboxes"
ID = 1337 
stateno = 1337
pos = 0,0
postype = p1    ;p2,front,back,left,right
facing = 1
redirectid = 57
```

**Comment by slzero-X** [comment]
I don't understand why you would even do this, honestly. What purpose does that exactly serve? Share any thoughts as to how this could be fixed and applied.

**Comment by Amidweiz** [comment]
> I don't understand why you would even do this, honestly. What purpose does that exactly serve? Share any thoughts as to how this could be fixed and applied.

Normally with helpers when you attach a statedef to them, the code that's attached will run as it's own character as the name implies. When redirected to the opponent as it's own copy, it does absolutely nothing. It should inherit the state that p1 has defined or else it would require both characters to be edited with statedef 1337 in this example.

Another thing I did discover even if you call said helper with P1 owning it outright... if you try to do a redirect to P2 the helper ignores states beyond it with this slightly modified example.

```
[statedef 1337]
type = S
anim = 1337

[State 0, bind to target]
type = bindtotarget
trigger1 = 1

[State 0, No colour for you]
type = PalFX
trigger1 = 1
time = -1
color = 0
redirectid = getplayerid(2)
;gets stuck here and P2 never turns B/W nor does the helper respond to the destroyself.

[State 0, DestroySelf]
type = DestroySelf
trigger1 = stateno = 195 ;reminder that this is for testing purposes

;---------------------------------------------------------------------------
; States that are always executed (use statedef -2)
;--------------------------------------------------------------------------
[statedef -2]
[State 0, Helper]
type = Helper
ownpal = 1
trigger1 = numhelper(1337) < 1
helpertype = player ;player
name = "b/w"
ID = 1337 
stateno = 1337
pos = 0,0
postype = p1    ;p2,front,back,left,right
facing = 1
```
If you where wondering what the original purpose of said code example is, it's meant to spawn a helper clone to be able to hit opponents that have no blue hitboxes. This code is intended to go along waruski3's Dio brando "za warudo" super if you need more context.

**Comment by Lazin3ss** [comment]
As far as I understand, RedirectID changes who executes a SCTRL, so, the results of the SCTRL execution would be based on the new executioner. In your case, when redirecting that helper SCTRL from p1 to p2, the new helper is created from p2, with the helper stateno being selected from p2's states.

What you have to do in this case, is to also redirect a selfstate SCTRL with ReadPlayerID from p1 to p2's helper, like this:

```
[statedef -2]

[State 0, Helper]
type = Helper
ownpal = 1
trigger1 = enemy,numhelper(1337) < 1
helpertype = player ;player
name = "no hitboxes"
ID = 1337 
pos = 0,0
postype = p1    ;p2,front,back,left,right
facing = 1
redirectid = 57

[State -2, Change helper 1337 state]
type = selfstate
trigger1 = enemy,numhelper(1337) = 1 && enemy,helper(1337),stateno != 1337
value = 1337
readplayerid = id
redirectid = enemy,helper(1337),id
```

**Comment by K4thos** [comment]
I assume Lazin3ss's reply solves this ticket and there is nothing to fix on engine side. Amidweiz, please test proposed solution. I will close this ticket after few days of no replies.

**Comment by Amidweiz** [comment]
I did test out said code and it does work.
