### ISSUE TITLE
Target does not determine it's own Posistion in it's own AIR File with their localcoord differences.

### ISSUE THREAD

**Issue by cyliamargatroid** [ikemen-engine/Ikemen-GO#459]
Character (LocalCoords = 640,480) does not determine the Target's own Positions in animation file.
Character I have played on Training mode:
**Princess Fine**
Character by Zzyzzyxx, Edited by AJ1Ayrton(Ninja), and edited by Me to have further Compatibility
Localcoord = 640,480
[My edit used for Testing](https://cdn.discordapp.com/attachments/282927929548210177/953701982839910460/FineMC.zip)

**Baby Bonnie Hood**
Character by Jmorphman
Localcoord = 320,240
[Character used for Testing](https://network.mugenguild.com/jmorphman/?characters=bbh)

[Video](https://cdn.discordapp.com/attachments/282927929548210177/953701897603272794/Ikemen_GO_2022-03-16_11-07-22.mp4)

**Comment by K4thos** [comment]
I don't understand this ticket. What do you mean by "own Posistion in it's own AIR File". What sctrl it refers to? Which part of the video shows the problem? I don't see a difference compared to mugen 1.1

**Comment by djonskin** [comment]
On closer inspection of this after I tested those characters, the issue visually from the video I would describe as BB Hood's "juddering" while flying up into the air during the move you see demonstrated. This phenomena is absent from Mugen 1.1, and BB Hood seamlessly flies up there.
