### ISSUE TITLE
Can you recover the code used in the 0.97 version

### ISSUE THREAD

**Issue by VELKA6421** [ikemen-engine/Ikemen-GO#464]
Hello
Recently, 0.98.2 version was updated, so I updated my screen pack accordingly.
However, existing commands are not compatible with the latest version or are not applied at all. Typical examples were Order Select and Score Results.
Order select the instructions can be completely replaced and existing instructions can be applied, and I don't know why but I, too to Work. very basic instructions will also be deleted because, even sprite resultHope in the next version of the improved
Good luck your Ikemen works

**Comment by K4thos** [comment]
no. It works as intended and was implemented after gathering feedback from users on discord. If you preferred previous implementation than you will have to recode it yourself (for example by overwriting `start.f_selectVersus` function with your own variant via external module)

**Comment by VELKA6421** [comment]
I didn't understand it until a few days ago, but now I've fixed it and it's
working well. thx

2022년 3월 21일 (월) 오후 6:58, K4thos ***@***.***>님이 작성:
