### ISSUE TITLE
Strange delay with sounds only on headphones.

### ISSUE THREAD

**Issue by VinVulpis** [ikemen-engine/Ikemen-GO#465]
Like the title says. There seems to be about a half-second delay on the sounds only when I'm using my headphones and I tested it that it's ONLY Ikemen having this issue. Watching videos and tested a couple other games, there's no desync with sounds.

I have noticed there is a very slight delay compared to Mugen with the sounds normally, but it's so strange that it's VERY delayed with headphones (They are bluetooth headphones). I have no idea what would cause this with only Ikemen.

Is thee any way to tweak the sound engine settings? I know Mugen have some stuff you could change with the sampling methods and such and I wanted to for this to see if I could solve it, but I haven't found it.

**Comment by Blac-Dragoon** [comment]
I don't why this happens either. Usually, if I accidentally tug on my headphones, that will happen but only to the music. I'm guessing it's a hardware issue or something else.

**Comment by VinVulpis** [comment]
> 
The issue is that it's ONLY Ikemen, and Mugen to a much lesser degree after more testing. Other games, videos, music have no sound lag.

I have noticed that Minecraft seems to bypass my Equilizer APO program only when my headphones are on and I haven't figured out why. So, it COULD be a weird issue with the APO, it's so weird that it's program specific only when the headphones are on though. When I'm using my speakers, all issues seemingly go away or midigate.

**Comment by samhocevar** [comment]
Hi! I believe this may have been fixed or at least mitigated with the audio engine rewrite (3c3abaf8df09620e345aad36f857c0ec9278bf6e). The audio buffer size and thus audio delay have been significantly reduced. Can you maybe try again with a newer version of the code if you have the chance?
