### ISSUE TITLE
Q takes double damage

### ISSUE THREAD

**Issue by Adnan1091** [ikemen-engine/Ikemen-GO#466]
Q takes double damage in ikemen.Tested on mugen1.1 it works as intended
[SF3 Q (Umihei).zip](https://github.com/ikemen-engine/Ikemen-GO/files/8323761/SF3.Q.Umihei.zip)
.

**Comment by K4thos** [comment]
this compatibility problem with DefenceMulSet has been already solved in 0.98.2
