### ISSUE TITLE
Enhancement: NoDust and NoSlam parameters for AssertSpecial

### ISSUE THREAD

**Issue by LasombraDemon** [ikemen-engine/Ikemen-GO#467]
Being hardcoded, Dust and other char FX can be bothersome and it would be cool for us to be able to disable them via code.

**Comment by K4thos** [comment]
you mean graphic effect made by MakeDust sctrl? That controller is deprecated since winmugen and many characters use Explod for this effect instead, which assertspecial wouldn't affect. If so, I don't think this feature makes sense.

**Comment by LasombraDemon** [comment]
While many chars use Explods for dust (and we cannot solve that universally), I'm referring to this: https://mugenguild.com/forum/topics/removing-makedust-176063.0.html

**Comment by slzero-X** [comment]
What this is implying is likely performance issues, since sometimes characters have very high resolution sprites that can indeed cause slowdown as they are being processed. Unless what you are saying is that they are distracting?
