### ISSUE TITLE
Bring back Final Round Music

### ISSUE THREAD

**Issue by jankespro12** [ikemen-engine/Ikemen-GO#471]
Thanks for adding a feature that on rounds 1, 2 or 3 music changes, but i miss hearing CvS1's Final Round Music, can you bring it back? this time as musicfinal?

**Comment by K4thos** [comment]
there are no plans to bring it back.

**Comment by jankespro12** [comment]
Shame

**Comment by K4thos** [comment]
I've added it after all, so final round music assignment will be available in next build
