### ISSUE TITLE
About  [Rank Info]  for 0.98.2 ? 

### ISSUE THREAD

**Issue by MOGEN-ATON** [ikemen-engine/Ikemen-GO#478]
How to add  [Rank Info]  for 0.98.2 ?  THANKS!!!!!

**Comment by Lazin3ss** [comment]
You're probably looking for this: https://github.com/ikemen-engine/modules/tree/main/external/mods/rank

**Comment by MOGEN-ATON** [comment]
> 您可能正在寻找这个：[https ://github.com/ikemen-engine/modules/tree/main/external/mods/rank](https://github.com/ikemen-engine/modules/tree/main/external/mods/rank)

Thank you so much!!!!!
