### ISSUE TITLE
Add TargetMapSet/TargetMapAdd?

### ISSUE THREAD

**Issue by Kokorz** [ikemen-engine/Ikemen-GO#482]
Adds a way to edit the enemy's maps or make new maps on the enemy. Works the same as MapSet/MapAdd otherwise.

This could be useful for setting custom attack parameters not in HitDef for your custom state, like if I made an attack go into a custom wall-bounce state and I want to manually assign a distance for the velocities of bouncing off the wall, OR adjust how many times I want the character in the hurt-state to bounce off the walls.

If this doesn't work out maybe it can be incorporated into a HitDef parameter that shows up in GetHitVar somehow, as in some sort of custom HitDef parameter that stores any value you want on the enemy character? Something along the lines of custom."name" = _value_.

**Comment by Lazin3ss** [comment]
wouldn't this be the same as using a mapSet  SCTRL with redirectID being `target,id`?

**Comment by Kokorz** [comment]
Quite literally yes, I forgot redirectID was a thing and for that I apologize
