### ISSUE TITLE
Screenpack bugs

### ISSUE THREAD

**Issue by Rurouni-X** [ikemen-engine/Ikemen-GO#488]
1- If you want to omit characters from the victory screen, using the stage as a background but want the characters to appear on the continue screen, it won't be possible. Since the states on the Continue screen are not being read, but instead the states of the victory screen are being used.

2 - I don't know if it's intentional, but if you only display 1 portrait on the versus screen with a team, for the member selection, only the 1st char button (A) will appear.

**Comment by K4thos** [comment]
1. fixed, thanks
2. intentional
