### ISSUE TITLE
musicvictory parameter being interrupted.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#495]
https://user-images.githubusercontent.com/77592586/165082188-551c24ec-d728-4c7d-8ece-4602174e950c.mp4

https://user-images.githubusercontent.com/77592586/165082196-6167fd84-2d9b-4306-b7c0-09c97ece4263.mp4

When I finish the match with supers the musicvictory effect is cut right way and only kicks in again after the super's sound effect.

[Ryu.zip](https://github.com/ikemen-engine/Ikemen-GO/files/8554162/Ryu.zip)

**Comment by K4thos** [comment]
it's a behaviour intentional by character's author (you can see it by assigning any music to stage, not necessarily victory one). Character uses nomusic assertspecial to pause any music during super finish. It's not a bug and there is nothing we can do on engine side about it.
