### ISSUE TITLE
Explods do not to display properly in some characters.

### ISSUE THREAD

**Issue by bedlight** [ikemen-engine/Ikemen-GO#508]
Greetings, ikemen seems to fail to render a number of effects involving these two characters made by completely different people
when activating super for example with both characters input being
D,F,a+b the effect fails to render into ikemen properly, in comparison to mugen where there it renders properly without any issues

https://www.mediafire.com/file/j99j918by6lmcyo/Sonic_Intro_fix.rar/file
https://www.mediafire.com/file/oq2bg32tys60f73/Shadow+(Fixed).rar/file

i would also like to point out that when activating tornado special with the character shadow with the input: DBc, the tornado also fails to render properly into ikemen, hopefully this issue can be fixed as soon as possible :)

**Comment by K4thos** [comment]
I beleve it's the same issue as #288, so closing this one

**Comment by K4thos** [comment]
not solved yet, the ticket is closed for maintenance reasons - duplicate report
