### ISSUE TITLE
Can't build the latest.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#509]
I ran build.cmd, but nothing is created in the bin folder.

**Comment by slzero-X** [comment]
Have you installed Go 1.18?

**Comment by Kuroteba** [comment]
Go version is 1.18.1.

**Comment by slzero-X** [comment]
I got the same result, so its obviously an issue in the source code.
If people are still able to build it, they are obviously using a modified version of golang.

**Comment by Lazin3ss** [comment]
It should work now, try again with the new changes.

**Comment by Kuroteba** [comment]
I was able to build with what I published today.
