### ISSUE TITLE
Instructions for Manjaro/ArcoLinux Users.

### ISSUE THREAD

**Issue by cyliamargatroid** [ikemen-engine/Ikemen-GO#51]
With an Arch based system, it can be compiled executing the following commands on a terminal:

Install golang:
```
sudo pacman -S go
```
Install git:
```
sudo pacman -S git
```
Install mesa (If not avalable on other Arch-Based systems):
```
sudo pacman -S mesa
```
Install OpenAL dependencies:
```
sudo pacman -S openal
```
If OpenAL is at ver.1.20, use this command to downgrade.
(Thanks to @madmaruo 's Advice)
```
sudo pacman -U https://archive.archlinux.org/packages/o/openal/openal-1.19.1-2-x86_64.pkg.tar.xz
```
Update glibc:
```
sudo pacman -S glibc lib32-glibc
```
Tested on:
Manjaro - Works!
Arcolinux - Works!

Issues:
The Build needs `script` folder...

**Comment by cyliamargatroid** [comment]
These lines works on Arch-Based system.

**Comment by cyliamargatroid** [comment]
On the Suprising note, Mesa and Xorg already has dev on Manjaro.

**Comment by cyliamargatroid** [comment]
And don't forget to add these lines to Make permission applied
```
chmod +x get.sh
chmod +x build.sh

**Comment by Windblade-GR01** [comment]
Thanks for the info!
I'll add to the linux build instructions.

**Comment by cyliamargatroid** [comment]
No Problem
