### ISSUE TITLE
unlock chars clearing the arcade mode with specific char?

### ISSUE THREAD

**Issue by JinDashjv** [ikemen-engine/Ikemen-GO#510]
Is it possible to determine that a char is unlocked only when arcade mode is finished with a specific char?
For example, unlock Scorpion clearing arcade mode with Sub-zero

**Comment by slzero-X** [comment]
I think it is, since lua has many features that you can use. Take a look at the wiki.
I am certain its definitely doable, since we can literally create new game modes with lua.
