### ISSUE TITLE
[Feature] Detect when a PlaySnd/PlayBgm end

### ISSUE THREAD

**Issue by Amidweiz** [ikemen-engine/Ikemen-GO#518]
One issue that I have came across when trying to include dynamic music involving an attached character is that there is no way currently to detect when a sound or a song ends. Here is an example zss snippet that I am currently working on.

```let round1 = (RoundNo = 1) #I forget if you can do this but this is meant to be an example anyways
let intro = 1
if $round1 && $intro = 1
{
	PlayBgm{bgm: "intro.mp3"; loop: 0;}
	#I have no way to detect when said into has stopped
}
if $round1 = 1 && $intro = 0
{
	PlayBgm{bgm: "round1Path1.mp3"; loop: $round1;}
	#Nor here as well
}
if $round1 = 0 && $intro = 1
{
	PlayBgm{bgm: "round2Path1.mp3"; loop: 1;}
}
if $round1 = 0
{
	PlayBgm{bgm: "round2Path2.mp3"; loop: 1;}
}
```
With my current example I cannot detect when the intro is ended nor if round 1's theme has played fully or not to allow round two to dynamically adjust the music. This also can't be solved with the current [bgmusicalt](https://github.com/ikemen-engine/Ikemen-GO/wiki/Stage-features/#bgmusicalt) that is included within a stage as I am looking for a smoother transition between music than what currently allotted by the stage def.

An implementation that could work out is a ID for a PlaySnd or PlayBgm state controller that you could detect for.

 ```let round1 = (RoundNo = 1) #I forget if you can do this but this is meant to be an example anyways
let intro = 1
let path1 = 0
if $round1 && $intro = 1
{
	PlayBgm{bgm: "intro.mp3"; loop: 0; ID: 1;}
	if BgmID(1) = 0
	{
		let intro = 0
	}
}
if $round1 = 1 && $intro = 0
{
	PlayBgm{bgm: "round1Path1.mp3"; loop: $round1; ID: 2;}
	if BgmID(2) = 0
	{
		let path1 = 1
	}
}
if $round1 = 0 && $path1 = 1
{
	PlayBgm{bgm: "round2Path1.mp3"; loop: 1;}
}
if $round1 = 0
{
	PlayBgm{bgm: "round2Path2.mp3"; loop: 1;}
}
```

**Comment by Lazin3ss** [comment]
I was thinking about adding some triggers to keep track of BGM that's currently playing (a trigger to return track position and duration in samples seems useful for this). That and a fade/crossfade effect could allow for dynamic music changes in matches. If you have suggestions to name the triggers, please let me know.

**Comment by Amidweiz** [comment]
It's been a little bit since I looked at this but considering what elecbyte put for audio triggers maybe
`bgmposition` for said current track position and `bgmlength` for the duration of the song. I don't thing it needs to be more complicated than that IMO.

**Comment by Lazin3ss** [comment]
Thank you, I just recently implemented the triggers for bgm tracking in an experimental branch in my fork, and also added a new parameter for PlayBGM, which lets you play a track starting from a chosen sample point. Gonna take in account your IDs idea too, but for PlaySnd.
