### ISSUE TITLE
[FNT v3] Suggestion

### ISSUE THREAD

**Issue by Rurouni-X** [ikemen-engine/Ikemen-GO#522]
I don't know the logic behind the programming, so I'm going to suggest this from an end user's point of view.

One thing that is discussed and lacking for users who are not natives of the English language is the impossibility of using fonts (especially custom ones) that have characters from their respective languages such as Romantic languages (eg Portuguese, Spanish and French).
So I wonder if it wouldn't be possible to combine the Font V2 structure with the Glyphs to make something new.

```
[FNT v3]
; FNT v3 version number.  Don't change this.
fntversion = 3,00
; Name of this font.
name = "Arcade"

[Def]
; This is a bitmap font
Type = bitmap
; Bank numbers are mapped to palette numbers (0, bank).
BankType = palette
; Size of font: width, height.  Width is used for spaces.
Size = 36,36
; Spacing between font glyphs: width, height.
Spacing = -12,4
; Drawing offset: x, y.
Offset = -2,3
; Filename of the sff containing the glyphs.  Use sff v2 only.
File = arcade.sff

[Glyphs]
...*
À = 0,127
Á = 0,128
Â = 0,129
Ã = 0,130
Ä = 0,131
Å = 0,132
Æ = 0,133
Ç = 0,134

 * 0,33 up to 0,127 would be used for the glyphs already used in v2 fonts.
```

**Comment by samhocevar** [comment]
Fonts with non-ASCII characters already work pretty well. You need to use the decimal Unicode codepoint for the character. For instance, the Wikipedia article for [Ç](https://en.wikipedia.org/wiki/%C3%87#Computer) says the codepoint is 199, so you’ll just have to store the sprite for `Ç` in `0,199`.

It is possible that some Ikemen Go features do not work with non-ASCII characters; I suggest posting specific bug reports if this happens to you.

**Comment by Rurouni-X** [comment]
That's great. There was no information about this, so I thought a new font type would be needed. But I've already started checking and it really works. If I find bugs, I will report them.
Thank you, Sam.
