### ISSUE TITLE
[Enhancement/Feature Request] "Override Working Directory" Command Argument

### ISSUE THREAD

**Issue by SuperFromND** [ikemen-engine/Ikemen-GO#528]
Right now, whenever IKEMEN is executed, it will use the current working directory (that is to say, the directory IKEMEN's executable is located in) as a sort of "master" directory from which IKEMEN uses as a base for finding relative files.  So for example, if you have a standard install in `C:/Example/Ikemen_Go.exe`, when launched, the executable will check for the various files and data folders (`chars`, `stages`, etc.) in the `C:/Example/` directory.  This is how both MUGEN and IKEMEN's behaved since day 1, and for 99.9% of use cases (especially given its intended nature as a game engine) there hasn't been much reason to want to change this.

So naturally, I run into one of those 0.1% cases.  [The details are rather long-winded (you can read them by clicking this text)](https://retropie.org.uk/forum/post/277432), but in short: I'm trying to figure out a way to get IKEMEN GO to conform to the directory layout of a [RetroPie](https://retropie.org.uk/) installation (which stores game data and executables in completely separte directories) while *also* being capable of launching multiple fullgames, without duplicating the executable or relying on symbolic links (Linux-ese for shortcuts). I've just-about figured out a way to do it, but in order for it to work IKEMEN needs to be able to have its working directory be something *other* than where the executable is located.

Hence, I propose the addition of a new command line argument- I haven't decided on a good name for it, maybe `-data_dir` or `-redirect` or just `-dir`- that would set IKEMEN's working directory to the directory given after the argument, after which it would do all the usual IKEMEN stuff (reading the config, parsing the motif, loading characters and stages, the works). If the argument isn't specified, IKEMEN would just use the working directory like usual.

By adding this, you could have a folder containing a fullgame's data (sans executable) located *anywhere*, and be able to use the argument to launch it using an IKEMEN executable also located *anywhere*.  This means you could have one single IKEMEN executable, and by changing the argument's value, change which fullgame IKEMEN runs regardless of where they are located.

**Comment by samhocevar** [comment]
> Right now, whenever IKEMEN is executed, it will use the current working directory (that is to say, the directory IKEMEN's executable is located in) 

This is not really true. The current directory is the current directory, regardless of where the executable is located. If you `cd C:/MyGame` and then run `C:/Example/Ikemen_GO.exe` the executable will check for the data in `C:/MyGame`.
