### ISSUE TITLE
Downtracking behavior is different from MUGEN.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#532]
In IKEMEN GO, the attack after Donald's down follow-up is not hitting.

https://user-images.githubusercontent.com/99640380/169691023-5bb10c69-4ba7-4419-a2fc-e405c839b468.mp4

**Comment by djonskin** [comment]
https://github.com/ikemen-engine/Ikemen-GO/pull/534
It seems like NeatUnsou's commit fixed enough of this Downed YVel issue. Confirmed it myself on that Donald.

**Comment by K4thos** [comment]
thanks for confirming that the issue is fixed
