### ISSUE TITLE
Lua script bug breaks -storyboard flag

### ISSUE THREAD

**Issue by samhocevar** [ikemen-engine/Ikemen-GO#537]
Handling of the `-storyboard` flag is done in `main.lua`, line 2248. The storyboard code in `storyboard.lua`, line 51, calls `main.f_playBGM`. However `main.f_playBGM` is only defined in `main.lua`, line 4032.

I’m not sure how to fix this. Moving `f_playBGM` higher in the file seems the safest thing to do, what do you think?

**Comment by K4thos-edu** [comment]
yes, the function can be just moved up.

**Comment by K4thos** [comment]
yes, the function can be just moved up
