### ISSUE TITLE
Feature suggestion for selection screen

### ISSUE THREAD

**Issue by Rurouni-X** [ikemen-engine/Ikemen-GO#538]
**- Skip slot**

A great new feature would be to be able to skip a cell/slot. Currently we can do this by adding a hyphen (some public screenpacks end up using the "do not modify" line), but this ends up requiring a specific select for certain screenpacks. Often the "select.def" ends up being very messy, and this new feature would move the work from "select" to system.def leaving everything cleaner and more organized. The syntax in action:

`cell.<col>.<row>.skip = (0: default), (1: skips*)`

*if "showemptyboxes = 1", the cell doesn't show up;
"moveoveremptyboxes = 1", it's skipped anyway.

An example of these features using the AX2 screenpack.

![preview](https://user-images.githubusercontent.com/68881657/170518046-f66d489f-ca1e-4bd5-9ade-adcc4b8d2e3a.png)

**Comment by GaryCXJk** [comment]
Okay, so, here's the issue. These suggestions can be implemented, however, they won't appear for every screenpack, or at least those that modify the Lua scripts, since the features outlined actually can be implemented through these scripts.
