### ISSUE TITLE
Groove Bars and Ikemen?

### ISSUE THREAD

**Issue by flatsixqt** [ikemen-engine/Ikemen-GO#539]
It seems whatever character I use that has a groove bar system like from warusaki3 the gauge visual does not show up however the gameplay of the groove is still there. Tried playing with the helper/explod max limits in settings but nothing. 

Is there something I have to change in the cns files of the characters?

using 98.2

warusaki's character I got from here https://www.mediafire.com/folder/j8srioxidnmi6/CVS

**Comment by K4thos** [comment]
Can't reproduce
![ikemen001](https://user-images.githubusercontent.com/8928195/171512846-f1b7b73a-294b-46a8-8dbc-0631c04e67eb.png)
![ikemen002](https://user-images.githubusercontent.com/8928195/171512859-6aef2fe7-6e69-459b-a7e3-38c996b67296.png)

**Comment by flatsixqt** [comment]
ok so I tested it again and found that it works in 640 x 480 res just fine however in 1280x720 which is what I had it too it was not working (must have been way off screen somewhere). 

I'm not sure if that's normal behaviour since I haven't had original mugen since forever but ill try to edit the cns files.

**Comment by K4thos** [comment]
it's a normal mugen behaviour. Here is screen made on mugen 1.1:
![mugen014](https://user-images.githubusercontent.com/8928195/171758503-3e2ea8fa-1cb2-46e4-bb9d-e0fe17933633.png)
