### ISSUE TITLE
Stage Audioloop crashes IKEMEN.

### ISSUE THREAD

**Issue by cyliamargatroid** [ikemen-engine/Ikemen-GO#54]
Playing this stage at (IKEMEN)/stage/runaway-train-3.def (Linux/Mac Version obviously supports stage filenames with lowercase letter)
This line includes this code
```
[Music]
bgmusic = sound/CPS2 Original Stages-Runaway Train Final Arrangement.mp3
bgvolume = 255
bgmloopstart= 3181294
bgmloopend=6205268
```
you recieve this while running terminal (Copied this line from MATE-Terminal)
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7915a4]

goroutine 19 [running]:
main.(*System).soundWrite(0xcac4e0)
	/home/cylia-margatroid/Ikemen_GO/src/system.go:438 +0x194
created by main.(*System).audioOpen
	/home/cylia-margatroid/Ikemen_GO/src/system.go:405 +0xd6

**Comment by Windblade-GR01** [comment]
It seems that this bug is Linux only. On Windows and a MacOS VM is not present.
I'll set up a Linux Mint VM and do more tests.

**Comment by cyliamargatroid** [comment]
yeah okay. Why not try Manjaro VM?

**Comment by K4thos** [comment]
can't reproduce on latest ubuntu and manjaro
