### ISSUE TITLE
BUG: Screenbound and RedirectID

### ISSUE THREAD

**Issue by LasombraDemon** [ikemen-engine/Ikemen-GO#540]
RedirectID + Screenbound will make only the MoveCamera part of the SCTRL work, and *not* the Screenbound itself.

**Comment by K4thos** [comment]
quoting wiki

> The following SCTLs does not work for RedirectID because they are only active in the frame they are executed:
    PosFreeze
    Trans
    Part of AssertSpecial (ScreenBound, PlayerPush, AngleDraw)

so not a bug

**Comment by LasombraDemon** [comment]
Then the MoveCamera parameter should not work? Screenbound doesn't work but MoveCamera does.

Still, I'd like a way to have them both work via RedirectID. xD
