### ISSUE TITLE
Could you provide the link to the original ikemen engine?

### ISSUE THREAD

**Issue by whiteeat** [ikemen-engine/Ikemen-GO#542]
Like the title, I'm not a GO guy, and I hope to get the source code of original Ikemen engine. But I google it and can't find it. Could you help? Thanks for considering my request!

**Comment by K4thos** [comment]
https://osdn.net/users/supersuehiro/pf/ikemen/wiki/FrontPage

**Comment by whiteeat** [comment]
> https://osdn.net/users/supersuehiro/pf/ikemen/wiki/FrontPage

Thanks so much!
