### ISSUE TITLE
BUG: Fall noise when victory screen loads

### ISSUE THREAD

**Issue by djonskin** [ikemen-engine/Ikemen-GO#548]
This is easily reproducible in the latest commits through even KFM or any character.

Have someone win a match by timeout (or cheat it). The losing character falls down in the background of the VICTORY screen- the ground hit noise can be heard from the immediate loser at any player number, but only for one losing character. It might be some odd Air changestate that's taking place, but I'm unsure on that lead.

**Comment by K4thos** [comment]
for some reason there is a code that always sets life to 0 at the end of match for team side that has been defeated, which leads to hardcoded selfstate 5030, even if the match ended in time over. Will do some tests before removing it.
