### ISSUE TITLE
Add Examples of Lua Unlocking coding for Story Arcs in the Wiki

### ISSUE THREAD

**Issue by JTDaddy17** [ikemen-engine/Ikemen-GO#549]
Just to let you know, the select.def file in the Ikemen Go data folder has a link to show examples of unlocking lua code for story mode arcs, but the link is nonexistent. For total newbies, some examples of unlocking code for story arcs in the Wiki would be greatly appreciated.

**Comment by K4thos** [comment]
https://github.com/ikemen-engine/Ikemen-GO/wiki/Miscellaneous-info#content-unlocking
