### ISSUE TITLE
Some observations of function call inconsistencies in ZSS

### ISSUE THREAD

**Issue by Lazin3ss** [ikemen-engine/Ikemen-GO#551]
Running this simple code as a commonStates file:
```cs
[Function CheckTransition(p)]
if $p = 2 {
	printToConsole{text: "%v"; params: $p; RedirectID: GetPlayerID($p);}
	displayToClipboard{text: "%v"; params: $p; RedirectID: GetPlayerID($p);}
}

if TimeElapsed > 1 {
	selfState{
		value: 40;
		ctrl: 0;
		ReadPlayerID: ID;
		RedirectID: GetPlayerID($p);
	}
}

[Statedef -2]

if playerno = 1 {
	call CheckTransition(1);
	call CheckTransition(2);
	call CheckTransition(3);
	call CheckTransition(4);
	call CheckTransition(5);
	call CheckTransition(6);
	call CheckTransition(7);
	call CheckTransition(8);
}
```
And running Ikemen GO from command-line with these parameters:
`Ikemen_GO kfmZ kfmZ kfmZ kfmZ kfmZ kfmZ kfmZ kfmZ -tmode1 1 -tmode2 1 -s stages/stage1.def`
I got these results:
- Only player 1 gets into state 40, all the other players stay in state 0
- `printToConsole` stops printing after `roundstate` is in 2, but `displayToClipboard` works anyway
- If you change `TimeElapsed` to another trigger like `Time`, `printToConsole` starts working again. The same if you comment all of `selfState` SCTRL definition.
- If you add this trigger: `playerID(GetPlayerID($p)),stateno != 40` to TimeElapsed conditional (with an && operator), only 4 players (first 2 members of both teams) go into state 40.

**Comment by LasombraDemon** [comment]
Same thing happens if you add this to a negative state:

if TimeElapsed > 1
{
    selfState{
        value: 0;
        ctrl: 0;
        RedirectID:playerid(getplayerid(1)),ID;
    }	
	    selfState{
        value: 0;
        ctrl: 0;
        RedirectID:playerid(getplayerid(2)),ID;
    }	
	    selfState{
        value: 0;
        ctrl: 0;
        RedirectID:playerid(getplayerid(3)),ID;
    }	
	    selfState{
        value: 0;
        ctrl: 0;
        RedirectID:playerid(getplayerid(4)),ID;
    }	
	    selfState{
        value: 0;
        ctrl: 0;
        RedirectID:playerid(getplayerid(5)),ID;
    }	
	    selfState{
        value: 0;
        ctrl: 0;
        RedirectID:playerid(getplayerid(6)),ID;
    }	
	    selfState{
        value: 0;
        ctrl: 0;
        RedirectID:playerid(getplayerid(7)),ID;
    }	
	    selfState{
        value: 0;
        ctrl: 0;
        RedirectID:playerid(getplayerid(8)),ID;
    }	
}


Only first instruction (Player 1) is run. Happens with ChangeState too. Will *not* break with VelSet or other SCTRLs.

**Comment by K4thos** [comment]
ChangeState and SelftState breaking current state execution (including negative ones) is expected mugen behaviour.

I've changed it in the above linked commit so that getplayerid being different than id should now stop this behaviour. But even with this change you would need to change lines order since in `call CheckTransition(1)` case RedirectID is the same as ID, so further execution will be stopped. It can't be changed due to backward compatibility with mugen.
