### ISSUE TITLE
[Feature] Lock characters and stages to modes.

### ISSUE THREAD

**Issue by jenngra505** [ikemen-engine/Ikemen-GO#555]
This feature would allow for the ability to have all characters unlocked in Online and Training but be locked in the singleplayer campaign. Or a more ambitious idea would be to make a set of complex stages with alternate rulesets (Like Platform Fighter or Basketball) and have them be their own mode.

**Comment by K4thos** [comment]
example 3: https://github.com/ikemen-engine/Ikemen-GO/wiki/Miscellaneous-info#content-unlocking
implementing new modes is also already possible (external modules)
