### ISSUE TITLE
Couple of issues with ReversalDef

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#557]
Found a few problems with this sctrl compared to how it works in Mugen.

The first one is easy to explain: if you use a ReversalDef without P2stateno, such as for autoguard moves or parrying, a player caught by it will become your target indefinitely. Or until you hit him again anyway. In Mugen the target is dropped if his Movetype is not H, like with HitDef.

The second one is more serious but also harder to explain. In Mugen, if a Hitdef clashes with a ReversalDef, the Hitdef will immediately be nullified. Like the ReversalDef is processed first. In Ikemen Go the Hitdef may keep going and be able to hit other players.

This can lead to some funny behaviour and also breaks my Parry code, which uses a ReversalDef in a separate helper. What's also interesting here is that the exchange between a ReversalDef and a HitDef will have different results according to player order. To use the Parry example again, the player that gets parried will receive a MoveHit or MoveReversed flag depending on which team side he is.

I'm attaching a video with a small example. In Mugen, only Geese's attack connects in this exchange.

https://user-images.githubusercontent.com/107247004/173037796-19abf1de-b6f4-43d6-86bc-673827863d60.mp4

**Comment by NeatUnsou** [comment]
Oh, that's just what I was working on fixing.
I think it's probably fixed.
#556 #553

**Comment by potsmugen** [comment]
Talk about perfect timing, heh. I checked it out and it looks like that specific Geese case and the Target handling have been fixed.

However it looks like ReversalDef (without p2stateno) still does not have more priority than HitDef. Keeping Geese as the example, if you parry (as in SF3 parry) the opponent's attack you can see that Geese is hit into state 5000 just before entering the parry state. In Mugen this does not happen because his helper's ReversalDef shields him from HitDefs with the corresponding attributes.

Oddly enough, in Simul, the helper's ReversalDef will shield player 3 but not player 1.

The character in question (many characters have borrowed this Parry code):
https://www.mediafire.com/file/khly2kksnixbnfn/geese_pots.zip/file

I'm attaching another video showing this case. In Mugen no character gets hit.

https://user-images.githubusercontent.com/107247004/173202980-75ce4ecc-b3c9-4fea-b72e-ae68e55b9030.mp4

**Comment by NeatUnsou** [comment]
It seemed to be a priority issue with the processing during the attack.
I hope this fixes it.
#563

**Comment by potsmugen** [comment]
Working perfectly. Thanks.

**Comment by potsmugen** [comment]
Since this was fixed a while ago, maybe you could create a new report for it. And ideally you'd provide a character that already has the system working (just upload KFM).
