### ISSUE TITLE
After every fight the game crashes

### ISSUE THREAD

**Issue by MyztikReaper** [ikemen-engine/Ikemen-GO#568]
The error: 
.\external\script\start.lua:1401: external/script/main.lua:1093: attempt to index a non-table object(nil) with key 'H'
stack traceback:
	external/script/main.lua:1093: in function 'f_textRender'
	.\external\script\start.lua:3323: in function 'f_victory'
	.\external\script\global.lua:233: in function 'loop'
	<string>:1: in function <<string>:0>
	[G]: in function 'game'
	.\external\script\start.lua:1401: in function 'f_game'
	.\external\script\start.lua:1834: in function 'launchFight'
	external/script/default.lua:20: in function <external/script/default.lua:0>
	.\external\script\start.lua:1456: in function 'f'
	external/script/main.lua:3037: in function 'loop'
	external/script/main.lua:3121: in function 'loop'
	external/script/main.lua:4093: in main chunk
	[G]: ?
stack traceback:
	[G]: in function 'game'
	.\external\script\start.lua:1401: in function 'f_game'
	.\external\script\start.lua:1834: in function 'launchFight'
	external/script/default.lua:20: in function <external/script/default.lua:0>
	.\external\script\start.lua:1456: in function 'f'
	external/script/main.lua:3037: in function 'loop'
	external/script/main.lua:3121: in function 'loop'
	external/script/main.lua:4093: in main chunk
	[G]: ?

**Comment by EgyLynx** [comment]
(Me get that:
.\external\script\start.lua:1401: chars/ANGELI/01.def:
Basic.cns
open Basic.cns: The system cannot find the file specified.
stack traceback:
	[G]: in function 'game'
	.\external\script\start.lua:1401: in function 'f_game'
	.\external\script\start.lua:1834: in function 'launchFight'
	external/script/default.lua:2: in function <external/script/default.lua:0>
	.\external\script\start.lua:1456: in function 'f'
	external/script/main.lua:3037: in function 'loop'
	external/script/main.lua:3121: in function 'loop'
	external/script/main.lua:4093: in main chunk
	[G]: ?)
And that worked at Mugen :::!
But others work at clean crystall, sound like youre try at different version/programs victory screen.?
Areyou try move at now files(somewhere else,), reunload at here at full pack (with exe) and unpack it
and give back person by person and stage by stage? (if you have any)

**Comment by K4thos** [comment]
MyztikReaper, posting error is not enough to reproduce it. You need to upload character that caused the crash.

EgyLynx, error says exactly what is wrong. 3rd line. I assume you're copying character from some full game and the file is outside character directory. I'm pretty sure the same problem would happen if you try to do the same on clean mugen.

**Comment by EgyLynx** [comment]
MyztikReaper, posting error is not enough to reproduce it. You need to upload character that caused the crash. If it happens for all characters than upload whole game without characters and stages folders.

(? Erf? I haven´t get that error, although i have some about some hunders person and over but ikemen just read only 1414 stages, just these evangelion persons but not THAT!)

EgyLynx, error says exactly what is wrong. 3rd line. I assume you're copying character from some full game and the file is outside character directory. I'm pretty sure the same problem would happen if you try to do the same on clean mugen.
( wELL, I GET THESE WORK MY MUGEN 1.1, bUT NOT  in game , just standalone...(?!) )
Actually, it at many *.def at one ... pre person... :/erf...

**Comment by K4thos** [comment]
if it says the file is not there than the file is not there. Not an engine problem.

**Comment by MyztikReaper** [comment]
Actually, it doesnt seem to be a problem with the characters or the stages, i tested, using a Z2i character and leaving only Training Room HD.

**Comment by MyztikReaper** [comment]
[exe + other stuff.zip](https://github.com/ikemen-engine/Ikemen-GO/files/8931823/exe.%2B.other.stuff.zip)
[important stuff.zip](https://github.com/ikemen-engine/Ikemen-GO/files/8931824/important.stuff.zip)
heres the game

**Comment by K4thos** [comment]
@MyztikReaper, it's caused by your local edit to main.lua. In line 1093 you have
`_def[symbol] = fontGetTextWidth(main.font[data.font .. data.height], symbol, data.bank)`
it should be
`font_def[symbol] = fontGetTextWidth(main.font[data.font .. data.height], symbol, data.bank)`
not an engine problem
