### ISSUE TITLE
Character not able to jump over.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#570]
https://user-images.githubusercontent.com/77592586/174342429-3f151604-2868-4d06-be53-206e4413f745.mp4

Mugen 1.1

https://user-images.githubusercontent.com/77592586/174342794-7a38c453-422c-4ec7-83db-110926afc210.mp4

Ikemen GO

[chars.zip](https://github.com/ikemen-engine/Ikemen-GO/files/8929366/chars.zip)

**Comment by EgyLynx** [comment]
Well, All stages aren´t at super jump... youre should try same stage both...

**Comment by UrsoManso** [comment]
Same result.

**Comment by djonskin** [comment]
By the way they're normally supposed to snap to the other side, it maybe looks like a potential Width sctrl thing.

**Comment by UrsoManso** [comment]
I had issues with Width sctrl before so that could be case.

**Comment by NeatUnsou** [comment]
I change the resolution in 1.1, I can no longer jump over it.
I do not know why this happens.

https://user-images.githubusercontent.com/47813229/174436373-f1df8f14-5d1b-4a89-8002-14c4cf8ff8d3.mp4

**Comment by potsmugen** [comment]
For what it's worth, I tried them in Mugen 1.1 and it never works for me regardless of resolution.

The cause seems to be Chang's "draw.offset = 0,3" constant, which pulls the Clsn2 down just enough to push against Kula's.

**Comment by UrsoManso** [comment]
Reducing the offset fixed the issue, but it still bugs me that it didn't worked for you regardless of resolution on 1.1.
