### ISSUE TITLE
Cell skip bug

### ISSUE THREAD

**Issue by Rurouni-X** [ikemen-engine/Ikemen-GO#571]
Regardless of whether the feature is being used or not, if I try to go to the second row in the select screen the game crashes no matter if the slot is empty or has a char.

```
.\external\script\start.lua:917: cannot perform add operation between nil and number
stack traceback:
	.\external\script\start.lua:917: in function 'f_cellMovement'
	.\external\script\start.lua:2558: in function 'f_selectMenu'
	.\external\script\start.lua:2071: in function 'f_selectScreen'
	.\external\script\start.lua:1416: in function 'f'
	external/script/main.lua:3096: in function 'loop'
	external/script/main.lua:3180: in function 'loop'
	external/script/main.lua:4147: in main chunk
	[G]: ?
```

https://user-images.githubusercontent.com/68881657/174455900-3b7677d8-fa47-4b81-afd2-ce85711ea1c8.mp4

You can also see that the 2nd Ryu's slot on the 1st row is being skipped for some reason.

Here's the code:
```
;1ST ROW
cell.1.1.skip = 1
cell.3.1.skip = 1
cell.5.1.skip = 1

;4TH ROW
cell.1.4.skip = 1
cell.5.4.skip = 1
```

Although the cells' bg.sprs are not being rendered, it is still possible to browse them and even select the chars that are in the "skipped" cells:

https://user-images.githubusercontent.com/68881657/174456096-8bbf4f69-0b4d-4ade-8702-faebe363df4c.mp4

I'm using moveoveremptyboxes = 0  

Here you can check the system and select.def files:
[mugen1.zip](https://github.com/ikemen-engine/Ikemen-GO/files/8934309/mugen1.zip)

**Comment by K4thos** [comment]
@GaryCXJk
