### ISSUE TITLE
Explod positioning

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#581]
If postype is ommitted when creating an explod, it will not behave as PosType = p1 but be created from what appears to be the center of the stage.

Also I've seen this one mentioned before but I can't find it here so I'll add it to the post. The Random parameter works differently from Mugen. In Mugen, setting "Random = 100, 0" makes the Explod appear anywhere from -50 pixels to +50 pixels of the defined position. In Ikemen Go it appears between -100 and +100 pixels.

**Comment by K4thos** [comment]
fixed problem with random. As for PosType positionining I can't see a problem. Tested using this code pasted to kfm's -3:
`[State 191, Wood 2]
type = Explod
trigger1 = AnimElemTime(7) = 1
anim = 192
pos = 60, -70
velocity = 2, -4
accel = 0, .32
removetime = 35`

if kfm mugenversion < 1.1 it defaults to p1. If 1.1 it defaults center. I've got the same result in mugen 1.1.

**Comment by potsmugen** [comment]
My bad. I hadn't realized Elecbyte changed the default Postype to none if Mugenversion >= 1.1.

Thanks for the random fix.
