### ISSUE TITLE
FallEnvshake and GetHitVar(fall.envshake.time)

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#583]
Very minor issue, but in Mugen the "fall.envshake.*" Hitdef parameters only shake the screen once per fall. In Ikemen they are applied in state 5100 and then again in state 5110. The Mugen docs offer the explanation in the FallEnvshake Sctrl:

> This controller is effective only if GetHitVar(fall.envshake.time) is not zero, and it sets GetHitVar(fall.envshake.time) to zero after being executed.

 Ikemen Go does not do the latter.

**Comment by K4thos** [comment]
fixed, thanks
