### ISSUE TITLE
ScreenshotFolder not working

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#585]
I've created a folder for screenshots and add it under the "ScreenshoFolder" line in config.json but it still saves in Ikemen GO's main folder. This is what it looks like: 

"ScreenshotFolder": "screenshots",

Also worth noting that if I change Ikemen GO's folder name to anything else, when I take a screenshot it will create another Ikemen GO folder with its default name and save it there.

**Comment by K4thos** [comment]
f12, same as mugen
