### ISSUE TITLE
Stage inconsistencies

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#588]
1. This is not accurate but may be a good way to explain it: it looks as if "boundhigh" is applied after the zoom in Mugen 1.1, but before the zoom in Ikemen Go. So a stage with boundhigh = 0 (or a low value) will zoom out in 1.1 but not Go. This may have been done to prevent black bars when using a widescreen stage outside of widescreen, but it has that negative effect.

2. If a stage has zooming, the corners will be at a different place depending on whether you're in widescreen or not. In 1.1 they are consistent.

3. The [Shadow] fade.range parameter acts slower than in 1.1

**Comment by lokpro** [comment]
related? https://github.com/ikemen-engine/Ikemen-GO/issues/160 https://github.com/ikemen-engine/Ikemen-GO/issues/172

**Comment by potsmugen** [comment]
Not from what I can tell.

**Comment by K4thos** [comment]
please provide stages that showcase these issues and can be tested in both mugen and ikemen to see the differences. Trying to reproduce something based on description alone often fails (and it's an extra effort)

**Comment by potsmugen** [comment]
Sorry. I'll keep that in mind next time.

I think you're right about the second one. The other two should be noticeable in this stage:
[Londinium_Test.zip](https://github.com/ikemen-engine/Ikemen-GO/files/9125644/Londinium_Test.zip)

**Comment by potsmugen** [comment]
I'm just going to record this here for the future, but it turns out the reason the shadow fading felt wrong to me is that that feature is broken in Mugen 1.0 and 1.1. Elecbyte forgot to make the fading range vary according to game resolution, so a 320x240 stage played in 640x480 resolution (my setup) will make the shadows fade twice as fast.

Ikemen works like Winmugen, which is the proper way.
