### ISSUE TITLE
Hitdef sound channels [feature request]

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#591]
While I'm not in a hurry to request new features, I think this one should be easy to implement and have a positive impact in the engine.

Hitdef could use two new parameters: "hitsound.channel" and "guardsound.channel". They should be self-explanatory. They could default to -1, which would be whatever channel is available, like the current behavior (and Mugen's).

Alternatively, this could be a constant instead (still defaulting to -1).

This is one of those things I and a few others had to code manually to make the characters feel more like they're out of a fighting game. It's subtle, but chaotic hit sound channels is one of the things that makes Mugen feel like Mugen (in a bad way). Most fighting games have each hitsound interrupting the last.

It'd be even better if all characters could just play these sounds in a common channel (like a screenpack channel or something like that), but the previous suggestion would be more than good enough.

**Comment by Sluigi123** [comment]
I agree with this idea! Implementing each of the [hit/guard] sounds to play over each other by hand uses up more lines of code than necessary. Reducing them down to parameters also improves the overall organization as well. ;)
