### ISSUE TITLE
Auto order select on team versus screen after time runs out.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#596]
In team versus screen mode if you don't select all your characters before the time runs out the screen just fades away to the match. It would be better if the engine just auto selected based on picked order and played the done animation before it transitioned to the match.

**Comment by K4thos** [comment]
this is not true. Use mugen1 motif shipped with engine as a reference how to set it up.

**Comment by UrsoManso** [comment]
Thanks.
