### ISSUE TITLE
Received damage resets before the combo counter

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#597]
Just ran into this one. If you combo the opponent with a grounded link in the last possible frame, the combo counter will go up but the ReceivedDamage will reset.

It's easy to see in this video:

https://user-images.githubusercontent.com/107247004/235480158-69d85ab1-8b83-44de-be1e-b85bc41991c3.mp4

Incidentally, it'd be nice if something could be done about that frame where P2 looks like he's idle but in reality he's still being comboed. Mugen is also like that but still.

**To reproduce:**
Add this code to Kung Fu Man's standing hard punch:
```
[State 210, Test]
type = changestate
trigger1 = movecontact
trigger1 = AnimTime = -4
value = 210
```
He will combo automatically into another hard punch at the right time. If you pause and step the game you will see P2 enters an idle state the exact moment the second punch connects, which is where the problems start.

**Comment by EgyLynx** [comment]
I remeber at mentioded just similar think...(or not)  Are you est any other person that conbo, just that person?

**Comment by potsmugen** [comment]
I used that character because I knew that combo fit the requirements to replicate the bug. The same thing happens with the other characters and combos I've tested.

**Comment by EgyLynx** [comment]
Bug you mentioded at also similar at Mugen 1.1 (beta) .. still not sure is it same... and is same persons, but... 

strange ...

**Comment by potsmugen** [comment]
Another thing I just noticed about this issue is that it lets GetHitVar(Hitcount) reset even though the chars never exited the hit states, which breaks some codes like damage scaling.
Odds are that everything related to getting hit is reset.

**Comment by potsmugen** [comment]
Update:
[This recent commit](https://github.com/ikemen-engine/Ikemen-GO/commit/c25853bf0f0e6f66ce28792b8bea20de1bb4173b) changed this bug a little. Now the damage display and ReceivedDamage trigger are in sync, but if you hit a character in the first frame where they're allowed to block, the lifebar combo display will go up by one hit.
