### ISSUE TITLE
Movelists not appearing on Mac OS

### ISSUE THREAD

**Issue by kahinli** [ikemen-engine/Ikemen-GO#599]
I noticed that for characters that have movelists, like the new POTS characters and even KFM himself, would not display the movelist correctly. It's like the movelists use a missing font on Mac.

![ikemen000](https://user-images.githubusercontent.com/58328444/176986646-dbb37fc1-efcc-4507-867a-904435e9382f.png)

**Comment by beterhans** [comment]
yeah same issue.
anything need ttf font support will not able to display.

**Comment by K4thos** [comment]
Most likely already fixed, please test on the nightly build
