### ISSUE TITLE
Hitdef getpower on block

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#602]
If you block Kung Fu Man's supers, he gains back some power. I think it's because this Mugen behaviour is not replicated:

> getpower = p1power, p1gpower (int, int)
> p1power specifies the amount of power to give P1 if this HitDef connects successfully. p1gpower specifies the amount of power to give P1 if this HitDef is guarded. If omitted, p1power defaults to hit_damage (from "damage" parameter) multiplied by the value of Default.Attack.LifeToPowerMul specified in data/mugen.cfg. **If p1gpower is omitted, it defaults to the value specified for p1power divided by 2.**

**Comment by K4thos** [comment]
fixed, thanks

**Comment by Iara1** [comment]
> fixed, thanks

Oh, question and I'm sorry for bumping. You say you fixed this. What do people who already have Ikemen GO do to fix this as well? Install it again, or wait for the newest release?  Because I don't see the release files updated.
