### ISSUE TITLE
Program dosent even open

### ISSUE THREAD

**Issue by SCAalpha** [ikemen-engine/Ikemen-GO#604]
for some reason, when i try to open the program, it open for a split second and closes instantly. theres nothing in the Ikemen log file either. 

here's a video of what happens (put on a zip  file because the file alone did not want upload)
[IMG_3781.zip](https://github.com/ikemen-engine/Ikemen-GO/files/9114708/IMG_3781.zip)

**Comment by lokpro** [comment]
maybe try opening in a cmd to see the output.
