### ISSUE TITLE
Alpha transparency function from 1.1b SFFv2.1 is treated as fully transparent in Ikemen

### ISSUE THREAD

**Issue by doubletrend-zeta** [ikemen-engine/Ikemen-GO#608]
No matter the level you set the alpha to for the standard transparency section of a palette, Ikemen will treat it as if the alpha channel is 0. Here I set my background to 255 and mugen 1.1b treats it as such, but ikemen chooses to treat it as fully transparent, regardless of the alpha channel set.
![EX1](https://user-images.githubusercontent.com/86899546/179380240-c0b4b538-9ae4-46de-8180-93ad2e5d45d0.PNG)
![EX2](https://user-images.githubusercontent.com/86899546/179380237-e2958979-911f-4df8-8e24-48176b867a99.PNG)
The palette in question with alpha channel = 255 in Fighter Factory
![ex3](https://user-images.githubusercontent.com/86899546/179380260-1786cdf9-9c7a-420b-8f89-3b92e1e745e1.PNG)

The display to clipboard parameters in the image are
```
[state display setup]
type = displaytoclipboard
trigger1 = roundstate >=0
text="prematch check \n =%d, cached as =%d"
params = palno, var(55)
```

The code used for the color selection is a standard null varset

```
[State 5900, 3] ; from VANS
type = Null
;---------------------------------------- DO NOT MODIFY THIS BLOCK
trigger1 = PalNo = 1           
trigger2 = PalNo = 2           
trigger3 = PalNo = 3           
trigger4 = PalNo = 4         
trigger5 = PalNo = 5           
trigger6 = PalNo = 6            
trigger7 = PalNo = 7            
trigger8 = PalNo = 8            
trigger9 = PalNo = 9           
trigger10 = PalNo = 10           
trigger11 = PalNo = 11          
trigger12 = PalNo = 12    
;---------------------------------------- 
;---------------------------------------- MODIFY VALUES BELOW.
trigger1 = var(55)  := 1    ;Palette 1.  Selected with "X"
trigger2 = var(55)  := 2     ;Palette 2.  Selected with "Y"
trigger3 = var(55)  := 3     ;Palette 3.  Selected with "Z"
trigger4 = var(55)  := 4     ;Palette 4.  Selected with "A"
trigger5 = var(55)  := 5    ;Palette 5.  Selected with "B"
trigger6 = var(55)  := 6    ;Palette 6.  Selected with "C"
trigger7 = var(55)  := 7    ;Palette 7.  Selected with "Start + X"
trigger8 = var(55)  := 8    ;Palette 8.  Selected with "Start + Y"
trigger9 = var(55)  := 1    ;Palette 9.  Selected with "Start + Z"
trigger10 = var(55) := 2    ;Palette 10. Selected with "Start + A"
trigger11 = var(55) := 3    ;Palette 11. Selected with "Start + B"
trigger12 = var(55) := 4    ;Palette 12. Selected with "Start + C"
persistent = 1

[State 5900] ;Change palette
type = RemapPal
trigger1 = 1
source = -1,-1
dest = 1,var(55)
```

**Comment by K4thos** [comment]
Please upload character showcased on screenshot so that problem can be reproduced without need to spend time on photoshop.

**Comment by doubletrend-zeta** [comment]
My phrasing of the issue ended up being a bit more misleading than I meant, I used a character sprite just to prove there was palette consistency in the example but it applies to everything because the masking of the first color of a palette seems to be forced. 

What I meant was more that even if an indexed image's palette was created without transparency, e.g. a full screen effect
![0168](https://user-images.githubusercontent.com/86899546/179423480-378a3695-fe0b-4021-9e80-d0fb7d73a424.png)
will have a mask value forced upon the first color of the palette it when added into the SFF in fighter factory
![EX1](https://user-images.githubusercontent.com/86899546/179423674-734ce8e4-1adb-4fd7-aa72-983fff0d19d7.PNG)

With mugen I can override this by forcing the mask color's alpha channel to be 255, which mugen will accept

![EX2](https://user-images.githubusercontent.com/86899546/179423733-e96af173-5fcb-4e88-9466-2fb56f71d83d.PNG)

Yet it seems that in ikemen mask transparency is forced no matter what the actual alpha channel's value is set to
![ex3](https://user-images.githubusercontent.com/86899546/179423774-f96d0e50-9b51-4a69-96cb-c11502a1608a.PNG)

It's technically just a small issue of compatibility, and palettes can be built around this, but I just was unsure of if this was an issue with SFF standards and how ikemen reads palette data.
Here's a copy of this example.
[kfm.zip](https://github.com/ikemen-engine/Ikemen-GO/files/9128487/kfm.zip)

**Comment by K4thos** [comment]
@doubletrend-zeta, your example doesn't show any difference between mugen 1.1 and ikemen.

ikemen:
![ikemen008](https://user-images.githubusercontent.com/8928195/213428507-f060515f-8bd8-44d6-8d5d-9855c2164482.png)

mugen 1.1:
![mugen005](https://user-images.githubusercontent.com/8928195/213428587-93fcd922-d054-4360-9baf-611f821b4227.png)
