### ISSUE TITLE
Crash with with OGG file

### ISSUE THREAD

**Issue by LasombraDemon** [ikemen-engine/Ikemen-GO#609]
This file has been reported to cause a crash when used as stage music.

[hellsing2.zip](https://github.com/ikemen-engine/Ikemen-GO/files/9128703/hellsing2.zip)

**Comment by K4thos** [comment]
steps to reproduce (please include information like this in future, following bug issue template)
1. Put the track to sound directory
2. Edit stages/kfm.def [Music] group: `bgmusic = sound/hellsing2.ogg`
3. Start training mode, select Kung Fu Temple stage and wait for the whole track to finish.
4. Engine freezes during song loop attempt.

Platform:
- Engine Version: latest github build
- OS: Windows 10
