### ISSUE TITLE
Update Arcade Paths / Story Mode Wiki

### ISSUE THREAD

**Issue by mixychan** [ikemen-engine/Ikemen-GO#616]
When I was attempting to make a custom arcade path using the methods in the Wiki, I couldn't seem to get it to work. I then realized that the wiki is not updated, and that I do not need to use the "[Arcade] section" that the wiki says I should. I was sitting here for 4-5 hours trying to troubleshoot what I did wrong and ran it through multiple friends and laughed when I realized that this was the issue. Could the wiki be updated to feature all of the current things in version 0.98.2? That was extremely frustrating and I don't want anyone else to have trouble like that again.

 - Engine Version [0.98.2]
 - OS: [Windows 10]

**Comment by K4thos** [comment]
I've just tested it on 0.98.2 by pasting `arcadepath = test.lua` below [Arcade] section in character's DEF file (path file relative to folder of character) and it worked just fine.

**Comment by K4thos** [comment]
Half a year passed without reply, so I'm closing it for maintenance reasons. Feel free to reopen the ticket with repo steps.
