### ISSUE TITLE
Delayed Super FX on compiled build.

### ISSUE THREAD

**Issue by UrsoManso** [ikemen-engine/Ikemen-GO#627]
https://user-images.githubusercontent.com/77592586/182526927-32ce0c25-ba91-4145-b0e9-8ebc6f189f67.mp4

This is 98.2 where the FX plays at the correct time.

https://user-images.githubusercontent.com/77592586/182527002-fdf689b5-e05f-4e24-aee1-34a6cae7bdba.mp4

This is from the compiled build.

[Malin.zip](https://github.com/ikemen-engine/Ikemen-GO/files/9248070/Malin.zip)

**Comment by NeatUnsou** [comment]
I could not reproduce the problem. Please update to the latest build and test again.

**Comment by UrsoManso** [comment]
Somebody compiled for me because I was getting stuck everytime I tried to compile myself. If you could send me the latest build I'd appreciate.

**Comment by NeatUnsou** [comment]
OK
[Ikemen_GO_0730.zip](https://github.com/ikemen-engine/Ikemen-GO/files/9257979/Ikemen_GO_0730.zip)

**Comment by UrsoManso** [comment]
It worked fine on the build you linked, thanks a lot.
