### ISSUE TITLE
The None's Blossomko and Dudereal crashes Ikemen GO

### ISSUE THREAD

**Issue by waspennator** [ikemen-engine/Ikemen-GO#632]
**Describe the bug**
Apparently something regressed from version 0.97.0 to version 0,98.0, cause Blossomko and DudeReal crashes Ikemen as soon as you start a match with them, last version they worked with was version 0.97.0 and happens across all versions past that.

**To Reproduce**
1: Download Blossmko and Dudereal 
http://www.justnopoint.com/lbends/download.php?file=blossomko
http://www.justnopoint.com/lbends/download.php?file=dudereal
2: Add them to roster and try to start a match with either one.
3: Watch as Ikemen GO panics and crashes.

**Expected behavior**
The entire game shouldn't crash.

**Screenshots / Video**
![Blossomko crash](https://user-images.githubusercontent.com/78768499/183328818-9eab8778-2a36-4295-8c2b-00135a67c53d.png)

**Platform (please complete the following information):**
 - Engine Version [e.g. 0.97, 0.98, 0.98.1, 0.98.2]
 - OS: [e.g. Windows 11]

**Additional context**
[Blossmko crash log.log](https://github.com/ikemen-engine/Ikemen-GO/files/9278288/Blossmko.crash.log.log)

**Comment by K4thos** [comment]
it's a bug with character and the error tells you everything you need to fix it locally (wrong syntax of sine in line 11134 of blossomko). Even though the engine here works as expected next version will allow this code bug to exists because of how widespread it is (most likely due to Fighter Factory 3 CNS editor using wrong syntax for ForceFeedback sctrl)

**Comment by waspennator** [comment]
That sounds good enough to me, also figured i'd ask one more thing for clarification, will that also make Fourthrhyme's Delta 
 warriors work too? Cause i've also tried em and they seem to crash the latest version of Ikemen GO and even version 0.97 with a similar error.

".\external\script\start.lua:1401: 
chars\DeltaruneTrio/DeltaruneTrio.cns:2609:
SCA,NA,SA,HA,NP,SP,HP,
attr: Invalid value: "

**Comment by K4thos** [comment]
no, you should fix the code bug yourself in line and cns file mentioned in error. If you don't know the syntax than refer to official mugen documentation.

**Comment by jankespro12** [comment]
This also happens with The None's Dee Bee Kaw
