### ISSUE TITLE
Properly written code not working as expected on team modes 

### ISSUE THREAD

**Issue by GV123h** [ikemen-engine/Ikemen-GO#633]
**Describe the bug**
Hi ,
I edited the code of pal selector so it can be universally applied to ikemen (maybe simul mode not cause in my ikemen build I disabled that mode to use tag mode instead)

the code requires to define a constant const(lastpal)

**To Reproduce**
the code works flawlessly on tag and single mode, but for some reason it bugs on turns mode on the 2nd and 4th members of the team

the 2nd member lets you select pal, but it wont show the helper anim (the pal selector anim in my case)

**Expected behavior**
the code to work as it does on member 1 or 3 

**Screenshots / Video**

**Platform (please complete the following information):**
 - Engine Version [e.g. 0.98]
 - OS: [e.g. Windows 10]

**Additional context**

Also, feel free to inspire yourself in this code to maybe add the so asked pallete selector universally on characters

see attached file for adding it in custom states
[PALSELECTOR.zip](https://github.com/ikemen-engine/Ikemen-GO/files/9293849/PALSELECTOR.zip)

Sorry in advance if in fact my code has the bug and not ikemen, but so far the way it is failing, leads me to believe it might be an Ikemen bug

regards

**Comment by K4thos** [comment]
can't reproduce
[video.zip](https://github.com/ikemen-engine/Ikemen-GO/files/9294228/video.zip)

**Comment by GV123h** [comment]
Hi

K4thos ,

On your end seems to be working just fine .

I’ll send you later a video of the bug and will try with more characters .

I hope the code to the pal selector is useful for you

Atte

GV

El 9 ago. 2022, a la(s) 2:08 p. m., K4thos ***@***.***> escribió:

﻿

can't reproduce
video.zip<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fikemen-engine%2FIkemen-GO%2Ffiles%2F9294228%2Fvideo.zip&data=05%7C01%7C%7C905470ab26ae4e9988f908da7a42eb41%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637956725082961566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=u6J5x2pjUjXWuBWqZoQLlnW2a1lYgftGmUnYzQzTUtY%3D&reserved=0>

**Comment by K4thos** [comment]
if it works for kfm than that's where my investigation ends. Before spending any more time on it I would need to be sure that it's indeed an engine problem, not specific way the character is coded.

**Comment by GV123h** [comment]
Hi

That sounds fair

Thank you  for your attention and I will let you know if anything else comes up.

Just a quick question .

Are maps defined though states supposed to be reset when moving to a next fight .?
(Not next round , but successive fights after the Vs screen to new rivals )

Thanks In advance

Atte

GV

El 9 ago. 2022, a la(s) 5:20 p. m., K4thos ***@***.***> escribió:

﻿

if it works for kfm than that's where my investigation ends. Before spending any more time on it I would need to be sure that it's indeed an engine problem, not specific way the character is coded.

**Comment by K4thos** [comment]
> Are maps defined though states supposed to be reset when moving to a next fight .?
yes

**Comment by GV123h** [comment]
Ok, I made some modifications to enhance the code, but so far I found out the problem persist on characters with mugen version 1.0 and only in turns mode when the characters with version 1.0 are member 2 or higher 

[PALSELECTOR.zip](https://github.com/ikemen-engine/Ikemen-GO/files/9312238/PALSELECTOR.zip)
