### ISSUE TITLE
[feature request] GetHitVar(ground.animtype) and GetHitVar(air.animtype)

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#636]
I would like to change the damage voice according to the strength of the ricochet of the received attack, like in DBFZ.
However, in MUGEN, once the fall=1 state is reached, the GetHitVar(animtype) value is fixed in most cases, no matter what the attack is, and it is impossible to determine the strength of the rattling from the attack. (You can do this by changing the HitDef's Fall.AnimType, but few characters do so.)

What I want this trigger to do is to be able to determine the AnimType (Air.AnimType) of the HitDef regardless of the state of the fall, so that the damage voice can be changed according to the strength of the ricochet, like in DBFZ.

Example

[State -2,light damage voice]
type = playSnd
triggerall = !IsHelper
triggerall = Time = [0,1]
triggerall = Hitshakeover = 0
triggerall = Alive
triggerall = MoveType = H
triggerall = stateno != [120,155]
trigger1 = StateType != A
trigger1 = GetHitVar(ground.animtype) = [0,2]
trigger2 = StateType = A
trigger2 = GetHitVar(air.animtype) = [0,2]
value = 5000,0
channel = 30
lowpriority = 1

[State -2,hard damage voice]
type = playSnd
triggerall = !IsHelper
triggerall = Time = [0,1]
triggerall = Hitshakeover = 0
triggerall = Alive
triggerall = MoveType = H
triggerall = stateno != [120,155]
trigger1 = StateType != A
trigger1 = GetHitVar(ground.animtype) = [3,5]
trigger2 = StateType = A
trigger2 = GetHitVar(air.animtype) = [3,5]
value = 5000,20
channel = 30
lowpriority = 1

**Comment by K4thos** [comment]
I'm not sure what you mean by `ground.animtype` and what it's supposed to [return.](url) I don't see such property in mugen docs. Only `animtype` (already detectable by gethitvar) and `air.animtype`, `fall.animtype` - not detectable.

**Comment by K4thos** [comment]
done. Let me know if everything works as expected.
