### ISSUE TITLE
Playsnd volume is too low

### ISSUE THREAD

**Issue by Isakku** [ikemen-engine/Ikemen-GO#640]
**Describe the bug**
My char has this playsnd controller

[State 1000500, PlaySnd]
type = PlaySnd
triggerall = Time%25=0;TimeMod = 25,0
triggerall = Root, Var(56) > 0 && numhelper(3991) = 0
triggerall = ifelse(NumHelper(1000510) > 0,(Root, var(35)=0),1)
trigger1 = Anim = 1000500 
trigger2 = Root, Var(30) < Root, Var(33)
value = 3, 0
channel = 1
freqmul = 0.7
volume = -250

**To Reproduce**
Detailed steps to reproduce the behavior, e.g.:
1. use volume = -250 in a playsnd controller
2. Or try with my sample char

**Expected behavior**
Even though the volume = -250 parameter seems so low, the sound's volume is not that low in MUGEN, but here on Ikemen it's almost completely inaudible. Maybe this is a bug in MUGEN instead, but it has not been a problem in either MUGEN 1.0 nor MUGEN 1.1
Maybe it's the sound in the .snd file

**Platform (please complete the following information):**
 - Engine Version [ 0.98.2]
 - OS: [ Windows 8.1 and Linux Manjaro]

**Additional context**
I'm adding a link for the char so you can test it. it's the charging sound for Vent & Aile 
So, charging the saber or the buster of any model has this problem, whereas in MUGEN it doesn't happen.

http://www.mediafire.com/?1hwwmq341wudb8g

Oh and by the way it seems freqmul is working? I just hope it is working correctly.

**Comment by Blac-Dragoon** [comment]
Change 'volume' to 'volumescale'. Volume is no longer supported from MUGEN 1.0 and above and not useable in IKEMEN Go.

**Comment by Isakku** [comment]
Well, using volumescale sovled this. However I find volumescale limited in other situations with the opposite problem, it can't go above beyond 100%.

**Comment by Blac-Dragoon** [comment]
The max is 100 when using it with PlaySnd. In the CNS file from this example:

`[Data]
life = 100
power = 3000
attack = 100
defence = 100
fall.defence_up = 50
liedown.time = 30
airjuggle = 30
sparkno = 2
guard.sparkno = 40
KO.echo = 0
IntPersistIndex = 60
FloatPersistIndex = 40
volumescale = 200`

You can set the volumescale as high as you needed. Here, I tried _200_ with was much louder than the default _100_.  Try playing with the volume for the desired result.

**Comment by Isakku** [comment]
> The max is 100 when using it with PlaySnd. In the CNS file from this example:

It seems that could help. Except that I would have to put a volumescale of 200 and then change every single PlaySnd controller to 50 so it's not too loud except the ones I want louder which would then need to be set to 100. Doesn't sound very practical. I just hope I would not happen to be in that exact situation.

**Comment by Blac-Dragoon** [comment]
Volumescale with type = PlaySnd only works with individual sounds. Volumescale with [Data] works for all sounds used. Just a heads-up.
