### ISSUE TITLE
when time over, characters are not leaving round in turns mode.

### ISSUE THREAD

**Issue by leandrooffline** [ikemen-engine/Ikemen-GO#654]
In turns mode the characters after lose or drawgame no go way for next character getting in fight.

https://user-images.githubusercontent.com/4389151/186482504-675412f4-1fdc-49c1-8f07-44d439b749d2.mp4

-Ikemengo build create 2022-08-24
-Windows 10
Sorry for bad english

**Comment by potsmugen** [comment]
This seems fixed in the current version.
