### ISSUE TITLE
Squeeky toldos me about fluidsynth for go

### ISSUE THREAD

**Issue by Mike77154** [ikemen-engine/Ikemen-GO#66]
@Mike77154 Note that fluidsynth is a C library, and this project is simply go bindings for it. So you'll need to build the fluidsynth shared library for this to work. There's pre-built binaries for windows at least available from the official repo: https://github.com/FluidSynth/fluidsynth/releases

The documentation available at https://github.com/FluidSynth/fluidsynth/wiki/Documentation is also useful as the go bindings closely follows the C api.

Anyway once you've got the library set up, to load up a sound font you go:

```
    //assuming: import "github.com/sqweek/fluidsynth"

    settings := fluidsynth.NewSettings()
    settings.setNum("synth.sample-rate", float64(audioFrequency)) // this should match your openAL config
    // customise more settings here if you like; see "FluidSettings" in the documentation for a full list
    synth := fluidsynth.NewSynth(settings)
    soundfontId := synth.SFLoad(soundfontPath, true)
```

`SFLoad` can take awhile for large soundfonts, so you might want to do this initialisation in the background.

Now you can do basic midi things like `synth.NoteOn/NoteOff/ProgramChange`, however nothing is going to happen until you take the audio samples produced by the synthesizer and send them to the soundcard. It's possible to create a fluidsynth.Driver to take care of that, but in your case you probably want to use `synth.WriteS16` to get the samples directly as 16-bit integers which you can use to fill your OpenAL buffers.

Does that make sense?

_Originally posted by @sqweek in https://github.com/sqweek/fluidsynth/issues/1#issuecomment-558191453_

**Comment by K4thos** [comment]
ticket for this missing mugen feature already exists #12
