### ISSUE TITLE
MacOS main Lua file error

### ISSUE THREAD

**Issue by python-nerder** [ikemen-engine/Ikemen-GO#662]
So, I got your code and everything, but whenever I double-click `Ikemen_GO_MacOS`, I get an error that says 
` "Main lua file "external/script/
             main.lua" error. 
open external/script/main.lua: no
          such file or directory"`

After downloading your file from `https://github.com/ikemen-engine/Ikemen-GO/releases/tag/0.98.2`, I double-clicked the command...

And got the error. 

So, I went back to compile it - but I didn't have the privileges - even though my Mac said I could read and write.

I was expecting the engine to run smoothly.
![error2](https://user-images.githubusercontent.com/112698783/188128541-2f73b30b-0cd6-49db-af97-386acf9355d4.png)

![error1](https://user-images.githubusercontent.com/112698783/188128257-9c9876b9-d6a1-48e1-809d-0361f5f10a5c.png)

My platform is `MacBook Air (13-inch, 2017)`

Please fix this - or tell me what I'm doing wrong.

PS: I've already installed Lua.

**Comment by Windblade-GR01** [comment]
Seems like the `Ikemen_GO_MacOS` lacks executable permissions.
Open a terminal and write:
`sudo sudo chmod u+x "path_to_Ikemen_GO_MacOS"`

Where `"Ikemen_GO_MacOS"` is the path to where the executable is located.

**PS:**
You can also just write `sudo sudo chmod u+x ` (with a space at the end) and drag the `Ikemen_GO_MacOS` file to the terminal.

**Comment by python-nerder** [comment]
I did _exactly_ as you said-
I wrote 
`Users/Onesimus/Dropbox/Mac/Downloads/Ikemen_GO_v0/Ikemen_GO_MacOS`
after the sudo,
but...

A - NOTHING happened, even after I entered my password.
![mama](https://user-images.githubusercontent.com/112698783/188413392-e9c21014-c6fb-4051-9685-40705501ab56.png)

B - The selfsame error occurred _again_.
![no lol](https://user-images.githubusercontent.com/112698783/188414491-b69e580c-ed29-4ab9-8ebd-1d8cbfff049b.png)

**Comment by python-nerder** [comment]
It is now saying:
`panic: Main lua file "external/script/main.lua" error.
open external/script/main.lua: no such file or directory
goroutine 1 [running, locked to thread]:
main.main() github.com/Windblade-GR01/Ikemen_GO/src/main.go:82 +0x7e7`

**Comment by Christian-Nerd** [comment]
I have the same issue this problem isn't closed.

**Comment by shinriyo** [comment]
```
panic: Main lua file "external/script/main.lua" error.
open external/script/main.lua: no such file or directory

goroutine 1 [running, locked to thread]:
main.main()
	/Users/runner/work/Ikemen-GO/Ikemen-GO/src/main.go:80 +0x529

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by Timeless-Xeno** [comment]
I've been having this issue whenever I try opening it

**Comment by TNTGans665** [comment]
Me too, after downloading the zip file from the official website and extracting it, I ran Ikemen_GO_MacOS.command, and this window popped up. Even using the solution mentioned above, it still couldn't be resolved.

<img width="328" height="295" alt="Image" src="https://github.com/user-attachments/assets/5ed75096-bef6-4c8a-a10f-88248aa4355f" />

**Comment by TNTGans665** [comment]
> Me too, after downloading the zip file from the official website and extracting it, I ran Ikemen_GO_MacOS.command, and this window popped up. Even using the solution mentioned above, it still couldn't be resolved.
> 
> <img alt="Image" width="328" height="295" src="https://private-user-images.githubusercontent.com/128218165/523061004-5ed75096-bef6-4c8a-a10f-88248aa4355f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ5NTQ3ODgsIm5iZiI6MTc2NDk1NDQ4OCwicGF0aCI6Ii8xMjgyMTgxNjUvNTIzMDYxMDA0LTVlZDc1MDk2LWJlZjYtNGM4YS1hMTBmLTg4MjQ4YWE0MzU1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwNVQxNzA4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzcwOGU3NjVhNTg5YTc3NjVhNmFjMWRmM2I1Y2E5MDYzNzk3MjA4YTE5MmRmNTE3ZWJhOTg3NWEyYjBlNzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0Wuzz5t1vayTmzbUFG8_8uxdxXwcsNtBbFUKb4O4sHc">

Ps. My macOS version is 26.1
