### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by throwbowbbw** [ikemen-engine/Ikemen-GO#666]
![Capture](https://user-images.githubusercontent.com/110943601/188336229-ed041554-493b-47c8-a8c5-499e9ab8a07c.JPG)

Randomly I get this error when starting Ikemen. How to reproduce? I don't know.

**Comment by lokpro** [comment]
looks like related to reading of /save/config.json
maybe check that file's existence, format(JSON), encoding(UTF-8) when you meet this error.
