### ISSUE TITLE
[suggestion]  "--legacy" option

### ISSUE THREAD

**Issue by skysix2** [ikemen-engine/Ikemen-GO#670]
Hi !
to facilitate the adoption of ikemen for normal users or retrogaming distros, it would be possible (as other game engines do) to add an option like "--legacy" which actually hides a preconfiguration that mimics normal operation as much as possible by MUGEN.
so that it can work as a direct replacement for MUGEN in existing games

and then the developers can begin to discover and implement the new features as well.

thanks!!

**Comment by pidgeon777** [comment]
It seems to be a good idea 👍.

**Comment by Lazin3ss** [comment]
Ikemen GO already tries to work as much of a direct replacement of MUGEN as possible, so I don't see the point in it.

**Comment by pidgeon777** [comment]
Maybe that flag could be used to support the very few MUGEN features not supported yet by ikemen-GO?

**Comment by Lazin3ss** [comment]
If there are missing MUGEN features, we can implement them directly so they can be accessed by default. For example, there's a replacement for config.json in the works, so in future versions, we will have something much like mugen.cfg.

We would be grateful if you can tell us which features are missing from MUGEN. Keep in mind version 0.98.2 feels very outdated right now in comparison to the latest changes in the repository (that resemble what next version, 0.99, will look like), so you might report missing features we already covered for 0.99.

**Comment by K4thos** [comment]
closing it since as Lazin3ss mentioned that's exactly how ikemen works. The only difference is not using mugen.cfg. In future versions (not 0.99) mugen.cfg will be automatically imported, if present. If there are missing features than no legacy option is needed - they should be implemented normally.

**Comment by skysix2** [comment]
Hi ! sorry for the absence, I wrote this suggestion because trying to directly replace MUGEN.EXE with IKEMEN-GO on a couple of working games, I think they were a "street fighter" and "ultimate cosmo", the graphics of the games were not consistent between the original version and ikemen (some elements had different positions and some zoom problems) but some time has passed and I have not done any more tests ...
but mugen.cfg import is probably the correct solution !!
and also saving in the new json format !! (so as to have a migration between configuration formats)
