### ISSUE TITLE
Bug characters colors

### ISSUE THREAD

**Issue by WWWEdobrimCOM** [ikemen-engine/Ikemen-GO#675]
Hi everyone, I have the latest version of Ikemen Go and I'm working on a Mugen style mod.
I have added stages and characters to the game and everything is fine.
The only weird thing that happens is with some characters.
Playing with some human style characters, in the 3D sense type downloaded from mugen sites, many of these characters change color.
For example by inserting a character who has a pink skin color (for example), in Ikemen Go it turns (when playing) in green or blue color.
This also happened to me with a 3D Tekken character that appeared green, while in mugen it appears normal.
How come?

Thank you

Example character:

1) https://mugenarchive.com/forums/downloads.php?do=file&id=147382-julia-bane84

2)
https://mugenarchive.com/forums/downloads.php?do=file&id=19987-justice-bane84

**Comment by K4thos** [comment]
please provide a link that doesn't require registration to download it

**Comment by WWWEdobrimCOM** [comment]
Hi sure. I'll send you everything as soon as I can


Il sab 19 nov 2022, 10:47 K4thos ***@***.***> ha scritto:

**Comment by WWWEdobrimCOM** [comment]
Hello, these are the characters that have problems with colors (not
always). But if you train, I don't know why, you can't see it. You
should play it.

https://drive.google.com/file/d/1g8NpMRM-SCHS4hGJa_RcgNWEU4gXIMTO/view?usp=share_link





Il giorno sab 19 nov 2022 alle ore 10:47 K4thos ***@***.***>
ha scritto:

**Comment by K4thos** [comment]
based on my test of Julia exactly the same behavior happens in mugen 1.1, so I assume it's how they're supposed to look. 
![mugen004](https://user-images.githubusercontent.com/8928195/213053709-d23b4a21-86b8-44ad-a967-7e80da7ae396.png)

**Comment by WWWEdobrimCOM** [comment]
> based on my test of Julia exactly the same behavior happens in mugen 1.1. Some pals are like this, some are not. So I assume it's how they're supposed to look. Screenshot made in mugen: ![mugen004](https://user-images.githubusercontent.com/8928195/213053709-d23b4a21-86b8-44ad-a967-7e80da7ae396.png)






Thank you
