### ISSUE TITLE
BOSS Rush Not Working

### ISSUE THREAD

**Issue by Flowrif** [ikemen-engine/Ikemen-GO#688]
**Describe the bug**
When I choose Boss rush mode, I am booted back to the main menu

**To Reproduce**
Detailed steps to reproduce the behavior, e.g.:
1. Open Ikeman. I have Infinite screenpack and using Orochi Kyo Tag btw.
2. Choose "Boss Rush", then I'm asked what mode to choose from: "Single, Simul, Tag, Turns, Ration". When I make the choices for myself and then the AI, I am then sent back to main menu
3. No specific message appears

**Expected behavior**
I want to see what Boss rush is about. I have one character set as a boss in select.def as order= 10or

**Screenshots / Video**
If applicable, add screenshots and/or videos to help explain your problem.

**Platform (please complete the following information):**
 - Engine Version [e.g. 0.98]
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by Blac-Dragoon** [comment]
Do you have the Boss Rush module installed. That's the only way you can play Boss Rush.
You can get it here: https://github.com/ikemen-engine/modules

**Comment by Lazin3ss** [comment]
Boss Rush is now an external module. See https://github.com/ikemen-engine/modules

**Comment by PGamer3** [comment]
Is there a specific way to make boss characters from IKEMEN GO in order?

**Comment by PGamer3** [comment]
Because when I beat Master Hand, it ended up in the "Congratulations" Screen

**Comment by PGamer3** [comment]
Rather than going to the next boss character
