### ISSUE TITLE
Supers Not Working

### ISSUE THREAD

**Issue by Flowrif** [ikemen-engine/Ikemen-GO#691]
**Describe the bug**

**To Reproduce**
Detailed steps to reproduce the behavior, e.g.:
1. Supers are inconsistent when I input the command for any character's super
2. Start match in arcade or training. Then attempt to do any super. This issue is intermittent
3. Super does not initiate, instead character does regular attack

**Expected behavior**
I expect super to launch everytime. This is very annoying in arcade mode.

**Screenshots / Video**
If applicable, add screenshots and/or videos to help explain your problem.

**Platform (please complete the following information):**
 - Engine Version [e.g. 0.98]
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by K4thos** [comment]
already reported: https://github.com/ikemen-engine/Ikemen-GO/issues/264
