### ISSUE TITLE
Bank Type Colors

### ISSUE THREAD

**Issue by XDK6** [ikemen-engine/Ikemen-GO#692]
So I am creating my screenpack. I will feature fonts as my main design but the problem is they are off colors even though they are font V2 and sprite bank type.

I wonder why it works on mugen 1.1b and not on Ikemen. I even indexed my sprite fonts, and align palettes but nothing seem to work.

![image](https://user-images.githubusercontent.com/98625540/196297167-215a0f3e-4ef2-4d09-b39c-260d28e13579.png)

**Comment by K4thos** [comment]
report without providing ways to reproduce it is not enough to test or help in any way. Please follow bug report template.
