### ISSUE TITLE
MacOS Error loading JSON

### ISSUE THREAD

**Issue by jmagee22** [ikemen-engine/Ikemen-GO#693]
I just downloaded the latest version of IKEMEN GO and attempted to open on my Mac (using the MacOs executable) and received the following message: 
<img width="255" alt="Screen Shot 2022-10-20 at 9 42 14 AM" src="https://user-images.githubusercontent.com/116285295/196966239-aa0892ce-1289-4cac-b386-87797c374370.png">

My current MacBook is 
<img width="244" alt="Screen Shot 2022-10-20 at 9 46 38 AM" src="https://user-images.githubusercontent.com/116285295/196966395-72e9f800-29b7-41de-9280-31c311dffade.png">

I'm not sure what I'm doing wrong. Any help would be greatly appreciated.

**Comment by K4thos** [comment]
delete config json and see if it works
