### ISSUE TITLE
[Visual Compatibility] Color -256 PalFX Trick

### ISSUE THREAD

**Issue by slzero-X** [ikemen-engine/Ikemen-GO#694]
In the official builds of MUGEN, only one character has been reported to use a quirk with PalFX. And that is The_None's Blizzard/Chaos. 
As far as I know, not a single person has pointed this out, even though The_None is arguably one of **the most famous** authors out there.

Searching for The_None's Blizzard/Chaos is quite easy, due to said authors notoriety. 

In the subject of PalFX, Blizzard/Chaos use a PalFX that has the Color parameter set to -256, which inverts the order of the color channels, creating a new palette that he flickers from back and forth, but only when he activated berserk mode.

For instance, when your character's red, they instead appear turquoise, and vice versa. Blue -> Yellow, Green -> Pink, etc.

It doesn't invert the colors completely, only which channels values are set and the brightness scales are preserved

In IKEMEN, any color value below 0 has no effect, the character remains grayscale, so for visual compatibility, allow characters to invert color channels by arbitrarily setting Color to -256, anything else would either just result in grayscale or full color.

**Comment by Sluigi123** [comment]
I agree with this idea, as it gives the creators more freedom and creativity than before. ;)

**Comment by potsmugen** [comment]
This is an undocumented feature in Mugen, and it even goes as far as displaying debug messages if you use a negative value for color, but it does work. I second that it'd be nice if Ikemen could do the same because you can make some neat effects with it.

(Randomly dropping a suggestion for a hue parameter as well.)

**Comment by Lazin3ss** [comment]
From my tests in Mugen 1.1, it seems the parameter has no limits at all, you can put any numeric value you want there and it will have an effect in the character.
