### ISSUE TITLE
Different handling of stage zooming

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#703]
I've just noticed that stages that use tensionhigh and tensionlow have a different zoom behavior compared to Mugen 1.1. In Mugen, the stage will only zoom out if the characters are far apart, whereas in Ikemen it zooms out regardless of that.

Here's Mugen 1.1:
![mugen038](https://user-images.githubusercontent.com/107247004/200186677-a366c551-79be-41f4-949e-1a23ad159d64.png)
The characters are high above but the camera doesn't zoom out, because they are close to each other.

Ikemen GO (current repo):
![ikemen001](https://user-images.githubusercontent.com/107247004/200186746-2df74ed4-b07d-4cf2-b668-53330d28ee0c.png)
Same scenario but the camera zooms out.

Here's the stage used:
[stage.zip](https://github.com/ikemen-engine/Ikemen-GO/files/9946463/stage.zip)

**Comment by potsmugen** [comment]
It looks like NeatUnsou's latest changes took care of this one as well. While the behavior's still not exactly like Mugen's, the main issue of zooming out while characters are close to each other is now gone.

**Comment by K4thos** [comment]
#785
