### ISSUE TITLE
BUG: Demos not functioning right

### ISSUE THREAD

**Issue by djonskin** [ikemen-engine/Ikemen-GO#709]
**The bug**
The startup demos don't show up when you leave the game at the title. I did for a moment get maybe a glimmer of a roundstate 1, but it almost immediately cuts back to the title screen instead of getting into the demo fights.

**To Reproduce**
Detailed steps to reproduce the behavior, e.g.:
1. Compile the latest build from here. Just make sure it's the default screenpack or something to get in.
2. Start the game and leave it alone. The demos won't really show up, but it'll act like it's trying to load it.

**Expected behavior**
Leave the game alone for a bit and just see some AI gameplay in demo fights. It never makes it there.

**Platform**
 - Whatever this latest compiled build was called
 - OS: Windows 10

**Additional context**
I suspect a recent NeatUnsou change to GameTime might have had something with it, but it's only a hunch.

**Comment by NeatUnsou** [comment]
Please update global.lua.
This script previously used a gametime trigger for the frame count to end the demo.
However, this trigger counts the game startup time in mugen, and by making the same behavior in ikemen, it can no longer be used to end the demo.
I created another trigger that returns the frame count from the start of the battle, so I'll use that instead.

**Comment by djonskin** [comment]
Oh, I did overlook that for update. A good heads-up! Thankyou.
