### ISSUE TITLE
KOF2003 Stage Intro Effect

### ISSUE THREAD

**Issue by jankespro12** [ikemen-engine/Ikemen-GO#710]
Can you implement the Stage intro Effect from The King of Fighters 2003? because that feature was never seen in every Ikemen Go Game.
Here's a concept of it

https://user-images.githubusercontent.com/63473068/200930627-2a48c49e-5a1a-45b0-accf-fd4da7fe7c1d.mp4

Also, when i played the PS2 version of The King of Fighters 2003 using PCSX2, the stage zoom thing from the arcade version is missing

**Comment by K4thos** [comment]
stage intro is already possible via attachedchar: https://github.com/ikemen-engine/Ikemen-GO/wiki/Stage-features#attachedchar
