### ISSUE TITLE
Audio problem (November 13, 2022 Added)

### ISSUE THREAD

**Issue by zzzz0424** [ikemen-engine/Ikemen-GO#711]
Hello IKEMEN GO development teams!
IKEMEN GO is a wonderful improvement over the previous library, which was changed to a new audio library that is easier to hear and almost free of crackling even when the same notes are played over and over again.

However, we have found a problem with the library change and would like to report it to you.

**Describe the bug**
I have found a bug that causes the volume to change with the bit rate of some audio files

**To Reproduce**
1. most snd files are affected
2. the volume of audio data whose wav file in the snd file is larger than 8bit is played back smaller than the actual audio.
3. this also causes the volume setting in [data] of const and the volume value of PlaySnd to be maximized, but no effect is observed.

**Expected behavior**
The volume function should be corrected, or the volume should be corrected to be equivalent to that of 8-bit audio.

**Screenshots / Video**
https://cdn.discordapp.com/attachments/640458144165789710/1040485239572680744/snd_problem.mp4

**Platform (please complete the following information):**
 - Engine Version: commits since 8d07796
 - OS: Windows 10 Home

**Additional context**
This report text was automatically translated by DeepL and some sentences may be incorrect.

November 13, 2022 EDIT:
This is a bug that was also present in 0.98.2 and earlier, but we have also found a bug where abspan in PlaySnd is constantly tracking the coordinates.
In the case of MUGEN, abspan follows only at the moment PlaySnd is executed.

**Comment by Kuroteba** [comment]
I too have confirmed that this bug occurs in v0.99.0-rc.1.
Converting to 8bit resolved it.

**Comment by potsmugen** [comment]
I think this is the same issue Eiton solved with #1408.
