### ISSUE TITLE
Bug: Slot function breaking skip cell 

### ISSUE THREAD

**Issue by Rurouni-X** [ikemen-engine/Ikemen-GO#722]
I was messing with a screenpack of mine that uses skip.cell and when I added the slot function it broke the organization of the cells.

Using "skip.cell" without the slot function:
![ikemen000](https://user-images.githubusercontent.com/68881657/202589171-404177bf-b0d1-4acf-9344-2d645d2c8596.png)

With slot function:
![ikemen001](https://user-images.githubusercontent.com/68881657/202589182-b79e36bf-f627-478b-94d4-611992c40ee2.png)

[mugen1.zip](https://github.com/ikemen-engine/Ikemen-GO/files/10036734/mugen1.zip)

**Platform**
 - 0.98.2
 - Windows 10, AMD Radeon RX Vega 10 (onboard).

**Comment by K4thos** [comment]
@GaryCXJk #560, #577
