### ISSUE TITLE
TargetState anim bug

### ISSUE THREAD

**Issue by zzzz0424** [ikemen-engine/Ikemen-GO#730]
**Describe the bug**
TargetState's anim change process is different from MUGEN's, or it is loaded with priority over ChangeAnim or ChangeAnim2.

**To Reproduce**.
Detailed steps to reproduce the behavior, e.g:
1. tokage's Yuujiro Hanma
2. start the match and perfrom move using the following commands '~D,DF,F,y' 
3. the opponent does not load anim, but displays 5050 anim and becomes rigid while following Yujiro

In addition to this, the same phenomenon has been found in the case of CHOUJIN's Goku's KAIOKEN state when he launches a guard cancel move, etc.

**Expected behavior**
This behavior was not observed in the current release of 0.98.2, and we hope to downgrade to the previous behavior.

**Screenshots / Video**
https://user-images.githubusercontent.com/60909119/203693208-108aff9b-6c08-475d-8c3d-94dc044c68c1.mp4

**Platform (please complete the following information):**
 - Engine Version build is 323c00f
 - OS: Windows 10 Home

**Additional context**
This report text was automatically translated by DeepL and some sentences may be incorrect.

**Comment by Lazin3ss** [comment]
From my tests, it seems the bug was introduced in 06d7cb60f6b65d861099194cbfb704effde2dd75 (at least with Yuujiro, haven't tested Goku).

**Comment by K4thos** [comment]
same result of my tests, #562, @NeatUnsou
