### ISSUE TITLE
Achievement System

### ISSUE THREAD

**Issue by DestinyLibertination** [ikemen-engine/Ikemen-GO#735]
I wanted to make an achievement system in my Ikemen
For example, play 20x with Kula to unlock Sula or die for Freeman playing with Kula to unlock Isabeau
If there is such a system, could you help me?

**Comment by K4thos** [comment]
https://github.com/ikemen-engine/Ikemen-GO/wiki/Miscellaneous-Info/#lua_unlock
If you have questions try asking on ikemen discord.
