### ISSUE TITLE
Stages max is 1414 even put somemore?

### ISSUE THREAD

**Issue by EgyLynx** [ikemen-engine/Ikemen-GO#737]
If stage number is 1414 alreadu it look just select random at just that and that´s it. Even put some more new at in, 1414 still at show.
1414+20 is not 1414 it is 1434!! But engine shows just 1414!

**Comment by K4thos** [comment]
this report does not meet the criteria. Consider asking someone better with English to help you write it. And next time please use bug report template.

**Comment by EgyLynx** [comment]
BUT aren´t YOU even test THAT ??? why it just show it 1414 when i have more STAGES``

**Comment by K4thos** [comment]
yes, I've tested it. There is no such problem.

**Comment by EgyLynx** [comment]
BUT why it my think stay 1414?? 
Erf, how it again at? Person,, stage , order ARE i should put any these at include?? I think it put them auto...
