### ISSUE TITLE
Ownpal default values are flipped

### ISSUE THREAD

**Issue by LasombraDemon** [ikemen-engine/Ikemen-GO#739]
**Describe the bug**
Ownpal does not default to 0 for helpers and explods, as it should. In MUGEN, for both explods and helpers, it does. FightFX explods should default to 1, though.

**Screenshots / Video**
This works fine in MUGEN
![imagen](https://user-images.githubusercontent.com/74574875/204158224-4955ee52-c410-4cea-b37a-e41fe20309e3.png)

**Platform (please complete the following information):**
0.98.2

**Comment by K4thos** [comment]
it's already fixed
