### ISSUE TITLE
HitDef PalFX bug

### ISSUE THREAD

**Issue by LasombraDemon** [ikemen-engine/Ikemen-GO#740]
**Describe the bug**
P2 Storm should be in PalFX for 27 frames. But as soon as hitpausetime is over (9 frames) she is back to normal P2 Storm.

Using this code:
palfx.time = 27
palfx.add = 0,64,226
palfx.mul = 128,256,256
palfx.sinadd = -80,-80,-80,6

**Screenshots / Video**
![imagen](https://user-images.githubusercontent.com/74574875/204158376-ebd805b9-87fc-4859-a830-f4a7260c5e66.png)

**Platform (please complete the following information):**
0.98.2

**Comment by K4thos** [comment]
most likely already fixed. Please upload character for testing or test it yourself in latest github build.

**Comment by LasombraDemon** [comment]
Hey there! 

Storm is found here: https://drive.google.com/file/d/1LnnnqwM36YvUYLYYXH8CA8z3YD2NBSGj/view?usp=share_link

**Comment by K4thos** [comment]
it's already fixed
