### ISSUE TITLE
now it put self at 1415 from 1414,( 4.7 gb stages)

### ISSUE THREAD

**Issue by EgyLynx** [ikemen-engine/Ikemen-GO#742]
a: stages at somewgat 4.7 gb at all? are that it reason why it not put these or just my bad kyck?

**Comment by SuperFromND** [comment]
This seems to be a continuation of #737?
Putting aside the apparent language barrier, if I'm reading the issue correctly you seem to be having problems with stages not being read past a certain point; sounds like a problem with your `select.def` to me.

Perhaps posting it (you can attach the file to Github directly, no need to copy-paste it) would give us an idea of what's wrong although I'd personally say more info is needed. If necessary, consider finding someone to translate your message if English isn't your strong suit.

**Comment by EgyLynx** [comment]
I self thought at / or \ at think, or at there are blank area(s) at extra stage list, no both : I
