### ISSUE TITLE
Pause doesn't work with bg and top dialogue animations

### ISSUE THREAD

**Issue by Rurouni-X** [ikemen-engine/Ikemen-GO#754]
**Describe the bug**
Even pausing the game, the animations used for the dialog parameter continue to play.

**Video**

https://user-images.githubusercontent.com/68881657/205417170-0d9abff4-0913-4a6a-9e6e-1c76f0fce2e6.mp4

**Platform:**
 - 0.98.2
 - Windows 10, AMD Radeon RX Vega 10 (onboard).

[system.zip](https://github.com/ikemen-engine/Ikemen-GO/files/10145391/system.zip)

**Comment by K4thos** [comment]
this is long time fixed
