### ISSUE TITLE
Missing round.final.text (?)

### ISSUE THREAD

**Issue by Rurouni-X** [ikemen-engine/Ikemen-GO#757]
I don't know it's a bug or if it hasn't been implemented yet, but checking the round.final parameters, I could see that it has the same functions as roundx/ round.default with the exception of text.

We have:
```
 round.default.font = 1,0, 0
 round.default.text = Round %i
 round.default.displaytime = 60
```

But this doesn't work:
```
round.final.font = 1,0, 0
round.final.text = Final Round
round.final.displaytime = 60
```

https://user-images.githubusercontent.com/68881657/205490459-3f542946-5763-4cc9-ba30-36f92b269ec9.mp4

While the sound will be triggered, it is kind of weird to hear "Final Round" while the text shows "Round 3" (or whatever the number).

**Comment by K4thos** [comment]
like in mugen round.default.text is always rendered and is not supposed to be altered by roundX.text parameters. So nothing to fix here, since final element follows the same logic as roundX elements. And changing it would conflict with mugen lifebars.

**Comment by K4thos** [comment]
correction. round.default.text is meant to be always rendered. roundX / round.final are meant to be rendered on top of it (which is the case in mugen). If it doesn't happen than you're likely missing offset parameter (round.default.offset is not used for other elements)
