### ISSUE TITLE
Sound playback is slower than MUGEN.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#771]
Landing sounds, etc. are played back slower than in MUGEN.

**Comment by K4thos** [comment]
please follow bug report template.

**Comment by Kuroteba** [comment]
I have tried the latest source code version, but it has not improved.
The sound of landing etc. is still reproduced slower than MUGEN.

**Describe the bug**
Landing sounds, etc. are played back slower than in MUGEN.

**To Reproduce**
Detailed steps to reproduce the behavior, e.g.:
1. Download the appropriate character. (This bug also occurs in kung fu man.)
2. Some action that plays some sound. (Landing, etc...)
3. Sound is played back later than MUGEN.

**Expected behavior**
Any audio in the game will play later than MUGEN.

**Video**

https://user-images.githubusercontent.com/99640380/206970954-d893f9dd-3099-48b7-80b8-1443cd092694.mp4

**Platform**
 - Engine Version [e.g. 0.98.2 && Latest source code version]
 - OS: [e.g. Windows 10]
