### ISSUE TITLE
Continue screen is playing the victory screen music

### ISSUE THREAD

**Issue by Rurouni-X** [ikemen-engine/Ikemen-GO#774]
**Describe the bug**
As described in the title. Even though there is no music assigned to the continue screen and the parameter "sounds.enabled = 0" is used, the victory screen music still continues.

**Platform**
 - Repo Build
 - Windows 10

https://www.mediafire.com/file/lhv8iz5zosoldj5/11122201.7z/file

**Comment by K4thos** [comment]
it's intentional
