### ISSUE TITLE
Problem with axis when animation frame uses scale

### ISSUE THREAD

**Issue by Rurouni-X** [ikemen-engine/Ikemen-GO#776]
**Describe the bug**
Specifically on the continue and challenger screens, frames using scaling don't stay in the position they should. In the example provided (.zip), using the animation for "Challenger" and "Countdown" they go off-screen although they use the same animation and offset that is used on the title screen, where the animation works correctly.

**Expected behavior**
Testing the animation on the same build, the correct result would be what happens on the title screen just like in MUGEN 1.1.

**Screenshots / Video**
![anim](https://user-images.githubusercontent.com/68881657/206927856-42670fb1-0a80-48be-be03-88bcdeca5ffd.gif)

**Platform (please complete the following information):**
 - Repo Build
 - Windows 10

[11122202.zip](https://github.com/ikemen-engine/Ikemen-GO/files/10203264/11122202.zip)

**Comment by K4thos** [comment]
@Rurouni-X, I can't reproduce the problem you described. Scale seems to be completely unrelated. And the difference for the x axis in your test case seems to be the result between how BGdef interprets x position (center, with negative and positive value being offset from center), compared to screenpack positioning outside BGdef - x position starting at from 0 on 320p localcoord, not 160. Which is something that I don't think can be safely changed without breaking mugen screenpacks (there are bg elements for select screen team mode in mugen that support anim, text elements also expect starting pos at 0, not center).

Here is modified test case that you've provided.
Image cropped and set at pos 0,0 in FF:
![t1](https://user-images.githubusercontent.com/8928195/229261144-3d7dd126-2fc5-461c-be16-953c7f6b4e7b.png)

```
[TitleBGdef]

[TitleBG S]
type  = anim
actionno = 6
start = 0,120
mask = 1

[Begin Action 6]
6,1, 0,0,-1, , , 1,1
```

```
[Title Info]
menu.bg.active.menuarcade.anim = 6
menu.bg.active.menuarcade.offset = 0, 120
menu.bg.active.menuarcade.facing = 1
menu.bg.active.menuarcade.scale = 1.0, 1.0
```
![ikemen009](https://user-images.githubusercontent.com/8928195/229261268-8ac02e92-11de-4c93-867d-3b2d6cb8cf6f.png)

Left side is menu.bg.active.menuarcade.anim (as expected starting at 0), right is the same anim rendered via [TitleBG S] - as you can see starting at center of the screen.

Let me know if I'm missing something.

**Comment by Rurouni-X** [comment]
@K4thos, I mean:
"Specifically on the continue and challenger screens." In the title screen (menu) it works as it should.

If you look at the gif, there are 4 screenshots:
1st image - MUGEN 1.1, "menu" - expected behavior.
2nd image - IKEMEN GO, "menu" - expected behavior.
3rd and 4th images - IKEMEN GO, "challenger" and "continue screen", buggy behavior.

**Comment by K4thos** [comment]
you are using different way to spawn those images in menu and in challanger/continue screen. If you spawn it the same way than there is no problem, based on my tests.
