### ISSUE TITLE
SaveFile / LoadFile savedata parameter isnt working

### ISSUE THREAD

**Issue by Orochikyocr** [ikemen-engine/Ikemen-GO#778]
**Describe the bug**
Whatever data you pass to the savedata parameter in both SCTRLS returns an "Invalid value" error. 
The parameters that do not return errors are MAP and VAR but only the words.
Map(younamevar) or var(value) with or without " " does not work.
Only the value or the map name does not work too. 

**To Reproduce**
Just use this sctrl on both CNS or ZSS.

**Expected behavior**
savedata should expect the map(yourmapname) or var(xx) to save/load these values into a gob file for later use.

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/42851314/206932599-ddb093b7-9bd1-4841-8cf5-43311a73fad9.png)

**Platform (please complete the following information):**
 - 0.98.2
 - OS: Linux

**Comment by K4thos** [comment]
read the documentation again. You are not supposed to use map names.
**Specifies the data type that should be saved. Valid values for var_type are "var", "fvar", and "map".**

**Comment by NeatUnsou** [comment]
If you want to handle only one variable, you can create a Helper and have the Helper do SaveFile / LoadFile and then read it with another char.

**Comment by Orochikyocr** [comment]
You were really quick to close this K4thos. How it is supposed I can use a save feature when I can't tell the code what map or varI want to save to the file?
I used this on 0.96 and I was able to save map(mapName) and var(xx) to any file.

**Comment by K4thos** [comment]
it worked exactly the same at 0.96. There was just no error message to tell you that you were using it wrong.

**Comment by Orochikyocr** [comment]
> If you want to handle only one variable, you can create a Helper and have the Helper do SaveFile / LoadFile and then read it with another char.

Ok, the thing is... Helpers are just dummy objects lurking around, being an obstacle in the debug console. Another object present on the screen or...
When I used 0.96 I thought I can cherry-pick what var or map I want to save. like why I would want to save every single map or var of my char in a file, even maps that are set from common files like the tag and action files...
