### ISSUE TITLE
Sound sounds slower than MUGEN has not been improved.

### ISSUE THREAD

**Issue by Kuroteba** [ikemen-engine/Ikemen-GO#779]
**Describe the bug**
Landing sounds, etc. are played back slower than in MUGEN.

I have tried the latest source code version, but it has not improved.
The sound of landing etc. is still reproduced slower than MUGEN.

**To Reproduce**
1. Download the appropriate character. (This bug also occurs in kung fu man.)
2. Some action that plays some sound. (Landing, etc...)
3. Sound is played back later than MUGEN.

**Expected behavior**
Any audio in the game will play later than MUGEN.

**Video**

https://user-images.githubusercontent.com/99640380/206971635-f238e94d-b609-462e-b246-f50d0f8f0fcf.mp4

**Platform**
 - Engine Version [e.g. 0.98.2 & Latest source code version]
 - OS: [e.g. Windows 10]

**Additional context**
The bug I mentioned before where the character's sprite goes wrong in certain positions has not been fixed either.

**Comment by K4thos** [comment]
sounds the same to me based on your video

**Comment by Kuroteba** [comment]
I gave you another video because I heard it sounds the same.
Characters used :kytes by bakisimu


https://user-images.githubusercontent.com/99640380/209452129-9f3727a8-7d39-4b3e-9b79-447368d4766f.mp4

**Comment by K4thos** [comment]
fixed by above commit
