### ISSUE TITLE
Couple of issues with Gethitvar(isbound)

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#780]
**Describe the bug**
This trigger is currently malfunctioning in at least 2 ways:
- It stays 1 even if the character is no longer a victim of TargetBind (main issue, second one is derived from it)
- If the character is hit by an attack (not a throw), sent to a custom state with TargetState, then bound with TargetBind, Gethitvar(isbound) will return 1 until the character is thrown

**To Reproduce**
Perform Kung Fu Throw with Displaytoclipboard on.

**Expected behavior**
This gethitvar is special in Mugen in that it has little to do with getting hit, being just used to detect if the character is under the effect of TargetBind.

**Screenshots / Video**
Kung Fu Throw
![ikemen017](https://user-images.githubusercontent.com/107247004/207131827-0064afe9-c3d0-4d79-a563-0e25d598df56.png)
![ikemen018](https://user-images.githubusercontent.com/107247004/207131843-0157cdee-8917-4f41-9c08-35c0f9cb7a1e.png)

An attack using a combination of TargetState and TargetBind (char is not out for testing yet):
![ikemen019](https://user-images.githubusercontent.com/107247004/207133204-6e13b254-034b-444c-98e2-d15a2e12c3d4.png)
![ikemen020](https://user-images.githubusercontent.com/107247004/207133224-d9b0b13d-7688-4ed9-a624-1efc01806648.png)

**Platform (please complete the following information):**
 - Latest build
 - Windows 7

**Comment by K4thos** [comment]
regression cased by #562
@NeatUnsou
