### ISSUE TITLE
[Feature Request] Char Select Screen - Enable Time Limit and Player 2 on Right Side in Single Mode Feature

### ISSUE THREAD

**Issue by TYTWC** [ikemen-engine/Ikemen-GO#782]
Since IKEMEN GO has more modding features compared to MUGEN, would it be possible to add an optional feature where the user can implement an optional set timer countdown on the Character Select screen akin to most fighting games in the mainstream?

Also is it possible to create a feature where when Player 2 starts a Single Player Mode game, it would automatically set the player on the right side with Player 2’s select cell instead of retaining on Player 1’s side?

**Comment by K4thos** [comment]
there is already feature like that. Check data/system.base.def. As for changing sides, it's not planned, maybe in future.

**Comment by TYTWC** [comment]
> 

Tried to edit the file to change 

#
	; Positive count enables timer, limiting time (count * framespercount) for
	; selecting team modes and characters. Each selection resets timer.
	timer.offset = 0, 0
	timer.font = -1, 0, 0, 255, 255, 255, -1
	timer.scale = 1.0, 1.0
	timer.text = "%i"
	timer.count = -1
	timer.framespercount = 60
	timer.displaytime = 10
To
#
	; Positive count enables timer, limiting time (count * framespercount) for
	; selecting team modes and characters. Each selection resets timer.
	timer.offset = 0, 0
	timer.font = -1, 0, 0, 255, 255, 255, -1
	timer.scale = 1.0, 1.0
	timer.text = "%i"
	timer.count = 30
	timer.framespercount = 60
	timer.displaytime = 10

But it seems to do nothing at all once I loaded up the program after making the changes.
