### ISSUE TITLE
Reversaldef and Hitfall

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#783]
**Describe the bug**
It looks like Reversaldef can't apply Hitfall-related Hitdef properties to its target(s). Maybe other Hitdef properties as well.

**To Reproduce**
1. Download my [Geese](https://www.mediafire.com/file/lpz0s809wrr82df/geese_pots.zip/file)
2. Perform one of his counters (half circle back + punch)
3. The target should return gethitvar(fall) and gethitvar(fall.recover) as 1, but they are 0

**Expected behavior**
In Mugen a Reversaldef can inflict these properties on the opponent just like a Hitdef can. May apply to more Hitdef parameters.

**Screenshots / Video**
Mugen:
![mugen017](https://user-images.githubusercontent.com/107247004/207417811-ae8d4daa-7f07-44df-853d-b7194dbb22d2.png)

Ikemen:
![ikemen023](https://user-images.githubusercontent.com/107247004/207418008-a065fbbd-425a-494b-92c7-37bbcee8a6b6.png)

**Platform (please complete the following information):**
 - Latest build
 - Windows 7

**Comment by potsmugen** [comment]
Found another thing related to this, in that a Reversaldef won't reset the xvel and yvel Gethitvars of its target. In Mugen it sets them to 0.
Although I think in Ikemen it could set them to whatever you put in the Reversaldef.

**Comment by K4thos** [comment]
I can't do this move reliably and don't know what to edit to make it easier. Easier test case, please. Checking if it also happens in 0.98.2 would be also useful.

**Comment by potsmugen** [comment]
Here's a version where he does it automatically and has debug on:
[geese test.zip](https://github.com/ikemen-engine/Ikemen-GO/files/10260378/geese.test.zip)

Just hit him with standing attacks.

The same thing happens in 0.98.2.
