### ISSUE TITLE
Weird Bug and Crash Regarding the Slot Parameter

### ISSUE THREAD

**Issue by Oceanboy1330** [ikemen-engine/Ikemen-GO#784]
**Describe the bug**
The Slot Parameter is Bugging Out for me. It Skips over when Pressing "W" and Crashes when Pressing "D" on Characters using Symbols like "!", "-", etc., and a Few Other Random Characters. I'm Using the EVE Screenpack Modified by olt-EDEN and Modified Again by Me With my Own Prefered Categories.

**To Reproduce**
1. Start Ikemen GO
2. Head Over to the Select Screen
3. Go Down to the "MUGEN" Category

**Expected behavior**
When Pressing D or W, The Bug Happens

**Screenshots / Video**
![Screenshot 2022-12-15 131713](https://user-images.githubusercontent.com/115200441/207969562-54f3fe11-4a8a-44d0-b789-e46e80be7e94.png)

**Platform (please complete the following information):**
 - 0.98.2
 - Windows 10 22H2

**Comment by Oceanboy1330** [comment]
Select.def: https://cdn.discordapp.com/attachments/282927929548210177/1053062709937184858/select.def

**Comment by K4thos** [comment]
there is no randomness in errors like this. Please try to prepare a test case with minimal select.def (most likely even 2 characters in 1 slot should be enough to reproduce it), not with 500 characters.

**Comment by Oceanboy1330** [comment]
Closing This as Fixed, I was Being Dumb. I Forgot to remove the Unnecessary Comment of the ", previous=d, next=w" of the Problematic Character. Silly Me.
