### ISSUE TITLE
BindtoTarget does not correct position in corners

### ISSUE THREAD

**Issue by potsmugen** [ikemen-engine/Ikemen-GO#786]
**Describe the bug**
If you use the BindtoTarget SCTRL in the corner, the position which the character binds to will often be wrong.

**To Reproduce**
1. [Download my Sakura](https://www.mediafire.com/file/gcd9a7sht6gv3yf/sakura_pots.zip/file)
2. Perform her punch throw in the corner (F + 2 punches)

**Expected behavior**
In Mugen the engine seems to correct the target's position to prevent this.

**Screenshots / Video**
Ikemen:
![ikemen010](https://user-images.githubusercontent.com/107247004/208293777-a78f1c7c-151c-44b8-a262-e56e72f58637.png)

Mugen:
![mugen018](https://user-images.githubusercontent.com/107247004/208293786-b5e2fa1a-ac39-4c9d-aa77-03e4a68a1c0e.png)

**Platform (please complete the following information):**
 - Latest build

**Comment by K4thos** [comment]
regression cased by #659
@Lazin3ss
