### ISSUE TITLE
IKEMEN Crashed

### ISSUE THREAD

**Issue by gohkenytp** [ikemen-engine/Ikemen-GO#792]
Whenever I try to put a stage with music when putting up Juggernaut/Giga Bowser vs Barney/Pooh, the game crashed for no reason at all!

**Comment by K4thos** [comment]
please use the bug report template, providing everything needed to reproduce it, otherwise the ticket will be closed.

**Comment by EgyLynx** [comment]
> Juggernaut/Giga Bowser vs Barney/Pooh
Whose ones are question? Which version at your Ikemen at?
