### ISSUE TITLE
Modules Repository License Clarification

### ISSUE THREAD

**Issue by EVILEDLIBRE** [ikemen-engine/Ikemen-GO#801]
What is the license for the modules repository?

https://github.com/ikemen-engine/modules

I ask because absolutely nothing in the repository itself says what license the modules are under.

My best guess is to assume that the modules are licensed under the same MIT Expat License as the Ikemen Go Engine itself is.

My two reasons for this guess are as fallows:

1: Their functionality used to be part of the Ikemen Go Engine before being taken out and placed into their own repository.

2: The License for the Ikemen Go Engine states "The MIT License applies to the Ikemen GO engine and the scripts in this repo."

However, this is not a good way to do things. Because "and the scripts in this repo" is an incredibly vague way to handle this.

Because, how does one define "this repo?"

"This repo" could mean literally what it says "this repo." In that case, it would only be referring to scripts found here

https://github.com/ikemen-engine/Ikemen-GO

Sense the modules are found here

https://github.com/ikemen-engine/modules

and not here

https://github.com/ikemen-engine/Ikemen-GO

then they really aren't part of "this repo" at all. At least not from a literal reading of the license.

After all, not everything found here

https://github.com/ikemen-engine

is covered under the MIT Expat License.

The screen pack, for instance, found here

https://github.com/ikemen-engine/Ikemen_GO-Elecbyte-Screenpack

is not. Even thought it's still linked to from here

https://github.com/ikemen-engine

It has its own license in its own repo (as the modules should.)

My entire point being that you can't really just pluck the modules out of the engine, stick them in their own separate repository without a license, and then just assume that they're still covered by the license they used to be covered by because the license text for the engine says "this repo" in it.

That's really not good enough. The module repo itself should have a license in it that clearly states what license they are under now that they are divorced entirely from the engine and exist in their own repo as their own thing. Otherwise, there is no logical way for people to know for sure what license they are under. Especially if they don't know the history of the engine; they wouldn't even know how to guess.

**Comment by K4thos** [comment]
done, thanks
https://github.com/ikemen-engine/modules/blob/main/License.txt
