### ISSUE TITLE
Bug Error: Can't Open Ikemen?

### ISSUE THREAD

**Issue by JJMP4** [ikemen-engine/Ikemen-GO#818]
Hello, 

I have recently came across this bug which prevents me from opening Ikemen, it looks like this.
<img width="301" alt="ERROR" src="https://user-images.githubusercontent.com/122961819/213101188-909bfa47-adf0-4c00-b0b9-05934c8992cb.PNG">

Any help will be nice, thank you.

**Comment by lokpro** [comment]
It looks like there are invalid settings in your select.def 


https://github.com/ikemen-engine/Ikemen-GO/blob/69b3936e60a7c12120686ab488bf1f7cfa96ef5b/external/script/main.lua#L2155

**Comment by K4thos** [comment]
Error alone is not enough to reproduce it locally. Please upload minimal build for testing that crashes (preferably as close to default release as possible). The problem is most likely caused by your select.def.
