### ISSUE TITLE
Crash when Going Backwards

### ISSUE THREAD

**Issue by LunarianRhapsody** [ikemen-engine/Ikemen-GO#956]
### Describe the bug

So, due to IKEMEN GO not having a Scolling Character Select, I've had to use the Multislot Function to not worry about running out of them. However, when scrolling through, characters just don't appear until going backward & then the game crashes.

### To Reproduce

1. Go to Character Select
2. Scroll through the Character Slot
3. Go to previous slots
4. Crashes

### Screenshots / Video

![image](https://user-images.githubusercontent.com/123664305/214911138-fbe41711-599b-49ce-b123-d008aca49c9b.png)
![image](https://user-images.githubusercontent.com/123664305/214911812-f1e1342d-1f60-49a6-bef0-19f070974435.png)

### Engine Version (or source code date)

0.98.2 (Albeit, using a OpenGL addon to let it work)

### Operating system

Windows

**Comment by K4thos** [comment]
please upload whole ikemen folder that includes everything present in your screenshot, ready for testing

**Comment by LunarianRhapsody** [comment]
[select.txt](https://github.com/ikemen-engine/Ikemen-GO/files/10523314/select.txt)
[start.txt](https://github.com/ikemen-engine/Ikemen-GO/files/10523322/start.txt)
[main.txt](https://github.com/ikemen-engine/Ikemen-GO/files/10523327/main.txt)

I'm very unsure if there is anywhere I could upload the full folder, due to it being 15GB

**Comment by K4thos** [comment]
not enough to reproduce it in reasonable amount of time for something that is likely already fixed. Please try to prepare a smaller build that can reproduce the problem.
