### ISSUE TITLE
TargetLifeAdd overflow bug

### ISSUE THREAD

**Issue by Eiton** [ikemen-engine/Ikemen-GO#971]
### Describe the bug

```
[state lifeadd]
type = targetlifeadd
trigger1 = movehit
value = -2147483648
pausemovetime = 9990000
supermovetime = 9990000
```
This instant kill targetlifeadd will heal the target in ikemen

### To Reproduce

Place the above code in statedef -3 of kfm

### Expected behavior

kfm will kill the opponent when any hit contacts in MUGEN.

### Engine Version (or source code date)

commit bff65193ab746e472b21a68db0f7c1d86d0e4b42

### Operating system

Windows

### Extra context or search terms

Range of int32 is -2147483648 to 2147483647
In the computeDamage function, the sign of the targetlifeadd value is flipped and the value is casted to int32. An overflow will occur and cause unexpected behavior if the value is -2147483648.
A fast fix would be adding an overflow check before passing the value to computeDamage but I am not sure whether this is the best solution:
```
add2 := add
if add2 == -2147483648 {
    add2 = -2147483647
}
dmg := float64(t.computeDamage(-float64(add2), kill, absolute, 1, c, true))
```

**Comment by potsmugen** [comment]
Funny thing here. In Mugen, if you use a Hitdef with damage >= 2147483648, the GetHitVar will overflow but life will be subtracted correctly regardless. Also, a Hitdef with damage = -2147483648 will kill in Mugen but (correctly) heal in Ikemen.

So the million dollar question is: should we only fix overflow bugs or flat out alter all of our logic to be like Mugen?
